### ISSUE TITLE
undefined method `new_record?' for nil:NilClass

### ISSUE THREAD

**Issue by davelab** [nathanvda/cocoon#107]
Hi i'm building a relations Company :has_many Notes.

i want to be able to add some new notes to a just created company in the Comany#show resource. so in the company scaffold's show.html.erb

i have follwed step by step the demostration and the git mardown, but your examples shows only the method to add nested attribute into _form.html.erb partial. I don't know if there is some particular things to do differently, but when i try to run the Company#show action it retrieves this erro:

undefined method `new_record?' for nil:NilClass

this is my code

show.html.erb:

``` ruby
...
<%= simple_form_for :notes, :html => { :class => 'form-horizontal' } do |note| %>
      <%= render 'note_fields', :f => note %>
    <% end %>
    <%= link_to_add_association 'Aggiungi Nota', f, :notes, :render_options => {:wrapper => 'inline' } %>
...
```

_note_fields.html.erb:

``` ruby
...
<div class="nested-fields">
    <%= f.input :body %>
    <%= link_to_remove_association "Elimina Nota", f %>
</div>
....
```

Company.rb:

``` ruby
...
has_many :notes
accepts_nested_attributes_for :notes, :reject_if => :all_blank, :allow_destroy => true
...
```

Note.rb

``` ruby
class Note < ActiveRecord::Base
  attr_accessible :body, :company_id
  belongs_to :company
end
```

thanks!
Dave

**Comment by justinj656** [comment]
I actually got into the same problem, use `f.simple_form_for` instead of 'simple_form_for'
