### ISSUE TITLE
Nested forms disappear when validation fails

### ISSUE THREAD

**Issue by DeanDeBlock** [nathanvda/cocoon#114]
When submitting the form the nested data doesn't render again if the validation fails

actions look like this

```
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  def new
    @event = Event.new
    respond_with(@event)
  end
```

An event belongs to a venue

```
  <fieldset>
    <legend><span class="label label-inverse" style="font-size: 1.0em">2</span>&nbsp;Where</legend>
    <div id="venue">
      <div id="venue_from_list">
        <div class="form-inputs">
          <%= f.association :venue, :include_blank => 'Choose existing venue', :input_html => { :class => 'span12' }  %>
        </div>
      </div>
      <%= link_to_add_association icon('plus') + ' add a new venue for this event', f, :venue, :class => 'btn btn-small', :style => "margin-left: 180px;" %>
    </div>
  </fieldset>
```

we also use simpleform 

Does anybody have an idea how to fix this?

**Comment by Chryus** [comment]
I think I may have found a solution (at least when using standard forms). In the else statement of the create action, rebuild the nested belongs_to object, like in the new action. This solved the missing field problem for me after redirect on validation failure.

    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        @event.build_venue
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end

**Comment by dgmstuart** [comment]
@Chryus That will build a new blank venue associated with the event, right? I think the desired behaviour is to instead display the venue data which the user had previously entered.

_(Apologies if I've got the wrong end of the stick: it's been a long time since I looked at this)_
