### ISSUE TITLE
link_to_add_association not working.

### ISSUE THREAD

**Issue by ohayon** [nathanvda/cocoon#121]
hi there, i have used concoon before successfully, and i have copied the code from my working example for rendering the partial for the first set of nested attributes, and the link is only adding on a `#` without displaying the partial, whereas on my working example, the url does not change to `localhost:3000/key/new#` and it does render the partial.

any ideas?

``` erb
<%= simple_form_for(@etios_key, :html => {:class => 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :oid %>
    <%= f.input :name %>
    <%= f.input :short_name %>
    <%= f.input :app_name %>
    <%= f.input :org_url %>
    <%= f.input :nav_color %>
    <%= f.input :facebook_id %>
  </div>

  <h2>Dashboard Actions</h2>
  <div class="dash_actions">
    <%= f.simple_fields_for :dashboard_actions do |action| %>
       <div class='dash_action'>
            <%= render 'dashboard_action_fields', :f => action %>
        </div>
    <% end %>
    <%= link_to_add_association 'Add Action', f, :dashboard_actions %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
```

**Comment by manfe** [comment]
In Rails 4.2.0 I wasn't able to display the add button I needed to add a build in the association. Check this link: http://stackoverflow.com/questions/26346850/cant-get-cocoon-to-work-on-ruby-on-rails-4.

Hope it help anyone else.
