### ISSUE TITLE
Don't display removed association on error.

### ISSUE THREAD

**Issue by woto** [nathanvda/cocoon#136]
Hi again, and again sorry for bad English :) 
I can't understand is it normal behaviour or not.

For example i have Categories -> Posts and validation for example on Title in Posts
Next i have form with ...f.fields_for :posts and 1 existing Post in some Category.

Loading page with form and one nested Post
Next i adding new Post with wrong validation Title and remove existing Post.

On form submit i got validation error message on new Post and wtf? already removed apperead again.

I viewed source and changed partial form for Post like this. 

```
  - if f.object._destroy
    = hidden_field_tag("#{f.object_name}[_destroy]", '1')
  - else
    = link_to_remove_association 'remove', f, :class => "btn btn-danger", :confirm => 'Are you sure?'
```

Is it right behaviour of cocoon and there is no features like this. Or i missed something and doing things wrong? Thanks.

**Comment by simo163** [comment]
I am also running into the same problem, I only added class="nested-fields" and seems to be working.

**Comment by nathanvda** [comment]
@simo163 i guess you are referring to the fact that link_to_remove_association does not work unless you use the correct class? Which is not related to this issue at all.

**Comment by simo163** [comment]
@nathanvda you're right, Thanks!
