### ISSUE TITLE
link_to_add_association: option for some kind of inline partial?

### ISSUE THREAD

**Issue by rvalyi** [nathanvda/cocoon#149]
Hello,

first kudos for cocoon, I'm making my way for using it for interacting with OpenERP from Rails. Hopefully will publish about this soon.

So basically I'm using cocoon along with cells. And in this context, I may need nested forms BUT the forms definitions may not be a partial file, they may be inline templates that I transcode automatically (via XSLT) from the OpenERP XML dialect form definitions.

Or said it straight: that would be cool if you could support some kind of inline template definition for the link_to_add_association partial. I think this could be useful in other contexts too. What do you think?

**Comment by Novsochetra** [comment]
try this one: 

`.links
      = link_to_add_association f, :user_permissions, partial: 'permissions/shared/user_permission_fields', class: 'btn btn-primary' do
        %i.fa.fa-fw.fa-database`
