### ISSUE TITLE
need help on editing nested-forms

### ISSUE THREAD

**Issue by Ezekiah** [nathanvda/cocoon#204]
Hello,

My aim is to be able to call existing nested objects in my database and edit them.
To do so I created a template which display the form objects according to an xml schema, each class has it's own form.

Example of form :
```ruby
builder = Nokogiri::XML::Builder.new do |t|
t.agent{      
          t.association(:type=>'association', :name=>'orgunits',  :display=>'public', :class_name=>'Orgunit')
          t.association(:type=>'association', :name=>'persons',  :display=>'public', :class_name=>'Person')
          t.rec_class(:type=>'hidden', :value=>'Agent')
          t.rec_id(:type=>'hidden', :value=>'', :display=>'public')
       
       }
```

I can display existing objects with the link_to_add like this :

```ruby
- link = link_to_add_association(' ', f, node_name.to_sym, :partial=>'/studies/display_fields', 
                  :render_options => {:locals => {:fedora_object=>data, :rec_type=>node_name, :edit=>true,:xml=>Object.const_get(class_name.capitalize).xml_form.to_xml,  :xpath=>'/'+class_name.to_s.singularize.downcase+'/*'}, },:data => {"association-insertion-method" => "before" },)
                  - link = Nokogiri::HTML(link)
```

However  when I open my edit popup the link_to add buttons generate wrong names.

It should output : 
study[authors_attributes][1395055572220][orgunits_attributes][1395055573891][name]

But it displays : 
study[new_authors][orgunits_attributes][1395055573891][name]

Could you help me, I don't think you have time to explore my code but do you know a good way to edit nested forms ?

My github is here : https://github.com/Ezekiah/hydra-head-archipolis/blob/master/app/views/studies/_display_fields.html.haml

**Comment by nathanvda** [comment]
Closed due to inactivity.
