### ISSUE TITLE
link_to_add_association generating duplicates issue

### ISSUE THREAD

**Issue by CaseJnr** [nathanvda/cocoon#207]
Hi. I have cocoon working well on a form if i refresh the page. However, I get duplicates for the link_to_add_association for every page i have clicked on since the last refresh. 

For example. If i go to a the products/new action by entering the url in a browser, the link_to_add_association works beautifully and generates one partial. But if i go to the products/index page and click on the the new_product_path link the  link_to_add_association will generate 2 partials. If i click on the product_path link 10 times then click on the new_product_path the link_to_add_association will create 10 partials.

I am using rails 4 with turbolinks, foundation and simple form. Here is the code I am using

class Image < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
  mount_uploader :image, ImageUploader     #carrier wave
end

class Product < ActiveRecord::Base
   has_many :images, :as => :imageable
   accepts_nested_attributes_for :images, :reject_if => :all_blank, :allow_destroy => true
end

class ProductsController < ApplicationController
...
def product_model_params
      params.require(:product).permit(:name, images_attributes: [:id, :image, :_destroy])
 end

#_form.html.erb
<%= simple_form_for @product do |f| %>
    <%= f.input :name %>
    <%= f.simple_fields_for :images do |image| %>
        <%= render 'image_fields', :f => image %>
    <% end %>	
    <%= link_to_add_association 'add image', f, :images  %>
    <%= f.button :submit %>
<% end %>	

// _image_fields.html.erb
  <%= image_tag(f.object.image.url(:thumb)) if f.object.image?   %>
  <%= f.input :image, :as => :file  %>
  <%= link_to_remove_association "remove image", f %>

Any guidance would be highly appreciated

**Comment by rhuppert** [comment]
I am experiencing a similar duplication problem.
For a completely unrelated reason, I have removed Turbolinks completely from my app.  
I am experiencing this link_to_add_assoiciation duplication of my cocoon view only in development and not in staging or production for all my cocoon views.
My javascript include tag Is in the head only.  Cocoon is loaded once only.
I have executed rake assets:clean and assets:precompile tasks.
I'm running Rails 4.2.0, Ruby 2.2.0, and Foundation 4.
I'd appreciate any suggestions on where to look.  As I said, this issue is only in development.

**Comment by nathanvda** [comment]
Only in development? Not using turbolinks? Define "similar" then :)

**Comment by rhuppert** [comment]
My question exactly.  Why development?  It had worked fine previously.
It made no sense until I started poking around the public assets folder. I removed several files I thought might be suspect and that resolved the issue.
Thanks for the gem, by the way.  Nice work.

Sorry to bother you on this, but I was frustrated.

**Comment by nathanvda** [comment]
Tips for the future: do not do `rake assets:precompile` in development, because I have noticed weird effects with that too. And to _really_ clean the assets, you have to do `rake assets:clobber` (clean leaves the last three compilations and deletes the older ones).

**Comment by monkeysh1ne** [comment]
OMFG!  I don't know how long I've been looking for this answer.  Thank you all soooo omuch!  Had a feeling Turbolinks may have been at fault.
