### ISSUE TITLE
need help on nested fields in a bootstrap modal

### ISSUE THREAD

**Issue by dealbertiphil** [nathanvda/cocoon#216]
Hi, great work on cocoon!
I'm trying to edit some fields inline and some fields in a modal.
the inline part works great but not sure how to make the modal part working. (the coordinates in the example below). 

form:

``` ruby
<div class= "row col-lg-12">
          <%= f.fields_for :routes do |route| %>
          <%= render 'route_fields', :f => route %>
          <% end %> </div>
           <div class= "row col-lg-12">
         <%= link_to_add_association 'add a route', f, :routes  %>
</div>
```

partial:

```
<div class = "col-xs-4">
<%= f.input :description %>
</div>

 <div class = "col-xs-2">
 <%= link_to "coord", edit_route_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#coordModal', 'data-type' => "html"}%>    
</div>

<div class = "col-lg-1">
<%= link_to_remove_association "", f %> 
</div>
```

.... the modal ....

```
<div class="modal fade " id="coordModal" tabindex="-1" role="dialog" aria-labelledby="coordModal" aria-hidden="true">
<div class="modal-dialog">
<div class="modal-content">
  <div class="modal-header">
   <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;          </button>
    <h4 class="modal-title" id="coordModalLabel">add coordinates</h4>
  </div>
  <div class="modal-body a-unique-class" >
   <%= f.input :coordinates %>
</div>

  <div class="modal-footer">
    <button type="button" class="btn btn-success" data-dismiss="modal">Save</button>
  </div>
    </div>
</div>
</div>
```

with this approach, it would only edit the same record in the database
If I assign f.object id to each modal, I won't be able to support the cocoon add since the id is not created yet.

Any thoughts?
thanks

**Comment by nathanvda** [comment]
Hello @webdevelopermeanstack!! Your comment seems strangely familiar to (this comment)[https://github.com/nathanvda/cocoon/issues/286#issuecomment-394159677] yet with a different user-name. Is this a new kind of spam? If you want to use a different form-name inside your partial, use the parameter `form_name`.

**Comment by mkok11019** [comment]
Hello @nathanvda !
It's not me.  Could you give details about form_name?
thanks

**Comment by nathanvda** [comment]
Please open a new issue.

**Comment by webdevelopermeanstack** [comment]
Hello @nathanvda !
As I said, I want to use a controller variable, such as "@flag".  But within partial view, it show that it is not defined. 

Could you know how to solve it?
thanks

**Comment by Mirv** [comment]
@webdevelopermeanstack  ... you are missing a part of the github etiquette ...  you should be opening a new issue.

It's not people being mean or anything - it's a documentation thing.  

If you want help, there's lots of people who give it - but you need to do it in a way that helps everyone else understand too...
