### ISSUE TITLE
Nested form without models

### ISSUE THREAD

**Issue by apeeyush** [nathanvda/cocoon#220]
Hi,

I would like to use cocoon to create a nested form but the nested form is not associated with any model. I am just posting all form data to server using JQuery.

I tried using cocoon but it gives an error saying

```
undefined method `reflect_on_association' for NilClass:Class
```

on line

```
     = link_to_add_association 'add task', f, :tasks, :render_options => { :wrapper => 'inline' }
```

I am using simple_form to build form without model in the following manner:

```
      = simple_form_for :project, :wrapper => 'inline' do |f|
```

Is there any way to get around this error?

The reason I want to use cocoon is because it nests the input name attributes very nicely and makes it easy to parse them on server. It also makes the code much more reusable. Hats off to nathanvda and awesome community!

**Comment by sandipsubedi** [comment]
@apeeyush Did you create StackOverflow question? If so, can you share the link please?
