### ISSUE TITLE
Cocoon dropping nested fields in grandparent rather than parent

### ISSUE THREAD

**Issue by kiddrew** [nathanvda/cocoon#249]
Here's my simplified code:

    fieldset
      ul
        = f.simple_fields_for :locations do |ff|
          = render 'location_fields', f: ff
        = link_to_add_association 'Add location', f, :locations

I would expect that clicking that link would drop the nested elements underneath the `ul` tag.  Instead, they're dropping under the `fieldset` tag.  I suspect I'm doing something wrong rather than this being a bug.  Ideas?

**Comment by nathanvda** [comment]
By default cocoon assumes, as indicated in the examples, that there is a div surrounding the `link_to_add_association`. See [here](https://github.com/nathanvda/cocoon#simpleform).

Does that help?

**Comment by kiddrew** [comment]
Yep, I just figured that out.  Adding 'data-association-insertion-node' => 'fieldset ul' to the html_options fixed it.  Thanks!
