### ISSUE TITLE
Passing variables to partial through link_to_add_association 

### ISSUE THREAD

**Issue by gonzag88** [nathanvda/cocoon#257]
Hi, i need every new item created with cocoon to have a different input id. That's why i want to pass a variable to the partial (something like Time.now or similar), and then use it as the id of the input. The problem is that I can't make it work. Following the official documentation, I've tried doing something like this:

This is a short version, and is not exactly the one i'm using, but i think is more readable:
`<%= link_to_add_association 'New', f, :something, :render_options => {:locals => {:sherlock => 'Holmes' }} %>`

This is the exact version, less readable:
`<%= link_to_add_association raw('Nuevo con empleado existente'), f, :parte_diario_item_indirectos, class: 'btn btn-primary btn-sm', 'data-association-insertion-node' =>  '#listado_item_indirectos_parte_diario', 'data-association-insertion-method' => 'append', :render_options => {:locals => {:sherlock => 'Holmes' }}  %>`

When i try to get the variable in the partial with <%= sherlock %>, it says that is undefined.

I hope someone can help me,
Thanks a lot!
Gonzalo

**Comment by nathanvda** [comment]
Right: the attack on multiple fronts again :) (get notified by email for a SO question, and then add an issue). 

Afaik this should just work. Which version of the gem are you using? 

Secondly: this will not solve your problem of assigning a unique id, as the partial to be included is only rendered once (server-side), and then inserted again and again in the browser.

**Comment by gonzag88** [comment]
jaja i'm really sorry for the attack. I've just answer in SO (before reading this), but i will continue here only so you don't have to answer twice (if a solution comes up, i will copy it to SO by my own).
Gem version is *1.2.6*. And thanks for the second comment, i didn't realize about that.

**Comment by joseluistorres** [comment]
@gonzag88 do you still have this problem? have you tried passing the partial in the link_to_add_association
```
<%= link_to_add_association '<span class="glyphicon glyphicon-plus white"></span>'.html_safe, f,
 :sub_budget_items,
                partial: 'budgets/my_partial',
                render_options:  {locals: { parent_item: f.object.item }},
                class: 'btn btn-default btn-sm pull-left' %>
```

**Comment by gonzag88** [comment]
Jose Luis, thanks for the answer. Yes i've tried that too but, again, without success.

**Comment by choonkeat** [comment]
> need every new item created with cocoon to have a different input id

AFAIK, `cocoon` *already* assign a unique id for input fields that matches rails convention. e.g. 
* `parent[children][new_child][name]` will become `parent[children][12345678][name]`
* `parent_children_new_child_name` will become `parent_children_12345678_name`

where `12345678` is the unique id generated by `cocoon.js` and anything that matches `regexp_braced` or `regexp_underscord` will be replaced by this unique id.

> i want to pass a variable to the partial (something like Time.now or similar), and then use it as the id of the input

instead of approaching the problem this way (pass variable), I propose @gonzag88 to piggyback on `regexp_underscord` mechanism instead.

i.e. assuming your cocoon association is `:something`, anywhere you need a unique id, just put `_new_something_` and it will be converted into something like `_1424061403520_` when it renders.

This is a hack though, and would be nice if there's proper option @nathanvda

**Comment by nathanvda** [comment]
@choonkeat imho @gonzag88 just wants to assign a unique html-id to an item or div, which cocoon does not do, it does make sure the input-forms are correctly build, as you say, but it would be very hard to select using that value. 

The suggesting solution (passing variables) should just work, imho. Alternatively I would suggest using a callback, selecting the contained item of a specific class and setting the id as wanted.

**Comment by joseluistorres** [comment]
I did the same thing that @choonkeat mentioned, it works but it feels like a hack obviously, not sure if it's out of the scope of cocoon but creating the item on the fly sometimes requires some special handling in my case to show modals or use other JS plugins

**Comment by nathanvda** [comment]
Passing variables to the render should work (except that the partial is rendered only once). Using a callback is imho the best solution, this what they are there for: manipulate the html or attach events when inserting into the page.

**Comment by choonkeat** [comment]
> Passing variables to the render should work (except that the partial is rendered only once).

yes it "works". and yes, it only renders once, so the value is not unique for new dom elements created by cocoon.

> Using a callback is imho the best solution, this what they are there for: manipulate the html or attach events when inserting into the page.

yes one way would be

``` javascript
$(document).on('cocoon:after-insert', function(e, item) { /* do stuff */ });
```

but it gets hairy when things to replace is more merely a class / id. e.g. inline js

my own case was that
* i use cocoon to add rows to a spreadsheet like table (so far so good)
* on each row, i use cocoon to add columns
* now the `data-association-insertion-node` in each row's cocoon need to be specifically for that row.

yes i can spend time hacking up via cocoon callback functions... but, really, rendering `_new_rows_` and letting `regexp_underscord` do its thing is way simpler & robust

**Comment by seanfcarroll** [comment]
The underscore piggyback worked for me, to create ids for a Bootstrap collapse within the partial

```
  <%# _new_user_languages_x : are piggybacking off javascript in https://github.com/nathanvda/cocoon/blob/master/app/assets/javascripts/cocoon.js %>
    <a data-toggle="collapse" href="#introduction_new_user_languages_x" aria-expanded="false" aria-controls="introduction_new_user_languages_x">
      Introduction
    </a>
  </div>


  <div class="collapse" id="introduction_new_user_languages_x"
      <div class="col-md-10 col-md-offset-2">
     ... etc ...
```
