### ISSUE TITLE
Can't create new objects

### ISSUE THREAD

**Issue by taylorscollon** [nathanvda/cocoon#263]
So I apologize in advance if I'm missing something obvious, but I can't seem to figure this one out. 

I am following the project_tags example, modified for my purposes to be guide_listings. The Guide form has a nested form for Listings, which are then associated with that guide. 

I can select a Listing from the pre-existing list and successfully add it to a Guide. However, I cannot create a new Listing through the link_to_add_association button. 

I'm not getting any errors in my console or terminal.

I don't think this is a bug with the gem, but if anyone has ideas on the issue it would be much appreciated. Thanks!

Here is my relevant code:

models/guide.rb

    class Guide < ActiveRecord::Base
    has_many :guide_listings
    has_many :listings, :through => :guide_listings, :class_name => 'Listing'

models/guide_listing.rb

    class GuideListing < ActiveRecord::Base
    belongs_to :guide
    belongs_to :listing

    accepts_nested_attributes_for :listing, :reject_if => :all_blank
    end

controllers/guide_controllers.html.erb

      def guide_params
        params.require(:guide).permit(
        :user_id, :title, :introduction, :cover, :city_id,
        guide_listings_attributes: [:id, :_destroy, :listing_id],
        listings_attributes: [:id, :_destroy, :name, :long_description, :address, :image]
        )
      end

guides/_form.html.erb

        <%= f.simple_fields_for :guide_listings do |guide_listing| %>
          <%= render 'guide_listing_fields', :f => guide_listing %>
        <% end %>
        <%= link_to_add_association 'Add a listing', f, :guide_listings %>

guides/_guide_listing_fields.html.erb

    <div class="nested-fields guide-listing-fields">
     <div id="listing_from_list">
    <%= f.association :listing, :collection => Listing.all, :prompt => 'Choose an existing listing' %>
    </div>
     <%= link_to_add_association 'Create a new listing', f, :listing %>
     <%= link_to_remove_association "Remove listing", f %>
    </div>

guides/_listing_fields.html.erb 

    <div class="nested-fields">
    <%= f.input :name %>
    <%= f.input :long_description, input_html: {id: "text-edit"} %>
    <%= f.input :address %>
    <%= f.input :image %>
    </div>

**Comment by nathanvda** [comment]
No errors? Then I am guessing a strong parameters issue. I would assume the `listing_attributes` should be nested inside the `guide_listing_attributes` and at least it should be singular. To be sure, can you show what is posted to the controller (check your logfile)? That structure should correspond with your parameters definition.

**Comment by taylorscollon** [comment]
You were right -- I had to nest the attributes. Thank you so much!

**Comment by nathanvda** [comment]
:+1:
