### ISSUE TITLE
Rails 4 / ruby 2.0.0  undefined method `link_to_remove_association' 

### ISSUE THREAD

**Issue by dhirajbajaj** [nathanvda/cocoon#264]
Hey, 
Its working great on local with cocoon (1.2.6). When deployed to production with same config, it is raising issue; 
Production Error: 
```
DEBUG[8b90780f] 	ActionView::Template::Error (undefined method `link_to_remove_association' for #<#<Class:0x007f703b862768>:0x007f703bd8f1f0>):
DEBUG[8b90780f] 	    10:         = f.file_field :attachment,                      :hide_label => true
DEBUG[8b90780f] 	    11:     .col-md-4.col-xs-3.no-margin.no-padding.pull-right
DEBUG[8b90780f] 	    12:       %small
DEBUG[8b90780f] 	    13:         = link_to_remove_association  f, class: 'pull-right' do
DEBUG[8b90780f] 	    14:           %i.fa.fa-times-circle
DEBUG[8b90780f] 	    15:           Remove Document
```

**Comment by nathanvda** [comment]
Seems like the cocoon gem is not installed or not loaded (not required). Cocoon is in your gemfile? When deploying, bundle install will skip development and testing groups, so make sure cocoon is in the correct group.

**Comment by dhirajbajaj** [comment]
EDIT: It was a deployment error; Weird Problem; Cocoon was installed; When deployed next time; it worked; I restarted Puma again though;

Appreciate quick Reply and great Gem.
