### ISSUE TITLE
get Data and put in span.help-block

### ISSUE THREAD

**Issue by laerciocrestani** [nathanvda/cocoon#266]
Hello!

I have the following form:
CODE form.slim
```
= bootstrap_form_for(@obj, layout: :horizontal, label_col: "col-sm-3", control_col: "col-sm-9", html: { id: 'new-edit' }) do |f|
...
#parentescos
  = f.fields_for :parentescos do |p|
    = render 'parentesco_fields', :f => p
```
CODE _acompanhamento_fields.slim
```
.nested-fields
	.form-group
		label.control-label.col-sm-3 Profissional
		.col-sm-7.text-left
			= f.select_without_bootstrap :funcionario_id, User.all.collect {|u| [ u.nome, u.id ] }, {}, { class: "form-control" }
		.col-sm-1.text-centerq
			= link_to_remove_association f, class:"btn btn-warning" do
				=fa_icon "ban fw"
	= f.text_area :acompanhamento_descricao, rows: 3, label: "Histórico", help: dateHour(DateTime.now)

```
My problems: 
```
= f.text_area :acompanhamento_descricao, rows: 3, label: "Histórico", help: dateHour(DateTime.now)
````
I`m print DateTime.now for example, but I wish return created_at data from database, return record created_at from acompanhamento table,

i'm try: 
f.created_at, return:
undefined method `created_at' for #<BootstrapForm::FormBuilder:0xc787e48>
p.created_at, return:
undefined method `created_at' for nil:NilClass

Example from database and form in attach.

Tanks for help.

![captura de tela 2015-02-18 as 18 35 19](https://cloud.githubusercontent.com/assets/1430869/6256180/1b75b290-b79d-11e4-9c16-a7a48c627a19.png)
![captura de tela 2015-02-18 as 18 18 05](https://cloud.githubusercontent.com/assets/1430869/6256181/1bb7c1d0-b79d-11e4-8991-73ed3444f994.png)

**Comment by nathanvda** [comment]
Hi! Thank you to take the time to pose such a well documented question. However, I feel to see the relation to cocoon. 

If you would use `simple_form` you could just write `f.input :created_at`, but I am guessing you are using `rails_bootstrap_forms`, so to answer your question, I have to check the [documentation](https://github.com/bootstrap-ruby/rails-bootstrap-forms) (what: did you just let met google something you could have just google yourself --what am I doing know: I am a free and google-bot now????) you have to write `f.datetime_field :created_at`. 

For future reference: please use stackoverflow.com for questions like this. There are a lot of very skilled people there, that can answer simple questions this (including me).

**Comment by laerciocrestani** [comment]
Okay, thank you,

I would like to print :created_at within a
```
<span class = "help-block"> 02/18/2015 ás 18:17 </ span>
```
and not within a <input> up because that date is not editable in this case.

I have in my Helper:
```
def dateHour (date)
     data.strftime return ("% d /% m /% Y at% H:% M") unless data.present not?
end
```
This helper formats the date for the view but I'm not able to send this variable to my helper handle.

**Comment by nathanvda** [comment]
Please post this question on stackoverflow instead.

**Comment by laerciocrestani** [comment]
I'm recruit!!!! i'm found a solution, see below:
```
= f.text_area :acompanhamento_descricao, rows: 3, label: "Histórico", help: f.object.created_at
```
In this case print created_at(or another data) into a <span> tag, instead <input>

Tanks
