### ISSUE TITLE
Prevent Deletion of a Nested Object?

### ISSUE THREAD

**Issue by brandonparsons** [nathanvda/cocoon#268]
Hi there,

I'm just coming across this library now (ran across my first need for nested forms :( )

I was wondering - with the `before-delete` trigger, how can I stop/cease deletion of a nested object?  I'd like to ensure that there is always at least one nested object, so the user should only be able to remove the item if there are two or more.

Thanks!

**Comment by nathanvda** [comment]
Personally I am not in favour of this, so that is currently not possible. My idea is: why allow a user to press a button, when you actually already know it will be allowed or not. So in those cases: hide the buttons. Less confusing for the user. 

So after deleting a nested element, count how many are left: if only one is left, hide the remove buttons. Dead easy and clean ui. What do you think?

**Comment by thiago-sydow** [comment]
Hello, i have a different situation where this is important. On delete i want to show an alert " Do you really want to delete this?", and only delete if the Confirm button is pressed. Currently i cannot do that because i can't prevent the deletion.

Sounds reasonable for make this feature ?

**Comment by nathanvda** [comment]
@thiago-sydow you can just do 

    = link_to_remove_association "remove task", f, data: {confirm:  'do you really want to do this?'}

**Comment by thiago-sydow** [comment]
Hmm true, my bad. Sorry for that !

**Comment by nathanvda** [comment]
Closed due to inactivity. Spring cleaning :smile:

**Comment by GenaroLegaspiJr** [comment]
> = link_to_remove_association "remove task", f, data: {confirm:  'do you really want to do this?'}

Hi @nathanvda, I did try this solution but clicking "Cancel" still removes an item.

**Comment by GenaroLegaspiJr** [comment]
> @thiago-sydow you can just do
> 
> ```
> = link_to_remove_association "remove task", f, data: {confirm:  'do you really want to do this?'}
> ```

Hi @nathanvda, I did try this solution but clicking "Cancel" still removes an item.

**Comment by nathanvda** [comment]
@GenaroLegaspiJr Please open a  new ticket.

**Comment by aqeelahmad506** [comment]
@nathanvda clicking on Cancel still removes the item. Was this issue fixed?

**Comment by nathanvda** [comment]
Yes, please open a new ticket and show code and versions you are using.

**Comment by aqeelahmad506** [comment]
@nathanvda I just used cocoon:before-remove callback in the JS to prevent deletion. It is working

**Comment by nathanvda** [comment]
Great that you found a working solution. The cancelling of the alert should also still work, since it would prevent the bubbling of the event afaik. But maybe that also depends on which rails version you are using etc.
