### ISSUE TITLE
ActionView::MissingTemplate

### ISSUE THREAD

**Issue by alatebloomer** [nathanvda/cocoon#269]
Hi there,

I am using rails 4.1.6 and ruby 2.1.3p242 and cocoon 1.2.6

.views/recipes/new.html.haml

    .form-horizontal
       = form_for @recipe, :url => recipes_path, :html => { :multipart => true } do |f|
    .form-group
      .col-sm-2.control-label= f.label :title
      .col-sm-6= f.text_field :title, class: "form-control"
    .form-group
      .col-sm-2.control-label= f.label :description
      .col-sm-6= f.text_area :description, rows: 10, class: "form-control"
    .form-group
      .col-sm-offset-2.col-sm-6= f.file_field :image
    .row
      .col-md-6
        %h3 Ingredients
        #ingredients
          =f.fields_for :ingredients do |ingredient|
            = render 'ingredients_fields', f: ingredient
          .links
            = link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button",:partial => 'recipes/ingredients_fields'
     .form-group
      .col-sm-offset-2.col-sm-10
        = f.submit "Create", class: "btn btn-default"

.views/recipes/_ingredients_fields.html.haml

    .form-inline.clearfix
      .nested-fields
        = f.text_field :name, class: "form-control"
        = link_to_remove_association "Remove", f, class: "form-button btn btn-default"

when I access /recipes/new. I got missing partial error message.
![screen shot 2015-03-12 at 2 36 35 am](https://cloud.githubusercontent.com/assets/4966249/6604040/aae56726-c860-11e4-899c-2314d42b4e02.png)

After I change the code in new.html.ham to 
<code> = link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button",:partial => 'recipes/ingredients_fields'</code>
which I add partial code in the end.

Everything works.

Why?

**Comment by nathanvda** [comment]
Cocoon will look by default for the singular form, in your case `ingredient_fields`. As documented. The error even clearly states which view he is looking for. A bit confused what you are asking me here? 

You are free to use the plural, imho it is more logical to use the singular, since you are rendering a single item (from a collection).

**Comment by alatebloomer** [comment]
Thanks for your explanation.
It seems like my bad which I should use singular form not plural.

:)

**Comment by maazbashir** [comment]
have u solve the error
