### ISSUE TITLE
Nested models save, but don't show up on edit form

### ISSUE THREAD

**Issue by tolgap** [nathanvda/cocoon#270]
The form looks as followed:

    #attachment-list
      = f.simple_fields_for :attachments do |af|
        = render "attachment_fields", f: af
      .links
        = link_to_add_association "Add", f, :attachments

In `_attachment_fields.html.haml`:

    .nested-fields
      = f.input :attached_file, as: :file
      = f.input :public,        as: :boolean
      = link_to_remove_association "Remove", f

The form is acting correctly when creating a new model with it's nested `Attachments`, they even save to the database. But when **editing** the same model, the nested models don't show up, even though when debugging, the `model.attachments` is actually populated.

I'm using Rails `4.2.0` and Ruby `2.1.5`.

**Comment by tolgap** [comment]
I just realized this might be a `simple_form` issue, any thoughts?

**Comment by nathanvda** [comment]
If you are just rendering the same form for edit and create, which is standard, if you are rendering the form for the same instance variable, if you can debug and inspect the `attachments` to be there, I have no idea why it would not work. On the other hand: you show very little code, so there could still be a lot of things wrong. The only thing I can think of is you have something like `@model.attachments = []` in your `edit` action ... or your view. That would explain it, but that is a bit far-fetched :)

**Comment by nathanvda** [comment]
Closed due to inactivity.

**Comment by tolgap** [comment]
@nathanvda I forgot about it, sorry. It was due to wrongly configured nested attributes in my controller. :(

**Comment by blackfist** [comment]
@tolgap I'm having the same problem. I was wondering if you could tell me what you were doing wrong in your controller that lead to the problem?

**Comment by ravi4rails** [comment]
This is snippet from my _form.html.erb
`<div>
    <p><strong>images:</strong></p>

    <%= f.fields_for :images do |image| %>
      <%= render 'image',f: :image %>
    <% end %>
    <%= link_to_add_association "Upload Image", f, :images, class: "btn btn-primary" %>
  </div>`

And this is my image partial:

`<div class="nested-fields">
  <%= link_to_remove_association "Remove Image", f, class: "btn btn-danger" %>
  <%= f.file_field :image %>
</div>`

Not the  form works correctly on create action but when try to edit the record i got the following error.

undefined method `object' for :image:Symbol
Did you mean?  object_id

**Comment by Mirv** [comment]
@blackfist ... he did answer your question actually ...

"... wrongly configured nested attributes in my controller... "

For slightly more detail you can read the cocoon front page for strong params ... here's a quick link! 
 https://github.com/nathanvda/cocoon#strong-parameters-gotcha

**Comment by bragamat** [comment]
Hope to get this answer as well!
