### ISSUE TITLE
Nested events

### ISSUE THREAD

**Issue by rikkipitt** [nathanvda/cocoon#271]
Hi guys,

I've got a dynamic form within a dynamic form. The events from the children and bubbling to the parent (cocoon:before-insert)...

Any ideas on how to stop this?

Cheers,

Rikki

**Comment by nathanvda** [comment]
Add a handler on the "children"-container and use `e.stopPropagation()` ?

**Comment by rikkipitt** [comment]
Hi @nathanvda thanks for replying, really appreciated. I tried e.stopPropagation() within the child cocoon:before-insert, but that didn't help. Is that what you are suggesting?

Cheers for the guidance.

**Comment by rikkipitt** [comment]
Just as an update, it's only an issue on the newly created parent children "Add" links...

**Comment by nathanvda** [comment]
Mmmmm ... "newly created parent children" what does that mean? Newly created children of a parent? Newly created children of a newly created parent? Or is a "parent child" something special that I should recognise/know? 

It is hard to say something more sensible without any code.

**Comment by rikkipitt** [comment]
I'll try and get something over to you in a meaningful manner, give me a sec! Cheers!

**Comment by rikkipitt** [comment]
Essentially, this is it with a book analogy instead of my real models. I've taken out actual fields from the partials to keep the below clean and tidy.

Page has_many Chapters which has_many Pages.

The cocoon:before-insert event is triggered on both chapter and page if I add a new "page" from a newly created "chapter". I hope that makes more sense now...

_form.html.erb

```ruby
<%= form_for @page |f| %>
<div id="chapters">
  <%= f.fields_for :chapter do |chapter| %>
      <%= render 'chapter_fields', :f => chapter %>
  <% end %>
  <div class="links">
    <%= link_to_add_association 'New', f, :chapters %>
  </div>
</div>
<% end %>
```

_chapter_fields.html.erb

```ruby
<div class="nested-fields">
  <div id="pages">
    <%= f.fields_for :pages do |page| %>
        <%= render 'page_fields', :f => page %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'New', f, :pages %>
    </div>
  </div>

  <%= link_to_remove_association 'Remove', f %>
</div>
```

_page_fields.html.erb

```ruby
<div class="nested-fields">
  <%= link_to_remove_association 'Remove', f %>
</div>
```

**Comment by rikkipitt** [comment]
And the javascript is:

```javascript
$("#chapters a.add_field").
        data("association-insertion-method", 'append').
        data("association-insertion-node", '#chapters');

    $("#pages a.add_field").
        data("association-insertion-traversal", 'children');

    $('#pages')
        .on('cocoon:before-insert', function(e) {
            e.stopPropagation(); // This only helps prevent the first chapter page insertion from "bubbling"
        })
        .on('cocoon:after-insert', function() {})
        .on("cocoon:before-remove", function() {})
        .on("cocoon:after-remove", function() {});

    $('#chapters')
        .on('cocoon:before-insert', function(e, added) {
            // This gets executed for a "page" insert...
        })
        .on('cocoon:after-insert', function() {})
        .on("cocoon:before-remove", function() {})
        .on("cocoon:after-remove", function() {});
```

**Comment by nathanvda** [comment]
In your real code, are you also using an id instead of a class (#pages) because that is probable cause for problems.

**Comment by nathanvda** [comment]
I see two problems: you are now binding events to dom-elements that are on the page when the js is executed. But the `chapter_fields` are added dynamically. Secondly you use an id `#pages` for a DOM-element which is repeating. So replace the id with a class, and the [.on()](http://api.jquery.com/on/) allows to specify a selector for dynamically added elements.

You will have to write your chapter-fields as follows (haml for brevity and clarity):

    .nested-fields
      .chapter-pages
        = f.fields_for :pages do |page|
          = render 'page_fields', :f => page
        links
          = link_to_add_association 'New', f, :pages %>

      = link_to_remove_association 'Remove', f %>

... and then in your javascript define a handler for the pages:

    $('#chapters')
        .on('cocoon:before-insert', '.chapter-pages', function(e, added) {
            // this gets executed for insert inside the pages
            e.stopPropagation():
   
        })
        .on('cocoon:before-insert', function(e, added) {
            // This gets executed for any page insert, since the pages do not propagate, it will only
            // handle chapter insertions
        })

Is that clear?

**Comment by nathanvda** [comment]
Not sure if it was not clear, and OP abandoned the problem, or it was clear and the OP was helped. Without more feedback I assume the OP was helped.

**Comment by rikkipitt** [comment]
Sorry @nathanvda, it did help thanks a lot!
