### ISSUE TITLE
File upload renders json response in browser

### ISSUE THREAD

**Issue by justinxreese** [nathanvda/cocoon#273]
I'm adding a file upload form with cocoon. I've removed some things for clarity and privacy, but this is hopefully enough. Here is the diff and the new attached_file_fields partial

```diff
diff --git a/app/controllers/work_groups_controller.rb b/app/controllers/work_groups_controller.rb
index 26bb1f4..e691740 100644
--- a/app/controllers/work_groups_controller.rb
+++ b/app/controllers/work_groups_controller.rb
@@ -271,6 +271,10 @@ class WorkGroupsController < ApplicationController
                                          :experience, :notes
+                                         attached_files_attributes: [:id, :attachable_id,
+                                           :attachable_type, :name, :type,
+                                           :file, :work_group_id,
+                                           :size, :url, :_destroy],
                                          redacted_things_attributes: [:id],

diff --git a/app/models/attachment.rb b/app/models/attachment.rb
index 3961a01..ebb236b 100644
--- a/app/models/attachment.rb
+++ b/app/models/attachment.rb
@@ -1,4 +1,5 @@
 class Attachment < ActiveRecord::Base
+  belongs_to :work_group
   belongs_to :attachable, polymorphic: true
   belongs_to :user
   mount_uploader :file, AttachmentUploader

diff --git a/app/models/work_group.rb b/app/models/work_group.rb
index cc1942d..d7eb409 100644
--- a/app/models/work_group.rb
+++ b/app/models/work_group.rb
@@ -8,6 +8,7 @@ class WorkGroup < ActiveRecord::Base
   has_many :attached_files, -> { order('created_at DESC') }, class_name: 'Attachment'
+  accepts_nested_attributes_for :attached_files, allow_destroy: true, reject_if: lambda {|a| a[:file].blank?}

diff --git a/app/views/work_groups/new.html.erb b/app/views/work_groups/new.html.erb
index cb34e42..c4c942c 100644
--- a/app/views/work_groups/new.html.erb
+++ b/app/views/work_groups/new.html.erb
@@ -26,7 +26,8 @@
       <strong>Success!</strong> Your progress has been saved.
   </div>
 
-<%= simple_form_for @work_group, html: {id: :new_work_group}, remote: true, format: :json do |f| %>
+<%= simple_form_for @work_group, html: {id: :new_work_group, multipart: true}, remote: true, format: :json do |f| %>
+  <%= token_tag %>
   <div class="onboarding-wizard">

diff --git a/app/views/work_groups/steps/_step3.html.erb b/app/views/work_groups/steps/_step3.html.erb
index 4be9b01..588aa5a 100644
--- a/app/views/work_groups/steps/_step3.html.erb
+++ b/app/views/work_groups/steps/_step3.html.erb
@@ -103,8 +103,20 @@
               </tr>
             </thead>
+            <tbody id="work-group-files-3">
+              <%= f.simple_fields_for :attached_files, f.object.attached_files.build do |attached_file| %>
+                <%= render 'attached_file_fields', f: attached_file %>
+              <% end %>
+            </tbody>
+          </table>
-          <a href="#" class="btn btn-primary pull-right" style="margin-top: 20px">+ Add a Report</a>
+              <%= link_to_add_association '+ Add a Report', f, :attached_files, {:"data-association-insertion-node" => "tbody#work-group-files-3", :"data-association-insertion-method" => "append"} %>

```

Partial
```erb
<tr class="nested-fields">
  <td>
    <%= f.input :id, as: :hidden %>
    <%= f.association :work_group, as: :hidden, input_html: {class: :work_group_association} %>
    <%= f.file_field :file %>
  </td>
  <td>
    <%= link_to_remove_association image_tag('remove-member.png'), f %>
  </td>
</tr>
```

When I submit the form, instead of handling the response with the javascript (as it did before), it is rendering the json response in the browser. Not sure what is going on here.

**Comment by justinxreese** [comment]
One thing that I'm working toward fixing is the association in the nested-fields should be to the polymorphic `Attachable`, but that's another issue. Just might see some relics of that in here.

**Comment by nathanvda** [comment]
Hmmmm confused. I seem to be missing some context. Showing diffs of code I have never seen before? Wrong repository?

**Comment by justinxreese** [comment]
I just thought a diff was a straightforward way to show the changes i've made to an existing form to try to add file uploads using cocoon. For some reason, it is changing how the form acts when it is submitted. 

You can see that I've only added multipart true and now it causes a form that used to submit remotely to render a response in the browser. `simple_form_for @work_group, html: {id: :new_work_group, multipart: true}, remote: true, format: :json do |f| %>`

**Comment by nathanvda** [comment]
Mmmmm using cocoon does not change how a form is posted, it only allows to dynamically add extra fields inside the form (form-content). 

So imho this problem is not cocoon related at all.

You did add some code to your controller as well, right? Why do specify format json? How do you handle the returned json? I generally do not specify a format (default is just js) and add js views that will do the updating.

**Comment by justinxreese** [comment]
So the controller just returns a formatted response with the created/updated entity
```ruby
class WorkGroupsController < ApplicationController
  def update
    respond_to do |format|
      if @work_group.update(work_group_params)
        format.json { render json: {work_group: @work_group, members: @work_group.work_group_memberships}, status: :ok, location: @work_group }
      else
        format.json { render json: @work_group.errors, status: :unprocessable_entity }
      end
    end
  end
end
```

I then listen on ajax events to do things with the formatted json

```coffee
  $('#new_work_group').on('ajax:error', (xhr, status, error) ->
    enable_form()
    clear_errors()
  ).on('ajax:success', (xhr, status, error) ->
    enable_form()
    clear_errors()
    do_some_stuff_with_the_json(status)
  ).on 'ajax:send', (xhr, status, error) ->
    disable_form()
```

**Comment by nathanvda** [comment]
So it looks like your javascript/handlers is not triggered?

**Comment by justinxreese** [comment]
Even more so, the form isn't submitting remotely anymore.

**Comment by nathanvda** [comment]
Things I can think of to verify: 

- check the `<form>` line in the html, if it still contains the `data-remote` option? 
- check/log in the controller if it is a `xhr` request? (`request.xhr?`)
- maybe you have a javascript error somewhere, which causes the `data-remote` to be skipped/the handlers to be skipped

Still not a cocoon problem though, so maybe best ok this question on stackoverflow?

**Comment by justinxreese** [comment]
Sure thing. I'll check those things and move it over there. Unless the javascript error is somewhere in cocoon, you're probably right. But I don't see any anyways.

**Comment by nathanvda** [comment]
Solved?

**Comment by justinxreese** [comment]
Not really. I was able to solve the problem with remotipart that was pushing me down the road of doing it this way

**Comment by nathanvda** [comment]
Ok. I generally use something like jqeury file upload or dropzone, and let my serverside handle the nested stuff. Easier for the user: just drop a bunch a files :smile: But good you got it solved.

**Comment by justinxreese** [comment]
I'll have to look at those. I'm guessing they play well with cocoon if you use them! Really appreciate cocoon

**Comment by nathanvda** [comment]
Cocoon works fine for doing file-uploads, it is just not as user-friendly as using dropzone or jquery file upload. So I generally do _not_ use cocoon for doing multiple file upload. It is way easier to just drop a bunch of files, and let the server side handle an array of files instead of a single one.
