### ISSUE TITLE
Cocoon image upload preview 

### ISSUE THREAD

**Issue by ImtiazEmu** [nathanvda/cocoon#276]
I want to show the uploaded image preview in a specifc div inside the partial. But as there are same divs within my current page, so if I want to show the preview, the preview always show to the top div. Could you please help?

**Comment by ImtiazEmu** [comment]
<div class="row nested-fields">
  <div class="col-lg-8 field">
    <div class="gallery-images">
      <% if f.object.picture.present? %>
        <%= image_tag f.object.picture_url, :class=> "gallery-preview-image" %>
      <% else %>
        <img class="gallery-preview-image" src="" alt="your uploaded image" />
      <% end %>
    </div>
    <div class="clearfix"></div>
    <div class="gallery-image-text">
      <%= f.label :text %><br />
      <%= f.text_field :text %>
      <%= f.hidden_field :gallery_id, :value => @gallery.id %>
    </div>
  </div>
  <div class="col-lg-4 field">
    <p>
      <%= f.label :position %><br />
      <%= f.text_field :position %>
      <%= f.file_field :picture, :id => "upload-gallery-picture", :style => "display: none;" %>
      <%= f.hidden_field :picture_cache, :value => f.object.picture_cache %>
      <%= link_to t('seller_home.gallery.upload_picture').html_safe, "javascript:;", :id => "upload-gallery-picture-link", :onclick => "browseFiles(this);" %>
    </p>
  </div>
  <div class="remove-gallery-image-link">
    <%= link_to_remove_association t('seller_home.gallery.remove').html_safe, f  %>
  </div>
</div>

<script>

    function browseFiles(){
        $("#upload-gallery-picture").trigger("click");
        changeOfFile();
    }

    function changeOfFile(){
        $("#upload-gallery-picture").change(function(){
            thumbImage(this, $(this).parents('.nested-fields').find('.gallery-images').find('.gallery-preview-image'));
        });
    }

    function thumbImage(input, selecttor) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            console.log(selecttor);
            reader.onload = function (e) {
                $(selecttor).attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }


</script>

**Comment by nathanvda** [comment]
Please ask this question on stackoverflow.com. If you post the link here, I will take a look.

**Comment by ImtiazEmu** [comment]
http://stackoverflow.com/questions/29428663/cocoon-gem-image-upload-with-preview
