### ISSUE TITLE
Nested models with has_and_belongs_to_many model

### ISSUE THREAD

**Issue by neoriddle** [nathanvda/cocoon#278]
Does cocoon support nested model with `has_and_belongs_to_many` association?
If it does, can you post some example?
Thank you!

**Comment by nathanvda** [comment]
The `has_and_belongs_to_many` is identical to the `has_many :through`, except the join table/model is implicit. So I always use the `has_many :through`. I assume it would just work, but the problem (to me) is, e.g. linking tags to projects, I want my tags to be shared between projects, and that is the easiest when you create the join-model explicitly. So you will need to be able to access the join model explicitly imho. 

So I would generally advice to use `has_many :through` instead.

Care to elaborate on what you are trying to do? Did you try something and it didn't work?

**Comment by nathanvda** [comment]
Closed due to inactivity.

**Comment by gregblass** [comment]
Just wanted so say that I just quickly refactored a `has_and_belongs_to_many` relationship to a `has_many_through` relationship and was able to use this to get what I needed working:

https://github.com/nathanvda/cocoon/wiki/A-guide-to-doing-nested-model-forms#the-has_many-through-relation

@thanks @nathanvda!
