### ISSUE TITLE
Ensure number of nested forms

### ISSUE THREAD

**Issue by jmarceli** [nathanvda/cocoon#279]
I'm looking for the way to ensure exactly four nested fields_for tags without forcing user to click "add fields" four times. Is it possible to define somewhere in cocoon that it should display four nested elements?

The only workaround/solution for this problem which I came up with is to override `initialize` function for the parent model:
```ruby
Class Order < ActiveRecord::Base
def initialize
  super
  items << Item.new
  items << Item.new
  items << Item.new
  items << Item.new
end
end
```
It's not the best solution because now I'm not able to create `Order` object without `items`.

**Comment by jmarceli** [comment]
I'm sorry it was silly question. It is not connected with `cocoon` of course. The solution is just to print `fields_for` four times ...
```ruby
        - 4.times do
          = f.simple_fields_for :items do |item|
            = render 'item_fields', f:item
```
I'm sorry for the spam.

**Comment by nathanvda** [comment]
Actually, that is not the way I would suggest to solve it. Do not change the model or the view, except in your controller, write something like

    def new
      @order = Order.new
      4.times { @order.items << Item.new }
    end

This way you will only add 4 empty items when you need them (e.g. when creating a new order), and your view will still work when editing existing items, and your model will not add 4 empty items even if it is retrieving an existing order from the database.

**Comment by jmarceli** [comment]
Thanks, when I realized that this question is not connected with `cocoon` I asked it on stack. I'll continue there http://stackoverflow.com/questions/29471462/ruby-on-rails-4-fields-for-number-of-repetitions/29471624#29471624
