### ISSUE TITLE
link_to_remove_association not working

### ISSUE THREAD

**Issue by anand9** [nathanvda/cocoon#284]
Hi, 
When i click link_to_remove_association nothing is happening , but link_to_add_association
This is what i did 

```
= f.simple_fields_for :key_activities do |k|
  = render 'key_activity_fields', :f => k
%div
  = link_to_add_association 'Add New', f, :key_activities, :class=>"new-btn"
```
in the partial key_activity_fields
```
.form-group
  = f.input :name , :placeholder => "Key activities", :label => false, :input_html=> {:class => "form-control"}
  = link_to_remove_association "remove key_activity", f,  data: {confirm: 'Are you sure?'}
```

When i click remove key activity, nothing happens . I am not sure whats missing :(

**Comment by nathanvda** [comment]
The `link_to_remove_association` relies on a wrapper class, default this is `.nested-fields`. You can also overrule this using the `wrapper_class` option. Check the [documentation](https://github.com/nathanvda/cocoon#link_to_remove_association)

**Comment by nathanvda** [comment]
Closing because OP did not respond, so I guess it is ok.

**Comment by anand9** [comment]
Sorry for the late reply, Thanks a lot it worked :+1:

**Comment by Tokinh0** [comment]
> relies

hi guys
I'm working in something with rails, and I using this gem, but how I'm a beginner and such a dum, I don't know how can I wrapper my class to pass as argument with the option wrapper_class, to create a link_to_remove_association. someone on 21 century can help me ?

please forgive my bad english, I'm learning the language too.
