### ISSUE TITLE
Name of local variables through two partials

### ISSUE THREAD

**Issue by allenwlee** [nathanvda/cocoon#286]
I don't know if this is a cocoon issue, but I found that my form doesn't work if I use a custom variable (in my case, `pt`) instead of `f`.  I am passing down locals through an embedded partial because I had read somewhere that the name of the `fields` partial is important.  The code below works:
###### models (just showing Ticket)
```
class Ticket < ActiveRecord::Base
  has_many :goods_tickets
  has_many :goods, through: :goods_tickets
  has_many :services_tickets
  has_many :services, through: :services_tickets
end
```
###### tickets/new.html.erb
```
@product_types = ['Good'.constantize, 'Service'.constantize]
```
###### new.html.erb
```
<%= form_for @ticket do |ticket| %>
    <% @product_types.each do |p| %>
       <%= ticket.fields_for "#{p.name.downcase}s_tickets".to_sym do |pt| %>
           <%= render "#{p.name.downcase}s_ticket_fields", { f: pt, product_type: p } %>        
       <% end %>
       <%= link_to_add_association "Add a #{p.name}", ticket, 
           "#{p.name.downcase}s_tickets".to_sym, 
           render_options: { locals: { product_type: p } }, class: 'btn btn-default' %>
    <% end %>
<% end %>
```
###### _goods_ticket_fields.html.erb
`<%= render 'ticket_fields', { f: f, product_type: product_type } %>`
###### _services_ticket_fields.html.erb
`<%= render 'ticket_fields', { f: f, product_type: product_type } %>`
###### _ticket_fields.html.erb
```
<%= f.fields_for product_type.name.downcase.to_sym do |p|  %>
      <%= p.select "#{product_type.classification_name.downcase}_id", 
              options_for_select(@classes), { include_blank: @placeholder}, 
              { class: "search-item form-control menu-select2" } %>  
      <label for="product-name"><%= product_type.name %> Name*</label>
      <%= p.text_field :name, 
            { class: "form-control #product_type.classification_name.downcase}-name", 
              placeholder: "Type in the name of your service, e.g., 'Pacific Cod'" } %>
<% end %>
```

but if i replace `f` in line 3 of `new.html.erb` with `pt`, and adjust all the references accordingly, I get the following error:
```
Showing .../app/views/tickets/_goods_ticket_fields.html.erb where line #1 raised:

undefined local variable or method `pt' for #<#<Class:0x007ffd940cabb8>:0x007ffd934c2208>
Extracted source (around line #1):
1
              
<%= render 'ticket_fields', { f: pt, product_type: product_type } %>

Trace of template inclusion: app/views/tickets/new.html.erb
```

**Comment by nathanvda** [comment]
The problem is this line 

    render "#{p.name.downcase}s_ticket_fields", { pt: f, product_type: p } %> 

You assign a local variable `pt` the value of `f` and i think that should be the other way round :smile: 

Your local variable is called `pt`. So you could just write `pt: pt` and use `pt` in the lower partials (e.g. `goods_ticket_fields`). But as it is written now, you use `f` and it is not defined, and `pt` is set to an undefined `f`.

**Comment by nathanvda** [comment]
Wait: the rest of your explanation does not make sense? I see no definition of `f` in the `new.html.erb`, only `pt`. :confused:

**Comment by allenwlee** [comment]
i understand what you are saying, but i've tried all variations and the result is the same.  for example:
```
Showing .../nk/app/views/tickets/_goods_ticket_fields.html.erb where line #1 raised:

undefined local variable or method `pt' for #<#<Class:0x007ffd8d0979b8>:0x007ffd8e1b1a00>
Extracted source (around line #1):
1
              
<%= render 'ticket_fields', { pt: pt, product_type: product_type } %>
```

**Comment by allenwlee** [comment]
> Wait: the rest of your explanation does not make sense? I see no definition of f in the new.html.erb, only pt.
sorry that was a typo.  fixed.

**Comment by nathanvda** [comment]
First off: this is not a cocoon issue. You are just handing down local parameters down to partials, and that fails. Not cocoon, but rails. The error clearly says that `pt` is not defined, so in the original top-line is the error imho.

It should be easy, probably a typo causing the problem. :smile: 
If you have a repo with the error, I can take a look. Or make a gist with the failing code.

**Comment by allenwlee** [comment]
Nathan,
thanks for offer and I appreciate your promptness.  Since I did solve my issue by just changing the local variable, I'm ok for now.  I just wanted to document this incident in the event that someone else runs into it.  I'm still a bit baffled by what happened but don't think it's worth our time to investigate further.

**Comment by hounsellal** [comment]
Thank you for writing this. I can confirm that the letter "f" MUST be used in order for cocoon to work. I got the exact same error when I simple switched all "f" to "a". I am 100% sure that every single reference was correct. I think you guys should look into this.

**Comment by nathanvda** [comment]
I do not think that was the same issue as the OP was making, check the documentation for [link_to_association](https://github.com/nathanvda/cocoon#link_to_add_association): if you want to use a different parameter, use the parameter `form_name` to overrule, by default it is indeed `f`.

**Comment by mkok11019** [comment]
Hello @allenwlee!
I used netsted form recently for now. But I don't feel comfortable because, I want to use a local variable with children partial.  
```

<%= link_to_add_association f, :tickets, class: 'ticket-btn btn', partial: 'ticket_fields_free', id:@event.tickets.size,
  :render_options => {:wrapper => 'table_input' }, data: {"association-insertion-node" => "tbody.tickets", "association-insertion-method" => "append"} do %>
```

I want to use a variable within ficket_fields_free.erb.  could you give me a solution?

**Comment by nathanvda** [comment]
Hello @mkok11019!! Please open a different issue if using the parameter `form_name` does not work for you?

**Comment by mkok11019** [comment]
Hello @nathanvda !
I want to pass a temporary variable to partial

**Comment by mkok11019** [comment]
Hello @nathanvda !
my modal works well, but I need to add it to a specific dom within partical view.

```
<tr class='nested-fields'>
  <td width="45%"><%= f.input :name, placeholder: 'Name*' %></td>
  <td><%= f.input :quantity, placeholder: 'Quantity*' %></td>
  <td>Free <%= f.input :base_price_cents, as: :hidden, :input_html => { :value => "0" } %>  
    <%= f.input :is_active, :input_html => { :value => "1" } %></td>
  <td class='text-center'>
    <%= link_to "#", data: { toggle: 'collapse', target: '#ticketSetting' } do %>
      <%= image_tag "https://s3-us-west-1.amazonaws.com/bluelayoutimages/settings.svg", class: 'pl-10' %>
    <% end %>
      </td>
</tr>
<%= render 'ticket_settings' %>
```
I want to use a temporary variable within ticket_seetings
ticket_settings.
