### ISSUE TITLE
Feature request "Partial layout"

### ISSUE THREAD

**Issue by woto** [nathanvda/cocoon#293]
Hi, is there a way to use [partial layout](http://guides.rubyonrails.org/layouts_and_rendering.html#partial-layouts) feature?

Something like this

```
partial: 'photo_fields', render_options: { layout: 'item' }, :data => {
```

which content may  be like this

**__item.html.erb**_

```
<% binding.pry %>
<% if f.object.marked_for_destruction? %>
  <%= hidden_field_tag("#{f.object_name}[_destroy]", '1') %>
<% else %>
  <div class="nested-fields well">
    <%= f.input :collectionable_type, as: :hidden %>
    <%= f.fields_for :collectionable do |c| %>
      <%= yield %>
    <% end %>
    <%= link_to_remove_association "Удалить", f, data: {confirm: 'Уверены, что хотите удалить?'} %>
  </div>
<% end %>
```

**Comment by nathanvda** [comment]
Good call. Quite unusual usecase. But also very simple to reproduce without any change, right? 

In your `_photo_fields.html.haml` you can just write

    = render `collectionable_photo_fields`, layout: 'item' 

Right? Then it would just work.

**Comment by woto** [comment]
I thought about this, but then i must to create 1 additional file for each ..._fields
I understood correctly?

**Comment by nathanvda** [comment]
Going through my old issues, and re-reading this one I do not see what is actually blocking this inside cocoon? 

Either the example given is bad, but cocoon just needs a partial per single nested item (that is required), but you still have that.  Cocoon only renders a partial in the `link_to_add_association`, what you do in the rest of the view does not matter ;)

**Comment by nathanvda** [comment]
Closed due to inactivity.
