### ISSUE TITLE
Duplicate entries on double nested form

### ISSUE THREAD

**Issue by dmastylo** [nathanvda/cocoon#294]
When editing the given ```game``` the perimeter points are duplicated. If there are 4 points, 8 show up in the DOM, four of them referencing the ones in the DB (with id values), and four that are exact copies of the lat/lng values, but without any IDs.

```ruby
def edit
  @game = Game.includes({ perimeters: :perimeter_points }).find(params[:id])
end
```

Form
```erb
<%= form_for(@game) do |f| %>
  <div class="locations">
    <div class="perimeters hidden">
      <%= f.fields_for :perimeters do |p| %>
        <%= render 'perimeter_fields', f: p %>
      <% end %>
  
      <div class="links">
        <%= link_to_add_association 'Add Perimeter',
            f,
            :perimeters,
            class: "button radius expand" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="large-12 columns">
      <%= f.submit class: "button radius expand hidden", id: 'submit-button' %>
    </div>
  </div>
<% end %>
```

_perimeter_fields.html.erb
```html
<div class="perimeter nested-fields">
  <%= link_to_remove_association "remove perimeter", f,
      class: "button radius alert" %>

  <div class="perimeter-points">
    <%= f.fields_for :perimeter_points, :wrapper => 'inline' do |pp| %>
      <%= render 'perimeter_point_fields', f: pp %>
    <% end %>

    <div class="links">
      <%= link_to_add_association 'Add Perimeter Point',
          f,
          :perimeter_points,
          :render_options => { :wrapper => 'inline' },
          class: "button radius expand perimeter-point-button" %>
    </div>
  </div>
</div>
```

_perimeter_point_fields.html.erb
```html
<div class="nested-fields perimeter-point">
  <div class="field">
    <%= f.hidden_field :lat, class: "lat-field" %>
  </div>

  <div class="field">
    <%= f.hidden_field :lng, class: "lng-field" %>
  </div>

  <%= link_to_remove_association "remove point", f,
      class: "button radius alert remove-point-button" %>
</div>
```

**Comment by nathanvda** [comment]
From the code I do not see anything out of the ordinary, that would explain the behaviour. Also cocoon does not automatically "add" new elements. Do you automatically build perimeter-points for a perimeter in your model, e.g. in a `after_initialize`? That is executed always, also when loading it from the database.

You would be able to reproduce this in the rails console, by just loading a `game` from the database.

**Comment by dmastylo** [comment]
Thanks for the quick response @nathanvda.

I don't have any after_initialize or auto-building code. Cannot reproduce this in rails console.

```ruby
class Perimeter < ActiveRecord::Base

  # Validations
  # ============================================================================
  validate :greater_than_3_points

  # Relationships
  # ============================================================================
  belongs_to :game

  has_many :perimeter_points, dependent: :destroy
  accepts_nested_attributes_for :perimeter_points

private

  def greater_than_3_points
    if perimeter_points.length < 3
      errors.add(:base, 'You must have three perimeter points to create a perimeter.')
    end  
  end

end
```

```ruby
class PerimeterPoint < ActiveRecord::Base

  default_scope { order('sequence ASC') }

  # Validations
  # ============================================================================
  validates :lat, presence: true
  validates :lng, presence: true
  validates :sequence, presence: true

  # Relationships
  # ============================================================================
  belongs_to :perimeter

end
```

**Comment by nathanvda** [comment]
I do not see anything wrong in your code as you post it. Cocoon will not create new elements, and definitely not copies of existing elements (technically the link_to_add_association creates a new _empty_ element).

So I am bit baffled. Pretty sure there must be some other problem.
I am willing to take a look if you a github project that can reproduce this.

**Comment by dmastylo** [comment]
I do have a project although I don't think I can give you access to it, do you have any idea what this could be other than the after_initialization callback (which I don't have)? Pretty baffled as well.

**Comment by nathanvda** [comment]
I see no error in the code you showed, so i am assuming the error is somewhere else. If you make a minimal rails site that reproduced the error, i will take a look (if you can't give me access to your code now). I cannot do more than that at the moment :smile: 

Where could you expect such duplication: if your strong parameters do not allow the id, after saving duplicates will be added. But this is not the same as what you described. If you have some javascript that "somehow" copies parts of the form (and blanks the id?), if you have some code in the model or controller that adds new perimeterpoints (but then why would they be identical except for the id??).

**Comment by jmrepetti** [comment]
I had a similar problem and was because I didn't permitted the ID parameter of the nested model in the controller. Now works as expected after allowing the ID parameter.

**Comment by sabril** [comment]
I had similar problem but the cause was because I called the cocoon in application.js twice.
