### ISSUE TITLE
[parent has_one child_group has_many children] only saving child_group on create (but working great on update ^^)

### ISSUE THREAD

**Issue by sebabouche** [nathanvda/cocoon#296]
Hi, thanks for this gem which is great and saved me so much work. But this time, I'm lost.
I need to instantiate the *parent* and the *first child*  at the same time. It's important to me because I can't always instantiate the child in my controller (there is another _DivorcedParent_ with the same
 polymporphic relationship I'm not showing here that shares the same result – working on update but not on create).
## Here are my models:

    class Parent < ActiveRecord::Base
        has_one :child_group, as: :child_groupable, dependent: :destroy
        has_many :children, through: :child_group
        accepts_nested_attributes_for :child_group, :reject_if => :all_blank, :allow_destroy => true
        accepts_nested_attributes_for :children, :reject_if => :all_blank, :allow_destroy => true
        after_initialize :init
        private
        def init 
            if new_record?
                self.build_child_group
            end
        end
    end

(the after_initialize is cool because it creates the ChildGroup child automatically but might be the source of all evils)

    class ChildGroup < ActiveRecord::Base
        belongs_to child_groupable, polymorphic: true
        has_many :children, dependent: :destroy
    
        accepts_nested_attributes_for :children, :reject_if => :all_blank, :allow_destroy => true
    end
And the grand child:

    class Children < ActiveRecord::Base
        belongs_to :child_group
    end
## Now the controller:
    class ParentsController < ApplicationController
        def index
            @parents = Parent.all
        end
    
        def show
            @parent = Parent.find(params[:id])
        end
    
        def new
            @parent = Parent.new
        end
    
        def edit
            @parent = Parent.find(params[:id])
        end
    
        def create
            @parent = Parent.new(parent_params)
        
            if @parent.save
                redirect_to parent_path(@parent), notice: 'Parent created'
            else
                render 'new'
            end
        end
    
        def update
            @parent = Parent.find(params[:id])
    
            if @parent.update_attributes(parent_params)
                redirect_to parent_path(@parent), notice: 'Parent updated.'
            else
                render 'edit'
            end
        end
    
        def destroy
            Parent.find(params[:id]).destroy
            redirect_to parents_path, notice: "Parent deleted"
        end
      
        private
      
        def parent_params
            params.require(:parent).permit(:title, :description, :published, 
                child_group_attributes: [:id, :_destroy, children_attributes: [:id, :_destroy]])
        end
    end
### parents/fields.html.slim
    = f.error_notification
    = f.input :title
    = f.input :description
    = f.simple_fields_for :child_group do |child_group|
        = render 'child_group_fields', :f => child_group
    = f.submit
### parents/child_group_fields.html.slim
    .nested-fields
        p 
            strong Children
        .children
            = f.simple_fields_for :children do |child|
                = render 'child_fields', :f => child
            .links
                = link_to_add_association 'Add child', f, :children
                = link_to_remove_association "Remove child", f
### parents/child_fields.html.slim
    .nested-fields
        = f.input :child_attribute

**Comment by nathanvda** [comment]
A bit confusing, your example code lists `tag_rating_group`, but I guess that is the name in your project for `child_group`. 

Instead of using an `after_initialize`, which is _always_ executed, also when fetching existing records form the database, I should just create the new elements when needed. 

It is a bit confusing where you want to instantiate the first child? For a parent (a child-group): just do it in the controller. Or when initializing a `child-group`? then do it in the `link_to_add_association`. There is an option to do some extra work when creating a new object, in the [`link_to_add_association`](https://github.com/nathanvda/cocoon#wrap_object). 

I do not see a `link_to_add_association` for `parent`. So, I assume it always has one `child_group`. So in the controller do something like

    def new 
       @parent = Parent.new
       @parent.build_child_group
    end 

If you would have an object creating on a `link_to_add_association` you could write

```
    = link_to_add_association('add child group', @form_obj, :child_groups,
       :wrap_object => Proc.new { |child_group| child_group.children.build; child_group })
```

**Comment by sebabouche** [comment]
Thank you for your fast answer and Oh sorry, you are right, I forgot to change those names. I'll do it right now and I'll answer right after ;) 
and by the way I'll add the other controller (with another layer) where I can't use the solution you provided.

**Comment by sebabouche** [comment]
Here is the other controller. I read your answer, I'll give a try to the Proc technique.
And if I don't succeed, I'll have to give another try to reform and Trailblazer's architecture ^^

## The GrandParent controller:
    class GrandParentController < ApplicationController
        def index
            @grand_parents = GrandParent.all
        end
    
        def show
            @grand_parent = GrandParent.find(params[:id])
        end
      
        def new
            @grand_parent = GrandParent.new
        end
      
        def create
            @grand_parent = GrandParent.new(grand_parent_params)
            
            if @grand_parent.save
                redirect_to grand_parent_path(@grand_parent), notice: 'GrandParent créée.'
            else
                render "new"
            end
        end
      
        def edit
            @grand_parent = GrandParent.find(params[:id])
        end
      
        def update
            @grand_parent = GrandParent.find(params[:id])
            
            if @grand_parent.update_attributes(grand_parent_params)
                redirect_to grand_parent_path(@grand_parent), notice: "GrandParent mise à jour."
            else
                render "edit"
            end
        end
      
        def destroy
            GrandParent.find(params[:id]).destroy
            redirect_to grand_parents_path, notice: "GrandParent supprimée."
        end
        
        private
        
        def grand_parent_params
            params.require(:grand_parent).permit(:title, :description, 
                divorced_parent_attributes: [:id, :_destroy, :title,
                    child_group_attributes: [:id, :destroy, children_attributes: [ :id, :_destroy, :title]
            ]])
        end
    end

**Comment by nathanvda** [comment]
Normally it should just work. Of course going the trailblazer route is also fine :smile:

You do understand just dropping this `grandparents_controller` here, without any indication what the relation is to the above, makes it a bit confusing/mystifying. I can imagine stuff (a lot of stuff), but I do not understand why this example suddenly proves you could not do it in the controller.

Of course, from the outside having a grand-parent class is a bit confusing to me, as that actually just is the parent of a parent. And a parent is a person, which is also a child. So I would model that entirely differently I guess (but I am guessing you are just using "fake" classes to show the examples).

**Comment by sebabouche** [comment]
You are totally right, I edited the previous answers.

**Comment by sebabouche** [comment]
I close this issue as I totally changed my structure and cocoon is now working like a charm (I'm not ready for the reform way so fas) ;)

By the way I'm have trouble with cocoon and bootsy (a WYSIWG form editor when it's nested with cocoon, I think the problem is more on their side but I just let you know in case. It's right here : https://github.com/volmer/bootsy/issues/153
