### ISSUE TITLE
undefined method `object' for nil:NilClass

### ISSUE THREAD

**Issue by jerome2** [nathanvda/cocoon#297]
i follow the doc and have this error when try to render the edit form:
undefined method `object' for nil:NilClass

my nested links works (show it on rails console)
this point me the error only when i add then:

    = link_to_remove_association f

inside the partial `_photo_fields.haml` embeded form called from the edition `_form.haml`
The model simple_form around model photo is well rended without... i also have a dragonfly "photo" uploader linked to this model, but all of this works, i try to add cocoon after that.

i use simple_form and rails-4.2.2, also dragonfly for link images; and have js files rend my the views (edition) inside html contents...
this show without error if i comment the link_to_remove_association.
ALSO... i can see without this, but at submit time, nothing is recorded but no error shown around this failed recording embeded nested part.

any idea for help ? (maybe i miss something... but just follow the doc, very simple doc to follow also)
could it be a turbolink problem ? (i have the jquery-turbolink gem for make it working some other kinds of gems...)

**Comment by nathanvda** [comment]
Hi Jerome2, your issue is a little confusing. 

But in your `link_to_remove_association` you are missing a parameter. It should be 

    = link_to_remove_association 'remove something', f

If that was not your exact code, it is hard for me to guess what could be wrong,
so could you show me some real code? Show me the views for starters.

**Comment by jerome2** [comment]
thanks for answer.
i try this also, but not works more. It said (and i don't know why) that there is no object for nilClass...
then the "forms objects" are present, because if i don't add this link_to special call, it show me without errors... that is also why it is confuse for me.
so... with all exact codes (except contaniers class name), this not works for me.
I look iniside the dummy_app example, and then i see there is sometimes no "belongs_to" in the models who refers to the table (mine have).
I check in my app the schema.rb for database links, and all are right (also index for reference keys primary and foreign's one). then from console, i can see the "accepts_nested_attributes_for :photos" do the job. but no recording and this error.
i see in the example app that it use renders with xml files... i try to give my apps this render form too... but no more success this way.

**Comment by nathanvda** [comment]
Your english is really bad and confusing. Could you please show some code?

**Comment by jerome2** [comment]
yes, sorry for my dirty english... 
ok, i have no more error (just no record happens now).
I don't know what's happen, i not do nothing for change... maybe the cache of the browser... very strange.
Could you consider this issue closed, and sorry again for bad english langage used.
thanks also for this nice gem.

**Comment by nathanvda** [comment]
No need to apologise for your English, it is not my mother tongue either. But if I understand your problem is now fixed. So closing. 

If it is not fixed, you are free to re-open this issue, but please: "show me the source-code!" (Jerry Maguire style :smile: ).
