### ISSUE TITLE
Cocoon has_many polymorphic association not sending form values in params

### ISSUE THREAD

**Issue by Mandeepahlawat** [nathanvda/cocoon#298]
I'm having a strange issue with Cocoon gem, whenever I add new fields by Cocoon those fields are not present in params hash. 

Regular fields, ones which are not build from the cocoon works as expected. Here's the relevant code. 

    class Standard < ActiveRecord::Base
      has_many :spaces, as: :space_sourceable
	  accepts_nested_attributes_for :spaces, :reject_if => :all_blank, :allow_destroy => true
	end

	class Space < ActiveRecord::Base
	  belongs_to :space_sourceable, polymorphic: true
    end

    class ContractsController < ApplicationController

      def create
		 set_resource(resource_class.new resource_params)
		 if get_resource.save
		   redirect_to authenticated_root_url, notice: "Contract successfully created."
		 else
		   render "new"
		 end
	  end

      def new
        set_resource(resource_class.new)
        build_nested_resources
      end

      private

      def build_nested_resources
        get_resource.spaces.build
      end

      def get_resource
  	    instance_variable_get("@#{resource_name}")
      end

      def set_resource(resource = nil)
	    resource ||= resource_class.find_by_id params[:id]
		instance_variable_set("@#{resource_name}", resource)
		failure unless resource
	  end

	  def resource_name
		@resource_name ||= self.controller_name.singularize
	  end

	  def resource_class
		@resource_class ||= resource_name.classify.constantize
	  end

      def resource_params
        params.require(resource_name.to_sym).permit(:id, :name, :note, spaces_attributes: [:id, :unit, :building, :floor, :amendment_type, :area, :space_sourceable_type, :space_sourceable_id, :_destroy]
      end
	end

	class StandardsController < ContractsController
	end

	#_form.html.haml
	= form_for resource do |f|
	  - if resource.errors.any?
	    #error_explanation
		  %h2 
		    = pluralize(resource.errors.count, "error") 
		        prohibited this lease information from being saved:
		  %ul
		    - resource.errors.full_messages.each do |msg|
		      %li= msg 
		  .field
		    %strong.upper Name:  
		    = f.text_field :name, class: "input", style: "width: 450px;", required: true
		    %h3.center-heading Space
		    = render partial: "spaces", locals: {f: f}

	#_spaces.html.haml
	= f.fields_for :spaces do |space|
	  = render "space_fields", f: space
    .links
	  = link_to_add_association 'Add Space', f, :spaces, partial: "space_fields"

	#_space_fields.html.haml
	.nested-fields
      .field
        .upper Unit  
		= f.text_field :unit, class: "input", style: "width: 450px;"
	  .field
	    .upper Building
		= f.text_field :building, class: "input", style: "width: 450px;"
	  .field
		.upper Floor
		= f.text_field :floor, class: "input", style: "width: 450px;"
	  .field
		.upper Area
		= f.text_field :area, class: "input", style: "width: 450px;"
      .field
	    .upper Amendment Type
		= f.text_field :amendment_type, class: "input", style: "width: 450px;"
		  = link_to_remove_association "Remove this Space", f

HTML generated by Cocoon and normal form fields looks good as well
		
	#normal field from form
    <input type="text" id="standard_spaces_attributes_0_unit" name="standard[spaces_attributes][0][unit]" class="input">

    #field generated by cocoon
    <input type="text" id="standard_spaces_attributes_1436417485840_unit" name="standard[spaces_attributes][1436417485840][unit]" class="input">

This is sending following parameters to server

    {"standard"=>{"name"=>"fdfdfd", "spaces_attributes"=>{"0"=>{"unit"=>"asds", "building"=>"", "floor"=>"", "area"=>"", "amendment_type"=>""}}, "note"=>""}, "commit"=>"Create Standard", "utf8"=>"✓", "authenticity_token"=>"MYAn/MTgEOpS5B0xubsmMEW53EbOSPkgvJ/1sWTJAVcIf8cZLMNI6O1Py3qBho4Kkgteq5smJyYBNH1GT26Bqw==", "controller"=>"standards", "action"=>"create"}

P.S  I'm able to save values under normal circumstances. I'm also able to add and remove fields by cocoon, it's just that those fields are not being sent along with other form attributes.

**Comment by nathanvda** [comment]
You refer to "fields", which I would take as a single "column" in a row (or single attribute in a form or model), but I guess you mean a nested `space` (in your example), correct? 

So if I understand correctly: newly added `space`s are not saved? And removing: does that work? (when saving). 

Possible causes I can think of (but do not see that reflected in your code): 

- you use css `id` instead of classes for repeating elements in your form
- you insert html, but it is not inserted "inside" the form (so it is on the page, visible, but when you inspect the html, it is "outside" of the form --only fields inside the form will be posted)

**Comment by Mandeepahlawat** [comment]
@nathanvda thanks for the response. I figured it out. I was using HTML table for rendering form and its field which was behaving oddly. When used normal divs it was working just fine.

Thanks for the response and awesome gem though.

**Comment by nathanvda** [comment]
Weird, it should just work with tables. It is just html. But I see no mention of a table in the code you showed me? So that was not the actual code? 

Anyway: glad you found it.

**Comment by Mandeepahlawat** [comment]
@nathanvda yeah it was bad HTML on my end. I was using table in new actions template, which I didn't post it up here. 

What was weird though and made it hard for me to guess was that the HTML of both nested attributes generated by cocoon and those build manually were outside of the form but still while submitting, form was sending manually build nested attributes but not the cocoon ones.

Any guesses why?
