### ISSUE TITLE
Is it possible to have the child_fields partial in another (shared) directory?

### ISSUE THREAD

**Issue by sebabouche** [nathanvda/cocoon#299]
I couldn't find a way to move the partials shared by two different users (providers and admins) to stay dry. Well, I found a way but it's not very clean. Here is my *views structure*:

    +-- admin
    |   +-- offers
    |       +-- _item_fields.html.slim ### = render 'offers/form/item_fields', f: f
    |       +-- _section_fields.html.slim ### = render 'offers/form/item_fields', f: f
    |       +-- edit.html.slim ### = render 'offers/form/admin_fields', f: f
    |       +-- index.html.slim
    |       +-- new.html.slim ### = render 'offers/form/admin_fields', f: f
    |       +-- show.html.slim
    +-- offers
    |   +-- form
    |       +-- _admin_fields.html.slim
    |       +-- _fields.html.slim
    |       +-- _item_fields.html.slim
    |       +-- _section_fields.html.slim
    +-- provider
    |   +-- offers
    |       +-- _item_fields.html.slim ### = render 'offers/form/item_fields', f: f
    |       +-- _section_fields.html.slim ### = render 'offers/form/item_fields', f: f
    |       +-- edit.html.slim ### = render 'offers/form/fields', f: f
    |       +-- index.html.slim
    |       +-- new.html.slim ### = render 'offers/form/fields', f: f
    |       +-- show.html.slim

Is there a way to get rid of the _symlink partials_ and define where to find the add association partial?
I tried: 

    = f.input :title
    #sections
      = f.simple_fields_for :sections do |section|
        = render 'offers/form/section_fields', :f => section
    .links
      = link_to_add_association 'Ajouter une section', f, :sections

But I still get this error with _link_to_add_association_ :
<img width="1412" alt="capture d ecran 2015-07-20 a 10 37 38" src="https://cloud.githubusercontent.com/assets/6465147/8772330/b30661ea-2ecb-11e5-9970-3eb41b51353f.png">

He is looking for a partial in the 'new' or 'edit' directory. That's why I created partials just pointing to the 'shared' offers directory.

**Comment by nathanvda** [comment]
You can specify the partial explicitly in the `link_to_add_association` (see [documentation](https://github.com/nathanvda/cocoon#link_to_add_association) )

So something like

       link_to_add_association 'add bla', f, :sections, partial: 'your/partial/here'

**Comment by sebabouche** [comment]
Thanks and… sorry for me being so blind ;-)
