### ISSUE TITLE
Problem with tr and td tags in partial form

### ISSUE THREAD

**Issue by oluffaroe** [nathanvda/cocoon#303]
I would like to format the partials as a table with table rows.

In the form file _form.html.erb I write

```
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Description</th>
        <th>Quantity</th>
        <th></th>
      </tr>
      </thead>
      <tbody id="lines">
        <%= f.simple_fields_for :lines do  |line| %>
            <%= render 'line_fields', f: line %>
        <% end %>
      </tbody>
    </table>
    <%= link_to_add_association 'add line', f, :lines,
                                :"data-association-insertion-node" => "tbody#lines",
                                :"data-association-insertion-method" => "append",
                                :partial => "line_fields",
                                :class => "links btn btn-primary" %>

```

In partial form file _line_fields.html.erb is the following construction:

```
      <div class="nested-fields">
        <tr>
        <td><%= f.input :description, label: false %></td>
        <td><%= f.input :quantity, label: false  %></td>
        <td><%= link_to_remove_association "remove", f, :class => 'btn btn-default' %></td>
      </tr>
      </div>
```

This works fine for existing lines which are displayed as rows in a table. But when I try to add a new line the tr/td tags in the partial are not added to the page. Only the form fields only are added. The result is that the new form fields are not display as a new row but as two fields on separate lines

I would like to add line to include the tr/td tags so the new line is displayed as a new row in the table.

Any help on this issue would be appreciated.

**Comment by nathanvda** [comment]
I would advice against using tables here. I would advice to look into haml, to produce cleaner mark-up. 

An improvement would be to place the `link_to_add_association` inside the `<tbody>` tag, and in the partial remove the surrounding div, and give the tr the class `nested-fields`. 

In haml this looks like: 

    %table.table.table-striped
      %thead
        %tr
          %th Description
          %th Quantity
          %th
      %tbody#lines
        = f.simple_fields_for :lines do  |line|
          = render 'line_fields', f: line
        = link_to_add_association 'add line', f, :lines, :class => "links btn btn-primary"

Since the link now is inside the `tbody`, I am guessing defaults should just work. Not sure. Not tested.

The partial should look like: 

    %tr.nested-fields
      %td= f.input :description, label: false
      %td= f.input :quantity, label: false  
      %td= link_to_remove_association "remove", f, :class => 'btn btn-default'

**Comment by oluffaroe** [comment]
This did not make it work. Below is the resulting tbody-html with two lines properly formatted and a newly added line which is added without the surrounding tr/td tags.

```
<tbody id="lines">        
      <!-- <div class="nested-fields"></div> -->
        <tr class="nested-fields">
        <td><div class="form-group string optional order_lines_description"><input class="string optional form-control" type="text" value="2" name="order[lines_attributes][0][description]" id="order_lines_attributes_0_description"></div></td>
        <td><div class="form-group integer optional order_lines_quantity"><input class="numeric integer optional form-control" type="number" step="1" value="2" name="order[lines_attributes][0][quantity]" id="order_lines_attributes_0_quantity"></div></td>
        <td><input type="hidden" name="order[lines_attributes][0][_destroy]" id="order_lines_attributes_0__destroy" value="false"><a class="btn btn-default remove_fields existing" href="#">remove</a></td>
      </tr>
<input type="hidden" value="5" name="order[lines_attributes][0][id]" id="order_lines_attributes_0_id">
       <!-- <div class="nested-fields"></div> -->
        <tr class="nested-fields">
        <td><div class="form-group string optional order_lines_description"><input class="string optional form-control" type="text" value="2" name="order[lines_attributes][1][description]" id="order_lines_attributes_1_description"></div></td>
        <td><div class="form-group integer optional order_lines_quantity"><input class="numeric integer optional form-control" type="number" step="1" value="3" name="order[lines_attributes][1][quantity]" id="order_lines_attributes_1_quantity"></div></td>
        <td><input type="hidden" name="order[lines_attributes][1][_destroy]" id="order_lines_attributes_1__destroy" value="false"><a class="btn btn-default remove_fields existing" href="#">remove</a></td>
      </tr>
<input type="hidden" value="6" name="order[lines_attributes][1][id]" id="order_lines_attributes_1_id">        

        <!-- <div class="nested-fields"></div> -->
        
        <div class="form-group string optional order_lines_description"><input class="string optional form-control" type="text" name="order[lines_attributes][1437923258818][description]" id="order_lines_attributes_1437923258818_description"></div>
        <div class="form-group integer optional order_lines_quantity"><input class="numeric integer optional form-control" type="number" step="1" name="order[lines_attributes][1437923258818][quantity]" id="order_lines_attributes_1437923258818_quantity"></div>
        <input type="hidden" name="order[lines_attributes][1437923258818][_destroy]" id="order_lines_attributes_1437923258818__destroy" value="false"><a class="btn btn-default remove_fields dynamic" href="#">remove</a>
</tbody>
```

**Comment by nathanvda** [comment]
Ok. This is just a simple html problem: because you are not allowed to insert, e.g. `tr` inside a `tr` the browser will attempt to _fix_ the markup. The fix is relatively simple: take the `link_to_add_assocation` back out of the table and write it as you did before (with the specific insertion method). Just make sure your partial starts with a `tr` at the top (so also no comments there).

**Comment by oluffaroe** [comment]
Solved.

The problem seemed to be that the first line in the partial file started with the following line
```
<!-- <div class="nested-fields"></div> -->
```
When I removed this comment-line everything worked.
