### ISSUE TITLE
Double nested form, 2nd level links_to_add do not create 3rd level links_to_add

### ISSUE THREAD

**Issue by Artaud** [nathanvda/cocoon#305]
Hi Nathan,
I've been trying for several days to make double nested forms work with cocoon, but I cannot seem to tack my issue.
I have three hierarchical models in my view, on the first load everything looks fine, all the add and remove links are there and working, but when I add another 2nd level field, it won't show the link_to_add_association for its 3rd level fields.
It seems to me as if the link_to_add should somehow build the next level objects, but it doesn't. At the first load, the build methods are invoked per the new action in the controller, but when clicking the cocoon links, this method is not invoked again and I'm not sure where I should go for building the objects.
I have no controller for the 2nd level objects, but I checked your demo repository and you also have just one controller there.
Sorry to bother you with this, but do you see what I might be doing wrong?
Using Rails 4, strong params are all fine, with ids and _destroys and stuff.

The code>>

_form.html.erb
```
<%= simple_form_for @ucetni_report do |f| %>
  <%= f.input :datum %>
  <%= f.input :uzavreny %>  

<h3>Účetní balíček</h3>
  <%= f.simple_fields_for :ucetni_baliceks do |ucetni_balicek| %>
    <%= render 'ucetni_balicek_fields', f: ucetni_balicek %>
    <div class="links">
      <%= link_to_add_association 'Pridat balicek', f, :ucetni_baliceks %>
    </div>
  <% end %>

  <%= f.button :submit %> 
<% end %>
```
_ucetni_balicek_fields.html.erb (2nd level partial)
```
<div class="nested-fields">
  <%= f.input :nadpis %>
  <%= link_to_remove_association "Odstranit balicek", f %>

  <%= f.simple_fields_for :ucetni_polozkas do |ucetni_polozka| %>
  	<%= render 'ucetni_polozka_fields', f: ucetni_polozka %>
	  <div class="links">
	    <%= link_to_add_association 'Pridat polozku', f, :ucetni_polozkas %>
	  </div>
  <% end %>
</div>
```

_ucetni_polozka_fields.html.erb (3rd level partial)
```
<div class="nested-fields">
  <%= f.input :nazev %>  

  <%= link_to_remove_association "Odstranit polozku", f %>
</div>
```

The controller new method
```
  def new
    @ucetni_report = UcetniReport.new
    @ucetni_report.ucetni_baliceks.build
    @ucetni_report.ucetni_baliceks.each do |b|
      b.ucetni_polozkas.build
    end
  end
```

And the models
```
class UcetniReport < ActiveRecord::Base
  has_many :ucetni_baliceks, :dependent => :destroy
  accepts_nested_attributes_for :ucetni_baliceks
end

class UcetniBalicek < ActiveRecord::Base
  belongs_to :ucetni_report
  has_many :ucetni_polozkas, :dependent => :destroy
  accepts_nested_attributes_for :ucetni_polozkas
end

class UcetniPolozka < ActiveRecord::Base
  belongs_to :ucetni_balicek
end
```

Thanks and take care!

**Comment by nathanvda** [comment]
Mmmm. You only show a `link_to_add_association` if there are already nested items??? 

You write

```
<%= f.simple_fields_for :ucetni_baliceks do |ucetni_balicek| %>
    <%= render 'ucetni_balicek_fields', f: ucetni_balicek %>
    <div class="links">
      <%= link_to_add_association 'Pridat balicek', f, :ucetni_baliceks %>
    </div>
  <% end %>
```

but it should be

```
  <%= f.simple_fields_for :ucetni_baliceks do |ucetni_balicek| %>
    <%= render 'ucetni_balicek_fields', f: ucetni_balicek %>
  <% end %>
  <div class="links">
    <%= link_to_add_association 'Pridat balicek', f, :ucetni_baliceks %>
  </div>
```

I guess you are not familiar with [haml](httlp://haml.info). Check the [erb examples](https://github.com/nathanvda/cocoon/wiki/ERB-examples) (but I prefer haml as it is much cleaner and shorter and you are less likely to make html errors --and it is really easy to learn imho).

**Comment by Artaud** [comment]
Nathan, you are absolutely awesome. I've read through the cocoon issues forum & cocoon on SO and it is unbelievable that you put so much care in this piece of code, doing your best to help everyone who just opens his mouth...thank you so much for your advice and for your passion!
I'm definitely going to switch to haml, it seems to be so clear .)
Oh and of course you've solved my issue.

**Comment by nathanvda** [comment]
Thank you for those kind words :smile: :heart: :heart: :+1:
