### ISSUE TITLE
Feature Request: Destroy nested association even if validation of parent object is failed

### ISSUE THREAD

**Issue by gabyshev** [nathanvda/cocoon#307]
Based on @nathanvda `simple_form_demo`. Modified [demo](https://github.com/gabyshev/cocoon_simple_form_demo) with the problem.

Suppose we have 4 tasks in the project. We need to replace then with others.
Steps will be:
1. Open edit view
2. Click `x` button against all tasks
3. Add new 4 tasks

Everything will be okey unless we missed on of the tasks and tried to submit only 3 of them.
With custom validation that I provided in [demo](https://github.com/gabyshev/cocoon_simple_form_demo) we will see 4 old and 3 new tasks at once.

Maybe add optional parameter to delete old tasks?
```
= link_to_remove_association f, { skip_parent_validation: true }
```

**Comment by nathanvda** [comment]
They are still marked for deletion, they are just visible. I still need to fix the js to be turbolinks compliant. 

This piece of js normally fixes that: https://github.com/nathanvda/cocoon/blob/master/app/assets/javascripts/cocoon.js#L102

So for now, you could manually hide the fields marked-for-deletion, and everything will go as planned once the validation passes.

Cocoon only works on the client, what you do on the server is either default rails, or something you wrote, so adding some flag will still not have any effect in the server.

**Comment by gabyshev** [comment]
Thanks, that helps!

So I close this. If you need this issue as a reminder just reopen it
