### ISSUE TITLE
undefined local variable or method `form'

### ISSUE THREAD

**Issue by LukeP91** [nathanvda/cocoon#309]
Hi, im not sure if its inteded or some strange interaction in my application, but when I did my form as in simple_from example 
```
= simple_form_for @invoice, url: admin_invoice_path(id: @invoice.id), method: :put, html: { class: 'form-horizontal'} do |form|
  [...]                
  = form.simple_fields_for :invoice_items do |invoice_item|
    .row 
      = render 'invoice_item_fields', form: invoice_item
  = link_to_add_association 'add invoice item', form, :invoice_items
```
and my partial 
```
.nested-fields
  %p test
  .col-md-3
    = form.input :item_description
  .col-md-3
    = form.input :quantity  
  .col-md-3
    = form.input :unit_price
  .col-md-3
    = link_to_remove_association "remove task", form
```
There was an error :
```
undefined local variable or method `form' for #<#<Class:0x007fac4d461288>:0x007fac4d81ea60>
```
Changing it to 
```
= simple_form_for @invoice, url: admin_invoice_path(id: @invoice.id), method: :put, html: { class: 'form-horizontal'} do |form|
  [...]                
  = form.simple_fields_for :invoice_items do |invoice_item|
    .row 
      = render 'invoice_item_fields', f: invoice_item
  = link_to_add_association 'add invoice item', form, :invoice_items

.nested-fields
  .col-md-3
    = f.input :item_description
  .col-md-3
    = f.input :quantity  
  .col-md-3
    = f.input :unit_price
  .col-md-3
    = link_to_remove_association "remove task", f
```
Fixed the issue.
 I'm not sure if its error in readme or some other strange interaction

**Comment by nathanvda** [comment]
By default I always assume a the form object to be called `f` in the partial, you can overrule this using the parameter `form_name` for the [`link_to_add_association`].(https://github.com/nathanvda/cocoon#link_to_add_association)

E.g. in your case

    = link_to_add_association 'add invoice item', form, :invoice_items, form_name: 'form'

**Comment by LukeP91** [comment]
I must have missed that in documentation. Thanks a lot for your answer

**Comment by sidhunavroop** [comment]
**_form.html.erb**
<div class='row'>
  <div class= 'col-xs-12'>
    <%= form_for(@parent, :html => {class: "form-horizontal", role: "form"}) do |form| %>
    	<div class = "form-group">
        <div class="control-label col-sm-2">
    	
        <%= form.label :parent_1_firstname %>
      </div>
      <div class="col-sm-8">
        <%= form.text_field :parent_1_firstname, class: "form-control", placeholder: "Parent 1 first name", autofocus:true %>
      </div>
    </div>
       <div class = "form-group">
        <div class="control-label col-sm-2">
             <%= form.label :parent_1_lastname %>
           </div>
           <div class="col-sm-8">
             <%= form.text_field :parent_1_lastname, class: "form-control", placeholder: "Parent 1 last name", autofocus:true %>
</div>
        </div>
        <div id = 'secondaryparents'>
        <%= form.fields_for :secondaryparents do |builder| %>
        <%= render 'secondaryparent_fields', :form => builder %>
        <% end %>
        <%= link_to_add_association 'Add Secondary Parent', form, :secondaryparents %>
      </div>

       

      <div class = "form-group">
        <div class="control-label col-sm-2">
        <%= form.label :address %>
      </div>
<div class="col-sm-8">
        <%= form.text_area :address, class: "form-control", placeholder: "Address", autofocus:true %>
      </div>
    </div>
<div class="col-sm-8">
        <%= form.text_area :address, class: "form-control", placeholder: "Address", autofocus:true %>
      </div>
    </div>
**_secondaryparent_fields.html.erb**
<div class='nested-fields'>
    <div class="field">
             <%= form.label :parent_first_name %>
           
             <%= form.text_field :parent_first_name %>
          </div>
        <div class="field">
        <%= form.label :parent_last_name %>
        <%= form.text_field :parent_last_name %>
          </div>
      
        <%= link_to_remove_association "Remove Parent", form %>

</div>

I am facing this. Please help
undefined local variable or method `form' for #<#<Class:0x00007fc295dd38d0>:0x00007fc2969e7338>
