### ISSUE TITLE
Belongs to with select shows class name and object id instead

### ISSUE THREAD

**Issue by Patrax** [nathanvda/cocoon#312]
I'm following the guide that uses the example for Person and Owner for Projects. And you're able to select a single owner out of a list of people or create a new owner.

I'm trying to do it for an app that uses recipe_groups to categorize recipes. This is my code in their respective partials:

##### _form.html.erb

    <div id="group" class="tab-pane">
      <div id="group_from_list">
        <%= f.association :recipe_group, collection: @restaurant.recipe_groups.order(:group_name), prompt: 'Choose an existing recipe group' %>
       </div>
    	<%= link_to_add_association 'Add a new recipe group', f, :recipe_group %>
    </div>

##### _recipe_group_fields.html.erb

    <div class="nested-fields">
	    <%= f.input :restaurant_id, :as => :hidden, :input_html => { :value => @restaurant.id } %>
      <%= f.input :group_name %>
      <%= link_to_remove_association "Remove group", f %>
    </div>

Thing is, the resulting form ends up showing the object id, like so:
![screen shot 2015-08-26 at 5 35 41 pm](https://cloud.githubusercontent.com/assets/1750530/9508153/f1b10304-4c18-11e5-8c1f-ea76c0dd9a2a.png)
It might have something to do with the fact that I'm nesting everything under restaurant. But either way, has anyone else encountered this?

**Comment by nathanvda** [comment]
You have to either define the `to_s` function in `RecipeGroup`, or add a method called `label` or give a specific `label_method` to your `f.association`, e,g. something like 

    = f.association :recipe_group, label_method: :group_name, collection: ...

Check the documentation for [simple_form associations](https://github.com/plataformatec/simple_form#associations)

In the future you should ask questions like this on [stackoverflow](http://stackoverflow.com).

**Comment by Patrax** [comment]
I see, thank you. Sorry about that, didn't know how to approach this rather specific bug, so couldn't find a lot on SO.
