### ISSUE TITLE
link_to_add_association error 'Association model doesn't exist on Model'

### ISSUE THREAD

**Issue by OscarBastardo** [nathanvda/cocoon#313]
Hello, 

Rails raise an error for the line 42 with the link_to_add_association 'Association experiencia_laborals doesn't exist on ExperienciaLaboral' in edit.html.erb https://gist.github.com/OscarBastardo/e8de9fc902f0a3f26a43

it's like it is looking for the association for the model in the same model. I don't understand why, I'm doing it just like the example in the github readme

Any help would be appreciated

**Comment by nathanvda** [comment]
Nope, you are not doing it like in the readme. I am guessing you are new to programming? Details matter. Check which form-object you are handing to the `link_to_association`: you write `el` which points to the nested model, you should be using `f`.

**Comment by OscarBastardo** [comment]
I'm using the equivalent objects to my view. Notice that the simple_fields_for in which I want to use cocoon is 3 levels deep (first obj f, second obj medico, third obj el). 

I now realize that I shouldn't use 'el' for the partial fields because of what you said. But there's something I don't get: In the readme example you use f for the first level, task for the second and t again for the partial fields. Is that because you need to reference the the first level object? 

In my case how could I apply it correctly, since it's a 3 level nested associations form (usuario has one medico and medico has many experiencias laborales (the ones I want to add dynamically))

**Comment by OscarBastardo** [comment]
Solved it. 

Thank you, Nathan.

**Comment by silvadavi** [comment]
Olá poderiam ajudar eu com esse mesmo erro?  "Association equipment doesn't exist on Equipment
" o meu projeto está no gitlab git@gitlab.com:Davu/lts.git

**Comment by silvadavi** [comment]
Hello, can I help with this same error? "Association equipment does not exist in the equipment
"my project is not on gitlab git@gitlab.com: Davu / lts.git

**Comment by nathanvda** [comment]
@silvadavi if you still need help, why did you close #572 ?
