### ISSUE TITLE
The sequence of addition nested forms

### ISSUE THREAD

**Issue by dborovsky** [nathanvda/cocoon#314]
Hi!

I have next code:

```
%h3#poll-items Варианты ответа (не больше пяти)
  .item_index  
    = f.simple_fields_for :poll_items do |poll|
      = render 'poll_item_fields', f: poll
    = link_to_add_association 'Добавить еще вариант', f, :poll_items, 
                                      'data-association-insertion-method' => 'after'
    .form-actions
      = f.button :submit, 'Опубликовать опрос', class: 'btn-bg'
```

_poll_items_fields.html.haml:

```
.poll_row
  .poll_item
    = f.input :answer, input_html: { class: 'ctrlenter expanding' }, label: false, placeholder: 'Введите вариант ответа'
    = link_to_remove_association "удалить", f, { wrapper_class: 'poll_item' }
```

When I click to add a second nested fields, are added above the first nested fields. When I click the third and the following are added after the second: i.e., located between the first and second. 

I dont know, but  why second nested filds is added above the first? How add second nested field after the first?

**Comment by nathanvda** [comment]
You describe the default behaviour, so I would remove the `data-association-insertion-method` :smile: 

Default behaviour is to insert each new nested item `before` the add-link.

The `data-association-insertion-method` sounds pretty obvious, except you do not specify a selector, and the default selector is `this`. So you specified to insert the new nested item `after` the `link_to_add_association` link, meaning: the second insert it will be inserted between the link and the previously inserted item. 

Is that clear?

**Comment by nathanvda** [comment]
Closed due to inactivity.
