### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by jarkelen** [nathanvda/cocoon#319]
I get this error:

`Cannot read property 'replace' of undefined`

on line 30 of cocoon.js:

` new_content           = content.replace(regexp_braced, newcontent_braced(new_id)),`

What might cause this, because it worked OK before?

**Comment by nathanvda** [comment]
You are giving me very little to work with here. If `content` is undefined, it means the template is not filled in correctly, but a bit baffled what could be causing that.

If it worked before, my advice is look at what you changed in the meantime.

**Comment by jarkelen** [comment]
My bad, I made a mistake.
