### ISSUE TITLE
f.index inside partial render does not work

### ISSUE THREAD

**Issue by take** [nathanvda/cocoon#321]
for example

```
.nested-fields
  = f.index
  = link_to_remove_association "remove task", f
```

the output of `f.index` which is added via the `link_to_add_association` will be `"newtask"` instead of `1`

is it impossible to support this? :(

**Comment by nathanvda** [comment]
`f.index` is the position in the array of _existing_ items. For new elements it always returns `newtask` afaik (since it has not position yet in the list of already linked elements). 

What are you trying to achieve? Depending on what you want to do this can easily be simulated using javascript.

**Comment by take** [comment]
Thanks for the quick reply!
I see.

I'm trying to show the positions of each rendered partial.

e.x.

```
.nested-fields
  = f.index # => 0
  = f.input :done, as: :boolean
  = link_to_remove_association "remove task", f
.nested-fields
  = f.index # => 1
  = f.input :done, as: :boolean
  = link_to_remove_association "remove task", f
.nested-fields
  = f.index # => 2
  = f.input :done, as: :boolean
  = link_to_remove_association "remove task", f
```

using `f.index` isn't a must, I just need to show the position :)

**Comment by nathanvda** [comment]
Imho the easiest way is to use css for counters like that. For example see https://css-tricks.com/numbering-in-style/

But otherwise you could combine the `f.index` with some javascript, e.g. replace the `newtask` with `$('nested-fields').size()` in a `cocoon:after-insert` callback?

**Comment by take** [comment]
aha thanks i'll try both :D

**Comment by edwardmp** [comment]
I had the same issue and I solved it using CSS counters. Example (SCSS):

```
.my-form-class {
  .element-you-want-to-count {
    counter-reset: element-counter;
  }

  .element-you-want-to-count:after {
    content: counter(element-counter);
    counter-increment: element-counter;
  }
}
```

Where I use it:
```
<div class="nested-fields">
  <div class="card">
    <div class="card-header">
      Numberplate <%= link_to_remove_association 'Remove this numberplate', n, {class: 'btn btn-danger btn-sm float-xs-right'} %>
      Numberplate <span class="element-counter">#</span>
```
