### ISSUE TITLE
Relations errors for link_to_add_association and remove

### ISSUE THREAD

**Issue by abournier** [nathanvda/cocoon#322]
Hello,

I have this issue on my Rails 4.2 app with Cocoon with the link_to_add_association link.

```undefined method `reflect_on_association' for NilClass:Class```

So I checked my models once again. A "Vintage" can have multiple "Grapes" through "Grapers".

```
class Vintage < ActiveRecord::Base
  
  self.table_name = 'vcl_vintages'
   
  has_many :grapers, dependent: :destroy
  has_many :grapes, through: :grapers  
  
  attr_accessible :grapers_attributes
  accepts_nested_attributes_for :grapers, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :grapes 
```

```
class Graper < ActiveRecord::Base
  
# real table name
  self.table_name = 'vcl_grapers'

# associations    
  belongs_to :vintage
  belongs_to :grape
  
# nested with cocoon
  attr_accessible :grape_attributes
  accepts_nested_attributes_for :grape, reject_if: :all_blank
```

```
class Grape < ActiveRecord::Base
  
# real table name
  self.table_name = 'shd_grapes'
  
# associations  
  has_many :grapers, dependent: :destroy
  has_many :vintages, through: :grapers 
```

Does the table name changes could be a problem for Cocoon ?

My vintage form:

```
<fieldset id="vintage-grapes">
<ol>
  <%= f.fields_for :grapers do |graper| %>
    <%= render '/admin/vintages/graper_fields', f: graper %>
  <% end %>
</ol>
<%= 
link_to_add_association 'add grape', f, :grapers, 'data-association-insertion-node' => "#vintage-grapes ol", 'data-association-insertion-method' => "append", :wrap_object => Proc.new {|graper| graper.build_grape; graper } 
%>
</fieldset>
```

And the nested form:

```
<li class="control-group nested-fields">
    <%= f.label :percent, "Percent:" %>
    <%= f.text_field :percent %>

    <%= f.fields_for :grape do |graper_grape| %>
      <%= graper_grape.text_field :name %>
    <% end %>

    <%= link_to_remove_association "remove", f %>
</li>
```
Note that I have a similar problem with the link_to_remove link (undefined method `new_record?' for nil:NilClass).

Thanks in advance,

**Comment by nathanvda** [comment]
You do not show it, but I am guessing the object you are inserting into your `form_for` is nil? The error `undefined method 'reflect_on_association'` usually means the form is working with a nil object, or the `accepts_nested_attributes_for` is misssing. But 1) I can see the `accepts_..` is present and 2) `new_record?` agains tests on the form-object, so pretty sure it is nil :smile:

**Comment by abournier** [comment]
In fact, the main form is:

```
<%= form_for @vintage, :url => admin_winery_reference_vintage_url(@winery, @reference, @vintage), :html => { :method => :put } do |f| %>
		<div id="form">
			<%= render :partial => 'form', :locals => {:f => f} %>
		</div>
	<% end %>
```

I tried `form_for :vintage` and `form_for @vintage`

If I comment the `link_to_add_association` and `link_to_remove_association `, the form is displayed without errors (but without the links...) ;)

So I think the main object @vintage is not nil.

**Comment by nathanvda** [comment]
The `form_for :vintage` will definitely not work and cause the error as given, but will render a form (not sure about the `fields_for` though). You _think_ `@vintage` is not nil? Is that a kind way to say you are sure, and not say I am wrong, or are you are really not sure? 

Ow and to take away your initial expressed concern: the legacy table names have no impact whatsoever on cocoon (or rails forms in general for that matter).

**Comment by abournier** [comment]
OK, you are right. The problem was  `form_for :vintage` instead of `form_for @vintage`. I changed it before but... not in the right view. Sorry for that. It's working now.

Now the next step will be to set an autocomplete field in the nested resource (graper). Hope it will work.

Thanks, Alex.
