### ISSUE TITLE
Editing objects with multiple file uploads

### ISSUE THREAD

**Issue by ngw** [nathanvda/cocoon#324]
Hi, I think I'm doing something wrong, but I'm not able to upload multiple files using cocoon:

_pet_picture_fields.html.haml

    .pet_picture
      .row
        .col-sm-3
          .form-group
            = f.file_field :photo_file, required: true
        .col-sm-4
          .form-group
            = f.input :caption, label: 'Didascalia'
        .col-sm-3
          .form-group
            = link_to_remove_association "Rimuovi", f, class: 'remove btn btn-danger', wrapper_class: 'pet_picture'

_form.html.haml

    #pet_pictures
      = form.simple_fields_for :pet_pictures do |pet_picture|
        = render partial: 'pet_pictures/pet_picture_fields', locals: {f: pet_picture}
      .links
        = link_to_add_association form, :pet_pictures, partial: 'pet_pictures/pet_picture_fields', 'data-association-insertion-method': :before, class: 'btn btn-default', id: 'add_pet_image' do
          %i.fa.fa-file-image-o
          Aggiungi immagine
 
The pet_pictures relation is a normal has_many, each pet_picture has a CarrierWave uploader mounted. The main form is obviously multipart.
Adding pictures (as when I create the object) works wonderfully, editing doesn't. What happens is that when I have, say, 3 pictures linked and I submit the form without doing anything, it appears to attempt to create new pictures without photo_file, and I don't understand why...

    "pet_pictures_attributes"=>{"0"=>{"caption"=>"", "_destroy"=>"false", "id"=>"11"}, "1"=>{"caption"=>"", "_destroy"=>"false", "id"=>"12"}, "2"=>{"caption"=>"", "_destroy"=>"false", "id"=>"10"}}}

Anyone has any idea what I'm doing wrong here?

**Comment by nathanvda** [comment]
A bit hard to say without any controller code, but my first guess would be that your strong parameters does not include the id?

**Comment by ngw** [comment]
That was it... Sorry for opening an issue about this.
Wouldn't it be better to have a google group or something?
Thanks a lot
