### ISSUE TITLE
When deleting final and only item, impossible to add more items

### ISSUE THREAD

**Issue by mcmire** [nathanvda/cocoon#325]
I am using Cocoon for the first time, and I'm finding that if you only have one item, and you remove that item, then adding another item is no longer possible.

I could add a conditional such that the "Remove" button next to an item is only rendered if there is only one item initially, but that wouldn't work if you add a new item (because at that point then you need to show the button next to the first item that was already there) -- in other words, the visibility of that button needs to be dynamic.

I didn't check through the code to see if this already happens in some form, or why you can't add another item to begin with, so I apologize -- I can do that later if need be. I was just wondering if you or anyone else has noticed this behavior before, or if there's something I need to do to make this happen (or, if this is even an issue). Thanks!

**Comment by nathanvda** [comment]
Nope, this behaviour should just work, so I am guessing you are doing something wrong. You are giving very little information for me to help you in any way. 

My first guess (since you do not describe the behaviour in great detail): if after removing the last item, there is no "add" button anymore, I am guessing you are placing the `link_to_add_association` in the wrong place, and that could mean you are not used to reading haml views, so check out the [erb examples](https://github.com/nathanvda/cocoon/wiki/ERB-examples)

Please show me the view code, so I can help you better.

**Comment by mcmire** [comment]
Hey, sorry for the lack of information. I didn't mean to imply that the gem was at fault -- I didn't have proper time to look into it, and simply needed a quick clarification.

As it turns out, you're correct, I was doing something wrong. I have a table where the user can add or delete rows. I'm using Cocoon like this:

``` erb
<%= form_for :group do |f| %>
  <table class="group-items">
    <% group.group_items.each do |group_item|
      <tr class="nested-fields">
        <td>... form fields go here ...</td>
        <td><%= link_to_remove_association "Remove", f %></td>
      </tr>
    <% end %>
  </table>

  <%= link_to_add_association(
    "Add group item",
    f,
    :group_items,
    partial: "group_item",
    "data-association-insertion-node" => ".group-items tr:last",
    "data-association-insertion-method" => "after",
  ) %>
<% end %>
```

You can probably notice the problem -- if you remove all rows, then `.group-items tr:last` won't match anything anymore, and thus it doesn't know where to insert a new row.

I wonder if it'd be worth it to print some kind of warning to the browser console if clicking on the "Add" link can't find an element to put the new item in? Or, would you be opposed to me adding a how-to to the wiki on using Cocoon to make a table the right way, to prevent someone else from running into this?
