### ISSUE TITLE
Partial with multiples locals only works without link_to_add_association

### ISSUE THREAD

**Issue by edipofederle** [nathanvda/cocoon#326]
Hi,

Thank you for your work on this gem. Very nice stuff.

I am with a *problem* here, consider this code:
```
<div class="ui bottom attached segment">
    <div class="new_node_address">
        <%= client.fields_for :client_addresses do |contact| %>
            <%= render "client_address_fields", {bar: 10, foo: 20} %>
        <% end %>
    </div>
    <%= link_to_add_association 'Add Endereço', client, :client_addresses, class: "ui mini green button add_client_address" %>
</div>
```

I need pass to ```client_address_fields``` partial two variables (just example here). But with this code I get the error:

```
undefined local variable or method `foo' 
```

But, is I remove ``` link_to_add_association``` line. It works fine.

[Complete form code](https://gist.github.com/edipofederle/67ce40e14254799a4614)

Any suggestion here?

Thanks in advance

**Comment by heliohead** [comment]
You need pass , render_options: {}

<%= link_to_add_association 'Add Endereço', client, :client_addresses, { class: "ui mini green button add_client_address", render_options: { foo: mylocals } %>

**Comment by edipofederle** [comment]
Sorry for late reply. The problem was other things.  But with locals works too.

Thanks.
