### ISSUE TITLE
cocoon is adding more than one item

### ISSUE THREAD

**Issue by xampo848** [nathanvda/cocoon#329]
I do not know what I'm doing wrong, but every time I want to add a new field nested link_to_add_association adds more than one.

This happens when I am on view 'new' and go to 'edit' view, more and more items are added.

I followed the instructions to the letter, but did not work for me.

 it seems that the javascript function  is called multiple times.
 I am relatively new in this.

thank you.

**Comment by nathanvda** [comment]
This sounds like #177

**Comment by xampo848** [comment]
it was the turbolinks, i just removed and work fine.
Thank You :)

**Comment by nathanvda** [comment]
It works just fine with turbolinks, but you have to include the application.js only once (meaning: include it in the head).
