### ISSUE TITLE
Cocoon + Bootstrap Nav Tabs

### ISSUE THREAD

**Issue by pablougas** [nathanvda/cocoon#332]
I'm new to this gem and working on trying to get Cocoon converted to display and generate as dynamic bootstrap tabs. Idea being that last tab would always be "Add Address" and the previous tabs would be existing addresses with their own tabs, has anyone had any luck in doing this? 

Example:

Address 1(active)   |    Address 2       |       + Add Address

**Comment by nathanvda** [comment]
This is not straightforward, as you will have two places that change: the tabs and the content.

You will have to use a callback to create the tab before/after insert of the content (your nested item). I have no example code for this specific case.

**Comment by pablougas** [comment]
Well, that leads me in the right direction. Seems like a great use and would be great sample code to add for future users. If I end up going back and adding it I will submit it here but appreciate the work on this gem. It's fantastic.

**Comment by nathanvda** [comment]
Nice :+1: Sample code like that could be added to the Wiki.
