### ISSUE TITLE
`link_to_add_association` raises ArgumentError 

### ISSUE THREAD

**Issue by TeTiRoss** [nathanvda/cocoon#334]
I have issue when adding `link_to_add_association` to my form. When I do this I'm getting `wrong number of arguments (0 for 1)`. Problem is not in partial cause first time rendering is going ok and without `link_to_add_association` is also works fine

This is how my code looks like:
```ruby
<%= u.simple_fields_for :educations do |education| %>
    <%= render 'education_fields', u: education %>
    <%= link_to_add_association '+', u, :educations %>
<% end %>
```

**Comment by simi** [comment]
Can you post whole stacktrace (with error) and templates?

**Comment by TeTiRoss** [comment]
`_form`:
```ruby
<%= simple_form_for [:admin, @user] do |u| %>
  <%= u.error_notification %>

  <%= u.input :name, label: "ПІП" %>
  <%= u.input :photo, label: false %>
  <%= u.input :tel, label: "Тел.:" %>
  
  <%= u.simple_fields_for :educations do |education| %>
     <%= render 'education_fields', u: education %>
     <%= link_to_add_association '+', u, :educations %>
  <% end %>
  
  <%= u.button :submit, "Надіслати" %>
<% end %>
```

`_education_fields`:
```ruby
<%= u.input :name, label: "Назва університету" %>
<%= u.input :year_started, label: "Початок навчання" %>
<%= u.input :year_finished, label: "Кінець навчання" %>
<%= link_to_remove_association "-", u %>
```
controller `new` method:
```ruby
  @user = User.new
  @user.educations.build
```
permited params
```ruby 
params.require(:user).permit(:name, :photo, :tel,
           :educations_attributes => [:id, :name,
                                      :year_started, :year_finished, :_destroy]
```
model `User`:
```ruby
has_many :educations, dependent: :destroy
accepts_nested_attributes_for :educations,
                                reject_if: :all_blank, allow_destroy: true
```
model `Eduction`:
```ruby
belongs_to :user
```
`application.js`:
```javascript
//= require jquery
//= require jquery_ujs
//= require twitter/bootstrap
//= require turbolinks
//= require cocoon
//= require_tree .
```
`Gemfile`
```ruby
gem "cocoon"
```
Think this is all included to the issue files :smiley:

**Comment by TeTiRoss** [comment]
<img width="1276" alt="screen shot 2016-01-17 at 4 44 55 pm" src="https://cloud.githubusercontent.com/assets/9665395/12378073/6ecf24b8-bd3b-11e5-9b82-0aa4a00138c9.png">

**Comment by nathanvda** [comment]
The stack trace does seem to suggest it is in the normal rendering, not in the `link_to_association`. But to be sure, you should show the stack trace with `All frames` selected (otherwise it is a bit pointless). 

Your code looks fine, however please note that the partial for the nested fields should start with a class called `nested-fields` (which is configurable, see [documentation](https://github.com/nathanvda/cocoon#link_to_remove_association))

**Comment by TeTiRoss** [comment]
nested fields are started now with the class `nested-fields` but it raises the same error
Here is page with `All frames`:
[ArgumentError .zip](https://github.com/nathanvda/cocoon/files/93632/ArgumentError.zip)

**Comment by nathanvda** [comment]
Please just copy-paste the error from the logfile.

**Comment by nathanvda** [comment]
Ha, I see the error: you use a different form-parameter name, so you have to supply it explicitly:

    link_to_add_association '+', u, :educations, form_name: 'u'

(by default it is assumed to be 'f').

**Comment by TeTiRoss** [comment]
Thank you! Everything is working now

**Comment by nathanvda** [comment]
Nice :+1:

**Comment by raouldevil** [comment]
I got an identical issue with 3 levels of nesting. Just to clarify, from what I can see the level within the `_(singular_child_association)_fields` partial should have a form parameter name `f`. My recommendation for anyone who encounters this issue is to always use `f` as the form parameter local variable being passed to the partial. So:

```
= render '(singular_child_association)_fields', f: name_of_parent_form_parameter
```

**Comment by nathanvda** [comment]
As said above: you can simply override the default form_name `f` by giving the parameter `form_name`. If that is not working for you, please open a new issue.

**Comment by raouldevil** [comment]
Thanks, just wanted to add some clarification. Comment edited.
