### ISSUE TITLE
Not really an issue, more a question

### ISSUE THREAD

**Issue by anovac** [nathanvda/cocoon#335]
Is there a way to force the partial to be rendered each time it's added? Right now "link_to_add_association" only displays a copy of the already rendered partial.

I ask this because I have a big nested form, and in one of the nested forms I need to have a dynamic select box (Once a category is selected and a new product is added, I want to update the category list in the select. I am passing the value to the controller via ajax, but each time I get the same category list).

**Comment by nathanvda** [comment]
No that is not possible. There are a few alternative approaches. The approach used in cocoon is that the form is rendered server-side (in one go), then is edited on the client, and the user can dynamically insert extra items, and is saved as a whole. 

So, if you want to use that approach, the state of the entire form is kept in the browser (and only sent to the server when submitting the form), so if you want to limit select-boxes, you will have to use a callback upon insert of the partial in the form. 

However, it is entirely possible to skip cocoon altogether, and the button to insert a partial fetch the form using ajax rendered server-side. Maybe, from your description, this is closer to what you expect? But in that case there is no need to use cocoon at all. 

In can go into further detail for each approach, but maybe it is already clear now? If you have more questions, just ask :wink:

**Comment by nathanvda** [comment]
Closed due to inactivity.
