### ISSUE TITLE
Trigger link_to_add_association mechanism using JavaScript (without clicking on a link)

### ISSUE THREAD

**Issue by jmuheim** [nathanvda/cocoon#337]
I want to add input fields for nested attributes by JavaScript, not by clicking on the provided `link_to_add_association` link.

How can this be done?

**Comment by nathanvda** [comment]
At the moment this is not possible, other than manually triggering the link.

**Comment by jmuheim** [comment]
What workaround do you suggest? Just manually adding input fields?

**Comment by nathanvda** [comment]
I might have used the wrong word with "manually", because I ment triggering the link through code. So you could just as well put a link in your html (which might not be not visible), and trigger the click event using code.

But of course I have no idea what you are working on and without more information it is hard to give advice.

**Comment by Adam21e** [comment]
I have used the following jQuery to do this in the past:
$("#add_link").find(">:first-child").trigger("click")

I wrapped the link_to_add_association in a <div> with id of 'add_link and I just trigger a click event on the first child within that <div>

As @nathanvda mentioned, you could then hide it with CSS.

Not sure on what would be required for it to work in vanilla JavaScript

**Comment by jmuheim** [comment]
Thank you, this worked for me.

**Comment by Dutsik** [comment]
Hi i am trying to run  the same call from chrome console but nothing happens. is there any  work around?
Thanks

**Comment by nathanvda** [comment]
Hi @Dutsik please open a new issue and show your view code and how you tried to trigger the link.
