### ISSUE TITLE
How can I have the first row on a new form already visible like when I click the button to add it?

### ISSUE THREAD

**Issue by ginolon** [nathanvda/cocoon#340]
How can I have the first row on a new form already visible like when I click the button to add it?

I go to my **example.com/new_form** and I want already the first line (blank, of course) already there, without click the first time on my "Add new row" button.

How to?

**Comment by nathanvda** [comment]
Build the first element in your controller.

A generic example, if you have a post with many comments, could look like this

```
    def new
      @post = Post.new
      @post.comments.build
    end
```

**Comment by ginolon** [comment]
Beautiful, I love you.

**Comment by nathanvda** [comment]
LOL :laughing: :+1:
