### ISSUE TITLE
I can use cocoon without nested form? Just in my Principal model?

### ISSUE THREAD

**Issue by ginolon** [nathanvda/cocoon#342]
I don't need nested elements. I just need a form with many rows to add that are all the same "Principal"  model, not a nested one.

How to accomplish this with cocoon. Is this possible?

For example:

My form is:

NEW PRINCIPALS:

- ONE PRINCIPAL
- TWO PRINCIPAL
- THREE PRINCIPAL
- FOUR PRINCIPAL

add line

and so on...

not a nested one.

**Comment by nathanvda** [comment]
Yes, check #223 for a detailed example.

**Comment by ginolon** [comment]
This (https://github.com/nathanvda/cocoon/pull/223) can't help me?

**Comment by ginolon** [comment]
When I click on a link_to `new_principal_path, remote: true` and insert a row in form I don't know how to add a model in that form, like a nested row as cocoon does. Thie is the problem.

**Comment by nathanvda** [comment]
Mmmm. Using ajax (`remote: true` links) to insert a form into a page and posting again is pretty standard, and a bit out of scope of the issues here. If you ask that question on stackoverflow you will get an answer in no time, if you send me the link I will add an answer if needed.

**Comment by ginolon** [comment]
Are you saying that my problem is similiar to that: http://stackoverflow.com/questions/16919711/multiple-non-nested-model-creation-on-same-page?

**Comment by nathanvda** [comment]
Note sure why you need to ask me this? The question seems _identical_ to me. Be happy, enjoy, you found a solution.
