### ISSUE TITLE
having troubles when editing nested-forms

### ISSUE THREAD

**Issue by mconiglio** [nathanvda/cocoon#343]
Hello, I'm having some troubles when editing a nested-form. Here I have three models with a many-to-many relationship: Material, StockEntry and StockEntryMaterial

```ruby
class Material < ActiveRecord::Base
  has_many :stock_entry_materials
end
```

```ruby
class StockEntry < ActiveRecord::Base
  belongs_to :employee
  has_many :stock_entry_materials
  accepts_nested_attributes_for :stock_entry_materials, reject_if: :all_blank, allow_destroy: true
end
```

```ruby
class StockEntryMaterial < ActiveRecord::Base
  belongs_to :stock_entry
  belongs_to :material
end
```

My idea is to have a nested form for a StockEntry as a parent and StockEntryMaterials as childs.
When I create new objects there is no problem and they are saved to the database, but when I try to edit any of the existing StockEntries, the childs of that object doesn't appear nested to edit. Although, if I edit a StockEntry adding some childs, those new childs are saved anyway.

This are the strong parameters on the StockEntriesController:
```ruby
def stock_entry_params
  params.require(:stock_entry).permit(:date, :employee_id, 
    stock_entry_materials_attributes: [:id, :material_id, :units, :_destroy])
end
```

stock_entries/_form.html.erb
```
<%= form_for @stock_entry do |f| %>    
    <div class="field">
        <%= f.label :date, "Fecha" %><br>
        <%= f.text_field :date, autocomplete: 'off', class: 'datepicker' %>
    </div>
    <div class="field">
        <%= f.label :employee, "Empleado" %><br>
        <%= f.select :employee_id, options_for_select(@employees.map{ |e| [e.name, e.id] }, selected_key = f.object.employee_id) %>
    </div>
    
    <h3>Materiales</h3>
    <div id="stock_entry_materials">
        <% f.fields_for :stock_entry_materials do |stock_entry_material| %>
          <%= render "stock_entry_material_fields", f: stock_entry_material %>
        <% end %>
        <div class="links">
            <%= link_to_add_association 'Agregar material', f, :stock_entry_materials %>
        </div>
    </div>
    
    <%= f.submit %>
<% end %>
```

stock_entries/_stock_entry_material_fields.html.erb
```
<div class='nested-fields'>
	<div class='field inline'>
    <%= f.select :material_id, options_for_select(@materials.map{ |m| [m.name, m.id] }, selected_key = f.object.material_id) %>
  </div>	
  <div class='field inline'>
    <%= f.label :units, 'Unidades' %>
  	<%= f.number_field :units %>
  </div>
  <%= link_to_remove_association 'borrar material', f %>
</div>
```

Thanks in advance for your help,

Mauricio Coniglio

**Comment by nathanvda** [comment]
The code looks good, i do not see an error immediately. Are you sure the `stock_entry_materials` are saved correctly?  E.g. from the `rails c` can you investigate a StockEntry and see the child materials? What does your controller do?

**Comment by mconiglio** [comment]
This is the controller code for updating and creating StockEntries and childs:
```ruby
def new
  @stock_entry = StockEntry.new
  @employees = Employee.active
  @materials = Material.all
end

def create
  @stock_entry = StockEntry.new(stock_entry_params)
  if @stock_entry.save
    flash[:info] = "Ingreso de stock agregado correctamente."
    redirect_to stock_entries_path
  else
    render 'new'
  end
end

def edit
  @stock_entry = StockEntry.find(params[:id])
  @employees = Employee.active
  @materials = Material.all
end

def update
  @stock_entry = StockEntry.find(params[:id])
  if @stock_entry.update_attributes(stock_entry_params)
    flash[:success] = "Ingreso de stock actualizado."
    redirect_to stock_entries_path
  else
    render 'edit'
  end
end
```

And the answer of your question is yes, if I search on the rails console for any of the created objects and look for its children, they appear correctly saved.

You think the problem could have something related to the id of the div that is surrounding the form on _form.html.erb? Because when I tried to use cocoon on a model (Project and Task) of a single word (the div id was "tasks") it worked correctly.

For the id I tried four things and nothing solved the problem: "stock_entry_materials", "stock-entry-materials", "stockentrymaterials", "StockEntryMaterials".
```
<h3>Materiales</h3>
    <div id="stock_entry_materials">
        <% f.fields_for :stock_entry_materials do |stock_entry_material| %>
        ...
```

Maybe it has nothing to do with the problem, but I tried that anyway.

Any other ideas?

Thanks for your help!

Mauricio

**Comment by nathanvda** [comment]
Just to be clear: when you edit an existing `stock_entry`, you do not see the existing children in the web-view? or you do see them but they do not save?

**Comment by mconiglio** [comment]
I just don't see the existing children in the view

**Comment by nathanvda** [comment]
Ow fuck it is a really stupid error/typo: you forgot the `=` for the block. So you wrote: 

    <% f.fields_for ...

and it should be

    <%= f.fields_for

This places it in the html. Wooooot :smile: Havvvvve fun coding :wink:

**Comment by mconiglio** [comment]
Haha what a stupid mistake! Thanks for your help Nathan!

**Comment by bragamat** [comment]
I'm really sorry for commenting on a closed issue (I actually dont know what are the conventions on that - anyway)...
 Well, I'm facing the same issue! altough, I'm using the " = " for my fields_for 

(my code looks almost exactly the same thing of @mconiglio  's code)

**Comment by nathanvda** [comment]
Hi @bragamat please open a new issue describing the troubles you have and show us your code.
