### ISSUE TITLE
Fields marked for destruction seem to loose _destroy tag upon validation fail

### ISSUE THREAD

**Issue by nwillis78** [nathanvda/cocoon#346]
I have noticed a bug with my project (in this project a question has answers and I am using cocoon to add answers to a question on the same page. A question is validated to make sure it has at least one answer).

Say I have a question, with an answer "Option A", and I remove the answer and press submit then validation fails because option A is marked for destruction as it should be. If I then press submit again the question is saved with Option A as it's answer. It seems that the answer field is no longer marked for destruction after the first time submit is pressed.

In my form
```
<table class="table">
			<thead>
				<tr>
					<th>Answer</th>
					<th>isCorrect</th>
				</tr>
			</thead>
			<tbody id="answer_table">
				<%= f.fields_for :answers do |answer| %>
					<% if !answer.object.marked_for_destruction? %>
							<%= render 'answer_fields', f: answer %>
					<% end %>
						
				<% end %>
			</tbody>
		</table>
```

In my _answers_fields

```
<tr class = "table_row" >

<div class="nested-fields" >
	
		<td class="col-sm-10">	
			<div class = "field">
				<%= f.text_field :answerString, class: "text_field_in_grid"%>
			</div>
		</td>
		<td class="col-sm-1">
			<div class = "field">
				<%= f.check_box :isCorrect %>
			</div>
		</td>
		<td class="col-sm-1">
			<div id="button_text">
				<button type="button" class="btn btn-danger">
				<%= link_to_remove_association "Remove answer", f, {wrapper_class: 'table_row'} %>
				</button>
			</div>
		</td>
	
</div></tr>
```

**Comment by nathanvda** [comment]
Weird this should work. It relies on the presence of the `_destroy` flag, if marked for destruction it will get a special class `destroyed` and the js will even hide deleted fields (note: there was a turbolinks error which is only recently fixed).

I think the problem is in your `marked_for_destruction?` check: this will make sure it is not shown in the form, and thus not saved, and thus it will not be changed (and still exist imho).

**Comment by nwillis78** [comment]
Thank you for your response, I updated to Cocoon 1.2.8 today and it seems to be working out. As you suggested I removed my marked_for_destruction? check and it seems to be working on its own now.

Thanks for your time, and Thanks for the amazing gem!!

**Comment by nathanvda** [comment]
Nice :+1:
