### ISSUE TITLE
My Nested Form not saving 

### ISSUE THREAD

**Issue by Rehankhan100** [nathanvda/cocoon#347]
my all above fields are successfully save but my nested form not going to save i tried to add data manually in database and fetch they easily fetch and also going to be remove but not insert data 

kindly solve my issue

**Comment by nathanvda** [comment]
> Note to self: I really need to add a trouble-shooting check-list.

Hi there, you are aware you gave very little information to be able to help? In most cases people make a typo, and when I see the code I can spot it. 

Nested children not saving is most likely a strong parameters issue or a validations issue.

**Comment by Rehankhan100** [comment]
Hey @nathanvda thanks for your response but i solve this issue by just moving to haml i think erb not support cocoon gem or may be anything else but now everything works fine

**Comment by nathanvda** [comment]
Well you did not give me much information (understatement), but glad you solved it on your own. 

For the record: it works perfectly fine with erb, the rendering engine does not make a difference. There even are [examples](https://github.com/nathanvda/cocoon/wiki/ERB-examples).

**Comment by Rehankhan100** [comment]
sorry for late reply yeah you are right cocoon gem also work find in erb but due to my limited knowledge i am not be able to resolve my error in erb so i just move my code to haml.
