### ISSUE TITLE
Double nested form.

### ISSUE THREAD

**Issue by DmitrySharikov** [nathanvda/cocoon#349]
Hello, Nathan!

I have problem with `cocoon:after-insert` binding.
In my case I have:
```ruby
class Questionary
  has_many :questions
  accepts_nested_attributes_for :questions
end

class Question
  has_many :question_options
  accepts_nested_attributes_for :question_options
end

class QuestionOption
end
```
```coffeescript
$('#question_options').on 'cocoon:after-insert', ->
```
Script above this text works fine only for first pair `Question & QuestionOption`, after inserting new `Question` script didn't work. Is there any way to solve my problem?

p.s. Please excuse my poor English

**Comment by nathanvda** [comment]
Normally this should work, let me tell you how events in js work: clicking on the link will trigger the event. Somewhere higher up in the DOM you have to bind a listener (the `on`). Reasons why this should not work anymore: 

* the event is not triggered in the container anymore (`#question_options`), e.g. when your callback changes the container? replaces it? 
* if you have some js error in your callback, but in that case, also inserting new items would no longer work

You show me the models, but can you show me your html-structure? Maybe it is also relevant to know what you do inside the `after-insert` callback?

**Comment by DmitrySharikov** [comment]
Nathan, thank You for reply
> Somewhere higher up in the DOM you have to bind a listener (the on)

Im just used this:
```coffeescript
$(document).on 'cocoon:after-insert', '#question_options', ->
```
instead of this:
```coffeescript
$('#question_options').on 'cocoon:after-insert', ->
```
and now my code works like a charm

Thank You
