### ISSUE TITLE
multilevel nesting

### ISSUE THREAD

**Issue by pablougas** [nathanvda/cocoon#351]
I am trying to set up a simple project management app up with cocoon where a user can create a project with many tasks and a task can be assigned to many users also using cocoon, however, I run into trouble when trying to save the assignment of course it being 2 levels deep. 

My question is, is this an option or should I try another route?

**Comment by nathanvda** [comment]
This is definitely an option, there is no limit on the level of nesting. Did you check out the [demo project](https://github.com/nathanvda/cocoon_simple_form_demo)? It contains an example with projects -> tasks -> subtaks.

If you need more help, provide more detail or ask a question on stackoverflow.com

**Comment by pablougas** [comment]
I have the following as the parent form. 
<div class="nested-fields">
<hr>
  <%= f.hidden_field :user_id, value:current_user.id %>
  <div class="col-md-9">
    <%= f.text_field :title, label:"Task" %>
  </div>
  <div class="col-md-3">
    <%= f.date_select :deadline %>
  </div>
  <div class="field">
    <%= f.text_area :content, label:"Special Instructions" %>
  </div>
  <fieldset id="assignees">
    <%= f.fields_for :assignees do |assign| %>
      <%= render 'assignee_fields', :f => assign %>
    <% end %>
  </fieldset>
  <%= link_to_add_association ' Assign Task', f, :assignees, class:"btn btn-success btn-block" %>
  <hr>
  <p class="links">
    <%= link_to_remove_association "Remove Task", f, class:"btn btn-danger btn-block" %>
  </p>
</div>

**Comment by pablougas** [comment]
Sub form is as follows.
<hr>
<div class="nested-fields">
		<%= f.collection_select :user_id, User.all, :id, :full_name, {:include_blank => true} %>
	<p class="links">
    	<%= link_to_remove_association "Remove Assignee", f, class:"btn btn-warning btn-block" %>
  	</p>
</div>

**Comment by pablougas** [comment]
Both are wrapped in a nested-fields div and also have a fieldset around the "assignees". Everything displays properly, I just can't seem to get it to save.

**Comment by nathanvda** [comment]
So my guess it is a strong-parameters problem: can you show me your strong parameters definition and what is posted to the server?

**Comment by pablougas** [comment]
Yep, you nailed it, I knew I was missing something simple! I had the assigned params under my tasks instead of inside of on my projects params. Thank you for clearing this up quickly!
