### ISSUE TITLE
Remove dependency on form builder?

### ISSUE THREAD

**Issue by adambedford** [nathanvda/cocoon#354]
I'm trying to render part of a form from JS using `render_to_string`, however the partial contains the cocoon fields. Without the ajax rendering, everything works fine since I have access to the form builder object, `f`, but this object isn't available in the remote controller action.

Is there a way to use cocoon without a form builder object?

**Comment by nathanvda** [comment]
For now there is not. Could you explain what you are trying to do?

**Comment by adambedford** [comment]
I've got a partial with some form fields (including cocoon fields) that gets rendered via ajax. Since the partial doesn't contain the whole form, it has no context over what `f` is when the partial is rendered as it is rendered independently of the rest of the view.

I've thought about wrapping the form fields in a second `simple_form_for`, but still not sure what the implications of that would be, and it doesn't feel like the right solution.

**Comment by nathanvda** [comment]
Yup, not making it much clearer ;) Not sure why you would be using ajax and still be using cocoon? Could you explain the scenario a little clearer, so I can understand why you are trying to server a part of a form through ajax (all missing the form-object, so how will you be able to post data correctly? manually build the correct field-names correctly?). Could you not simply pre-render the form on the server, and only show it when requested? (if that is what you are trying to do?). Why not replace the complete form when queried? Why not build nested elements using the same mechanism and skip cocoon altogether?

**Comment by adambedford** [comment]
thanks for your suggestions!
