### ISSUE TITLE
Add button insert more than one field 

### ISSUE THREAD

**Issue by YousefAlsalem** [nathanvda/cocoon#357]
I'm new in Rails 4.2 world and trying to use cocoon to create an app for recipes and Ingredients following a tutorial on Youtube. So, every recipe  has many Ingredients. The issue comes with link_to_add_association, when I click the "Add Ingredients" button it inserts more than one fields at once while it should be inserting only one field. 
I noticed, the number of added fields come from the previously inserted ingredients that have been added to any recipe, that means if I inserted 10 Ingredients  for recipe A, then I created recipe B and clicked add Ingredients, it will dynamically add 10 empty fields as new ingredients!! 
Any help to fix that?

The code:

recipes controller 
```
`	def new
		@recipe = Recipe.new 
		@recipe.ingredients.build 
	end`
	def recipe_params
		params.require(:recipe).permit(:title, :description, :image, ingredients_attributes: [:id, :name, :_destroy])
	end 
```
 _form.html.haml
```
=simple_form_for @recipe, html: {multipart: true} do |f|
	- if @recipe.errors.any?
		#errors
			%p
				= @recipe.errors.count
				Prevented this recipe from saving 
			#ul
			- @recipe.errors.full_messages.each do |msg|
				%li= msg
	.panel-body
		= f.input :title, input_html: {class: 'form-control'}	
		= f.input :description, input_html: {class: 'form-control'}	
		= f.input :image, input_html: {class: 'form-control'}

		.row
			.col-md-6
				%h3 Ingredients
				#ingredients
					%h4 Name
					= f.simple_fields_for :ingredients do |ingredient|	
						= render 'ingredient_fields', f: ingredient
					.links
						= link_to_add_association '', f, :ingredients, class:"btn-sm btn-warning add-button glyphicon glyphicon glyphicon-plus"	

	= f.button :submit, {class: "btn btn-primary"}
```
ingredient_fields
```
.nested-fields
	.row
		.col-md-6
			= f.input :name, :label => false , input_html: {class:'form-input form-control'}
		.col-md-6
			= link_to_remove_association "", f,  class: 'btn btn-danger btn-sm glyphicon glyphicon-remove'
```
new.html.haml
```
%h1 New Recipe

= render 'form'

%br/

= link_to "Back",  root_path, class: "btn btn-default"
```
application.js
```
//= require jquery
//= require cocoon
//= require jquery_ujs
//= require turbolinks
//= require_tree .

```

**Comment by nathanvda** [comment]
Where do you include the `application.js`? You are using turbolinks, so it should be in `head`. Otherwise you would get multiple click-handlers (for each time a page is loaded/navigated), which could explain your behaviour.

**Comment by YousefAlsalem** [comment]
It's in the head, but still having the same issue.

application.html.haml
```
!!! 5
%html
%head
	%title Recipe app
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand= link_to "Recipe Box", root_path

			%ul.nav.navbar-nav.navbar-right
				%li= link_to "Recipe", recipes_path
				%li= link_to "Sign Out", root_path
				%li= link_to "Order", orders_path

	.container
		-flash.each do |name, msg|
			= content_tag :div, msg, class: "alert"
		= yield
```

**Comment by nathanvda** [comment]
Mmmm weird. Which version of the gem are you using?

**Comment by YousefAlsalem** [comment]
1.2.9.. as mentioned in #329, when I removed turbolinks every things  worked fine!!.. 
Thank you.

**Comment by nathanvda** [comment]
As mentioned in aforementioned issue: it just works with turbolinks, I always use it with turbolinks in my own projects. So you better check if you are not including either application.js or cocoon.js somewhere else (mostly that is the cause). But anyway: if you are happy with disabling turbolinks, that is fine by me as well.
