### ISSUE TITLE
Adding 4 nested_fields in one click

### ISSUE THREAD

**Issue by Rubioli** [nathanvda/cocoon#360]
How can I make my nested form works so when user clicks on **add new**, it add **4** nested_fields and not only **1**?

Thanks in advances!

**Comment by nathanvda** [comment]
Ha, I see the documentation is missing, but it is really easy: 

    = link_to_add_association 'add post', f, :posts, count: 4

**Comment by Rubioli** [comment]
Great, Thanks @nathanvda
