### ISSUE TITLE
Modify Nested_Field before adding association

### ISSUE THREAD

**Issue by Brotakuu** [nathanvda/cocoon#361]
**After** the user submits the form, but **before** the association is added, is it possible to modify the nested field during this time? 

For example my nested fields may look like:

```
<div class='nested-fields'>
    <div class="field">
      <%= f.label :count %>
      <%= f.number_field :count %>
    </div>
    <%= link_to_remove_association "remove section", f %>
  </div>
```

Say I want to multiply `count` x 2 **before** adding the association (after user submits form). Is this possible?

Or a more complex example, I might want to convert the integer to a string then save the association.

**Comment by nathanvda** [comment]
Please post this question on stackoverflow.com and post the link here.

**Comment by Brotakuu** [comment]
Resolved: http://stackoverflow.com/questions/36713709/modify-nested-field-before-adding-association-cocoon
