### ISSUE TITLE
Other ways to include cocoon.js?

### ISSUE THREAD

**Issue by expilo** [nathanvda/cocoon#363]
This is not a bug, just a queston. It would be useful for me to have cocoon.js included in my grunt task, as I don't use Rails assets pipeline to deal with my javascript. Any ideas how to do it in a portable manner?

**Comment by nathanvda** [comment]
Sorry, I have no idea. Frankly it would be very hard to do in a "clean way" imho. Since gems could be installed anywhere (e.g. vendored or system folder or rvm). 

Could you explain what the advantage would be of using grunt?

**Comment by expilo** [comment]
Having access to most up-to-date versions of npm packages as opposed to their sometimes latish gem versions, but to me mostly a matter of clear separation between backend and frontend work.

**Comment by nathanvda** [comment]
Imho gems and the asset pipeline are ideal when offering a piece of ruby-code that needs some corresponding javascript, like the cocoon gem. I understand this is less than ideal for pure npm modules. I tend to use [rails-assets.org](https://rails-assets.org) for pure asset gems (but not all packages have equally good bower definitions, so succes may vary --it has been very useful for me).

So for me, skipping the rails asset pipeline completely is unthinkable (loosing access to the gems I love) , so with that in mind I googled around and stumbled upon [browserify-rails](https://github.com/browserify-rails/browserify-rails) which allows you to combine pure npm/js modules and inject those into the rails asset pipeline, and have imho the best of both worlds. Of course no real experience with it as such, so not sure how it would work out for you. 

* A more in depth article: http://blog.arkency.com/2015/04/bring-commonjs-to-your-asset-pipeline/

**Comment by nathanvda** [comment]
Closed due to inactivity.

**Comment by kmontag** [comment]
@nathanvda any chance we could get an official NPM package? That would cover most non-asset-pipeline use cases. Looks like someone added https://www.npmjs.com/package/cocoon-rails but it's a bit out of date. 

Pretty sure this just means adding a `package.json` to the repo root, with the gem's JS as it's main file, and `npm publish`ing to release the JS.

**Comment by nathanvda** [comment]
Can you explain why you would want to do that? You would still need the gem, right? (I have no experience with npm at all)

**Comment by kmontag** [comment]
Yes, the gem is still necessary for server-side behavior, but we use Webpack instead of the asset pipeline to bundle JS (faster and more configurable for our setup), which runs outside the Ruby environment - so it's difficult to pull in JS directly from gems.

(It's a bit awkward of course to have to keep the gem version in sync with the NPM module version, but I'm not aware of any alternative ways to set things up)
