### ISSUE TITLE
Question: Any ways to insert the forms via JS?

### ISSUE THREAD

**Issue by take** [nathanvda/cocoon#364]
hi thanks for the awesome library, it works like a charm :D 
I was wondering if there's a way to add new nested forms via JS instead of the `link_to_add_association` view helper.

Thanks!

**Comment by nathanvda** [comment]
Nope, not really. The `link_to_add_association` renders the partial to be inserted, so for the moment the only way is to use the view helper, optionally hide the link, and trigger the click-event programmatically. Note that the location of the link has an influence on the insertion point of the partial.

**Comment by take** [comment]
thx!
