### ISSUE TITLE
retrieve partial id

### ISSUE THREAD

**Issue by catuss-a** [nathanvda/cocoon#365]
Hi !

Is there anyway we could retrieve the temporary generated id "new_id" inside the partial ? Or another way would be to send dynamic datas into the partial each time link_to_add_association is triggered ?

Thanks!

**Comment by nathanvda** [comment]
Could you explain to me why you would need this? Is this related to #362 (e.g. use callbacks to manipulate html before insert) or do you need the `wrap_object:` option to set specific values (although this is server side).

**Comment by catuss-a** [comment]
Hi nathan! Thanks for your answer and your work.

Callbacks work perferctly for what I need however it has to be outside of the partial. I just wanted to know if there was a tricks to access to the js context when an association is added.
My issue is kind of related to #362 so i'm closing it.

Merci !
