### ISSUE TITLE
Form involving three models with many to many association between them through an intermediate table.

### ISSUE THREAD

**Issue by AhmadSaleem** [nathanvda/cocoon#366]
@nathanvda I'm not sure if opening an issue here is the right thing to do but I'm kind of stuck at a point and your help would be greatly appreciated. I have the following models.

````
class Event < ActiveRecord::Base
  has_many :day_event_locations, dependent: :destroy
  has_many :days, through: :day_event_locations
  has_many :event_locations, through: :day_event_locations
  accepts_nested_attributes_for :day_event_locations
end

class Day < ActiveRecord::Base
  has_many :day_event_locations, dependent: :destroy
  has_many :events, through: :day_event_locations
  has_many :event_locations, through: :day_event_locations
end

class EventLocation < ActiveRecord::Base
  has_many :day_event_locations, dependent: :destroy
  has_many :days, through: :day_event_locations
  has_many :events, through: :day_event_locations
  has_many :shifts, through: :day_event_locations
end

class DayEventLocation < ActiveRecord::Base
  belongs_to :day
  belongs_to :event
  belongs_to :event_location
  has_many :shifts, dependent: :destroy
  accepts_nested_attributes_for :shifts
  accepts_nested_attributes_for :day
  accepts_nested_attributes_for :event_location
end
````

And I'm attaching the picture of my form to give you an idea how it works. 
![screenshot from 2016-05-04 23 31 49](https://cloud.githubusercontent.com/assets/7367254/15025047/dc0f9c82-1250-11e6-8792-0f28934eed4e.png)

Whenever we add a location or a day, a new instance of day_event_location gets built and when the form is submitted, we have an instance of day_event_location for each day/location. It works fine if no validation fails and the records get saved in the database successfully. 

However, whenever a validation fails, the locations which were built inside a day are shown under separate days, i.e. each day contains only one location. This creates duplicate entries for the same day in the form if there are multiple locations under a day and each day has one of the locations. When ideally what it should be doing is to display all locations under one day. 

Below is the markup in events form for your reference:

````
  <%= f.fields_for :day_event_locations, @day_event_locations do |day_event_location_builder| %>
    <%= day_event_location_builder.fields_for :day, @day do |builder| %>
      <div class="well">
        <%= render partial: 'day_fields', locals: { f: builder, del_builder: day_event_location_builder, event_builder: f } %>
        <%= link_to_add_association "Add Day", f, :day_event_locations, class: 'btn btn-sm btn-default init-add', render_options: { locals: { event_builder: f, type: "day" } } %><br>
      </div>
    <% end %>
  <% end %>
````

day_event_location_fields partial:

````
<% if type == 'day' %>
  <%= f.fields_for :day, f.object.build_day do |builder| %>
    <%= render partial: 'day_fields', locals: { f: builder, del_builder: f, event_builder: event_builder } %>
  <% end %>
<% else %>
  <%= f.fields_for :event_location, f.object.build_event_location do |builder| %>
    <%= render partial: 'event_location_fields', locals: { f: builder, del_builder: f } %>
  <% end %>
<% end %>
`````

It would be a great help if you can help me resolve this issue. Thanks

**Comment by nathanvda** [comment]
Honestly, just trying to read this question, a lot of stuff is unclear to me. Obviously you are not pointing out a cocoon bug, it sounds more like a problem using associations and validations. Please try asking this question on stackoverflow.com, where you can get more eyes on your question quickly (here it is just me). 

Just one tip: if you build one big form, any validation that fails will halt the saving of the complete form. You might want to split things up: adding a day to an event, or a location, sounds like something that should always succeed. Also, as an outsider, not sure why a "day" should be an object, and not just a date? But maybe in your case that _is_ the smartest solution.

**Comment by AhmadSaleem** [comment]
Thanks for getting back to me. Not sure if I was able to phrase my question well enough. I'm closing this issue because it doesn't seem like the right place to discuss this.
