### ISSUE TITLE
Issues with link_to_remove association when submit form and server responds with error.

### ISSUE THREAD

**Issue by LuuchoRocha** [nathanvda/cocoon#367]
I have a little issue after try to **edit** a resource. When the server responds _with errors_ and renders **:edit** again, the deleted associations using `link_to_remove_association` are shown again. 
I checked the `_destroy` value and it is `true`, so, the record deletion is working fine but the nested-fields divs are shown in the form. 
I've solved it in my project with one line of js:

`$('div.nested-fields').has('input[id$=__destroy][value=true]').css('display','none');`

Of course this is easy to solve in the core of the gem but I don't have time to make a PR, sorry...

**Comment by nathanvda** [comment]
This should be working, which version of the gem are you using? This was a turbolinks issue, and is only fixed in the latest version. Or, the code relies on the the `link_to_remove_association` to be inside the wrapper class, maybe that is your case?

**Comment by LuuchoRocha** [comment]
I'm really sorry, my gem was outdated. After update it, now everything is working fine.
