### ISSUE TITLE
Problems with placeholder in simple_form textarea

### ISSUE THREAD

**Issue by nononoy** [nathanvda/cocoon#368]
`= f.input :description, as: :string, input_html: { placeholder: 'Placeholder', rows: 3}, label: false, required: true` provides me a placeholder

![43838ee8f3](https://cloud.githubusercontent.com/assets/5082711/15365808/45e54178-1d2a-11e6-8e2b-5598f6e78c22.png)

but, `= f.input :description, as: :text, input_html: { placeholder: 'Placeholder', rows: 3}, label: false, required: true` makes me feel sadness

![08219391e4](https://cloud.githubusercontent.com/assets/5082711/15365958/e9e61ea0-1d2a-11e6-94cb-843b5c7488d9.png)

**Comment by nathanvda** [comment]
Posted in wrong repository? Cocoon has no influence on how textarea or placeholders are rendered. 

Anyway quick look: the html looks correct, so guessing you have css or js that messes with placeholders?

**Comment by nononoy** [comment]
hmm, I probably made ​​a mistake with the repository) thanks
