### ISSUE TITLE
Trouble when creating a new entry inline replacing existing ones

### ISSUE THREAD

**Issue by kimadactyl** [nathanvda/cocoon#372]
Heya, a bit hard to explain! Apols if this doesn't really get it.

I have members, locations, and member_locations - i.e., people live at addresses to and from certain dates. Members have_many locations :through member_locations, so I'm basically with the tutorial in theory.

My problem comes when I want to add a new location rather than attaching an existing one. When I do this, the last location added edits to become the new one: i.e, it's not making a new record but updating the current one. Everything else is working as expected, not added any JS yet so it's ugly but basically working.

Any ideas? Can take some screenshots if that helps.

My form:
```ruby
<%= semantic_form_for(member) do |f| %>
  <%= f.inputs do %>
    <div id="tasks">
      <%= f.semantic_fields_for :member_locations do |member_location| %>
        <%= render 'member_location_fields', f: member_location %>
      <% end %>
      <div class="links">
        <p>
          <%= link_to_add_association 'add existing location', f, :member_locations %>
        </p>
      </div>
    </div>
  <% end %>
  <%= f.actions do %>
    <%= f.action :submit, :as => :button %>
  <% end %>
<% end %>
```

_member_location_fields.html.erb
```ruby
<div class="nested-fields member-location-fields">
  <%= f.inputs do %>
    <div id="location-from-list">
      <%= f.input :location, :collection => Location.order('name ASC').all, :prompt => 'Choose an existing location' %>
      <%= f.input :from, :as => :date_picker %>
      <%= f.input :to, :as => :date_picker %>
    </div>
    <%= link_to_add_association 'create a new location', f, :location %>
    <%= link_to_remove_association "remove location", f %>
  <% end %>
</div>
```

_location_fields.html.erb
```ruby
<div class="nested-fields">
  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :line1 %>
    <%= f.input :line2  %>
    <%= f.input :city %>
    <%= f.input :postcode %>
  <% end %>
</div>
```

**Comment by nathanvda** [comment]
If I understand correctly: you want to add a member-location with either an existing location, or create a new location on the fly. 

Did you check the [demo-project](https://github.com/nathanvda/cocoon_simple_form_demo) where I demonstrate this behaviour?

If you did, and you are stuck, I need to see some more code: 

* your model definition (especially the relations + `accepts_nested_attributes_for`)
* your JS, because as in my demo, you will need javascript code to when clicking the `create new location` to hide/remove the `f.input :location`
* what is posted to the controller (check your logfile)

**Comment by kimadactyl** [comment]
Yes that's it exacttly. I've tried to base it on demo-project, might be missing something :)

I haven't used any additional JS at all yet - will this be stopping it working? I thought that was for cosmetic purposes alone!

Relevant model logic:

```ruby
class Member < ActiveRecord::Base
  has_many :member_locations
  has_many :locations, through: :member_locations
  accepts_nested_attributes_for :member_locations, allow_destroy: true
  accepts_nested_attributes_for :locations
end

class MemberLocation < ActiveRecord::Base
  belongs_to :member
  belongs_to :location
  validates_presence_of :member, :location

  accepts_nested_attributes_for :location, :reject_if => :all_blank
end

class Location < ActiveRecord::Base
end
```

```
Started PATCH "/members/2" for 127.0.0.1 at 2016-06-21 13:56:15 +0100
Processing by MembersController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"zZMwLcozA9MMVSbDiTGmLyQopo+OYBmiAdeWxs4dy5BCbQ6InniVTFuHL1kqRBFoBhsrIxwONxbpOHAfVzVzcA==", "member"=>{"member_locations_attributes"=>{"0"=>{"location_attributes"=>{"name"=>"Test Location Added", "line1"=>"", "line2"=>"", "city"=>"", "postcode"=>""}, "location_id"=>"62", "from"=>"2001-09-30", "to"=>"", "_destroy"=>"false", "id"=>"51"}}}, "button"=>"", "id"=>"2"}
Geokit is using the domain: localhost
  Member Load (0.3ms)  SELECT  "members".* FROM "members" WHERE "members"."id" = $1 LIMIT 1  [["id", 2]]
   (0.2ms)  BEGIN
  MemberLocation Load (0.2ms)  SELECT "member_locations".* FROM "member_locations" WHERE "member_locations"."member_id" = $1 AND "member_locations"."id" = 51  [["member_id", 2]]
  Location Load (0.2ms)  SELECT  "locations".* FROM "locations" WHERE "locations"."id" = $1 LIMIT 1  [["id", 62]]
  Member Load (0.3ms)  SELECT  "members".* FROM "members" WHERE "members"."id" = $1 LIMIT 1  [["id", 2]]
  SQL (0.3ms)  INSERT INTO "locations" ("name", "line1", "line2", "city", "postcode", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["name", "Test Location Added"], ["line1", ""], ["line2", ""], ["city", ""], ["postcode", ""], ["created_at", "2016-06-21 12:56:15.550522"], ["updated_at", "2016-06-21 12:56:15.550522"]]
  SQL (0.3ms)  INSERT INTO "entities" ("created_at", "updated_at") VALUES ($1, $2) RETURNING "id"  [["created_at", "2016-06-21 12:56:15.552185"], ["updated_at", "2016-06-21 12:56:15.552185"]]
  SQL (0.3ms)  UPDATE "locations" SET "name" = $1, "line1" = $2, "line2" = $3, "city" = $4, "postcode" = $5, "created_at" = $6, "updated_at" = $7, "id" = $8, "entity_id" = $9 WHERE "locations"."id" = $10  [["name", "Test Location Added"], ["line1", ""], ["line2", ""], ["city", ""], ["postcode", ""], ["created_at", "2016-06-21 12:56:15.550522"], ["updated_at", "2016-06-21 12:56:15.550522"], ["id", 63], ["entity_id", 113], ["id", 63]]
  SQL (0.5ms)  UPDATE "member_locations" SET "from" = $1, "location_id" = $2, "updated_at" = $3 WHERE "member_locations"."id" = $4  [["from", "2001-09-30"], ["location_id", 63], ["updated_at", "2016-06-21 12:56:15.555684"], ["id", 51]]
   (1.8ms)  COMMIT
Redirected to http://localhost:3000/members/2
Completed 302 Found in 18ms (ActiveRecord: 4.5ms)
```

**Comment by nathanvda** [comment]
Well, now you post both a `location_id` and the `location` contents, which seems to cause (from the logging) to overwrite the old location (as you said). So you have to remove the `location_id` from the form, and only when you press the `link_to_add_association` button, and the only way is using js and listening to the `cocoon:after/before-insert` callback. 

Is that clear?

**Comment by kimadactyl** [comment]
Oh! I understand, thankyou. Will have a try tomorrow. Thanks again.

**Comment by nathanvda** [comment]
Awesome! 👍 😉

**Comment by kimadactyl** [comment]
Hmm still getting the same problem. Get what it's trying to do but think I'm missing a step. Also, weirdly, line 15 is only triggering when I click "create new address" the second time. Any ideas? Also the demo project is a lil different to the other documentation now, not sure which to go with? :)

```javascript
$(function(){

  $("#js-member-locations a.add_fields").
    data("association-insertion-position", 'before').
    data("association-insertion-node", 'this');

  $('#js-member-locations').bind('cocoon:after-insert',
    function(e, loc) {
      console.log("inserting new location...");
      $(".js-member-location-fields a.add_fields").
        data("association-insertion-position", 'before').
        data("association-insertion-node", 'this');
      $(this).find('.js-member-location-fields').bind('cocoon:after-insert',
        function() {
          console.log("insert new location...");
          $(this).children("#js-location-from-list").remove();
          $(this).children("a.add_fields").hide();
        });
      });
});
```

_member_location.html.erb
```ruby
<%= semantic_form_for(member) do |f| %>
  <%= f.inputs do %>
    <div id="js-member-locations">
      <%= f.semantic_fields_for :member_locations do |member_location| %>
        <%= render 'member_location_fields', f: member_location %>
      <% end %>
      <div class="links">
        <%= link_to_add_association 'add existing location', f, :member_locations %>
      </div>
    </div>
  <% end %>
  <%= f.actions do %>
    <%= f.action :submit, :as => :button %>
  <% end %>
<% end %>
```

_member_location_fields.html.erb
```ruby
<div class="nested-fields member-location-fields js-member-location-fields">
  <%= f.inputs do %>
    <div id="location-from-list js-location-from-list">
      <%= f.input :location, :collection => Location.order('name ASC').all, :prompt => 'Choose an existing location' %>
      <%= f.input :from, :as => :date_picker %>
      <%= f.input :to, :as => :date_picker %>
    </div>
    <%= link_to_add_association 'create a new location', f, :location %>
    <%= link_to_remove_association "remove location", f %>
  <% end %>
</div>
```

_location_fields.html.erb
```
<div class="nested-fields">
  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :line1 %>
    <%= f.input :line2  %>
    <%= f.input :city %>
    <%= f.input :postcode %>
  <% end %>
</div>

```

**Comment by nathanvda** [comment]
Your code seems ok, except: an html idem can only have one ID, not two. So no sure which ID will actually be used. Also: repeating items cannot have the same id either, so that would be a problem when actually posting it to the server. So instead of `<div id="location-from-list js-location-from-list">` that should be `<div class="location-from-list js-location-from-list">` and adapt your jquery selector accordingly (use `.js-location-from-list`).

Not sure if that will resolve your problem though 😉

**Comment by kimadactyl** [comment]
Ooops, yeah, wasn't sure if your js classes do anything in the cocoon js (do they?) and got a bit carried away :)

ID rather than class was copied from here though, is there a difference between our implementations or is this a bug? https://github.com/nathanvda/cocoon/wiki/A-guide-to-doing-nested-model-forms#the-has_many-through-relation

Updated and not working - still only getting the "insert new location" line pop up on a second click. Any ideas?

```javascript
$(function(){

  $("#js-member-locations a.add_fields").
    data("association-insertion-position", 'before').
    data("association-insertion-node", 'this');

  $('#js-member-locations').bind('cocoon:after-insert',
    function(e, loc) {
      console.log("inserting new location...");
      $(".js-member-location-fields a.add_fields").
        data("association-insertion-position", 'before').
        data("association-insertion-node", 'this');
      $(this).find('.js-member-location-fields').bind('cocoon:after-insert',
        function() {
          console.log("insert new location...");
          $(this).children(".js-location-from-list").remove();
          $(this).children("a.add_fields").hide();
        });
      });
});
```

```ruby
<div class="nested-fields member-location-fields js-member-location-fields">
  <%= f.inputs do %>
    <div class="location-from-list js-location-from-list">
      <%= f.input :location, :collection => Location.order('name ASC').all, :prompt => 'Choose an existing location' %>
      <%= f.input :from, :as => :date_picker %>
      <%= f.input :to, :as => :date_picker %>
    </div>
    <%= link_to_add_association 'create a new location', f, :location %>
    <%= link_to_remove_association "remove location", f %>
  <% end %>
</div>

**Comment by nathanvda** [comment]
Yes, in that specific example: a project only has one owner :wink: so in that case it is ok to use id's because there is only one owner on a page. 

Cocoon does nothing with the class or id, it is pure html. Class is for repeating elements, id's should be unique on a page. And while rendering your html will not give an error, only one of the items will actually receive the id, and it is a bit random (undefined) which html element will keep the id. Also when submitting a form, we noticed that having repeating elements with id's only one element is submitted to the server (in this case: "we" is people submitting the bug and me and other people finding the error :wink: )

But I see one more typo: you attach your jquery to `#js-member-locations` but it also should be a class (you already defined it as a class). Also always easy to debug: add a `console.log` to check if your callback is triggered or not.

**Comment by kimadactyl** [comment]
I meant the Tags example, not the Owners one :)

Hmm. Not sure why having that as an ID rather than class would make a difference but changed it anyway to all classes and no luck. Good to know on the HTML too, didn't want to break anything built in :)

I'm using Rails 4, should I be using the demo site or the docs as a base or does it not matter?

I'm also confused what's going on here.

```javascript
  $('.js-member-locations').bind('cocoon:after-insert',
    function(e, loc) {
      console.log("inserting new location...");
      $(".js-member-location-fields a.add_fields").
        data("association-insertion-position", 'before').
        data("association-insertion-node", 'this');
// This is currently only firing on second "create new location" click - is that right?
      $(this).find('.js-member-location-fields').bind('cocoon:after-insert',
        function() {
          console.log("insert new location...");
          $(this).children(".js-location-from-list").remove();
          $(this).children("a.add_fields").hide();
        });
      });
```

**Comment by kimadactyl** [comment]
Oh - just discovered if I click on "add existing location", THEN "create new location", it works fine. Is that how it's meant to work? Maybe my links are just in the wrong place!

**Comment by nathanvda** [comment]
Hmmmmm *confused*. That is indeed how it is supposed to work, afaik: 

* `add new location` -> get dropdown to select exisiting location, which sets `location_id` accordingly
* click `create new location` -> adds fields for new location (cocoon), but should remove the `location_id` from the form or we overwrite the fields of the given `location_id`

Is that how you intended it to work? 

*coughs* and !@$#%# I should fix the tags example *coughs* :+1: nice catch :+1:

**Comment by kimadactyl** [comment]
I'm currently getting:

- `create new location` -> replaces the last location in the list
- `add existing location` -> `create new location` in the newly created element -> adds the new address to the list. Not currently hiding the "select an exiting address" element but doesn't seem to matter (prob another problem)

(BTW the .nested-fields and .links classes do stuff in cocoon right? that's kinda what I meant, or I'm going mad!)

**Comment by nathanvda** [comment]
Ok, confused again. What are you describing? You have two links for `create new location` ? 

I thought we are still busy with the case where, you wanted to add a location to a member, and by default, you show a drop-down list of (existing) locations, and when wanting to add a new location instead, it overwrites the already selected exisiting location, right? The solution was you need to remove the `location_id` field, so it is imperative to remove it, or saving will not work. 

Indeed, the `.nested-fields` and `.links` is important for cocoon behaviour. That was probably not clear, but I was just explaining the specific rule "use classes instead of id's for repeating elements" which is just standard html.

I am sorry, but this is getting to be a little too time consuming for me. So either, you have a look at the demo project where this works (and the js is not only needed for cosmetic purposes, but is needed to make sure saving will work correctly), or if you have a github project where you can reproduce this problem and I can easily run on my machine, I am willing to take a look. 

Or take this question to stackoverflow.com where there are more people who can help you.

**Comment by kimadactyl** [comment]
Thanks for this and sorry for my poor descriptions. Will have a proper tidy up and go through your example with a fine tooth comb and if that doesn't work will post it up properly with screenshots etc. Thanks for your help thus far making it a lot clearer now :)

**Comment by nathanvda** [comment]
Ok, thanks, and sorry for not being able to help you yet :(
