### ISSUE TITLE
Add association button appearing multiple times

### ISSUE THREAD

**Issue by askl56** [nathanvda/cocoon#373]
Hi @nathanvda great work on the gem.

When I'm using it on an edit form as opposed to a new form, I get multiple "Add association" buttons. How would you suggest the best way of getting around this is?

Code: https://gist.github.com/askl56/449956e303c8429431fa9078361419cc

SS: https://www.dropbox.com/s/bye5zbns8f57wts/Screenshot%202016-07-23%2020.05.33.png?dl=0

Cheers man,

//askl56

**Comment by askl56** [comment]
I've temporarily fixed with: 

```
$(function() {
  $('.edit_associated_products .edit-add:not(:last)').remove();
});
```

but would welcome feedback on if this is the right solution

**Comment by nathanvda** [comment]
You place the `link_to_add_association` inside the `fields_for` loop, which results in a "add button" for each nested item. Generally, if you want only one "add" button, you place it outside this loop (as demonstrated in my examples). 

Your code is not cleanly formatted at all which does not help with readability, for me that is good reason to use haml. But I am guessing you are not used to haml, so check out the [ERB examples](https://github.com/nathanvda/cocoon/wiki/ERB-examples).

**Comment by askl56** [comment]
Problem is that when I move it outwith the `fields_for` loop it no longer follows the right route
