### ISSUE TITLE
Weird HTML rendering by method link_to_remove_association

### ISSUE THREAD

**Issue by bgvo** [nathanvda/cocoon#377]
Hi,

We just migrated from ERB to Slim. We have been working with Cocoon for quite some time now. However, with slim we cannot make a has_many relation to work properly.

The problem seems to be with `link_to_remove_association`. When added, the HTML elements are messed up. You can see the diff [here](https://www.diffchecker.com/wm4apjro) (left side is the result of commenting link_to_remove_association; right side is the result once we add link_to_remove_association).

The code generating this is the following:

```slim
.col-xs-8.col-sm-8.col-md-8.col-lg-8
  .call-box.nested-fields
    .row
      .col-xs-12.col-sm-12.col-md-12.col-lg-12
        .call-start
          - unless f.index == 0
            .row.close-button
              / = link_to_remove_association '<i class="fa fa-times" aria-hidden="true">'.html_safe, f
          .row
            .col-xs-12.col-sm-12.col-md-12.col-lg-12
              = f.input :flexible_start, as: :boolean, input_html: {class: 'form-checkbox flex-start'}
          .row
            .not-flexible
              .col-xs-12.col-sm-12.col-md-12.col-lg-12
                .row
                  .col-xs-2.col-sm-2.col-md-2.col-lg-2
                    = f.input :start_day, collection: 1..31, input_html: {class: 'not-flexible'}
                  .col-xs-2.col-sm-2.col-md-2.col-lg-2
                    = f.input :start_month, collection: 1..12, input_html: {class: 'not-flexible'}
                  .col-xs-3.col-sm-3.col-md-3.col-lg-3
                    = f.input :start_year, collection: Date.today.year..(Date.today.year+3), input_html: {class: 'not-flexible'}
                  .col-xs-5.col-sm-5.col-md-5.col-lg-5
                    = f.input :facility_id, collection: @facilities, input_html: {class: 'facility-select',:data => {:target => "#{f.object.facility_id}" } }, include_blank: false, "data-parsley-required"=>"true"
```

Any help will be very appreciated. Thanks.

**Comment by nathanvda** [comment]
That _is_ weird. I think you have discovered a slim bug, no idea how cocoon could be causing this. From your diff, what I can see is that the content of the link (the icon) is repeated several times, right? Cocoon internally just calls a regular `link_to` to render the link. 

Did you try writing it like this:

      = link_to_remove_association  f do 
        %i.fa.fa-times

*this should be identical, because I just capture the block-contents. But maybe for some reason it makes a difference. 

Personally I generally use haml (and recently [hamlit](https://github.com/k0kubun/hamlit) is even faster than slim).

**Comment by bgvo** [comment]
Thanks! You made my day. 

Something weird is definitely happening. Just as you described, for some reason it goes down in the tree and adds the markup to other elements. I'll open an issue in [Slim](https://github.com/slim-template/slim) and see what they say.

Thanks a lot :)

I'll close this as it seems something unrelated to Cocoon.
