### ISSUE TITLE
Drag & drop image to Add new button to add new field

### ISSUE THREAD

**Issue by Rubioli** [nathanvda/cocoon#381]
Is it any way we can make it so when user **Drags & Drops** an image to `add new` button, it generate a new `field/nested_form` with image inside `input field`?

**Comment by nathanvda** [comment]
Never tried that. It is not something cocoon supports out of the box, if that is what you are asking. Better look at something like dropzone.js in that case. 

Nevertheless I think it should be possible. Something like: 

- add a `link_to_add_association` button
- listen for a `drop` event on the button

When a drop occurs: 

* trigger the `click` event of the button
* in the `after-insert` callback you set the input field to the dropped contents (file/image?)

Anyway, better ask such a question on stackoverflow.com where you will can get more relevant help sooner.

**Comment by Rubioli** [comment]
Thank you for your help 👍
