### ISSUE TITLE
Array of Hashes

### ISSUE THREAD

**Issue by eddieramirez** [nathanvda/cocoon#383]
I see that this supports simple arrays. What about array of hashes..

My Profile model has a links hstore array column...

The correct fields should be..
`profile[links][][name]`
`profile[links][][url]`

but I keep getting...
`profile[links][name]`
`profile[links][url]`

I've played around with `build_link` and `build_links`.. but no go..

**Comment by nathanvda** [comment]
Could you show some code, to see what you tried?

**Comment by eddieramirez** [comment]
I got it working with the following in my model..
<pre>
 def build_link
    {"" => ""}
  end
</pre>

and this in the partial for dynamic fields.
<pre>
= f.text_field "][name"
= f.text_field "][url"
</pre>

this is my partial for the existing fields..
<pre>
= f.label :name
= f.label :url
</pre>
