### ISSUE TITLE
Modal dialog for entry form?

### ISSUE THREAD

**Issue by cmcguff** [nathanvda/cocoon#384]
Tool is working fine, but I am trying to convert the display slightly to work better on a mobile device and looking for some options.

Currently I have a grid display, adding/removing etc. in the grid but this does not work well on a smaller screen device.

I would like to change this to popup a modal dialog with the entry fields in vertical display for better mobile entry, but retain the grid display overall. How can I attempt this in Cocoon?

Perfect world would be:
- Read only grid with actions per line to edit/delete
- On Edit or Add, details are displayed in a modal form
- On Save from modal, grid is updated as well

I suspect I need to look at having two fields partials, one for the modal and one for the grid but I'm unsure how to achieve it.

**Comment by nathanvda** [comment]
Cocoon allows you to manipulate/prepare a form, dynamically, which is only saved when submitted to the server.

When working with modal dialogs, I expect I add/edit something, and when the modal form is closed it is immediately saved. So you are not editing the parent object with it's children, but directly editing the child. Imho this is way easier and no need to use cocoon in that case.

I think your question scope is a little wider than merely cocoon (handling two possible renderings of the same view (mobile vs non-mobile), and best ui/ux/technical approach to achieve that), i propose you ask this question on stackoverflow, where you will get more interesting feedback.

**Comment by cmcguff** [comment]
Thanks, good points.
