### ISSUE TITLE
cancelling file upload adds an extra input

### ISSUE THREAD

**Issue by Sashkan** [nathanvda/cocoon#387]
I'm using cocoon for a nested form that accepts different kind of files.

Everytime I click on the button, a new input is created, and once the user selects a file, the preview appears inside of the input.

BUT, if for some reason, my user cancels the file upload (by clicking on the usual 'cancel' button, in the file selection window), the extra input is still added, with nothing in it, and when the form is submitted, the empty input is still processed, resulting in an extra, unnescessary record.

Is there a way to prevent this behaviour, so that if the file selection is cancelled, the extra input will be destroyed ?

**Comment by nathanvda** [comment]
If I understand correctly, you can simply ignore "posted" nested attributes using the `reject_if` option, e.g.

     accepts_nested_attributes_for :tasks, reject_if: :all_blank

will ignore `:tasks` that are completely empty. For instance, you could do something like 

     accepts_nested_attributes_for :files, reject_if: proc { |attributes| attributes['file'].blank? }

This might be easier then handling it on the UI side (also covers the case where a user just clicks the `link_to_add_association` button and never selects a file)

But if that does not answer your question, please show me some code.

**Comment by nathanvda** [comment]
Closed due to inactivity.
