### ISSUE TITLE
Do foundation and cocoon not play well together?

### ISSUE THREAD

**Issue by padrigirdap** [nathanvda/cocoon#389]
I'm trying to do a toggle dropdown menu to give myself some different options on whether to add 1, 2, or 3 of the same nested attribute (not sure how I'm going to do that but that's a different problem!). Anyway, when I throw in a Foundation 6 dropdown menu and try to nest the link_to_add_association, the animation doesn't work and I'm just left with a deflated menu!
```
<div class="medium-12 columns continuous_dropdown_grid">
  <ul class="dropdown menu" data-dropdown-menu data-alignment="right">
    <li>
      <a href="#" class="fa fa-plus-square fa-2x"></a>
      <ul class="pane_choice menu medium-horizontal">
           <li><%= link_to_add_association '1 Pane', f, :panes %></li>
           <li><%= link_to_add_association '2 Panes', f, :panes %></li>
            <li><%= link_to_add_association '3 Panes', f, :panes %></li>
      </ul>
    </li>
  </ul>
</div>
```

**Comment by nathanvda** [comment]
Check https://github.com/nathanvda/cocoon/pull/175 containing an example for exactly what you want to do.

**Comment by padrigirdap** [comment]
Thanks for the direction on my other issue. I actually just tried to implement it and can't seem to get it to work.

```
<div class="nested-fields">
  <div class="field">
    <%= f.label :rowtitle, 'Row Title', class: "row_title" %>
    <%= f.text_field :rowtitle, class: "row_title_input" %>
    <%= link_to_remove_association "Remove Row", f %>
  </div>
  <div id="panes">
    <%= f.fields_for :panes do |pane| %>
    <%= render 'pane_fields', :f => pane %>
    <% end %>
  </div>
  <div class="add-pane-items">
    <%= link_to_add_association '+', f, :panes%>
    <%= f.select :panenum, ['1', '2', '3']%>
  </div>
</div>
```

and the js

```
$('.add-pane-items').on('change', 'select', function() {
    count = $(this).val();
    $(this).closest('.add-pane-items').find('.add_fields').data('count', count);
});
```

**Comment by padrigirdap** [comment]
Whoops. Just searched more of the questions already posed. This has already been solved and I was trying to implement unnecessary Javascript! Sorry about that. All fixed :)

**Comment by nathanvda** [comment]
I linked the PR containing the `count` explanation, so I hope you just clicked on it? :smile: 

There are no known issues between cocoon and any css framework as such. If foundation uses js to enable specific parts (e.g. a dropdown), and you dynamically insert the html (e.g. using cocoon) you might need to use the callbacks to activate the behaviour. But I would assume you add the dropdown outside of the nested-fields partial?

**Comment by padrigirdap** [comment]
The dropdown is part of the first nested partial so judging by your answer it seems I would need to use the callbacks then! I'll give it a shot and update :)

**Comment by padrigirdap** [comment]
Was able to get the foundation initialized just fine using the callbacks. Unfortunately, I didn't think about what would happen if I added the link_to_add_association into a dropdown menu..The generated form shows up within the dropdown, not on the actual page. 
![cocoon-issue](https://cloud.githubusercontent.com/assets/18333208/19562839/d10935a2-96ab-11e6-876b-78eaedccfc0b.png)

using this code 
```
<div class="nested-fields">
  <div class="field">
    <%= f.label :rowtitle, 'Row Title', class: "row_title" %>
    <%= f.text_field :rowtitle, class: "row_title_input" %>
    <%= link_to_remove_association "Remove Row", f %>
      <div class="medium-12 columns continuous_dropdown_grid">
        <ul class="pane_dropdown dropdown menu" data-dropdown-menu data-alignment="right">
          <li>
            <a href="#" class="fa fa-plus-square fa-2x"></a>
            <ul class="pane_choice menu medium-horizontal">
              <li><%= link_to_add_association 'Add 1', f, :panes, count: 1%></li>
              <li><%= link_to_add_association 'Add 2', f, :panes, count: 2%></li>
              <li><%= link_to_add_association 'Add 3', f, :panes, count: 3%></li>
            </ul>
          </li>
        </ul>
      </div>
  </div>
  <div id="panes">
    <%= f.fields_for :panes do |pane| %>
    <%= render 'pane_fields', :f => pane %>
    <% end %>
  </div>
</div>
```
Is there a way to use my dropdown menu but generate panes inline with the rest of the elements in the body?

**Comment by nathanvda** [comment]
Yep, you can totally modify that. Check the documentation regarding the [insertion behaviour](https://github.com/nathanvda/cocoon#control-the-insertion-behaviour).

**Comment by padrigirdap** [comment]
Hmmm. I can't seem to get the selector to work. Is it because it has something to do with the fields being dynamically generated? For example, I put in 

```
$('#add_onepane').click(function() {
  console.log("found it");
});
````
this will not work.

but 
```
$('a.add_fields').click(function() {
  console.log("found it");
});
```
will work. This would be fine if I just had one nested form but I have 2 levels of nested forms, so I can't be that broad with selectors. I've tried a bunch of combinations but I can't get that jQuery to fire.
```
<div class="field">
    <%= f.label :rowtitle, 'Row Title', class: "row_title" %>
    <%= f.text_field :rowtitle, class: "row_title_input" %>
    <div class="medium-12 columns continuous_dropdown_grid">
      <ul class="pane_dropdown dropdown menu" data-dropdown-menu data-alignment="right">
        <li>
          <a href="#" class="fa fa-plus-square fa-2x"></a>
          <ul class="pane_choice menu medium-horizontal">
            <li><%= link_to_add_association 'Add 1', f, :panes, count: 1, id: "add_onepane"%></li>
            <li><%= link_to_add_association 'Add 2', f, :panes, count: 2%></li>
            <li><%= link_to_add_association 'Add 3', f, :panes, count: 3%></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
```

**Comment by nathanvda** [comment]
I will start with your initial sentence "I can't seem to get the selector to work" and you lost me already. Which selector? What are you trying to select?

**Comment by padrigirdap** [comment]
I was having trouble finding the correct link id using jQuery, however as it turns out, it was a spelling error in my `after-insert`. everything is as you said: laid out quite well in the docs, so I'll be closing this!
