### ISSUE TITLE
Can't get this gem working with Rails5, standard forms, and erb.

### ISSUE THREAD

**Issue by gbrl** [nathanvda/cocoon#390]
I recreated the demo app in your README on rails 5.0.0.1 with standard forms and erb views, but I can't get it working, no errors in console, nothing in logs. 

https://github.com/gbrl/debugcocoon

It's been a long day so maybe I missed something really simple. It seems like my partial doesn't render at all.

<img width="305" alt="screenshot 2016-10-16 00 18 22" src="https://cloud.githubusercontent.com/assets/733896/19415187/1486d358-9336-11e6-81ad-3cea2f2f38fd.png">

Any ideas? I'm totally stumped, but it could be something very simple. 

Thank you for your time!!

P.S. I'd be glad to have this app included in the README, since there is no demo app right now for standard rails forms. I can rename it if you want to include it in the docs.

**Comment by nickooolas** [comment]
No views are rendering?

**Comment by gbrl** [comment]
@nickooolas Views are rendering, see screenshot above. Also here is the HTML: 
<img width="791" alt="screenshot 2016-10-16 00 43 36" src="https://cloud.githubusercontent.com/assets/733896/19415266/a099a3ea-9339-11e6-86a3-ae9f22a2c2e2.png">

**Comment by nickooolas** [comment]
Did you instantiate the child objects (tasks) could only see Project.new on load from a quick look on mobile. 

Also, I believe need to wrap nested-fields div around the partial, couldn't see that, but once again I'm on the mobile ;)

**Comment by nickooolas** [comment]
Had another look, you need to instantaite the child object tasks...either can do it in Controller as Task.new or in the view

**Comment by gbrl** [comment]
Ah, I get it now. Strange that I didn't see that in the other demo apps. Thanks for your help!
@nathanvda Want to use my demo app in the readme?

**Comment by nathanvda** [comment]
You place the `link_to_add_association` inside the iteration of tasks (inside the `fields_for` loop), it should be outside (otherwise you cannot add a new task if there is none). 

Please check the wiki where I have translated [ERB-examples](https://github.com/nathanvda/cocoon/wiki/ERB-examples)

Imho ERB is too error-prone to serve as an example qed :grin: but I can understand ERB is maybe a little easier to grasp.

**Comment by gbrl** [comment]
@nathanvda Very true, I was wrote my ERB too fast! (and too late at night.)
Thank you!!

**Comment by gbrl** [comment]
@nathanvda I converted my demo app to HAML. 

https://github.com/gbrl/debugcocoon

**Comment by felintosudre** [comment]
https://gist.github.com/felintosudre/d0173b5aa5987ec7b349115efbbc5d43

My code don't render @nathanvda

**Comment by nathanvda** [comment]
Please ask this in a separate ticket, or ask it on stackoverflow, because you are probably just overlooking something. But then make sure to explain what "Your code doesn't render" means? You get an error and where? You do not see what you expect to see (and what did you expect to see?).

**Comment by felintosudre** [comment]
@nathanvda 
I expected to see the label and text_field for email registration. When you click the link you do not render the fields.

**Comment by nathanvda** [comment]
(I ment: ask in a separate ticket/issue or on stackoverflow and _explain there_)

**Comment by nathanvda** [comment]
@felintosudre BTW I do not see anything really wrong. Did you load the application.js? Do you have an error in the js console?

**Comment by felintosudre** [comment]
@nathanvda 
Grateful for the attention, the error was in the order of the file application.js
Correct
`//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require cocoon
//= require bootstrap
//= require_tree .`

My code
`//= require cocoon
//= require bootstrap
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require_tree .`

**Comment by variousred** [comment]
This bit me too by a sloppy translation of the HAML. At a glance it _appears_ that the `link_to_add_association` is _within_ the `fields_for`. Dont know if a change needs to occur, maybe a note to that effect in that section (if anyone else has experienced this hiccup)

**Comment by Mirv** [comment]
@variousred 

Two parts ...

I understand you have a new point to make.  Just to let you know, github etiquette is to start a new issue & link back to the old issue as a reference.  Github even includes nice an auto link handler for the purpose if you copy & paste the url ink: https://github.com/nathanvda/cocoon/issues/390.  (I just used URL pasted in & github shorted it for me)

On addressing your issue - it got us all at one time :)

The warning is actually one of the first things in the documentation ... look for `form builder` in the quote from the documentation, it's a matter of verbiage really, but it gets me sometimes when I'm just sloppy too ...

https://github.com/nathanvda/cocoon#link_to_add_association

> link_to_add_association
> This function adds a link to your markup that, when clicked, dynamically adds a new partial form for the given association. This should be called within the form builder.
> 
> link_to_add_association takes four parameters:

Also, not many people have done it - but if you wanted to contribute to the wiki - please do!  If you're really motivated submit a demo copy or just link to your github repo via the wiki on the Cocoon repo.

To help out with the house cleaning, when you've read this - can you close this issue.  Thanks!
