### ISSUE TITLE
How to implement auto-save?

### ISSUE THREAD

**Issue by gbrl** [nathanvda/cocoon#393]
I'm using this code for auto-save:

```
<script>

$(document).on('turbolinks:load', function() {

  var $form = $('form.autosave');
  var saving = false;

  function autoSaveForm(actionPath) {
    var data = $form.serialize();
    console.log("POST: " + actionPath);
    var request = new XMLHttpRequest();
    request.open('POST', actionPath, true);
    request.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded; charset=UTF-8');
    request.send(data);
    request.onreadystatechange = function () {
      if(request.readyState === XMLHttpRequest.DONE && request.status === 200) {
        saving = false;
      }
    };
  }

  $form.on('blur', 'input', function() {
    if (saving) {
      return; // don't do the blur action
    }
    saving = true;
    var actionPath = $form.attr('action');
    autoSaveForm(actionPath);
  });

});

</script>
```

However I'm getting two event triggers. Here's my console output:

```
POST: /user/profile VM1717:9 
POST: /user/profile VM1717:9 
```

Any idea what is causing this? I end up with two new records in the DB every time the blur event is triggered. I think it would be really useful to have one good example of how to implement auto-save on the forms this gem generates. 

If the ID is being sent along in the data, why does ActiveRecord not recognize that the record isn't new?

**Comment by gbrl** [comment]
I've posted this on SO if anyone wants the reputation points! :D 

https://stackoverflow.com/questions/40160726/how-do-i-prevent-multiple-duplicate-events-from-firing-on-a-dynamic-form/40160829?noredirect=1#comment67591448_40160829

**Comment by gbrl** [comment]
I figured out the issue. I need to create a new child record through AJAX every time the user clicks on the .add_fields link, and save the ID in the HTML that is generated...

**Comment by nathanvda** [comment]
Cocoon just helps in preparing the form. So this auto-save in itself has nothing to do with cocoon. 

However, if the form is only saved once, it is ok. But after an auto-save you should re-render the form, because otherwise the state of the form does not match the state in the database, and it will re-add the newly added nested fields (which were saved in a previous auto-save).

**Comment by gbrl** [comment]
So are you suggesting I make an action in my controller that returns just the form?

**Comment by gbrl** [comment]
Anyways, I think I know what to do now. Thanks for your advice!

**Comment by gbrl** [comment]
I'm wondering if re-rendering the form would cause whatever the user is typing to disappear, if the AJAX call was slow..... I think I'll do implement auto-save by adding the ID hidden field with JS.

**Comment by nathanvda** [comment]
You do what you think is best, however a few thoughts: 

- with a normal form, a user has the ability to cancel, and also: not saving is cancel
- if you are worried people leave or close the screen without saving, then do that. Like facebook or stackoverflow do, give an alert that there are unsaved changes on the page. The user still has the option to "just leave" in case she does not want to save, or she can save _all_ the data
- if you just want to save nested/related items immediately when they are added, without using a form, just use ajax, do not use cocoon :wink:
