### ISSUE TITLE
perform calculation on one coulmn

### ISSUE THREAD

**Issue by yousef-alsalem** [nathanvda/cocoon#398]
Let's say I have an order request, and it has many items (nested_froms) which user can add the title, quantity and price of each item, and JS will automatically  calculate the price of the item whenever it price or quantity has been change. I have done that so far.
Now, I need to update the "Total Amount" of the order every time any price of an item change or an item has been deleted.  So, how can I calculate the Total Amount of all items' prices?
Thanks in advanced.

**Comment by nathanvda** [comment]
Euhm, a bit baffled why you ask this here? But let's roll with it: the total is the sum of all parts. So select all individual prices and do a sum. Easy with jquery. E.g. something like: http://stackoverflow.com/questions/2417553/jquery-calculate-sum-of-values-in-all-text-fields
