### ISSUE TITLE
Cocoon callbacks aren't firing on elements with cocoon event listeners? 

### ISSUE THREAD

**Issue by dskvr** [nathanvda/cocoon#399]
I am employing cocoon successfully multiple times in the past without much issue, until today. Structure is as follows (raw html and simplified)

```
<% link_to_association... %>
<table>
<thead>...</thead>
<tbody>
  <tr class="nested-fields">...</tr>
  ...
</tbody>
<tfoot>...</tfoot>
</table>
```

Adding and removing nested fields works flawlessly. However, the callbacks don't fire, on any element.

In this example, I should be able to listen to `tbody` for these events. This is based on docs and by referencing other implementations. It should be noted, I found conflicting information about this in a resolved issue that stated "I should not listen on the direct parent of the nested fields" unless I misunderstood (paraphrased), so I tried `table` and `form`  ... This was confusing because all my previous implementations listen on container itself, but I digress.

All had similar results (nothing happened) So I tried a wildcard to see if the event fired anywhere (it didn't)

```
$("*").on('cocoon:before-insert', function () { alert('something happened'); });
```

I then profiled the page, and found that at no point was *any* cocoon event fired. Though, adding and removing works as expected. 

Thoughts?

**Comment by nathanvda** [comment]
It is the clicked link to emits the event, and since it is not inside the table that explains the first part of your post. So to catch the event you need to listen on any surrounding container (of the link), for instance the surrounding form should just work. 

Or something like `$(document).on("cocoon:before-insert", function() {} )` (because events bubble up until they are handled). 

I am not sure why the `$('*')`  does not work. 

If you want to see if events are fired, you can this as follows: http://stackoverflow.com/questions/3787555/how-to-find-out-which-javascript-events-fired (from your explanation it was not clear if that was where you were looking)

**Comment by dskvr** [comment]
I've adjusted the title to more accurately reflect the issue given the information you've just given. 

It wasn't known that the trigger element had to be inside the container, and once correcting that issues, I was able to see cocoon events bound to the trigger element. 

However, I encountered the same issue. The callback is never fired, despite seeing evidence of it being bound to element that I have bound the callback to. See below.

This is the event listeners on the trigger element (add_fields)

![screen shot 2016-12-18 at 11 22 03 am](https://cloud.githubusercontent.com/assets/299465/21294805/4dad55e8-c514-11e6-8373-0f40ca4622ce.png)

And here's the code.

```
$(function(){
    $("a.add_fields")
      .on('cocoon:before-insert', function () {
          console.log('before insert');
      })
      .on('cocoon:after-insert', function () {
          console.log('after insert');
      })
      .on("cocoon:before-remove", function () {
          console.log('before remove');
      })
      .on("cocoon:after-remove", function () {
          console.log('after remove');
      });

   $("*").on('click', function(){
     console.log('no issues with stack');
   });
});
```
Here's console output. No obstructive JS errors, nothing. 

![screen shot 2016-12-18 at 11 30 29 am](https://cloud.githubusercontent.com/assets/299465/21294851/75f1fd0a-c515-11e6-9193-b47dd13ae5e6.png)

I'm going on day 5 of something that normally would have taken me approximately 5 minutes, and really just curious if you have any known issues, edge cases or uncommon sensitivities you may be hyper-aware of, I don't expect you to solve this issue for me :)

Notes:
- This application utilizes cocoon successfully in multiple areas, cocoon and its callbacks work flawlessly in these parts of application. 
- I've stripped down this functionality and the JS assets loaded on the page of this particular functionality for the purpose of debugging (cocoon and jquery are the only js assets being loaded, so I can infer with certainty it is not a conflict)
- The patterns I'm employing are **identical** to other areas of the application (less the button location in the example listed in the issue, which was a markup error I overlooked resulting in the button being *rendered* outside of the nested fields element.)

Anyways, thank you for any information or any ideas you could provide.

**Comment by nathanvda** [comment]
* Did you try with the `$(document).on("cocoon:before-insert", ...)`. This would handle any unhandled event ?
* from your code, I thought it could be a turbolinks problem? (using the `ready` event only, but in that case the click-event would also not be captured)
* there is, by coincidence, not another event-handler that captures it first and stops propagation? 

In the cocoon-code, the inserting of the html is surrounded by the raising of the events, so if the inserting works, raising the events should work. So weird you would not be seeing them. Also weird it works in other places, and not on that page?? 

If you can create a small test-case (as you already did?) and are willing to share that in a separate repo, I am willing to take a look. My

**Comment by dskvr** [comment]
Looks like a premature publish, I'll look into the issues you've listed so far and see what I can come up with. If all else fails, I'll send you a vanilla test case. :)

**Comment by dskvr** [comment]
I feel like an idiot.

jQuery was being included twice, I didn't confirm this was the exact because I need to move like the wind at this point, but what I speculate is that the listeners were bound on a different instance of jQuery than Cocoon was firing the events from. How I didn't notice this before I have no idea. It took an accident and some snooping in adjacent partials to notice the discrepancy. (I hit my head against the table at the cafe for a good 10 minutes.)

😞

**Comment by Innarticles** [comment]
@dskvr @nathanvda I have been having similar issues. 
My callbacks are not working. I have tried all I can. 
See my code

js:
```javascript
$(document).ready(function() {
    $('#items')
      .on('cocoon:after-insert', function(e, added_task) {
        console.log(added_task);
      })
      $("#items").on('click', function(){
     console.log('looks like clicking works...'); //this works fine
   });

});
```



_form

```html
        <div id="items">
          <% f.fields_for :sale_items do |sale_item| %>
          <%= render "sale_item_fields", f: sale_item -%>
          <% end -%>

          <div class="field">
            <%= link_to_add_association '+ Add another line', f, :sale_items %>
          </div>
        </div>
```

_sale_item_fields

```html

<div class="nested-fields" id="items2">
  <div class="col-sm-2 pad5">
    <%= f.text_field :price, :class => 'item_price form-control ',  placeholder: "enter price" %> 
  </div>
  <div class="col-sm-2 pad5">
    <%= f.text_field :quantity, :class => 'item_quantity form-control ', placeholder: "enter quantity" %> 
  </div>
  <div class="col-sm-2 pad5">
   <input type="text" class="form-control item_amount" value="0.0">
 </div>
 <div class="col-sm-1 pad5" align="center">
  <%= link_to_remove_association "X", f %> 
</div>

</div>
```

application.js

```javascript
//
//= require jquery
//= require jquery_ujs
//= require cocoon
//= require turbolinks
//= require jquery-ui
//= require autocomplete-rails
//= require twitter/bootstrap


//= require_tree .
```
Every other thing works fine but the callbacks are not working. Is it the jquery?

**Comment by nathanvda** [comment]
@Innarticles supposing none of those callbacks work (after-insert and click), and cocoon is working (clicking the link does insert new items), I am guessing that this javascript is executed while `#items` is not yet on the page. E.g. if you are turbolinks this might be very likely. 

Either do something like 

    $(document).on('ready page:load turbolinks:load') {
       $('#items'). ... 
    }

to attach the events (and this will rerun the code not only on first load, but also on turbolinks load and will work for turbolinks 4 and 5). 

Or a safer way to write this, is like this: 

    $(document).on('cocoon:after-insert', '#items', function(added_task) { ... })

We attach the handler to the top-level, this will always work (the document is always there), and when the event `cocoon:after-insert` is triggered on `#items` the callback is called. This should only be called once (in the ready block), as it will keep working after consecutive turbolinks loads.

**Comment by Innarticles** [comment]
So I have tried all the ideas shared, but still have not been able to make the callback work. 
My application.html looks good. 

```html 
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %> 
</head>
```
This is my gemfile 
```ruby
source 'https://rubygems.org'

ruby '2.2.5'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
# Use sqlite3 as the database for Active Record

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
# for front-end library


# Use jquery as the JavaScript library
gem 'jquery-rails'
gem "twitter-bootstrap-rails"
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'rails_12factor', group: [:staging, :production]
gem 'puma'
gem "jquery-ui-rails"
gem 'rails4-autocomplete'
gem "cocoon"
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
  gem "better_errors"
  gem "binding_of_caller"
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

gem 'devise'
gem 'pg'
```
This code didn't work too
```html
$(document).on('cocoon:after-insert', '#items', function(added_task) {
     console.log("in working"); });
```
I am able to see the event on chrome's event listner dev tab
![selection_192](https://cloud.githubusercontent.com/assets/7821781/23830912/da130918-0715-11e7-915d-8851b5120743.png)


When I inspect the link_add element, this is what I see
```html
<a class="add_fields" data-association="sale_item" data-associations="sale_items" data-association-insertion-template="


<div class=&quot;nested-fields&quot; id=&quot;items2&quot;>
    1489313066
  <div class=&quot;col-sm-5 pad5&quot;>
...
```

I can't think of what next to do.
Any ideas?

**Comment by nathanvda** [comment]
Can you share a repo with a minimal case where I can test/reproduce this? Everything you share seems to look good, so I am at a loss otherwise 👍

**Comment by Mirv** [comment]
@Innarticles ... one thing I missed last time ... you have an extra symbol in your view ...

`          <%= render "sale_item_fields", f: sale_item -%>`

At the very end there's an extra `-`, ... could that be it?

**Comment by Innarticles** [comment]
@Mirv That didn't do it. 
@nathanvda I have reproduced the app here https://github.com/Innarticles/kaya_test
The specific file is at app/views/sales/new.html.erb and js at app/assets/javascript/sales.js
Thank you for your help.

**Comment by Mirv** [comment]
My cloud9 hates me today, I've ran postgres before but can't get it today with your implementation ... only thing I would do be doing assuming the rest works is commenting out other stuff from the application.js & header till cocoon just starts working.  That heavy looking companyjs with app.min.js would also be something I'd remove while testing.

**Comment by Innarticles** [comment]
@Mirv @nathanvda Finally, double jquery to blame. 
Always double jquery. Another jquery was loaded in app.min.js. 

Thank you all for your time. And sorry for making you go through all the work :100:

**Comment by Mirv** [comment]
@Innarticles ... Yea, it's frustrating because you never know how or where it comes up! ... can you tell us where your double instance was?  So others can maybe read about it one day if in similar circumstances?

**Comment by ConfusedVorlon** [comment]
Adding another possible fail here. I was confused for a long time as to why my events were not firing and was wondering if I somehow had two jQuery instances.

the problem was simply that the form was loading asynchronously - so wasn't ready when I tried to bind to it.

**Comment by askrynnikov** [comment]
A change in `config/webpack/environment.js` helped me:
`environment.splitChunks((config) => Object.assign({}, config, { optimization: { runtimeChunk: 'single', }}))`

with these configuration options, callbacks did not work:
`environment.splitChunks()`
`environment.splitChunks((config) => Object.assign({}, config, { optimization: { splitChunks: true }}))`

solution found here: [How do I share the same instance of jQuery](https://stackoverflow.com/a/62740910/5013769)

**Comment by chessboardjscontagious** [comment]
i searched extensively for a solution and finally found the answer https://lnkr.fun/57e004c
