### ISSUE TITLE
What would it take to remove the jQuery dependency?

### ISSUE THREAD

**Issue by Dunkirk** [nathanvda/cocoon#401]
I read Giles Bowkett's new ebook, which makes the claim that Javascript has matured, and has made the need for jQuery obsolete. As an exercise, I started working through one of my newer apps to remove jQuery, and find replacements for anything that depended on it. One of these, of course, is this gem. While I could go back to writing hand-tooled helpers to deal with this problem, as per the traditional Railscasts way, I love the idea of this gem, and how it works in practice, by not needing a round trip to the server to insert new model instances in the DOM. I wondered if it would be possible to make cocoon.js work without the need for jQuery. I don't know much about what would be involved in rewriting it to use vanilla ES5, though, so I thought I'd just ask. It SEEMS like it might be straightforward. Is it feasible? Is it even desirable?

**Comment by nathanvda** [comment]
Good question. At the moment I have no real answer to that. While I understand it is definitely possible to remove jquery, not sure what the impact is with regards to backwards compatibility, with regards to browser compatibility (jquery handles all that for me), and I still pretty much like the jquery api (selector/sizzle). 

Anyway: at the moment I probably do not have the time, nor the inclination to investigate this. I am still pretty happy using jquery. 

But good tip: I should that ebook 👍

**Comment by artemgurzhii** [comment]
I would like to help with this, what browsers you want to support?

**Comment by nathanvda** [comment]
For the moment I am going to close this issue, as I see no added benefit in having to maintain support for different browsers, something jquery already manages perfectly.

**Comment by artemgurzhii** [comment]
Rails have dropped [jQuery](https://github.com/rails/rails/issues/25208) as dependency. And not all projects using jQuery.

**Comment by Mirv** [comment]
@artemgurzhii true, but commercial rails applications roll serverside (jquery) to the app till the regular js gets delivered enough to run - so it's not like it's going away.  I wouldn't mind seeing a project started on here for an all JS thing, as I'm learning some ember.js too - just saying that there's a niche regular js can't fill when loading your application up - especially on older/slower connections like mobile.
