### ISSUE TITLE
Any way to "seed" the values of a new instance?

### ISSUE THREAD

**Issue by Dunkirk** [nathanvda/cocoon#404]
I posted this [fully](http://stackoverflow.com/questions/41577571/how-could-i-clone-a-child-object-in-rails-using-cocoon) over at StackOverflow, but, to summarize here: Is there any way to hand an existing object to `link_to_add_association` function to pre-seed the HTML generated with the current values of the existing object? Something like this:

`link_to_add_association 'Clone', f, :codes, data: {"association-insertion-node" => "tbody.codes", "association-insertion-method" => "append"}, render_options: {locals: {code: code.object}}`

I tried looking at the code, but it's so abstracted, I'm having a hard time following whether I can inject a current object such that it will use it's attribute values as data in the fields.

**Comment by nathanvda** [comment]
Take a look at the [:wrap_object](https://github.com/nathanvda/cocoon#wrap_object) option, it allows to pre-initialize the object, I think you should be able to use it to clone from an existing object as well. 

E.g. something like this might work: 

    - code_to_clone = f.object
    = link_to_add_association('Clone', f, :codes,
        wrap_object: Proc.new { |new_code| new_code.name = code_to_clone.name; new_code })

Just copy 1 field for demonstration purposes :)

**Comment by Dunkirk** [comment]
`= link_to_add_association 'Clone', f, :codes, data: {"association-insertion-node" => "tbody.codes", "association-insertion-method" => "append"}, wrap_object: Proc.new {|d| d = code.object.clone; d.id = nil; d}`

Brilliant. Cheers!

**Comment by nathanvda** [comment]
:+1:
