### ISSUE TITLE
Nested form disappears when validation errors occurred

### ISSUE THREAD

**Issue by wgkoro** [nathanvda/cocoon#405]
I'm using cocoon for nested models.
I got problems when form validation failed, and couldn't solve it. I need help...

1. It worked **perfect for saving models**.
1. Got problems **when form validation failed**. 
1. When returned to form, nested form did not appear.

I want to show nested forms with input values.

## models

I have 2 models "Dish" and "DetailedDish".
Dish has many DetailedDishes.

```ruby
class Dish < ApplicationRecord
  has_many :detailed_dishes, dependent: :destroy, inverse_of: :dish
  accepts_nested_attributes_for :detailed_dishes, allow_destroy: true

  validates :title, presence: true, length: { maximum: 255 }
  validates :description, presence: true, length: { maximum: 1000 }
end
```

```ruby
class DetailedDish < ApplicationRecord
  belongs_to :dish

  validates :caption, presence: true, length: { maximum: 255 }
  validates :order, presence: true, numericality: true
end
```

## controller

Method "new" and "create"

```ruby
  def new
    @dish = Dish.new
    @dish.detailed_dishes.build
  end

  def create
    @dish = Dish.new(dish_params)
    @dish.user = current_user

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private
    def dish_params
      params.require(:dish).permit(:title, :description, :image_id, \
            detailed_dishes_attributes: [:id, :order, :caption, :_destroy])
    end
``` 

## forms

```erb
<h1>New Dish</h1>

<%= form_for @dish do  |f| %>
    <div>
      <%= f.text_field :title %>
      <%= f.text_area :description %>
      <%= f.text_field :image_id %>
    </div>
    <div>
      <p>Detail</p>
      <%= debug @dish.detailed_dishes.inspect %> <%# For debugging %>
      <% f.fields_for :detailed_dishes do |detail| %>  <%# Does not appear when validation failed%>
          <%= render 'detailed_dish_fields', f: detail %>
      <% end %>
    </div>
    <div>
      <%= link_to_add_association 'add_detail', f, :detailed_dishes %>
    </div>

  <%= f.submit %>
<% end %>

<%= link_to 'Back', dishes_path %>
```

### partial

_detailed_dish_fields.html.erb
```erb
<div class="nested-fields">
  <div class="field">
    order_id:<%= f.text_field :order %>
  </div>
  <div class="field">
    caption:<%= f.text_field :caption %>
  </div>

  <div>
    <%= link_to_remove_association "remove dish", f %>
  </div>
</div>
```

## Debug result at forms

`<%= debug @dish.detailed_dishes.inspect %>` shows like this when validation failed.
```
--- '#<ActiveRecord::Associations::CollectionProxy [#<DetailedDish id: nil, dish_id:
  nil, caption: "bbb", order: 1, created_at: nil, updated_at: nil>]>'
```
I put 1 detailed dish. Debugger shows nested object and input values `#<DetailedDish...` but f.fields_for shows nothing...

**Comment by wgkoro** [comment]
I forgot environment.
- Rails 5.0.1
- ruby 2.4.0
- cocoon 1.2.9

**Comment by nathanvda** [comment]
To test/verify/reproduce i upgraded the [cocoon_simple_form_demo](https://github.com/nathanvda/cocoon_simple_form_demo) to rails 5, added a validation, and I cannot simply reproduce it. 

For me it just renders the form with the validation errors: 

<img width="752" alt="screen shot 2017-01-15 at 17 22 31" src="https://cloud.githubusercontent.com/assets/34460/21964209/f0bf1f70-db47-11e6-997e-ee728e5b606e.png">

So I am a bit stumped here. I do not understand why the `inspect` would show something, and iterating over the nested items would not. 

The only things I can think off (wild guesses): 

* the association has a default scope (mmmmm NOPE inspect would show the same info)
* the view is rendered but hidden for some reason?

**Comment by wgkoro** [comment]
@nathanvda Thank you for quick reply :)

Now I made a very small app(rails) for reproduce problem.
https://github.com/wgkoro/cocoon_nested_problem
↑ It shows same problem (ruby 2.3, and 2.4). 
Would you please check this app?

At `/projects/new` page
<img width="247" alt="2017-01-16 9 37 14" src="https://cloud.githubusercontent.com/assets/551459/21968888/11d9bc98-dbdd-11e6-9ec4-ec57a270d7aa.png">

Click "Add detail" link, and fill forms except 1 input.
<img width="234" alt="2017-01-16 9 39 33" src="https://cloud.githubusercontent.com/assets/551459/21968906/2c85f4da-dbdd-11e6-8a34-7eea264f1f51.png">

Submit form. Then it shows error because 1 input was blank.
And it doesn't show nested form.
<img width="533" alt="2017-01-16 9 39 48" src="https://cloud.githubusercontent.com/assets/551459/21968934/6107533e-dbdd-11e6-8e8d-3848d7e7cc51.png">
 
Maybe I miss something...?

**Comment by wgkoro** [comment]
OMG I solved...

NOT VALID: `<% f.fields_for :detailed_dishes do |detail| %>`
**valid**:  `<%= f.fields_for :detailed_dishes do |detail| %>`  (equal was missing)

**Comment by nathanvda** [comment]
Owwww sorry, completely forgot to take a look. Awesome you found it :+1: :+1:

**Comment by codeglover** [comment]
I had this problem too, but because of another reason.

I was sorting the f.objects using :order:
<%= f.simple_fields_for :blocks, f.object.blocks(:order) do |block| %>

Order requires fields to be saved in the database, which the new fields were not. This was resulting in the new objects being removed upon failed validation.

The fix was to use sort_by instead of :order. Sort_by doesn't care about the database:
<%= f.simple_fields_for :blocks, f.object.blocks.sort_by{|x|x.position} do |block| %>

**Comment by DavidLowndes** [comment]
I also had this problem, but of a slightly different breed. My associated objects were eager loading their own associations:

          <%= f.fields_for :lines, @purchase_order.lines.includes(:map_type, :sender, :recipient) do |line| %>

Similar to the `:order` above, `.includes` dropped the new lines. My solution was to not eager load if the form was being used for creation:

          <%# Conditionally eager load lines. This prevents new lines disappearing on validation error %>
          <% lines = @purchase_order.persisted? ? @purchase_order.lines : @purchase_order.lines.includes(:map_type, :sender, :recipient) %>

          <%# Lines form %>
          <%= f.fields_for :lines, lines do |line| %>
            <%= render 'line_fields', f: line %>
          <% end %>
