### ISSUE TITLE
Can't create multiple level self-joined relation

### ISSUE THREAD

**Issue by dsounded** [nathanvda/cocoon#408]
let's say I have associations like this:

`belongs_to :parent, class_name: 'SomeClass', inverse_of: :children`
`has_many :children, class_name: 'SomeClass', foreign_key: :parent_id, inverse_of: :parent`

And when I build self-joined forms like this 

`<%= link_to_add_association f, :children, { partial: 'class/partials/class_fields' } %>`

I have infinity loop, I have read about making a limitation for the multiple nesting, but any chances to deal without it ?

**Comment by nathanvda** [comment]
I am assuming your partial contains the same `link_to_add_association` again.

Every `link_to_add_association` is pre-rendered at server side. If you do not limit the nesting it will indeed create an endless loop. 

If you need to have indefinite nesting, maybe cocoon is not the best tool for you, and you should maybe be using ajax/xhr.

**Comment by dsounded** [comment]
@nathanvda yeah, I see, `nested_form` can't do the same also, maybe it's not really a good choice in the situation, anyway just wanted to know if it works now, because other topics were way too old.

Thanks, I think we can close it.
