### ISSUE TITLE
link_to_edit_association

### ISSUE THREAD

**Issue by matzke** [nathanvda/cocoon#411]
after my form is saved, the nested objects are shown by another partial. now i want to offer a link_to_edit_association where the nested field is rendered again. how do i access parent form object? is there a link_to_edit_association?

**Comment by nathanvda** [comment]
I do not understand this question. In general I render the same form for new and edit, so there is no difference? 

What do you think a `link_to_edit_association` would do, as 1) the edit form for the parent will already show the editable content of the children, and 2) you can then remove the association, or add new ones. Or, you can just edit the child directly, but then you would use the child controllers and not go through the form of the parent (and then you do not need cocoon at all?)

**Comment by matzke** [comment]
okay nevermind, thanks for your answer ... and great work!
