### ISSUE TITLE
link_to_remove_association not removing from database

### ISSUE THREAD

**Issue by Cobbalobb** [nathanvda/cocoon#412]
Hi, 

Thanks so much for cocoon, it's great. 

I just have one issue I can't work out. My nested form items save correctly, but don't delete.

Here's my code:
Question section model:
```
class QuestionSection < ActiveRecord::Base
	belongs_to :section
	belongs_to :question

	accepts_nested_attributes_for :section, :reject_if => :all_blank
	accepts_nested_attributes_for :question, :reject_if => :all_blank
end
```

Question model:
```
class Question < ActiveRecord::Base
	belongs_to :section
	has_many :question_sections
 	default_scope { order(order: :asc) }

 	accepts_nested_attributes_for :section
 	accepts_nested_attributes_for :question_sections
end
```

Question form nested form
```
<fieldset>
    <ol>
      <%= f.fields_for :question_sections do |question_section| %>
        <%= render 'question_section_fields', f: question_section %>
      <% end %>
    </ol>
        <%= link_to_add_association 'add question section', f, :question_sections %>

  </fieldset>
```

/_question_section_fields.html.erb
```
<div class="nested-fields">
	  <%= f.label :question_id %>
	  <%= f.text_area :question_id %>
	<%= f.label :section_id %>
	<%= f.text_area :section_id %>
	<%= f.label :weight %>
	<%= f.text_area :weight %>
	<%= link_to_remove_association "remove from section", f %>
</div>

```
params
```
`def question_params
      params.require(:question).permit(:question, :section_id,
        question_sections_attributes: [:id, :question_id, :section_id, :weight, :_destroy ])
    end`
```

When I click the remove button it hides it from the DOM, but once I click update it doesn't actually remove it from the database.

Any help really appreciated.

Thanks,
James

P.S (I'm aware I have so un-needed code on my models, i'm going to clean it up when I have it all working.)

**Comment by Mirv** [comment]
Great post of the info needed to trouble shoot!  I did not see where you named which element/button specifically that you clicked ... so here's the generalize answer after looking at your code ...

---

I check the models first in these situations (even though statistically, it's a typo in the views)...

One thing standing out is that you are using:

`accepts_nested_attributes_for`

...without the...

`allow_destroy: true`

...in your models.

Example:

`accepts_nested_attributes_for :section, :reject_if => :all_blank`

This should probably be ...

`accepts_nested_attributes_for :section, :reject_if => :all_blank, allow_destroy: true`

**Comment by Cobbalobb** [comment]
Ahh, that was it!

I needed....
`accepts_nested_attributes_for :question_sections, :reject_if => :all_blank, allow_destroy: true`

... In my questions model.

Thanks so much for the help, i'm just teaching myself Ruby so really appreciated.

**Comment by Mirv** [comment]
Aye ... still teaching myself ruby & am paying @nathanvda back for the time he gave me :)
