### ISSUE TITLE
form_nested don't add dinamicaly

### ISSUE THREAD

**Issue by CHRSousa** [nathanvda/cocoon#416]
When i click in "Adicionar serviço" nothing happens, no new "linha" is rendered

Attach my code below:

_form.html.erb:

<%= form_for(@orcamento) do |f| %>

<% if orcamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(servico.errors.count, "error") %> prohibited this orcamento from being saved:</h2>

      <ul>
      <% orcamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.label :nome_proprietario %>
    <%= f.text_field :nome_proprietario %>
  </div>

  <div class="form-inputs">
    <%= f.label :cpf_proprietario %>
    <%= f.text_field :cpf_proprietario %>
  </div>

  <div class="form-inputs">
    <%= f.label :obra %>
    <%= f.select :obra_id, options_for_select(Obra.all.map{|u|[u.descricao, u.id]}, f.object.obra_id) %>
  </div>

  <div class="form-inputs">
    <%= f.label :bdi %>
    <%= f.text_field :bdi %>
  </div>

  <h3>Serviços</h3>
  <div id="linhas">
    <%= f.fields_for :linhas do |linha_form| %>
      <%= render 'linha_fields', f: linha_form %>
    <% end %>
  </div>

  <div class="form-actions">    
    <%= link_to_add_association 'Adicionar Serviço', f, :linhas %><br>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

_linhas_fields.html.erb
<div class="form-group nested-fields">
  	<%= f.label :quantidade %>
  	<%= f.text_field :quantidade %>
   	<%= f.hidden_field :id %>
    <%= f.hidden_field :_destroy %>
    <%= link_to_remove_association "ApagarServico", f %>
    <br>
</div>

**Comment by CHRSousa** [comment]
Segue o código no github: https://github.com/CHRSousa/orcRails

**Comment by nathanvda** [comment]
* please use english (you do not have to change your code example)
* please correctly format code (github uses markdown)

Anyway, this is most likely a javascript error: 
  
* did you add require the cocoon js in `application.js` and did you include it in the page?
  * do you have errors in the javascript console

At first glance, from your code,  the `javascript_include_tag` seems wring/missing: you load a `default` and I am not sure this is still supported, imho you should be using at least the symbol `:defaults` or explicitly load `application`. This would explain why the `cocoon.js` is not loaded :smile:

**Comment by CHRSousa** [comment]
When i put "<%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>" in the file application.html.erb the app returned the error below:

Showing C:/Users/Carlos Henrique/Desenvolvimento/Projeto Orcamento Engenharia/rails/orc/app/views/layouts/application.html.erb where line #7 raised:

TypeError: O objeto não dá suporte para a propriedade ou método
Extracted source (around line #7):
5    <%= csrf_meta_tags %>
6    <%= stylesheet_link_tag 'default', media: 'all', 'data-turbolinks-track': 'reload' %>
7    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
8
9    
10     <link rel="stylesheet" type="text/css"  href="http://arquivo.devmedia.com.br/artigos/LinhaDeCodigo/RicardoArrigoni/MenuEmCSSdropdown/estilo.css" />

Rails.root: C:/Users/Carlos Henrique/Desenvolvimento/Projeto Orcamento Engenharia/rails/orc

**Comment by CHRSousa** [comment]
When I change from 'default' to 'application'. My website didn't work.
When I change from 'application' to 'default', it work, but it note:
GET http://localhost:3000/javascripts/default.js
and:
GET http://localhost:3000/stylesheets/default.css
Thank so much...

**Comment by nathanvda** [comment]
I do not understand what happened, but if I understand correctly it is working now? If so you can just close the ticket.

**Comment by CHRSousa** [comment]
I reinstall node and it is working. Thanks.
