### ISSUE TITLE
Update multiple checkboxes on association model through nested attributes

### ISSUE THREAD

**Issue by mahendhar9** [nathanvda/cocoon#417]
Hello,
Can someone guide me on solving this issue.

[http://stackoverflow.com/questions/43034905/update-multiple-checkboxes-on-association-model-through-nested-attributes-coco](http://stackoverflow.com/questions/43034905/update-multiple-checkboxes-on-association-model-through-nested-attributes-coco)

Thank you.

**Comment by nathanvda** [comment]
I answered on stackoverflow.
