### ISSUE TITLE
Using link_to_remove_association without deleting associated object

### ISSUE THREAD

**Issue by benjam1n** [nathanvda/cocoon#418]
Hello! How can I use link_to_remove_association only for removing the association, not actually deleting the associated object?

**Comment by Mirv** [comment]
Going to have to be way more specific ... do can you link to repo of your senario?

Several senario's ....

1. You want to delete the foreign key entry from a single entry (schema would be `has_many` & `belongs_to `)

1. You want to ONLY delete the join table entry row linking the two tables.  The schema would be self-referential table or join table M:M / M:1:M ala has_many` + `through:`

On a side note ... the other thing I was thinking ...

Just don't use the `dependent: :destroy` part leaving any children of the owning object if you delete it?

**Comment by nathanvda** [comment]
Well you give us no data-model, so it is a little bit of guesswork, but did you check out the [demo-project](https://github.com/nathanvda/cocoon_simple_form_demo)? 

There we demonstrate for example 

> a project `:has_many` tags `:through` project-tags. Either you select an existing tag, or create and link to a new one. When unlinking from a tag, the tag is not deleted, only the link.

If you need more specific information/help, you will have to provide more information yourself.

**Comment by nathanvda** [comment]
Closed due to inactivity.
