### ISSUE TITLE
How to give unique ID for a repeating div in a Cocoon ?

### ISSUE THREAD

**Issue by smartmall** [nathanvda/cocoon#419]
I need to add a unique ID for a each repeating div in a cocoon, how can i do that ? any help will appreciate

**Comment by nathanvda** [comment]
Of course there are many different options, so if you explain _why_ you need this, I could maybe point to some solutions or alternatives. 

The simple answer is: use the callbacks to manipulate the HTML before/after insert and add a unique ID. 

Check the following (possibly) related issues: 

* #403 
* #394 
* #362 
* #365 
 
If you explain in more detail what you are trying to achieve and show me some code, I can give you more specific help.

**Comment by smartmall** [comment]
This is my Html.erb 

<script>
    $( document ).ready(function() {
        document.addEventListener("turbolinks:load", function() {
            console.log('load');
            $(document).on('cocoon:after-insert', '#repeatingz', function(added_task) {
                console.log("in working"); });
            // console.log($('.repetediv').length);
        });
    });

    $(document).on('click', '.myDivs', function () {
        $(this).toggleClass('selected');

        var selectedRoles = $('.selected').map(function() {
            var divId = this.id;
            var parentDivId = $(this).parents(".repetediv")[0].id;
            console.log("pA "+parentDivId);
            //var roleNames = $('#'+divId+' h5').text();
            var roleNames = $('#'+parentDivId).find('#'+divId+' h5').text();
            return roleNames;
        }).get();

        console.log(selectedRoles);
        var top = $(this).parents(".repetediv")[0].getElementsByClassName("rolefield")[0].id;
        console.log('top '+top);
        document.getElementById(top).value = selectedRoles;
    });

    function getSelectedTags(){
        var txt = $('#selectedTags p').text();
        alert(txt);
    }
</script>

<div class="col-md-12">
  <h3 class="subheading">ADDITIONAL USER</h3>
</div>
<%= form_for @vender_shop_details,id:"form_vender_property", url: {action: "create_shop_details"} do |f| %>
    <% @count =0 %>
    <div class = "repeating">
      <% f.fields_for :usr_additional_users do |builder| %>
          <% render 'usr_additional_user_fields', f: builder%>
      <%end%>
    </div>
    <%= link_to_add_association 'Add new', f , :usr_additional_users , class: 'btn btn-primary repeatz',
                                data:{association_insertion_node: '.repeating',association_insertion_method: :append } %>
    <%= link_to_remove_association "remove", f %>

    <%= f.submit({:value=>'submit',:class => 'btn btn-primary'})%>
<% end %>

This is my partial view 

<style>
  .selected {
    border: 1px solid #0000FF;
  }
</style>

<div class="rectangle repetediv" id="repetediv">
  <div class="row">
    <div class="col-md-6">
      <p class="file_field">
        <%=f.text_field :email,{:class => 'form-control', :placeholder => 'email'} %>
        <%=f.text_field :role, :class=>'rolefield'%>
      </p>
    </div>
    
    <div class="col-md-12"><h4 class ="pageRole">Page role</h4></div>
    <div class="col-md-12 long-multiselect__outer" style="width: 100%; height:200px; overflow: auto">
      <% @roles.each do |role| %>
          <% @count += 1 %>
          <div class = "col-md-6 myDivs-col">
            <div class="input-group btn-group myDivs" id="div<%=@count.to_s%>">
                  <span class="input-group-addon">
                  <i><img src='../assets/user_female' /></i>
                  </span>
              <div class= "form-control long-multiselect item-div">
                <h5><%=role.role_name%></h5>
                <p><%=role.description%></p>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

**Comment by smartmall** [comment]
This is my html.erb file 
`<script>

    $( document ).ready(function() {

        document.addEventListener("turbolinks:load", function() {
            console.log('load');
            $(document).on('cocoon:after-insert', '#repeatingz', function(added_task) {
                console.log("in working"); });
            // console.log($('.repetediv').length);
        });
    });

    $(document).on('click', '.myDivs', function () {
        $(this).toggleClass('selected');

        var selectedRoles = $('.selected').map(function() {
            var divId = this.id;
            var parentDivId = $(this).parents(".repetediv")[0].id;
            console.log("pA "+parentDivId);
            var roleNames = $('#'+parentDivId).find('#'+divId+' h5').text();
            return roleNames;
        }).get();

        console.log(selectedRoles);
        var top = $(this).parents(".repetediv")[0].getElementsByClassName("rolefield")[0].id;
        console.log('top '+top);
        document.getElementById(top).value = selectedRoles;
    });

</script>

<div class="col-md-12">
  <h3 class="subheading">ADDITIONAL USER</h3>
</div>
<p><%= form_for @vender_shop_details,id:"form_vender_property", url: {action: "create_shop_details"} do |f| %> </p>

<p>    <% @count =0 %></p>
 <p>   <% @patialCount = 0%></p>
  <p>  <div class = "repeating" id = "repeatingz"></p>
 <p>     <% f.fields_for :usr_additional_users do |builder| %></p>
   <p>       <% render 'usr_additional_user_fields', f: builder%> </p>
  <p>    <%end%></p>
 <p>   </div></p>

<p> <%= link_to_add_association 'Add new', f , :usr_additional_users , class: 'btn btn-primary repeatz', 
        data:{association_insertion_node: '.repeating',association_insertion_method: :append } %>
    <%= link_to_remove_association "remove", f %> </p>

<p>    <%= f.submit({:value=>'submit',:class => 'btn btn-primary'})%> </p>
<p><% end %></p>
`

**Comment by smartmall** [comment]
This is my partial view 

![div2](https://cloud.githubusercontent.com/assets/26533269/25273556/e1b7c100-26a9-11e7-89fb-141ba14000cd.PNG)

**Comment by smartmall** [comment]
Thank you for reply me.

**Comment by Mirv** [comment]
@smartmall ... so ... we kind of understand WHAT you want, but to best answer the question, if you told us WHY you want it?  What does getting the div ID allow you to do?

Also, do you get the console log messages?  If you don't get the console log messages please check this document on how to trouble shoot your issue ... [Trouble shooting Jquery](https://github.com/nathanvda/cocoon/wiki/Trouble-shooting:-Jquery-issues)

**Comment by Mirv** [comment]
@smartmall ... I stumbled this when digging something else too ... but you have to conver tot using haml instead of ERB (I'm sure there's other ways,but haml is better in general)...http://stackoverflow.com/questions/2217583/how-do-i-make-dynamic-ids-in-haml

**Comment by nathanvda** [comment]
Closed due to inactivity.
