### ISSUE TITLE
Assign records to current user

### ISSUE THREAD

**Issue by Rubioli** [nathanvda/cocoon#421]
In my application I have models `Post` & `Slides` & I have:
 ```
class Post < ActiveRecord::Base
   has_many :slides, inverse_of: :post
   accepts_nested_attributes_for :slides, reject_if: :all_blank, allow_destroy: true
```

Everything works fine, only thing I need *(because of how my application will work)*, is when a `slide` is created, I need to **assign** it to `current_user`.

I already have `user_id` in my `slides` table and:

```
class User < ActiveRecord::Base
  has_many :posts
  has_many :slide
end

class Slide < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end
```

Any help is appreciated!

**Comment by Mirv** [comment]
So, this is actually likely to be best answered on stackoverflow as it's not a functionality issue, but rather an implementation issue of how you setup your controllers.

If you link to the stackoverflow.com question - I'll take a peak with you ... post your controller code too.

Also, `current_user` is probably the devise_gem helper &  you can't assign anything too, but you could save it to a controller instance variable & then use that to create a has_one/has_many relationship.

**Comment by Rubioli** [comment]
Thanks a bunch.

Here is the link: http://stackoverflow.com/questions/43659184/assign-nested-attributes-records-to-current-user-when-using-cocoon-gem

**Comment by nathanvda** [comment]
Thanks @Mirv :+1: 

Closing this because we are answering the SO question :smile:
