### ISSUE TITLE
Don't Pre-populate existing/added posts in edit action

### ISSUE THREAD

**Issue by Rubioli** [nathanvda/cocoon#422]
[I have this question on SO](http://stackoverflow.com/questions/43781427/ruby-on-rails-cocoon-gem-dont-pre-populate-existing-added-posts-in-edit-acti), and wondering if someone can help me out.

Sorry for adding it as a issue, but the question is not getting any attention :)

Thanks in advanced

**Comment by nathanvda** [comment]
Stackoverflow notifies me daily of cocoon related questions, no need to open an extra issue.
