### ISSUE TITLE
Wrong behavior after adding second project in belong_to association

### ISSUE THREAD

**Issue by maximtop** [nathanvda/cocoon#425]
Hi, @nathanvda !
Thank you for gem.
I found in my project that when I try to create transaction second time with a new client,  my select form doesn't disappear, while after page refresh all works just fine.
I installed locally your example from https://github.com/nathanvda/cocoon_simple_form_demo and its behavior is the same as in my project.
![](https://media.giphy.com/media/xUA7aYRmt5QoMoMvTO/giphy.gif)
Here is my project on heroku:
https://fathomless-shore-32492.herokuapp.com/transactions
And code on github
https://github.com/maximtop/counter

Where did I get wrong? Why form correctly works only after pressing refresh button?

**Comment by nathanvda** [comment]
Your code is not turbolinks compliant. In `transactions.coffee`, instead of using `$(document).ready` you should be using `$(document).on('turbolinks:load')` (which is triggered on first page ready or a turbolinks load).

**Comment by maximtop** [comment]
Thank you very much! That resolves my problem!
