### ISSUE TITLE
How to remove link_to_remove_association for first nested fields alone?

### ISSUE THREAD

**Issue by Aravin** [nathanvda/cocoon#430]
Hi Team,

How to remove `link_to_remove_association` for first nested fields alone?

**example**:
```
 <td>
    <%= f.text_field :total_item_cost, required: "required" %>
  </td>
..
 <td>
    <%= f.text_field :total_item_cost, required: "required" %>
  </td>
  <td>
    <%= link_to_remove_association "x", f,  class: 'button hollow alert' %>
  </td> 
..
 <td>
    <%= f.text_field :total_item_cost, required: "required" %>
  </td>
  <td>
    <%= link_to_remove_association "x", f,  class: 'button hollow alert' %>
  </td> 
```

Instead of 
```
 <td>
    <%= f.text_field :total_item_cost, required: "required" %>
  </td>
  <td>
    **<%= link_to_remove_association "x", f,  class: 'button hollow alert' %>**
  </td>  <td>
    <%= f.text_field :total_item_cost, required: "required" %>
  </td>
  <td>
    <%= link_to_remove_association "x", f,  class: 'button hollow alert' %>
  </td>  <td>
    <%= f.text_field :total_item_cost, required: "required" %>
  </td>
  <td>
    <%= link_to_remove_association "x", f,  class: 'button hollow alert' %>
  </td> 
```

**Comment by Mirv** [comment]
I'm going to need you to elaborate on why to answer that...only thing I can think of is you want to change the placement of the remove button?  If you are doing to remove the ability to remove only the first item in a list there's 3  or 4 ways you can handle that differently than what you're looking at...

So, if you are trying to require something be filled out - then you just use validation on the model to force the user to leave the first field filled in and alone.  It's bad programming practice to make up new ways to force people to do something - normally you try to find a better way to convey to the user how to get what they want out of your form.

**Comment by nathanvda** [comment]
Please in the future ask questions like these on `stackoverflow.com` (SO). They are not really related to cocoon and are easily solved using plain javascript, when asking on SO you will get a reply a lot quicker.

Simplest way I can think of is simple javascript with jquery, if you give for instance all your remove-links a special class, something like `remove-nested-item` (well I would prefer a more specific name, but since you give no details whatsoever it has to be a little more abstract) : 

```
$('a.remove-nested-item').first().hide()
```

**Comment by Aravin** [comment]
@nathanvda Thanks. I though you will have some built-in method in cocoon itself.
