### ISSUE TITLE
Suggestion for when want to select each nested-fields div in jquery

### ISSUE THREAD

**Issue by Rubioli** [nathanvda/cocoon#433]
In almost all applications I have done, because of some additional changes I add to each `nested_form div`, such as collapsing, expending, moving around etc, I needed to select each `div` for itself in `jquery`.

I'm not sure if there is already a way to do it in `cocoon gem`, but a workaround I do is to get `id` from one my `inputs` and apply that as `data` to `nested_form div` or other parts I wanted to add changes too.

*My workaround:*
```
- field_title = f.input :title
// I do this sometimes when I can't select the ID
- tab_id = field_title.match(/id="(?<id>[^"]*)"/)

.nested-fields
  .panel{data: {div: "#{field_id_id}".tr('"=', '')}}
     // Other parts
```

Is this a good idea and maybe would be great to have a such *div selector* in the gem.

*Great `gem`* 👍

**Comment by nathanvda** [comment]
Sorry for keeping this open and unanswered for so long. This seemed more like a hint and not an actual question (?)
