### ISSUE TITLE
How to interrupt deletion on cocoon:before-remove

### ISSUE THREAD

**Issue by supiash1** [nathanvda/cocoon#435]
Hi,

Could you please let me know if there is a native solution for this in Cocoon gem now? or would really appreciate if you could suggest alternatives

https://stackoverflow.com/questions/22328180/ruby-on-rails-4-and-cocoon-gem-how-to-interrupt-deletion-on-cocoonbefore-remo

Thanks

**Comment by nathanvda** [comment]
Related issue: https://github.com/nathanvda/cocoon/issues/268

What is your specific use-case? Please note that cocoon helps in building a complete form with additions/edits/deletions which is only sent to the server/saved when actually submitting the form.

**Comment by supiash1** [comment]
Hi @nathanvda 
Thanks for your response,
I am doing a backend validation and giving them a flash message and allow the delete to go on based on the validation, and also delete them in certain situation independently of parent association(so it does not add _destroy)

**Comment by nathanvda** [comment]
This is all a bit confusing: you do a backend validation --> before the save, after the form submit, right? how does this relate to the `before-remove` javascript callback?

**Comment by supiash1** [comment]
@nathanvda, the user requirement is to delete the association independently of save, so there is an ajax to perform that operation and any validations on it, the argument is
In the Edit Screen - we delete some items and we add some items and click save, 
if the delete were not persisted on the backend before save and if there were an error on one of the add item, nothing will be updated so the user has to re-delete the ones which were previously done and then click save

**Comment by nathanvda** [comment]
This is old, but fixed in the meantime: https://github.com/nathanvda/cocoon#canceling-a-callback
