### ISSUE TITLE
Extra "[new_(modelName)]" is added to dinamically generated input tags 

### ISSUE THREAD

**Issue by Vuneu** [nathanvda/cocoon#436]
I have two models, Pregunta (question) and Encuesta (survey).

I was having problems with setting up a form for a one-to-many relationship; the nested values for the form were not saving, the server log complained about a parameter:

`Unpermitted parameter: new_preguntas`

So, I changed the controller to allow all parameters.

The form now saves the nested item, but only the first one. Server log outputs:

`Parameters:
 {"utf8"=>"✓","authenticity_token"=>"xYFEPCVVOyI8M7gk0qoCN8QeH7W94ioosQq6TPKlZP/i+o65EGxhW5r86FRsgZ1w5UIbgsWklgzc7Ir53PVthg==", "encuesta"=>{"tipo"=>"test", "preguntas_attributes"=>{"new_preguntas"=>{"texto"=>"test", "_destroy"=>"false"}}}, "commit"=>"submit"}`

I was at a lost on where this "new_preguntas" was coming from.

I checked my HTML and each new input added followed this format:

`encuesta[preguntas_attributes][new_preguntas][texto]`

Why is this happening?!

I changed the inputs to 

`encuesta[preguntas_attributes][i][texto]`

I submitted and all the nested questions were saved. 

Here are my models/views in case they are helpful.

```ruby
class Encuesta < ApplicationRecord
    has_many :preguntas, inverse_of: :encuesta, dependent: :destroy #cascade delete
    accepts_nested_attributes_for :preguntas, reject_if: :all_blank, allow_destroy: :true
end
``` 
```ruby
class Pregunta < ApplicationRecord
    belongs_to :encuesta
end
```
`_form.html.erb`
```erb
<%= simple_form_for(@encuesta) do |f| %>
  <%= f.error_notification %>

  <!--<div class="form-inputs">-->
    <%= f.input :tipo %>
    <h3>Preguntas</h3>
    <div id='preguntas'>
      <%= f.simple_fields_for :preguntas do |pregunta| %>
        <%= render 'pregunta_fields', :f => pregunta %>
      <% end %>
      <div class='links'>
        <%= link_to_add_association 'add pregunta', f, :preguntas %>
      </div>
    </div>
  <!--</div>-->

  <!--<div class="form-actions">-->
    <%= f.submit :submit %>
  <!--</div>-->
<% end %>
```
`_pregunta_fields.html.erb`
```erb
<div class='nested-fields'>
    <%= f.input :texto %>
    <%= link_to_remove_association "remove pregunta", f %>
</div>
```

**Comment by Mirv** [comment]
What's strange about the Parameters hash?

**Comment by Vuneu** [comment]
@Mirv Hey! I just finished editing my post, not sure if the question still stands now? If anything I found it strange because I expected it to go like this: 

`{"utf8"=>"✓","authenticity_token"=>"xYFEPCVVOyI8M7gk0qoCN8QeH7W94ioosQq6TPKlZP/i+o65EGxhW5r86FRsgZ1w5UIbgsWklgzc7Ir53PVthg==", "encuesta"=>{"tipo"=>"test", "preguntas_attributes"=>{"texto"=>"test", "_destroy"=>"false"}}}, "commit"=>"submit"}`

**Comment by nathanvda** [comment]
Theoretically the `new_preguntas` is not a problem at all, since it serves as an _index_ to find existing items. Problem is when you add multiple items. So that is why cocoon will replace the `new_preguntas` with a generated id before insert (so you can add multiple items at once). 

It _is_ a bit weird that this replacement would not work for you. Which version of rails/cocoon gems are you using?

**Comment by Vuneu** [comment]
> Theoretically the new_preguntas is not a problem at all, (...) 

That makes sense!

Rails version is 5.1.2, Cocoon's is 1.2.10

**Comment by Vuneu** [comment]
I tried to replicate my issue using Rails 5.0.4 and Rails 5.1.2, mostly reusing my previous code, and the issue didn't reappear. I guess it was something about my specific setup which was causing it.

**Comment by buncismamen** [comment]
I have the same issue 

in my another app it generated random [id] instead [new_model_name]

**Comment by nathanvda** [comment]
Can you show me how you added the inflections so rails (and by extension, my code) generates the correct plural/singular form? 

E.g. it should be located in `config/initializers/inflections.rb` and should contain something like 

```
ActiveSupport::Inflector.inflections do |inflect|
  inflect.irregular 'sleeve', 'sleeves'
  inflect.irregular 'valve', 'valves'
  inflect.irregular 'curve', 'curves'
end
```

So add a line like `inflect.irregular 'direksi', 'direksis'`. 

Personally we keep all our code in English and just translate the frontend :smile:

**Comment by buncismamen** [comment]
the problem is not from cocoon but 

its because I forget to set the inflections 

so when I add the inflections `inflect.irregular 'direksi', 'direksis' ` it works flawlessly

```
# Be sure to restart your server when you modify this file.

# Add new inflection rules using the following format. Inflections
# are locale specific, and you may define rules for as many different
# locales as you wish. All of these examples are active by default:
# ActiveSupport::Inflector.inflections(:en) do |inflect|
#   inflect.plural /^(ox)$/i, '\1en'
#   inflect.singular /^(ox)en/i, '\1'
#   inflect.irregular 'person', 'people'
#   inflect.uncountable %w( fish sheep )
# end

# These inflection rules are supported but not enabled by default:
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.irregular 'direksi', 'direksis'
end
```

**Comment by Mirv** [comment]
It's not defined in the normal English language you have to set the pluralization?  If so that's a great catch!

**Comment by nathanvda** [comment]
Not sure @buncismamen ever read my answer to them, but I have created a few rails applications with a lot of models and irregular plurals, and since rails depends on correct plural/singularisation to deduce association/model/controller-names (and as a non-English speaker myself) I learned pretty early on to set the pluralisation correctly. So when buncismamen mentioned the incorrect plural form I had a :bulb: moment 😝
