### ISSUE TITLE
link_to_add_association not adding forms

### ISSUE THREAD

**Issue by RinneHellscythe** [nathanvda/cocoon#439]
Hello, I'm a newbie to Rails and I was wondering why link_to_add_association was only adding "#" and not doing anything. i.e. the link was "orders/new" to "orders/new#"

Here's my new.html.erb

```
<h1>New Order</h1>
<%= simple_form_for @order do |f| %>
<%= f.error_notification %>
  <h3>Tasks</h3>
  <table class='table'>
    <thead>
      <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Price</th>
      </tr>
    </thead> 
    <%= f.simple_fields_for :order_lines do |ol| %>
      <%= render 'order_line_fields', f: ol %>
    <% end %>
  </table>
  
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
  <div class="links">
    <%= link_to_add_association 'Add Product', f, :order_lines, class: 'btn btn-primary'%>
  </div>
<% end %>
```

Here's my order_line_fields partial
:product_id_id was a mistake, but I think it's still supposed to work
I tried to make product_id:references
``` 
<div class="nested-fields">
      <%= f.collection_select :product_id_id, Product.all, :id, :name, :prompt => true %>
      <%= f.input :quantity %>
    </div>
```

Here's my Orders and OrderLines Controller
```
class OrdersController < ApplicationController
    before_action :authenticate_admin!, only: [:new, :edit, :update, :create, :destroy, :index, :show]
    def new
        @order_line = OrderLine.new
        @products = Product.all
        @order = Order.new
    end
    def edit
    end
    def update
    end
    def create
        @order = Order.new(params[:order].permit(:cashier_id_id, :total_price, :cash))
        @order.save
        OrderLine.delete_all
        redirect_to '/'
    end

class OrderLinesController < ApplicationController
    def new
    end
    def create
        
    end
```

My models for Order and OrderLine
```
class Order < ActiveRecord::Base
  belongs_to :cashier_id
  has_many :order_lines
  attr_accessor :total_price, :cash, :cashier_id_id, :order_line_attributes
  accepts_nested_attributes_for :order_lines, 
                                allow_destroy: true,
                                :reject_if => :all_blank
end

class OrderLine < ActiveRecord::Base
  belongs_to :order_id
  has_many :product_id
  has_many :products
  attr_accessor :product_id_id, :quantity, :price
  accepts_nested_attributes_for :products, 
                                allow_destroy: true,
                                :reject_if => :all_blank
                                #reject_if: proc { |att| att['description'].blank? }
end
```

I'm not sure why or how this problem exists, and it's driving me nuts.
Sorry if I pasted too much code.

**Comment by Mirv** [comment]
Is there an error message associated with this in particular?  Can you paste a snippet of the html code from viewing it?

Also, have you checked the server console to see if there's any errors?  If not, perhaps check log/development.log too?

(ignoring the obvious part of you really should go back and redo the _id_id thing, as rails assumptions might be hinging on this)

**Comment by nathanvda** [comment]
Seems like the javascript is not loaded (if clicking the link is not doing anything) 

* did you add the line `//= require cocoon` to your `application.js` ?
* did you include the `application.js` in your application layout? 

The `product_id_id` is a classic, just add a migration to rename the attribute because it will be a pain otherwise.

**Comment by RinneHellscythe** [comment]
Hey guys, sorry for the late reply. Turns out I have "//= require j-query-ujsn" in application.js (if I remember the name correctly), I removed it and worked. After that, the thing doesn't save, and turns out you have to put in attributes in the params for the nested forms too like
```
:order_lines_attributes => [ #fields and stuff]
```
Hope this'll help someone too, and thanks guys for taking the time to respond.
