### ISSUE TITLE
Can only create Order from form with nested forms once

### ISSUE THREAD

**Issue by josefinnilsson** [nathanvda/cocoon#440]
Hi, I've encountered a problem that I can't solve. If I could get some help that would be really appreciated! 

I have a model Order that has many Products trough OrderItems. I have a form for @order with fields_for :order_items. I can create an order without any problem, but when I try to create a second order I run in to two problems: 

1. The products which I selected form the previous order are still there. When I use `link_to_add_association` they disappear visually at least but I don't know why they are still there in the first place. 
2. After removing the products from the previous order, I add some new products and submit the form. Then I get the following error: _Couldn't find OrderItem with ID=1 for Order with ID=_. I guess that this is somehow related to problem number 1. 

Any ideas on how to solve this? Here's some code that might be helpful:
**order.rb** 
```
class Order < ApplicationRecord
	has_many :order_items, inverse_of: :order
	has_many :products, :through => :order_items, :class_name => 'Product'
	accepts_nested_attributes_for :order_items, :reject_if => :all_blank, :allow_destroy => true
	accepts_nested_attributes_for :products, :reject_if => :all_blank, :allow_destroy => true
end
```
**order_item.rb**
```
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  accepts_nested_attributes_for :product, :reject_if => :all_blank

  def products
  	@products = Product.all
  end
end
```
**product.rb**
```
class Product < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true

  has_many :purchases
  has_many :orders, through: :order_items
  has_many :order_items, inverse_of: :product
end
```
***orders_controller.rb***
```
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def index
    @orders = Order.all
  end

  def show
  end

  def new
    @order = Order.new
  end

  def edit
  end

  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to edit_order_path(@order), notice: 'Inköp tillagt'
    else
      render :new
    end
  end

  def update
    if @order.update(order_params)
      redirect_to edit_order_path(@order), notice: 'Inköp uppdaterat'
    else
      render :edit
    end
  end

  def destroy
    @order.destroy
    redirect_to orders_url, notice: 'Inköp borttaget'
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:total, :date, :mammerist, order_items_attributes: [:id, :_destroy, :product_id, :quantity, product_attributes: [:id, :_destroy, :name]])
    end
end
```
***views/orders/_form.html.erb***
```
<%= simple_form_for @order do |f| %>
<% if @order.errors.any? %>
<div id="errorExplanation">

  <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

  <ul>
    <% @order.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div>
  <%= f.date_select(:date, :order => [:day, :month, :year]) %>
  <%= f.text_field :mammerist, class: 'form-control' %>
  <%= f.number_field :total, class: 'form-control' %>
</div>

<div>
  <p><strong>Produkter:</strong></p>

  <div id="order_items">
    <%= f.simple_fields_for :order_items do |order_item| %>
    <%= render 'order_item_fields', f: order_item %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'add item', f, :order_items %>
    </div>
  </div>
<div>
<%= f.submit %>
<% end %>
```
***views/orders/order_item_fields.html.erb***
```
<div class="nested-fields">
   <%= f.association :product, collection: Product.order(:name)%>
   <%= f.number_field :quantity %>
  <%= link_to_remove_association "remove task", f %>
</div>
```

Thanks in advance!

**Comment by Mirv** [comment]
Addressing just the stuff in place ... I'm guessing that the jquery isn't firing or validation is catching up your submission of the form.  

Can you verify the jquery is firing correctly in the console? 
 
(https://github.com/nathanvda/cocoon/wiki/Trouble-shooting:-Jquery-issues#if-the-asset-is-loading-in-the-chrome-web-browser-elements-section-we-know-its-either-a-conflict-or-a-syntax-issue)

It would explain the stuff disappearing when you add the next link.

**Comment by josefinnilsson** [comment]
Okay so I tried to see if jquery is firing correctly, and before that I did a `bundle update`. After that I saw that jquery was working properly and so did my form! I don't really know what made everything work, could it have been that some gems were outdated? Anyways, thanks!

**Comment by Mirv** [comment]
Excellent, feel free to close this issue & keep in mind you normally get faster response on stackoverflow for help.
