### ISSUE TITLE
How to dynamically add nested object in new/edit form with autocomplete input

### ISSUE THREAD

**Issue by Nikolay-Lipovtsev** [nathanvda/cocoon#445]
Already a month trying to solve the problem at first sight is not very complicated: There are 3 models - team, user and team_user (has_namy: through) In the form of edit and new team to do the ability to dynamically add members of this team with autocomplete input.

app/models/user.rb

```ruby
class User < ApplicationRecord
  has_many :team_users
  has_many :teams, through: :team_users
  accepts_nested_attributes_for :team_users, :teams, allow_destroy: true
end
```
app/models/team.rb

```ruby
class Team < ApplicationRecord
  has_many :team_users
  has_many :users, through: :team_users
  accepts_nested_attributes_for :team_users, allow_destroy: true, reject_if: proc { |a| a['user_id'].blank? }
end
```
app/models/team_user.rb

```ruby
class TeamUser < ApplicationRecord
  belongs_to :team
  belongs_to :user
  accepts_nested_attributes_for :team, :user, allow_destroy: true
end
```

Something like this:

![-09-2017 21-04-51](https://user-images.githubusercontent.com/5441376/29136639-815bece8-7d46-11e7-9665-5a40e3a84413.gif)

**Comment by nathanvda** [comment]
Yep, that is indeed not a hard problem, but I would use ajax/xhr and not cocoon for this specific case. If you are troubles starting, please ask this question on stackoverflow. If you link the question here (and nobody replies sooner), I could share how I would handle this.

**Comment by Nikolay-Lipovtsev** [comment]
I have already published on stackoverflow.com a few questions on this topic, but unfortunately still can't do a proper implementation:

[Rails 5 - how to dynamically add nested fields in the edit form?](https://stackoverflow.com/questions/40960413/rails-5-how-to-dynamically-add-nested-fields-in-the-edit-form)
[Rails 5 and AJAX - can't do autocomplete and saving a nested form](https://stackoverflow.com/questions/45229715/rails-5-and-ajax-cant-do-autocomplete-and-saving-a-nested-form)

If possible, tell me how you solve this problem

**Comment by Nikolay-Lipovtsev** [comment]
@nathanvda 've asked another question on stackoverflow.com

[Rails 5 - how to dynamically add to the form a nested object using autocomplete](https://stackoverflow.com/questions/45638941/rails-5-how-to-dynamically-add-to-the-form-a-nested-object-using-autocomplete)

**Comment by dgleba** [comment]
I have replied here: [https://stackoverflow.com/questions/45638941/rails-5-how-to-dynamically-add-to-the-form-a-nested-object-using-autocomplete/45640137#45640137](url)

Let me know if that helps. I can work with you to define the answer further if it will help you and others who might read it later.
