### ISSUE TITLE
bad association pluralization produces invalid form

### ISSUE THREAD

**Issue by fauno** [nathanvda/cocoon#446]
hi, no idea if this is an issue with rails' inflections or cocoon, but i just hit this.  i'm using cocoon to create nested fields for a has_many relation called `agresores` in spanish, where the singular is `agresor`.  

adding and removing nested fields works ok but i noticed the params were rejected when i send more than the built agresor.  checking the generated fields i found that the id was "new_agresor" instead of a random id.

so while debugging this i discovered it was because the `.add_fields` element had a `data-associations="agresoreses"` instead of the correct `agresores`.  if i fix this manually using the web console i can add fields with the correct id.

i traced this to https://github.com/nathanvda/cocoon/blob/master/lib/cocoon/view_helpers.rb#L93 where the association is being re-pluralized so i wonder if it's really needed.  in the rails console i can test this works for words rails can understand:

```ruby
> :agresores.to_s.pluralize
=> "agresoreses"
> :users.to_s.pluralize
=> "users"
```

the agresor inflections are already added to `config/initializers/inflections.rb`...

**Comment by fauno** [comment]
changing L93 to `html_options[:'data-associations'] = association` works correctly, should i create a pr?

**Comment by nathanvda** [comment]
Mmmm weird, this should work. I also have a few models with irregular pluralization. How did you add the inflections to `inflections.rb` ?

If I add the following to my inflections: 

```
ActiveSupport::Inflector.inflections do |inflect|
  inflect.irregular 'sleeve', 'sleeves'
  inflect.irregular 'valve', 'valves'
  inflect.irregular 'curve', 'curves'
  inflect.irregular 'agresor', 'agresores'
end
```

Then `'agresores'.pluralize` just returns `'agresores'`. Which rails version are you using?

**Comment by fauno** [comment]
i'm using rails5 but my inflections are like this:

```ruby
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.plural 'agresor', 'agresores'
  inflect.singular 'agresores', 'agresor'
end
```

which has always worked for me

-- 
.oÓ)

**Comment by nathanvda** [comment]
If I define the inflections as you do (with the two lines), I get the same behaviour, so imho the `irregular` command seems a little more correct, since it defines the relation correctly between singular and plural and you only need one line. 

> What's with the "Which has always worked for me" ? That translates to: no room for learning something new? improvement? Not even just trying if it works better? Obviously it does not work because it tries to pluralize a plural form?

**Comment by fauno** [comment]
it works! thanks :)

i meant it always worked for the use cases i had and that's why i was surprised it didn't work this time.  model associations do work, for instance, but it seems i never had to pluralize, just singularize.
