### ISSUE TITLE
How to handle datepickers with cocoon?

### ISSUE THREAD

**Issue by Drillan767** [nathanvda/cocoon#451]
I'm using Cocoon (great gem by the way) in a form. In the generated partial, I want to use a datepicker (not jQuery UI, but [this one](https://github.com/fengyuanchen/datepicker))

However, I went through the same problem that some people had, which is that the datepicker works fine for the partial generated by default, but it won't work for any of the generated partials. 

I managed to find a solution that seems outdated, but still checks out with your doc. However, I can't make this work:

``` javascript
    $('.datepicker').datepicker();
// #specs is the div in which the partials are rendered
    $('#specs').on('cocoon:after-insert', function(e, insertedItem) {
        insertedItem.find('.datepicker').datepicker();
    });
```
I have 2 problems: the first one is that this doesn't work, but what troubles me is that if I run a `console.log(insertedItem)`, it gives nothing. I made sure that cocoon.js is loaded before my script.

What am I doing wrong?

Thank you in advance

**Comment by nathanvda** [comment]
Weird. This should work imho. Is the callback triggered at all? 

You could also check the examples in [the demo project?](https://github.com/nathanvda/cocoon_simple_form_demo) I noticed that I also use `$(this)` to start searching from?

**Comment by Drillan767** [comment]
I don't think the callback is being triggered, well at least `console.log(insertedItem)` does nothing, not even an error. However, clicking on adding or removing an element works really fine.
Also, where should I look in your demo project to check this `$(this)`?

Thank you for your answer!

**Comment by Drillan767** [comment]
Ok I discussed with the dude for whom I'm building this website. Turns out I don't need to put the datepicker inside the nested form, so there is no problem now :)

Thank you for your suggestions!

**Comment by SuperJones** [comment]
Was this issue ever revisited? 
I want to put 2 datepickers in with cocoon. 
So far the second datepicker works but the first one loosing focus. After too much time trying to figure this out and working with other devs, we decided not to use cocoon😔.

**Comment by SuperJones** [comment]
Just wanted to follow up:
I completely removed cocoon from my application and tried to manually recreate it based off a [railscast](https://www.youtube.com/watch?v=amT27SfNhKM) and the datepicker still broke. 
So I agree, it is not a cocoon issue.

**Comment by nathanvda** [comment]
Thanks for the feedback! Unfortunately this means you did not get it to work?

I would love to be of help, either through stackoverflow or open a ticket here? Probably you just need a nudge in the right direction.
