### ISSUE TITLE
How would you improve performance?

### ISSUE THREAD

**Issue by echan00** [nathanvda/cocoon#458]
I know this isn't particularly related to this awesome cocoon gem, but if I have many record associations (100-800), how could I improve performance when updating the record (especially when many of the associated records didn't change)?

**Comment by nathanvda** [comment]
To be honest, in that case I would be considering to use a different approach. Saving 100 nested items, and even if only one had changed, rails would have to load all 100 of them, just to be able to compare the data to see _if_ the data changed and should be updated or not. Also: loading all 100 in one go? I would assume you would want pagination? (that would break being able to save the nested form in one go).

So I would rather go for some kind of ajax/in-place-editing, so you always add one at a time or edit one at a time. Does that help?

**Comment by echan00** [comment]
Yes that does. That is a good idea. Ajax per associated record is a way to go about this.

**Comment by nathanvda** [comment]
Good question. I am not sure. Imho it is not possible to use pagination together with cocoon: you have to present the _complete_ nested-form (actually not cocoon functionality but rails that handles the saving of the nested form). But on the other hand: we have to set the `_destroy` flag in the form, soooooo if it is not set and the nested item is just missing, will rails just leave it be? To investigate 😎 :+1:

**Comment by echan00** [comment]
Yes, this seems to be a problem. I'm surprised to find that no one else has encountered this issue with too many associated records. 

I suppose AJAX per associated record could help improve performance a bit, but it also sort of means I wouldn't be using this awesome cocoon gem and writing a lot of custom code.

**Comment by echan00** [comment]
I ended up writing some code to remove all the records that didn't change in the params before saving the model. Not the best optimization but probably still better than doing a find and update on each record. 
A possible better solution would be to track which records changed in the front-end and only pass those params to the server. 

Still trying to figure out the best way to optimize loading many associated records though. I see a long list of partials each loaded separately!
