### ISSUE TITLE
Newly inserted form field overlaps one built through controller

### ISSUE THREAD

**Issue by TKB21** [nathanvda/cocoon#460]
My goal is have a blank form field available in my new action without clicking the button to "add association". My first inclination was do so in the "new" action of my controller as so:

```
def new
  @course = Course.new

  @course.sessions.build
end
```

This did as it should but when I want to add more fields they're inserted outside of my form container.

https://imgur.com/a/meMPy

Am I overlooking something in the docs that shows you how to accomplish this. My apologies if I did.

```
<div class="session-form-inputs">
  <h2>Sessions</h2>
    
  <%= f.simple_fields_for :sessions do |session| %>
    <%= render 'session_fields', f: session %>
  <% end %>

  <%= link_to_add_association 'Add Session', f, :sessions %>
</div>
```

**Comment by nathanvda** [comment]
Please check the [ERB examples](https://github.com/nathanvda/cocoon/wiki/ERB-examples) in the wiki. You can perfectly override the default insertion behaviour, but if not, your form should like this: 

~~~
<h3>Tasks</h3>
  <div id='tasks'>
    <%= f.simple_fields_for :tasks do |task| %>
      <%= render 'task_fields', :f => task %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'add task', f, :tasks %>
    </div>
  </div>
~~~

(copied verbatim from documentation; the link has to be wrapped in a separate div so it can remain at the end)

**Comment by cbanksbi** [comment]
Right on. After removing any and all sibling elements from the nested form field I was able to get the desired result:

```
<fieldset>
  <h2>Sessions</h2>

  <div class="session-form-inputs">
    <%= f.simple_fields_for :sessions do |session| %>
      <%= render 'session_fields', f: session %>
    <% end %>

    <%= link_to_add_association 'Add Session', f, :sessions %>
  </div>
</fieldset>
```

Thanks for the clarification.

**Comment by TKB21** [comment]
Right on. After removing any and all sibling elements from the nested form field I was able to get the desired result:

```
<fieldset>
  <h2>Sessions</h2>

  <div class="session-form-inputs">
    <%= f.simple_fields_for :sessions do |session| %>
      <%= render 'session_fields', f: session %>
    <% end %>

    <%= link_to_add_association 'Add Session', f, :sessions %>
  </div>
</fieldset>
```

Thanks for the clarification.

**Comment by nathanvda** [comment]
Ow weird, normally the code inserts `before` the `parent` of the link, so not sure how your updated view-code can achieve that, but happy you got it to work :+1:
