### ISSUE TITLE
preventDefault does not stop action

### ISSUE THREAD

**Issue by hudadiaz** [nathanvda/cocoon#462]
I have the following code:
```
$('#new_object').on('cocoon:before-remove', function(e) {
  var children = $(this).find('.nested-fields')
  if (children.length === 2) {
    e.preventDefault();
  }
});
```

If `object` has only 2 children, it should prevent the removal.

The code runs and reaches `e.preventDefault()` when `object` has 2 children but it still removes the `.nested-fields`.

**Comment by nathanvda** [comment]
Ha! I see I did not yet release the gem with that code, so for now you will have to do something like: 

    gem 'cocoon', git: 'git@github.com:nathanvda/cocoon' 

in your `Gemfile`. 

I will release the gem later today or somewhere this week.

**Comment by hudadiaz** [comment]
Yep, it works.

I'll just close this for now

**Comment by randikabanura** [comment]
still having this issue in the newest version. Anyway to solve this?

**Comment by nathanvda** [comment]
@randikabanura it should work (obviously it works since 2017). Please open a new ticket with your code, explain how you would expect it to work, and what fails. Please also specify which version you are using of ruby/rails/cocoon. I will be happy to help look into your problem.
