### ISSUE TITLE
after-insert callback not called on edit view for rendered fields

### ISSUE THREAD

**Issue by nicolrx** [nathanvda/cocoon#464]
Hello,
Not sure if it's an issue or just a troubleshooting question. I have a problem with my views when an error is raised on create or on the edit view.

My button association is not built. This issue is when the card records are rendered (on error view and edit view):
<%= render 'card_fields', f: card_fields %>

It does not create the buttons within the partial (wrapped into another field for)

Here is [the stackoverflow link](https://stackoverflow.com/questions/47049724/cocoon-gem-deep-association-not-built-when-edit-or-error-raised). I would really appreciate if you can take a look.

Thanks.

UPDATED bellow

**Comment by nicolrx** [comment]
This issue is with (on error view and edit view):
<%= render 'card_fields', f: card_fields %>

It does not create the buttons within the partial (wrapped into another field for)

**Comment by Mirv** [comment]
Great information setup on S/O !

**Comment by nicolrx** [comment]
UPDATE:
The problem is not about the fields not being built. I assumed the callback after-insert would be called for each record rendered in my edit view but it's not.

Thus, I have some jquery not working on those rendered fields, whereas if I add a new card with my link_to_add_association, everything works well.

Any idea how to trigger the after-insert callback for each card rendered easily?

**Comment by Mirv** [comment]
Try this ... https://github.com/nathanvda/cocoon/commit/f4241557c677455f6f0c7bce4829df5978aeb7af

**Comment by nathanvda** [comment]
Closed because the question was answered on S/O apparently.
