### ISSUE TITLE
Access Link Attributes From Event

### ISSUE THREAD

**Issue by ayaman** [nathanvda/cocoon#465]
Hello,

I'm trying to figure out a way to pass parameters to the JS events triggered by Cocoon. The best option seems to me to add data attributes to `link_to_add_association`, then get those attributes when "cocoon:before-insert" is called. Is there currently a way for the link to be referenced from the event function?

Thank you.

**Comment by Mirv** [comment]
> I'm trying to figure out a way to pass parameters to the JS events triggered by Cocoon.

JS or jquery?  I imagine you'd use the jquery either ...

Read the field which was generated by cocoon after rendering by using a dom selector to get the value

OR

 to get the parms out of the url that just execute using ... https://stackoverflow.com/questions/19491336/get-url-parameter-jquery-or-how-to-get-query-string-values-in-js

**Comment by ayaman** [comment]
Apologies if my question wasn't clear, I did mean the jQuery events. There are ways with which this could be achieved but I felt that adding some extra parameters to the event itself would be the cleanest. Added it in PR #466.

**Comment by Mirv** [comment]
If this is solved do you want to go ahead & close them both out?

**Comment by ayaman** [comment]
Certainly, I suppose I wanted to see if there may be a better solution which I missed, but I guess this works well enough.

**Comment by Mirv** [comment]
I would definitely keep it open if you were going to gather ideas to submit a PR for the cocoon gem, as generally this issues list is for bugs or features & stackoverflow has a tag for cocoon gem which is checked by the gem maker almost daily.  ( https://stackoverflow.com/questions/tagged/cocoon-gem )
