### ISSUE TITLE
How to delete nested model in edit action without mark the _destroy check box?

### ISSUE THREAD

**Issue by thaivankhoa** [nathanvda/cocoon#470]
Hi, i have a problem when using cocoon gem.

When i want to edit a form that include many nested forms in this, the nested form will hide after i clicked into `link_to_remove_association`. But if i don't mark the check box for `:_destroy`, the nested model won't be delete after update action.

And i'm finding the way to change the `_destroy` value into `true` whenever users click on `link_to_remove_association`. But i dont know how to pass the params in the 
`<%= link_to_remove_association "remove address", f , class: "delete-duration" %>`

It's a little bit weird if users must mark the _destroy box when they want to delete a nested model in edit action. 

Could you suggest me any solutions?

Thanks a lot.

This is a part my main form **_form.html.erb**
```
<div class="duration-form">
    <div class="request-form-label" id="duration-form-label"><%= f.label "Date time" %><span> *</span></div>
    <div class="request-duration-single-form">
    	<%= f.fields_for :durations, request.durations do |duration| %>
    		<%= render 'duration_fields', f: duration %>
    	<% end %>
    	<div class="request-duration-single-form">
    		<%= link_to_add_association 'Add another date', f, :durations, class: "add" %>
    	</div>
    </div>
</div>
```
And this is nested form _durations_field.html.erbdurations_field.html.erb**

```
<div class="nested-fields">
  <div class="duration-label"><%= f.label :first_date %></div>
  <div class="duration-input"><%= f.text_field :first_date, class: "gui-input request_date_picker" %></div>
  <div class="duration-label"><%= f.label :last_date %></div>
  <div class="duration-input"><%= f.text_field :last_date, class: "gui-input request_date_picker" %></div>
  <div class="duration-label"><%= f.label "Duration" %></div>
  <div class="duration-radio-input">
    <% duration_type = ['Morning','Afternoon','All day'] %>
    <% duration_type.each do |duration| %>
      <%= f.radio_button :duration_type, duration, checked: "checked" %>
      <label style="display: inline-block;" for="<% duration %>"><%= duration %></label>
    <% end %>
  </div>
  <div></div>

  <%= f.check_box :_destroy %>
  
  <%= link_to_remove_association "remove address", f , class: "delete-duration" %>
</div>
```
I passed the `:id` and `:_destroy` in nested params
```
def request_params
      params.require(:request).permit(:id, :reviewer, :ccer, :request_type, :reason, :status, :user_id, durations_attributes: [:id, :first_date, :last_date, :duration_type, :request_id, :_destroy])
end
```

**Comment by thaivankhoa** [comment]
Thanks, i found the solution. This will be done after add an script:

```
JQuery ->                                                                                                                                                                                                   
        $(document).on 'click' , ".delete-duration" , (event) ->                                                                                                                                              
                $(this).prev('input[type=hidden]').val('1')                                                                                                                                                 
                $(this).closest('fieldset').hide()                                                                                                                                                          
                event.preventDefault()  
```

**Comment by nathanvda** [comment]
Just remove the `check_box :_destroy`, it is an hidden field automatically added (by the `fields_for` helper I think).

**Comment by thaivankhoa** [comment]
Thanks man, i solved it. Have a nice day :D

**Comment by nathanvda** [comment]
Look it is very possible you are happy with your solution, you got it working which is and feels awesome. Great work! :+1: 

But the easiest solution is to just remove the `check_box :_destroy` from your form in the first place. I do not know who told you or why you added it in the first place, in all my examples I never add it (there is no need to) and if you needed to add it to get it working, could you please explain which rails version you are using or which form-builder, because then maybe something changed and I need to change the documentation.

**Comment by thaivankhoa** [comment]
But if i dont' mark the check_box for `_destroy` when edit the nested form, that nested form won't be deleted after the update action, even i clicked on `link_to_remove_associasion`. Meanwhile the value of `params[:_destroy]` is `false` by default. That's why i'm finding the way to pass the `true` value to param[:_destroy] when i click on `link_to_remove_association`.

**Comment by thaivankhoa** [comment]
This solution worked for me. But i'm still finding the better way to solve this :D
I change the value of `hidden_field` of (for `_destroy`) to `true` whenever i clicked on `link_to_remove_association`. It's all be done by coffee script.
P/s: i'm using Rails 5.0.6.

```
JQuery ->                                                                                                                                                                                                   
        $(document).on 'click' , ".delete-duration" , (event) ->                                                                                                                                              
                $(this).prev('input[type=hidden]').val('1')                                                                                                                                                 
                $(this).closest('fieldset').hide()                                                                                                                                                          
                event.preventDefault() 
```

**Comment by nathanvda** [comment]
Not sure why you repeat everything you already said before. 

Since it obviously was not clear enough, I will repeat myself as well very simply: did you try _removing_ the check-box from the form? In other words: remove the line `<%= f.check_box :_destroy %>` from  the view `_durations_field.html.erb`

You do not need to add and manage the `_destroy` field yourself. Rails form helpers will add a hidden field for `:_destroy` and the `link_to_remove_association` will set it correctly. 

If you insist in placing a `check_box` yourself, of course it overrules the hidden field which is placed by rails.

**Comment by thaivankhoa** [comment]
Sorry, i just want to focus the problem.

Following your advise, I tried to remove the hidden_field for `_destroy` in the form. And it work perfectly, even after i deleted the coffeescript code.

Actually, i do not add a filed for `_destroy` (both hidden_field or check_box) in the form for the first time.  And I have no idea why it didn't work correctly it at that time. Maybe it's because i did something that overrules the cocoon form and It made things even more complicated.

Thanks for your quick reply and clearly explain, nathanvda :+1:  I will carefully consider the problem before asking in the next time.
