### ISSUE TITLE
Using HTML Select returns empty edit fields

### ISSUE THREAD

**Issue by fkugland** [nathanvda/cocoon#472]
I am using cocoon in my Rails app for assigning employees (users) to projects (many to many connection). The creation of associations is working correctly, but each time I add another employee cocoon adds an empty form field in the edit view. None of the other cocoon form fields in the edit view are populated either. Could this be due to the usage of dropdowns (select)?

![bildschirmfoto 2017-11-28 um 18 01 37](https://user-images.githubusercontent.com/29799414/33476021-b5ea3238-d680-11e7-90af-608e2ca34716.png)

When I inspect the form in my browser I can see that each field seems to be assigned to one of the associations, but the selection is still empty.

What I would like to achieve is, that every association is displayed in a cocoon form field, so that they can be edited. Thanks for any help in advance and sorry if this turns out to be a stupid mistake!

**Project Edit View**
``` 
<%= form_for(@project, :url => project_path, method: :patch) do |f| %>

    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :customer %>
        <%= f.text_field :customer, class: "form-control" %>
    </div>

    <%= f.fields_for :user_projects do |collab| %>
        <% collab.hidden_field :project_id, value: @project.id %>
        <%= render 'user_project_fields', f: collab %>
    <% end %>
    <div class="add-collaborator">
        <%= link_to_add_association "add", f, :user_projects, class: "btn btn-mmc" %>
    </div>

    <div class="actions">
        <%= f.submit "Save Changes", class: "btn btn-mmc btn-mmc-medium" %>
    </div>
<% end %>
```

**cocoon field partial**
```
<div class="nested-fields">
    <%= f.label "Select User" %>
    <div class="form-group custom-form-group">
        <%= f.select(:user_id, options_for_select(User.all.map { |u| [u.email, u.id] }), {include_blank: true}, {class: 'form-control'})%>
        <div class="btn-user-project">
            <%= link_to_remove_association "x", f, class: "btn btn-mmc-attention btn-mmc" %>
        </div>
    </div>
</div>
```

**Project Controller**
```
 def edit
    @project = Project.find(params[:id])
    @project.user_projects.build
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to projects_path
    else
      render :edit
    end
  end

private
  def project_params
    params.require(:project).permit(:title, :customer, :delted, user_projects_attributes: [:user_id, :project_id]).reject { |_, v| v.blank? }
  end
```

**Comment by nathanvda** [comment]
This seems to be the same question as https://stackoverflow.com/questions/47533576/cocoon-gem-edit-view-is-only-showing-empty-form-fields/47592660#47592660

**Comment by fkugland** [comment]
Yes, I have also posted it on Stackoverflow, but so far I have not received an answer that solved the problem. Therefore, I was hoping to get help here. Sorry, if that caused any inconvenience!

**Comment by nathanvda** [comment]
Sorry if that was unclear, but I had just answered that question and it seemed eerily similar :) (I get automatic notifications for cocoon questions but a day later). I think my answer solves your question, but let me know :+1: 😉

**Comment by fkugland** [comment]
Thank you very much! Your answer was exactly what I needed. Unfortunately, I didn't see it before posting here. Very sorry about that!

**Comment by nathanvda** [comment]
Not a problem at all, no need to apologise, just wanted to make sure it was the same question, and I prefer to answer the stackoverflow questions because it is easier to search/find stuff there so it more easily reached by other people having the same problems (and I literally just posted my answer when I got the notification for this question, so you could not have known beforehand).

And glad it helped you :+1: :+1 :+1: :clap: :clap: :clap: :smile:
