### ISSUE TITLE
form error messages not returning with `remote: true` when creating pictures?

### ISSUE THREAD

**Issue by Lee1984** [nathanvda/cocoon#473]
Hi Nathan. I am getting similar to this issue [https://github.com/nathanvda/cocoon/issues/150](url) where I use remotipart gem to get past the authenticity token issue when using `remote: true` in a form. When I use `remote: true` everything renders out correctly from server to the page except error messages are not being sent. The only reason I believe its a cocoon issue is the problem only occurs when I add pictures. If I do not add any pictures and submit a invalid form the error messages display.My server reads these two results

POST req without pics

Started POST "/users/2/galleries" for ::1 at 2017-12-11 16:52:42 +1100
Processing by GalleriesController#create as JS
  Parameters: {"utf8"=>"✓", "gallery"=>{"name"=>"Hello", "cover"=>""}, "commit"=>"Create Gallery", "user_id"=>"2"}
  User Load (0.0ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
   (0.0ms)  begin transaction
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
   (0.0ms)  rollback transaction
  Rendering galleries/new.js.erb
  Rendering galleries/new.html.erb
  Rendered shared/_error_messages.html.erb (0.5ms)
  Rendered galleries/_picture_fields.html.erb (1.0ms)
  Rendered galleries/_form.html.erb (303.9ms)
  Rendered galleries/new.html.erb (455.6ms)
  Rendered galleries/new.js.erb (605.8ms)
Completed 200 OK in 796ms (Views: 791.3ms | ActiveRecord: 0.5ms)

POST req with pics

Started POST "/users/2/galleries" for ::1 at 2017-12-11 16:52:11 +1100
Processing by GalleriesController#create as JS
  Parameters: {"utf8"=>"✓", "gallery"=>{"name"=>"Hello", "cover"=>"", "pictures_attributes"=>{"1512971529011"=>{"picture_cache"=>"", "_destroy"=>"false", "picture"=>#<ActionDispatch::Http::UploadedFile:0xd1409f0 @tempfile=#<Tempfile:C:/Users/Lee/AppData/Local/Temp/RackMultipart20171211-11944-1ox30j6.jpg>, @original_filename="All-Out-EDM-mix-picture-3.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"gallery[pictures_attributes][1512971529011][picture]\"; filename=\"All-Out-EDM-mix-picture-3.jpg\"\r\nContent-Type: image/jpeg\r\n">}}}, "commit"=>"Create Gallery", "remotipart_submitted"=>"true", "authenticity_token"=>"6H0jpCI/uTwUTeKMdWK3ttYL2loFFjSZh8DXoDdxhPrPUL8YNVLQL05/V9iMVidAmoeN+An+8D1+39q77IQQIQ==", "X-Requested-With"=>"IFrame", "X-Http-Accept"=>"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01", "user_id"=>"2"}
  User Load (0.0ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
   (0.0ms)  begin transaction
  User Load (0.0ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
   (0.5ms)  rollback transaction
  Rendering galleries/new.js.erb
  Rendering galleries/new.html.erb
  Rendered shared/_error_messages.html.erb (0.5ms)
  Rendered galleries/_picture_fields.html.erb (2.0ms)
  Rendered galleries/_picture_fields.html.erb (1.0ms)
  Rendered galleries/_form.html.erb (490.6ms)
  Rendered galleries/new.html.erb (663.8ms)
  Rendered galleries/new.js.erb (828.0ms)
Completed 200 OK in 1521ms (Views: 1026.6ms | ActiveRecord: 0.5ms)

The form looks like this

    <%= form_for([@user, @gallery], remote: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :cover %>
        <%= f.text_field :cover %>
      </div>
      <table class="user-picture-form">
        <tbody>
          <%= f.fields_for :pictures do |pic| %>
          <%= render 'picture_fields', f: pic %>
          <% end %>
       </tbody>
     </table>
     <div class="links">
       <%= link_to_add_association 'add picture', f, :pictures %>
       <%= f.submit %>
     </div>
    <% end %>

and

    <tr class="nested-fields">
      <td>
        <%= f.file_field :picture, accept: 'image/jpg,image/jpeg,image/gif,image/png' %>
        <%= f.hidden_field :picture_cache, :value => f.object.picture_cache %>
      </td>
      <td class="thumb">
        <% if f.object.picture.url.present? %>
        <%= image_tag f.object.picture.url %>
        <% end %>
        </td>
        <td> 
          <%= link_to_remove_association "remove", f %>
        </td>
    </tr>

Also I am confused because removing `remote: true` from the form and submitting as html and also adding pictures the form returns the errors correctly so things work when the response is HTML. I even removed remotipart gem and changed `ActionView::Helpers::FormTagHelper.embed_authenticity_token_in_remote_forms = true` to true but then rails would not recognise js format.
Wondering if you can shed some light on this.

**Comment by nathanvda** [comment]
Please show your controller code.

**Comment by Lee1984** [comment]
galleriescontroller

      def new
        @user = User.find(params[:user_id])
        @gallery = @user.galleries.build
     end
    
    def create
       @user = User.find(params[:user_id])
       @gallery = @user.galleries.build(gallery_params)
       if @gallery.save  
         @user = User.find(params[:user_id])
         @galleries = @user.galleries
         render 'index' and return  
      else	
        render 'new'	  
      end
    end
    ....

**Comment by Mirv** [comment]
From a trouble shooting perspective it feels like you might have missed a step in there or simply forgot to tell us ... getting an invalid form submission isn't the same as saying your form works for everything except pictures.

If you use git to branch & remove the picture code feature / validation check etc, then submit valid information for the rest - does it work?  (this is different than the 2 tests  you mentioned already)

Also, I've never seen ` @gallery = @user.galleries.build(gallery_params)` used before in the `create` action.  Here's a demo of what it normally looks like ... [Cocoon: Formtastic Demon](https://github.com/nathanvda/cocoon_formtastic_demo/blob/master/app/controllers/projects_controller.rb#L42)

**Comment by Mirv** [comment]
I'm guessing if you're like me, you're 100+ edits in on it...when I do that I tend to introduce new difficulties.  If you run the other test without the picture code & everything works ignore this next bit .... otherwise here's your adjusted code to try ...

```
   @gallery = @galleries.new(gallery_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @gallery , notice: 'Gallery was successfully created.' }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
```

I've changed my controller code to reflect your variable names, this isn't tested against your stuff.  I noted you `render & return`, used `@user.galleries.build`, both of which are unnecessary, but the main difference is I've got a `respond_to` call in there with `format.`.

This isn't tested of course, but it normalizes the code to a place where I know it should work & gets us back to a normal trouble shooting flow.

**Comment by Lee1984** [comment]
Oh yes I wasn't saying it doesn't submit, I added a validation in for :cover attr to check how my failure would render and if error messages would display, sorry if I wasn't clear. I did not mean there is something wrong with cocoon I was just lost as to why it did this, plus I need to use `remotipart` gem to get rid of the authenticity token problem which adds more questions.

I tried the code above eg,

    def create
      @user = User.find(params[:user_id])
      @gallery = @user.galleries.new(gallery_params)
      respond_to do |format|
        if @gallery.save
          format.html { redirect_to @gallery , notice: 'Gallery was successfully created.' }
          format.js { render :show, status: :created, location: @gallery }
        else
          format.html { render :new }
	  format.js { render json: @gallery.errors, status: :unprocessable_entity }
        end
      end
    end

The server gives out a `completed 422 Unprocessable entity...` and doesn't render anything. 

I checked the response to the POST req though and it gave this `<script type="text/javascript">try{window.parent.document;}catch(err){document.domain=document.domain;}</script> <textarea data-type="text/javascript" data-status="422" data-statusText="Unprocessable Entity">{"cover":["can't be blank"]}</textarea>` 

so my information is there but not in the div. 

Also going back to my old code the response is this 

`<script type="text/javascript">try{window.parent.document;}catch(err){document.domain=document.domain;}</script> <textarea data-type="text/javascript" data-status="200" data-statusText="OK">console.log("hello");
$("div#id5").html("<form class=\"new_gallery\" id=\"new_gallery\" enctype=\"multipart/form-data\" action=\"/users/2/galleries\" accept-charset=\"UTF-8\" data-remote=\"true\" method=\"post\"><input name=\"utf8\" type=\"hidden\" value=\"&#x2713;\" />\n  <div id=\"error_explanation\">\n    <div class=\"alert alert-danger\">\n      The form contains 1 error.\n    <\/div>\n    <ul>\n      <li>Cover can&#39;t be blank<\/li>\n    <\/ul>\n  <\/div>\n\n  <div class=\"field\">\n    <label for=\"gallery_name\">Name<\/label>\n    <input type=\"text\" value=\"Hello\" name=\"gallery[name]\" id=\"gallery_name\" />\n  <\/div>\n  <div class=\"field\">\n    <div class=\"field_with_errors\"><label for=\"gallery_cover\">Cover<\/label><\/div>\n    <div class=\"field_with_errors\"><input type=\"text\" value=\"\" name=\"gallery[cover]\" id=\"gallery_cover\" /><\/div>\n  <\/div>\n  <table class=\"user-picture-form\">\n    <thead>\n      <tr>\n        <td>input<\/td> \n        <td>preview<\/td>\n        <td>remove<\/td>\n	  <\/tr>\n	<\/thead> \n    <tbody>\n      \n      <tr class=\"nested-fields\">\n  <td>\n   <input accept=\"image/jpg,image/jpeg,image/gif,image/png\" type=\"file\" name=\"gallery[pictures_attributes][0][picture]\" id=\"gallery_pictures_attributes_0_picture\" />\n   <input value=\"1513058157-15884-0017-3254/All-Out-EDM-mix-picture-3.jpg\" type=\"hidden\" name=\"gallery[pictures_attributes][0][picture_cache]\" id=\"gallery_pictures_attributes_0_picture_cache\" />\n  <\/td>\n  <td class=\"thumb\">\n    <img src=\"/uploads/tmp/1513058157-15884-0017-3254/All-Out-EDM-mix-picture-3.jpg\" alt=\"All out edm mix picture 3\" />\n  <\/td>\n  <td> \n    <input type=\"hidden\" name=\"gallery[pictures_attributes][0][_destroy]\" id=\"gallery_pictures_attributes_0__destroy\" value=\"false\" /><a class=\"remove_fields dynamic\" href=\"#\">remove<\/a>\n  <\/td>\n<\/tr>\n\n\n	<\/tbody>\n    <\/table>\n    <div class=\"links\">\n       <a class=\"add_fields\" data-association=\"picture\" data-associations=\"pictures\" data-association-insertion-template=\"&lt;tr class=&quot;nested-fields&quot;&gt;\n  &lt;td&gt;\n   &lt;input accept=&quot;image/jpg,image/jpeg,image/gif,image/png&quot; type=&quot;file&quot; name=&quot;gallery[pictures_attributes][new_pictures][picture]&quot; id=&quot;gallery_pictures_attributes_new_pictures_picture&quot; /&gt;\n   &lt;input type=&quot;hidden&quot; name=&quot;gallery[pictures_attributes][new_pictures][picture_cache]&quot; id=&quot;gallery_pictures_attributes_new_pictures_picture_cache&quot; /&gt;\n  &lt;/td&gt;\n  &lt;td class=&quot;thumb&quot;&gt;\n  &lt;/td&gt;\n  &lt;td&gt; \n    &lt;input type=&quot;hidden&quot; name=&quot;gallery[pictures_attributes][new_pictures][_destroy]&quot; id=&quot;gallery_pictures_attributes_new_pictures__destroy&quot; value=&quot;false&quot; /&gt;&lt;a class=&quot;remove_fields dynamic&quot; href=&quot;#&quot;&gt;remove&lt;/a&gt;\n  &lt;/td&gt;\n&lt;/tr&gt;\n\n\" href=\"#\">add picture<\/a>\n       <input type=\"submit\" name=\"commit\" value=\"Create Gallery\" data-disable-with=\"Create Gallery\" />\n	<\/div>\n<\/form>");</textarea>`

Which is the exact code I needed returned. Just wondering why it isn't on the page?

I threw a alert into the `new.js.erb` as well but that didn't pop up either upon the response.

My `new.js.erb`  code is,

    alert("hello");
    $("div#id5").html("<%= j render template: "galleries/new.html.erb" %>");

And I check the markup to be sure it wasnt being put in as hidden but not there..

**Comment by nathanvda** [comment]
Your first version of the controller is ok. It will render `new.html.erb` when doing html call and `new.js.erb` when doing a `remote: true` call. I prefer to be a little more explicit (e.g. do not allow html calls if you only expect js calls and vice versa). But it should work as is. 

So the `new.js.erb` you showed should also work, with the alert. Does it (with the first version of the controller)?  I am not familiar with `remotipart` so not sure how it interferes. Normally, when you inspect the network calls and your console in the browser you would see the remote call being made, the response sent and possible an error in the javascript.

**Comment by Mirv** [comment]
Apologies, I misread part of that original!

Is this with carrierwave for the picture handling?

**Comment by Lee1984** [comment]
Yes it is like that, I linked to that in my first post incorrectly so the link didn't work but yes I am uploading pictures with carrierwave and using remotipart gem to handle this via ajax except I already have `// require remotipart` in correct spot. 

The alert shows on rendering a new gallery through ajax, but upon invalid form submission and rendering the new action from create the alert doesn't show, although does show in the POST request response..

I may take this to stackoverflow. I can set `authenticity_token: true` instead of using remotipart but the response is always html sent back even if `remote: true` is set in the form.

**Comment by nathanvda** [comment]
Could you verify that what is in the POST request response is valid, e.g. copy the contents of the response and run it in the browser console, then you will most likely get an error (that would explain the behaviour)(or for instance replacing a selector that is no longer on the page, also a classic).

I have no experience with this because I tend to use dropzone.js for uploading images (which only works after the "owner" element is created --so I never create the owner and attachments in one nested form).

**Comment by Lee1984** [comment]
I can confirm the code is legittament and the response code when pasted in is displaying exactly as it should/does when its html submitted. But there is a but

I think the problem may lay in this part here in the response body

Exact response when no pictures is sent and just a :name and :cover field

    $("div#id5").html("<form class=\"new_gallery\" id=\"new_gallery\"............ Lots of code.......<\/form>");

Exactly like my new.js.erb file shows

When I add pictures and remotipart-submitted="true" is registered in server output

    <script type="text/javascript">try{window.parent.document;}catch(err){document.domain=document.domain;}</script> 
    <textarea data-type="text/javascript" data-status="200" data-statusText="OK">
    $("div#id5").html("<form class=\"new_gallery\" id=\"new_gallery\"...... Lots of code.....</form>");</textarea>

So it is wrapped in this textarea for some reason.

**Comment by nathanvda** [comment]
Yep, upon further investigation: that textarea is added by remotipart. They overwrite the normal `render`, check the source: https://github.com/JangoSteve/remotipart/blob/master/lib/remotipart/render_overrides.rb
 
So I am a bit confused how to proceed here. Open a ticket/issue there? Or on stackoverflow?

**Comment by Lee1984** [comment]
I see. So I wonder why it would work with single file upload or multipart but not with multiple file fields? Is there some connection there between cocoon and remotipart.

I will open a ticket on remotipart issues and let them know that the textarea code is interfering with my form and see if I can get a answer.

**Comment by Mirv** [comment]
Not sure if this is copy paste error when putting it on github, but you're missing a '<' on the html tag .... at the end of the line here ...

```
("div#id5").html("<form class=\"new_gallery\" id=\"new_gallery\
```

**Comment by nathanvda** [comment]
@Mirv: imho a copy error but I don't see that, did you scroll the code-blocks or else @Lee1984 already fixed it :) 

@Lee1984 link the remotipart issue here so we can follow along. I am trying to understand how the remotipart code should work and it does extract the code from the textarea so actually it should be working. But they will be much better placed to understand and explain what might be going wrong.

**Comment by Mirv** [comment]
Nathanvda - I updated the spot where I found it in the previous message.

To me, when I search with control+f on this page - I see 3 places in his posts where that code is used & in the latest two of them, there is that missing part.   I only mention it incase something was changed & the original (correct) dump at the top is out of date.

**Comment by Lee1984** [comment]
I posted on SO [here](https://stackoverflow.com/questions/47828455/response-not-being-inserted-into-html-document-rails-remotipart-cocoon) and remotipart ticket [here](https://github.com/JangoSteve/remotipart/issues/188) but as a work around I just put `return` in the custom renderer and everything works fine.

Eg [link]( https://github.com/JangoSteve/remotipart/blob/master/lib/remotipart/render_overrides.rb) nathan linked to and code

    ....
    def render_with_remotipart *args
      render_without_remotipart *args
      if remotipart_submitted?
	    return # added by lee as this (remotipart) renderer wasnt inserting code into div with cocoon enabled.
        textarea_body = response.content_type == 'text/html' ? html_escape(response.body) : response.body
        response.body = %{<script type=\"text/javascript\">try{window.parent.document;}catch(err){document.domain=document.domain;}</script> <textarea data-type=\"#{response.content_type}\" data-status=\"#{response.response_code}\" data-statusText=\"#{response.message}\">#{textarea_body}</textarea>}
        response.content_type = ::Rails.version >= '5' ? Mime[:html] : Mime::HTML
      end
      response_body
    end
    ...

The issue is weird but I am not that smart when it comes to javascript and the browser, only good at troubleshooting events on nodes and thats about it. Thanks guys. There is another gem to which may be good as a fallback to remotipart here [ufujs-rails](https://github.com/activebridge/ufujs-rails) but not sure on how well maintained..

**Comment by nathanvda** [comment]
Ow that is a ugly hack, that could not be the intention at all (that textarea is used later in js-code). I checked open issues and pull-requests on remotipart, and I believe [this pull request](https://github.com/JangoSteve/remotipart/pull/179) would work for you. 

Not sure how actively remotipart is maintained, but using that fork could already help you.

**Comment by Lee1984** [comment]
Yes I just tested and the response doesn't go back, I am just taking a look now at those links.. sorry was hitting a dead end so was just trying something. Thanks for the link. Will get back to you.

**Comment by Lee1984** [comment]
Yes so, viola. Things are working now. Had to use this in gemfile

    gem 'remotipart', :git => 'https://github.com/westonganger/remotipart', :branch => 'fix_escape_javascript'

as this branch was not merged with jangosteve/remotipart master.

**Comment by nathanvda** [comment]
Awesome., great you found a solution :smile: :+1: Maybe you should give some feedback on the remotipart issue/PR that it helped you, which might be relevant/help to get things merged there.

**Comment by Lee1984** [comment]
Ok thanks mate, will do
