### ISSUE TITLE
getting couldn't find file 'cocoon' with type 'application/javascript'

### ISSUE THREAD

**Issue by thirumal1** [nathanvda/cocoon#474]
I am using cocoon within a gem I am developing.I get this error when I am using the gem in a host application.

Thanks in advance.

**Comment by nathanvda** [comment]
So for the record: you are developing a gem, using cocoon, and _in the host application_ using your gem the cocoon gem cannot be found? And somehow you think this is a bug inside cocoon? 

My guesses: 

* Did you correctly declare the dependencies of your gem you are developing? 
* did you do bundle install? 
* is cocoon installed? 

You will have to investigate your Gemfile (Gemfile.lock) to see if cocoon is installed, add it manually in the host-application or fix your gem dependencies.

**Comment by thirumal1** [comment]
My apologies for miscommunication,Thanks for pointing me in the right direction.I have include cocoon gem in the host application and it works, but I need to figure out how to include it in the my Gem.


-R

**Comment by Mirv** [comment]
Unless I misunderstood, it looks like you are hitting an issue with authoring your own gem.

If it's not something in cocoon that is broke, that is a question you need to research in a tutorial or on stackoverflow.

Some helpful hints:

 ... are you following the ruby tutorial for it?  [Link](http://guides.rubygems.org/make-your-own-gem/#requiring-more-files)

If you are correctly following the tutorial, then this answer (will only work if you gem is setup right) might provide specific directions ... [Link](https://stackoverflow.com/questions/5159607/rails-engine-gems-dependencies-how-to-load-them-into-the-application)

**Comment by thirumal1** [comment]
Thank you very much, I got the solution from the links below, and cocoon works like a charm in my gem.I missed putting the require 'cocoon' in the engine.rb file.

-R
