### ISSUE TITLE
building resources after form is rendered

### ISSUE THREAD

**Issue by qaswm** [nathanvda/cocoon#476]
I have asked the same question on SO. [Link here](https://stackoverflow.com/questions/47917761/cocoon-building-resources-after-form-is-rendered)

 I have a form for bills. Once open I choose a vendor to show the list of open purchase orders for the vendor. Selecting the purchase order should take all the items that were ordered in the purchase order and show them as line items in the bill.How can this be achieved when the form is already rendered and I already see nested attributes and the link to add more or remove etc on the form?My current implementation is the simple nested resource using cocoon.

    <%= simple_form_for(@bill) do |f| %>
      <%= f.error_notification %>
      <div class="form-inputs">
        <%= f.input :vendor_id, as: :select do %>
          <%= f.grouped_collection_select :vendor_id, Warehouse.ordered, :vendors, :name, :id, :name, include_blank: true %>
        <% end %>
      </div>
      <div id="items">
        <div id="ingredient_purchase" class="row">
          <div class="row">
            <%= f.simple_fields_for :warehouse_ingredient_purchase_logs do |warehouse_ingredient_purchase_log| %>
            <%= render 'warehouse_ingredient_purchase_log_fields', :f => warehouse_ingredient_purchase_log %>
            <% end #f.simple_fields_for %>
            <div class="links">
              <%= link_to_add_association 'Add More', f, :warehouse_ingredient_purchase_logs %>
            </div>
          </div>
        </div>
      </div>
      <div class="form-actions">
        <%= f.button :submit %>
      </div>
    <% end #simple_form_for(@bill) do |f| %>
    
    <div id="modal1" class="modal bottom-sheet">
      <div class="modal-content">
        <h4>Purchase Orders</h4>
        <div class="purchase_orders_data"></div>
      </div>
    </div>

**Comment by Mirv** [comment]
The owner of the gem is already working with you in SO.

This forum is supposed to be for improving the gem or submitting bugs which would affect anyone.

Best practice would be for you to close this ticket unless you can demonstrate this issue stems from a bug & from your stackoverflow question it's too early to tell.
