### ISSUE TITLE
New fields being wrapped with <div class="fields">

### ISSUE THREAD

**Issue by kingp0dd** [nathanvda/cocoon#477]
Are new fields really wrapped with `<div class="fields">`?
I noticed this when I'm trying to insert new fields into a `<table>`.

My fields partial starts with `<tr>`, but it still seems to wrap it with `<div class="fields">` automatically. 

This only happens when there's already an existing nested field on the **edit** form. It doesn't do that on the **new** form.

**Comment by nathanvda** [comment]
No. Cocoon does not do any "wrapping". Cocoon needs to know the wrapper-class, if it is not the default (`.nested-fields`) to be able to correctly delete/hide upon removal. 

Show a little more of your code if you need a hand. Are you rendering your new and edit form differently?

**Comment by kingp0dd** [comment]
Thanks for taking the time to reply, Nathan.
I'm on mobile right now, I'll post the complete code snippets when i get
back.

The fields partial looks like this:
.nested-fields
  %tr
    ...
  %tr
    ...

I use the same _form.html.haml partial in my edit and new pages.

Here's the behavior I'm getting:
1. New.html.haml (*no nested field yet)
Template is correct:
%tr
  ...
%tr
  ...

2. Edit.html.haml (*with existing 1 or more nested field already)
I get an additional div on top:
%div.fields
  %tr
    ...
  %tr
    ...

Which breaks the table after insertion.

**Comment by nathanvda** [comment]
I will await the complete code-snippets, this does not clarify anything.

**Comment by kingp0dd** [comment]
Here are the snippets:

_form.html.haml

```
= form_for(@voucher) do |f|
  ...
  %div{ id: 'sd_deductions' }
    = f.fields_for :sd_deductions do |builder|
      = render 'sd_deductions/sd_deductions_fields', f: builder

  %div
    = link_to_add_association "Add SD", f,         |
      :sd_deductions,                                                      |
      partial: 'sd_deductions/sd_deductions_fields',                    |
      data: { 'association-insertion-node' => '#sd_deductions', |
      'association-insertion-method' => 'append' }                             |

```

_sd_fields.html.haml

```
%div .nested-fields
  %table.table
    %thead
      ...
    %tbody
      ...
```


new.html
* no child is rendered in view yet
```
<div id="sd_deductions">
  
</div>
<div>
  <a class="add_fields" data-association-insertion-method="append" data-association-insertion-node="#sd_deductions" data-association-insertion-template=" 
    <div class=&quot;nested-fields&quot;>
      <table class='table'>
```



edit.html
* already with one child. Being rendered inside `<div class="fields">`
```
<div id="sd_deductions">
  <div class="fields">
    <div class="nested-fields">
      <table class="table">
        ...
</div>

<div>
  <a class="add_fields" data-association-insertion-method="append" data-association-insertion-node="#sd_deductions" data-association-insertion-template="
    <div class=&quot;fields&quot;>
      <div class=&quot;nested-fields&quot;>
        <table class='table'>
```

**Comment by Mirv** [comment]
Are you sure your _form / layout / edit doesn't have a "fields" div in there somewhere?   I'd search all your template files just incase?  Its not in cocoon to just randomly throw that down that I'm seeing.

Have you looked at the demo's on here already?  SLIM - [Link](https://github.com/nathanvda/cocoon_simple_form_demo/tree/master/app/views/projects)

Here's a quick drop of my views from an old project....I have to get up in under 6 hours for the first of my 12 hour days :(

Ignore the "|" at the start it's a chrome thing to put them there...
```

<h2>
--
  | Campaign List
  | </h2>
  | <div class='list-group'>
  | <!-- / .list-group-item.my-well.nested-player -->
  | <div class='list-group-item my-well nested-player'>
  | <p><li>Id:  27</li><li>Name:  Test002</li><li>Description:  </li></p>
  | <div class='button-interact btn-group btn-group-xs'>
  | <a class="btn btn-xs btn-default" href="/campaigns/27">Show</a>
  | <a class="btn btn-xs btn-default" href="/campaigns/27/edit">Edit</a>
  | <a data-confirm="Are you sure?" class="btn btn-xs btn-default" rel="nofollow" data-method="delete" href="/campaigns/27">Destroy</a>
  | </div>
  |  
  | </div>
  | <!-- / .list-group-item.my-well.nested-player -->
  | <div class='list-group-item my-well nested-player'>
  | <p><li>Id:  26</li><li>Name:  Test001</li><li>Description:  New partial test</li></p>
  | <div class='button-interact btn-group btn-group-xs'>
  | <a class="btn btn-xs btn-default" href="/campaigns/26">Show</a>
  | <a class="btn btn-xs btn-default" href="/campaigns/26/edit">Edit</a>
  | <a data-confirm="Are you sure?" class="btn btn-xs btn-default" rel="nofollow" data-method="delete" href="/campaigns/26">Destroy</a>
  | </div>
  |  
  | </div>
  | <!-- / .list-group-item.my-well.nested-player -->
  | <div class='list-group-item my-well nested-player'>
  | <p><li>Id:  5</li><li>Name:  test</li><li>Description:  test</li></p>
  | <div class='button-interact btn-group btn-group-xs'>
  | <a class="btn btn-xs btn-default" href="/campaigns/5">Show</a>
  | <a class="btn btn-xs btn-default" href="/campaigns/5/edit">Edit</a>
  | <a data-confirm="Are you sure?" class="btn btn-xs btn-default" rel="nofollow" data-method="delete" href="/campaigns/5">Destroy</a>
  | </div>
```

**Comment by kingp0dd** [comment]
I found the problem. I was using nested_form before, i checked
edit.html.haml again and it's still using nested_form_for form helper.

**Comment by nathanvda** [comment]
So you assumed your edit and new view were the same. You know the popular sayings about assumptions? 😛 😛 

But awesome you found your bug :+1:
