### ISSUE TITLE
Cocoon should not modify the options hash 

### ISSUE THREAD

**Issue by jeffblake** [nathanvda/cocoon#478]
Here, cocoon deletes the locals from the options passed in. In my app, I setup my options first, and then render many `link_to_add_association` links, one for each type of STI class. Thus, the locals were only being added to the first link in the iteration.

Perhaps `dup` the options instead?

https://github.com/nathanvda/cocoon/blob/868a732ae53238b17a8126fbc49083b457e26a34/lib/cocoon/view_helpers.rb#L47

**Comment by nathanvda** [comment]
Ow good catch! I am guessing nobody ever used it that way before. 

Would you be willing to create a PR for it?
