### ISSUE TITLE
has_many :through relationships?

### ISSUE THREAD

**Issue by kirkbushell** [nathanvda/cocoon#48]
We're trying to use cocoon to support the following relationship:

``` ruby
Product has_many :product_people
Product has_many :people, :through => :product_people
ProductPerson belongs_to :product
ProductPerson belongs_to :person
Person has_many :products, :through => :product_people
```

Now, the idea is that when creating a new product, we're trying to manage people, by adding more people and managing their titles.etc.

However, something appears to be not working her with cocoon. I can see that it's meant to look for something like _new_person or whatever, but instead of that we're seeing _0_person and I'm sure this is because of the partials and the arguments we're sending to cocoon helpers. However, I don't see a way around this. In the view we have:

``` haml
= f.semantic_fields_for :product_people do |pp|
    = render 'person_fields', :f => pp
        %li
            Bio and details can be added after the film is accepted.
            .links
                = link_to_add_association 'Add person', pp, :person, :id => 'addRole'
```

I have tried changing the link_to_add_association by passing in "f" instead of "pp", but that just gives me ruby errors. How I see it - we appear to have done everything correctly, but this level of depth isn't supported?

**Comment by allenwlee** [comment]
just a note that the local variable representing `form` MUST be named `:f`.  Took me a long time to figure this out.

**Comment by nathanvda** [comment]
Uhm, there is no such dependency afaik. All my examples are created with `f` but you give the form name to the `link_to_add_association` or `link_to_remove_association`. 

Would you mind creating a separate issue for this?

**Comment by allenwlee** [comment]
thanks, i did so here https://github.com/nathanvda/cocoon/issues/286
