### ISSUE TITLE
Is there a way to know if cocoon is loaded?

### ISSUE THREAD

**Issue by manuelsm** [nathanvda/cocoon#480]
I'm in a edit view and I want to get the inputs' values of the items generated by cocoon... 

Something like this:

html:
```
<div id="items">
  <div class="nested-fields">
    <p>City: <input type="text" value="city name" name="place[addresses_attributes][0][city]" id="place_addresses_attributes_1_quantity"></p>
    <p>Street: <input type="text" value="street name" name="place[addresses_attributes][0][street]" id="place_addresses_attributes_0_quantity"></p>
  </div>
</div>
```

jQuery:
```
$(document).on('turbolinks:load', function(){
   $(function() {
      var $items = $("#items").find('.nested-fields');
      var array = [];
      for (var i = 0; i < $items.length; i++) {
         array.push($items.find("#place_addresses_attributes_" + i + "_city").text());
         array.push($items.find("#place_addresses_attributes_" + i + "_street").text());
      }
     console.log(array)
   });
});
```

but I'm only getting empty strings in my array...

And I notice that this is because cocoon is loaded after `document.ready`, or am I wrong?...

So, is there a way to know if cocoon is loaded in order to get that values? o is there another way?

PD. I'm sorry for my bad english, I still learning it

**Comment by nathanvda** [comment]
Just to make sure: this code works when the page is loaded, right? And now you want to make sure, when a user has added a new item, you want to do something as well? 

Check out the [callbacks](https://github.com/nathanvda/cocoon#callbacks-upon-insert-and-remove-of-items)

**Comment by manuelsm** [comment]
Thanks for the answer!

Yes, the code that I mentioned works when the page is loaded, filling the array with empty strings...
But I just fixed it when I put a setTimeout, getting my array filled in the way that I want

```
$(document).on('turbolinks:load', function(){
   $(function() {
    setTimeout(function() {
      var $items = $("#items").find('.nested-fields');
      var array = [];
      for (var i = 0; i < $items.length; i++) {
         array.push($items.find("#place_addresses_attributes_" + i + "_city").text());
         array.push($items.find("#place_addresses_attributes_" + i + "_street").text());
      }
     console.log(array)
    }, 0);
   });
});
```

**Comment by nathanvda** [comment]
Ok, so if I understand correctly this code did _not_ work when the page is loaded (only after the timeout), so then I do not see the relationship with cocoon (cocoon does not interfere in any of the form rendering, only when dynamically adding and removing items). The `turbolinks:load` event is triggered when the page is loaded and ready, so the inputs should be filled so not sure why they were not on your page (did you have any other js code blocking the processing? Is the form loaded via ajax?).

Glad you got it solved :+1:, in the future please ask such questions on stackoverflow.com.

**Comment by manuelsm** [comment]
Yes, you're right, at the end I noticed that the problem it had no relationship with cocoon but with the way I got loaded my inputs. The code I posted was an example and not the one that I used (I thought the example it would serve better to understand the problem I had).

Sorry for not noticed that and posting this here 😓 

Thanks for your time!
