### ISSUE TITLE
Does cocoon work with a form with no model associated to it ?

### ISSUE THREAD

**Issue by sandipsubedi** [nathanvda/cocoon#482]
I have a rails app. And the partial that has to be repeated on button click looks like this.
```
%div.added-row
  .form-group.row
    .col-md-2.col-form-label= label_tag('name', 'First label')
    %div.col-md-3
      = number_field_tag :size, nil, placeholder: '512', min: 1, required: true, class: 'form-control'
    %div.col-md-1
      = select_tag :unit, options_for_select([ 'A', 'B', 'C' ], 'B'), class: 'form-control'
    .col-md-2.col-form-label= label_tag('name', 'Second Label')
    %div.col-md-4
      = number_field_tag :count, nil, placeholder: '1', min: 1, required: true, class: 'form-control'
```

There is no Model associated with this view. When user clicks submit, all the input fields become a JSON object and is stored as a single attribute.

Can I use `cocoon` in this case? Looks like `cocoon` is tied to the model and I don't have any model for all the input fields.

And `f` is being used everywhere on the documentation. And I don't have `f` because input fields are hardcoded. 

This is what my code looks like, after adding `cocoon`:
```
%div.added-row
  .form-group.row
    .col-md-2.col-form-label= label_tag('name', 'First label')
    %div.col-md-3
      = number_field_tag :size, nil, placeholder: '512', min: 1, required: true, class: 'form-control'
    %div.col-md-1
      = select_tag :unit, options_for_select([ 'A', 'B', 'C' ], 'B'), class: 'form-control'
    .col-md-2.col-form-label= label_tag('name', 'Second Label')
    %div.col-md-4
      = number_field_tag :count, nil, placeholder: '1', min: 1, required: true, class: 'form-control'
      = link_to_remove_association('remove this', @form_obj, { wrapper_class: 'added-row' })
```

And this is the error I am getting:
```
undefined method `object' for nil:NilClass

%div.col-md-4       
    = number_field_tag :count, nil, placeholder: '1', min: 1, required: true, class: 'form-control'      
    = link_to_remove_association('remove this', @form_obj, { wrapper_class: 'added-row' })

```

**Comment by nathanvda** [comment]
No, you are right, cocoon will not help you in this case. So you will have to write your own code/javascript to add/remove fields to build your json. This is pretty specific but not too hard, imho, if you ask that question on stackoverflow you will get help pretty quick.

**Comment by sandipsubedi** [comment]
Thank you for your answer. I will go ahead and use JS.
