### ISSUE TITLE
Unable to get the results that I want with the nested-form

### ISSUE THREAD

**Issue by RailsCod3rFuture** [nathanvda/cocoon#483]
I'm trying to build a job application form for the job model. The job itself, is created by the employer model. But, the user model will access the job_application model to sign the form. With cocoon, I have no problem seeing the entire form, but it's showing the job form with all inputs on the show page. I simply want the job_application part of the form to show for normal users. 
Here is the code below. How would you approach solving this problem using cocoon?

job.rb
```
class Job < ApplicationRecord
belongs_to :employer 
has_many :job_applications, dependent: :destroy
has_one :job_category
end
```

job_application.rb
```
class JobApplication < ApplicationRecord
  belongs_to :employer
  belongs_to :user
  belongs_to :job
  delegate :resume, to: :user
  validates :user_first_name, presence: true, uniqueness: false, length: {maximum: 50}, format: {with: /\A[a-zA-Z]+(?: [a-zA-Z]+)?\z/}
  validates :user_last_name, presence: true, uniqueness: false, length: {maximum: 50}, format: {with: /\A[a-zA-Z]+(?: [a-zA-Z]+)?\z/}
  validates :user_resume_link, presence: true
  validates :user_contact_time, presence: true
end
```

user.rb
```
class User < ApplicationRecord
has_many :job_aplications
has_many :jobs, :through => :job_applications
end
```

employer.b
```
class Employer < ApplicationRecord
has_many :jobs, :dependent => :destroy
end
```

jobs/_form
```
<%= simple_form_for(@job) do |f| %>
// Other attributes
  <div id="job-applications">
      <%= f.simple_fields_for :job_applications do |job_application| %>
      <%= render 'job_applications/form', :f => job_application %>
    </div>
<% end %>
```

**Comment by nathanvda** [comment]
Only employers can see all the entered job-applications, right? So how do you know an employer is watching the page? And even more specifically, imho only the employer offering the job can see all the job-applications. 

So you could simply test if the currently signed in user is an employee of the company offering the job, and then show all the entered applications, in all other cases just show an empty job-application form to enter. Also you do not need to use cocoon for this at all. Any visitor just has to enter a new job-application for a specific job (e.g. the `job_id` will be a hidden parameter in the form), definitely DO NOT let any user also enter/change job-details :smile: :+1:

**Comment by RailsCod3rFuture** [comment]
ok. Thanks.
