### ISSUE TITLE
Dynamic form for a single model

### ISSUE THREAD

**Issue by akshat12** [nathanvda/cocoon#486]
I was wondering if it's possible to make a dynamic form for a single model. For e.g., I have a `Book` model and I want the ability to add multiple books through a single form. There is no nesting in this case. Is it possible to achieve this using `Cocoon`? Thank you

**Comment by Mirv** [comment]
This is a stackoverflow question ... you will get a wider range of answers for various technologies there.

The short version is no, not without rewriting it to be your own thing & I guessing if you're asking, you don't have the expertise to recognize that by just reading thru the source code of cocoon.

The longer version is would be little to no point to using cocoon as the jquery on the server side is tasked with creation of fields which nest in divs that call to nesting relationships ... though perhaps if you knew jquery, you could use said calls to write your own jquery scripts ... but that has been done hundreds of times already ... just google jquery (if you know for a fact you need server side rendering) or javascript dynamic forms.

Also, please don't forget to close this ticket.

**Comment by akshat12** [comment]
Sounds good. Thank you for the help, Mirv.
