### ISSUE TITLE
link_to_add_association fields not working when used with default input fields

### ISSUE THREAD

**Issue by RuneDrop** [nathanvda/cocoon#489]
I'm rather new to Rails and never used Cocoon before, but it seems to be pretty useful so far :)

I hope that I just haven't overlooked something obvious and stupid here, but I'm having issues getting link_to_add_association fields to work in combination with default rendered fields (I hope it's clear what I mean, but you will probably see what I'm trying to do in the code).

I have a Voting and an Option model: 
```
class Voting < ApplicationRecord
  has_many :options, inverse_of: :voting
  accepts_nested_attributes_for :options, reject_if: :all_blank

  validates :content, presence: { message: "Error: Please enter your Voting Question." }
  validate :option_counter

  def option_counter
    return errors.add :vote, "Error: at least two Options required." if options.size < 2
  end
end
```
```
class Option < ApplicationRecord
  belongs_to :voting
end
```
(including the validations to stay on the safe side)

my new.html.erb:
```
<%= form_with model: @voting, local: true do |f| %>
  <p>
    <%= f.label :voting %><br>
    <%= f.text_area :content , rows: 4, cols: 35%>
  </p>
  <p>
    <%= f.label :options %>
    <%= f.fields_for :options do |option| %>
      <%= render 'option_fields', f: option %>
    <% end %>
    <%= link_to_add_association "add option", f, :options %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
```
and the _option_fields.html.erb:
```
<ul><%= f.text_field :vote %></ul>
```

so you can create a voting object together with its nested option objects. 
the link_to_add_association function works well so far, records are going to be saved in the DB and everything is fine.
BUT I want to offer the user 3 option fields as default and then he can choose to add more via "add options"-link.
The problem is, as soon as I add `3.times { @voting.options.build }` or even just `@voting.options.build` into the new action of my VotingsController, the dynamic fields from Cocoon won't save their values into the DB anymore. Only the values added into the default fields will be saved, the values of the dynamically added fields are ignored. And I can't see why, I already searched for similar issues but couldn't find any.

I'm using Rails 5.1.5 and Cocoon 1.2.11

**Comment by nathanvda** [comment]
I cannot think why `@voting.options.build` would be saved and a dynamically added option would not.
Because that is what you are saying right: only the pre-built options will be saved, and the other will not? 

Can you show us the parameters that are posted to the controller (you can find that in the logfile) and your strong-parameters definition? If your controller-code does something extra, maybe it might be useful to show that too?

**Comment by RuneDrop** [comment]
Thank you for the fast reply.
Yes, only the pre-built options will be saved, and the other won't.

here is the part of the logfile:

> Started POST "/votings" for ::1 at 2018-03-09 12:42:20 +0100
Processing by VotingsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"jWVjPjzh9RSnSl/4kAYcbubu1ed4wgexThciKHStT4utb+Pa/qzNs4rGvnWcmGV1sT2YaPcI+R1hLkJpo8PH1A==", "voting"=>{"content"=>"test??", "options_attributes"=>{"0"=>{"vote"=>"test1"}, "1"=>{"vote"=>"test2"}, "2"=>{"vote"=>""}}}, "commit"=>"Create Voting"}
  [1m[35m (1.0ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (0.0ms)[0m  [1m[32mINSERT INTO "votings" ("content", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"[0m  [["content", "test??"], ["created_at", "2018-03-09 11:42:20.704533"], ["updated_at", "2018-03-09 11:42:20.704533"]]
  [1m[35mSQL (0.0ms)[0m  [1m[32mINSERT INTO "options" ("voting_id", "vote", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"[0m  [["voting_id", 217], ["vote", "test1"], ["created_at", "2018-03-09 11:42:20.706534"], ["updated_at", "2018-03-09 11:42:20.706534"]]
  [1m[35mSQL (1.0ms)[0m  [1m[32mINSERT INTO "options" ("voting_id", "vote", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"[0m  [["voting_id", 217], ["vote", "test2"], ["created_at", "2018-03-09 11:42:20.708536"], ["updated_at", "2018-03-09 11:42:20.708536"]]
  [1m[35m (1.0ms)[0m  [1m[35mCOMMIT[0m
Redirected to http://localhost:3000/votings/217
Completed 302 Found in 12ms (ActiveRecord: 3.0ms)


This is what I did: I wrote "test1" in the first pre-built option field, "test2" in the second and left the third one empty. I also added two dynamic fields with the "add option"-link. In the first (dynamic) i wrote "test3" and in the other "test4". 
Like I said, their values are ignored for some reason. 

Here is what happens, when I comment out any `@voting.options.build` stuff:

> Started POST "/votings" for ::1 at 2018-03-09 12:52:09 +0100
Processing by VotingsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"fxJtUDwJqlljoSAM4gaf46vxOIYxSI8Nc/C8MPfz3xBfGO20/kSS/k4twYHumOb4/CJ1Cb6CcaFcydxxIJ1XTw==", "voting"=>{"content"=>"test??", "options_attributes"=>{"1520596312210"=>{"vote"=>"test1"}, "1520596313050"=>{"vote"=>"test2"}, "1520596314259"=>{"vote"=>""}}}, "commit"=>"Create Voting"}
  [1m[35m (0.0ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (1.0ms)[0m  [1m[32mINSERT INTO "votings" ("content", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"[0m  [["content", "test??"], ["created_at", "2018-03-09 11:52:09.447871"], ["updated_at", "2018-03-09 11:52:09.447871"]]
  [1m[35mSQL (0.0ms)[0m  [1m[32mINSERT INTO "options" ("voting_id", "vote", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"[0m  [["voting_id", 218], ["vote", "test1"], ["created_at", "2018-03-09 11:52:09.448873"], ["updated_at", "2018-03-09 11:52:09.448873"]]
  [1m[35mSQL (0.0ms)[0m  [1m[32mINSERT INTO "options" ("voting_id", "vote", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"[0m  [["voting_id", 218], ["vote", "test2"], ["created_at", "2018-03-09 11:52:09.450873"], ["updated_at", "2018-03-09 11:52:09.450873"]]
  [1m[35m (0.5ms)[0m  [1m[35mCOMMIT[0m
Redirected to http://localhost:3000/votings/218
Completed 302 Found in 10ms (ActiveRecord: 1.5ms)

The values of the dynamic fields are successfully saved.

Here is my VotingsController stuff that you wanted to see:
```
class VotingsController < ApplicationController
  def show
    @voting = Voting.find(params[:id])
    @options = @voting.options
  end

  def new
    @voting = Voting.new
    #3.times { @voting.options.build }
    #@voting.options.build
  end

  def create
    @voting = Voting.new(voting_params)

    if @voting.save
      flash[:notice] = "Voting created!"
      redirect_to @voting
    else
      render :new
    end
  end

  private
  def voting_params
    params.require(:voting).permit(:content, options_attributes: [:vote])
  end
end
```

**Comment by nathanvda** [comment]
Ok. I can see that the `test3` and `test4` are just not sent to the controller. So I am guessing your html is not built correctly (for instance: your form is split, some fields are outside the form, some elements have the same id). Does your partial really only contain a `<ul>` item? (because then: where are the `<li>` elements?). Can you use just `<div>` instead of `<ul>` for test?

**Comment by RuneDrop** [comment]
Hm, I tried out replacing the `<ul>` with `<div>` in the partial like you suggested, but that didn't change anything.
For now, I will test around a little with the html in my form, then. Let's see if it helps.

**Comment by nathanvda** [comment]
Can you show the pure html when adding the pre-built options, and having added some manual options? I am trying to understand why those should be ignored?

**Comment by RuneDrop** [comment]
Okay, so I changed some html in my form and got it to work. It really only missed a `<div>` tag (I actually didn't know that this was important to bring it to work). 
Well, the issue is solved, so I will close it now.
Thank you very much for your help.
