### ISSUE TITLE
Custom code needed in the controller create method?

### ISSUE THREAD

**Issue by myfitment** [nathanvda/cocoon#490]
The form works great, but I guess I can't just call ```myobj.save``` any more? For example:
```
with invoice_params = {"description"=>"dfasefa", "invoice_line_items_attributes"=>{"0"=>{"_destroy"=>"false", "description"=>"Basic Subscription", "subscription_service_id"=>"", "amount"=>"19.0"}}}
```

The basic Rails create methods no longer work:

```
  def create
    @invoice = current_subscription.invoices.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end
```
Do I have to write custom controller code to break out the ```has_many``` items everywhere I use this?

I actually had to add ```invoice_line_items_attributes``` to ```attr_accessible``` in my ```Invoice``` model. Is that normal? And the ```save``` line in the create method is trying to save the line item attributes to my main model. This is really confusing.

**Comment by nathanvda** [comment]
Please detail: which rails version are you using? (you are not using strong parameters but `attr_accesible`?) Do you have the `accepts_nested_attributes_for` line in your model? Which error do you get on save? How

**Comment by myfitment** [comment]
Rails 4.2.7, cocoon 1.2.1, simple_form 3.5.1

I was using protected_attributes, then I got rid of that and I'm just trying to use the default functionality.

    def invoice_params
      params.require(:invoice).permit(:subscription_id, :description, :amount, :paid, :billing_period, :approved, :invoice_line_items_attributes => [:id, :_destroy, :description, :subscription_service_id, :amount])
    end

and the save call fails:

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = current_subscription.invoices.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

invoice_params gives:

{"description"=>"", "invoice_identifier"=>"E79D20D-0002", "invoice_line_items_attributes"=>{"0"=>{"_destroy"=>"false", "description"=>"Basic Subscription", "subscription_service_id"=>"", "amount"=>"19.0"}}}

And I guess that's fine, but then the error is:

NoMethodError (undefined method `subscription_service_id' for #<Invoice:0x007ff16c775118>

That makes absolutely no sense whatsoever. It's like it's flattening the attribute hash and trying to cram everything into Invoice. Why would it do that?




This transmission is for the sole use of the intended recipient(s) and may contain information that is confidential and/or privileged. If you are not the intended recipient, please delete this transmission and any attachments and notify the sender by return email immediately. Any unauthorized review, use, disclosure or distribution is prohibited.

**Comment by nathanvda** [comment]
Ok. Cool. How are your associations declared and do you have the `accepts_nested_attributes_for` line?

**Comment by myfitment** [comment]
Ugh. This error is a red herring. You put me on the scent. I had that field in a validator on the Invoice model instead of the InvoiceLineItem model. Works fine now. File under idiot. Thanks for your help!



This transmission is for the sole use of the intended recipient(s) and may contain information that is confidential and/or privileged. If you are not the intended recipient, please delete this transmission and any attachments and notify the sender by return email immediately. Any unauthorized review, use, disclosure or distribution is prohibited.
