### ISSUE TITLE
link_to_add_association and link_to_remove_association are reloading the full page instead of just load the partial

### ISSUE THREAD

**Issue by maykcastroo** [nathanvda/cocoon#491]
When I click on the link to add new fields, it cleans all the fields in the form and doesn't load the new fields where it should appear.

models:
class SchoolClass < ApplicationRecord
	has_many :school_class_subjects
	accepts_nested_attributes_for :school_class_subjects
end

class SchoolClassSubject< ApplicationRecord
	belongs_to :school_class
	belongs_to :subject
	belongs_to :teacher
end

Form: 
    <%= form.fields_for :school_class_subjects, SchoolClassSubject.new do |school_class_subject| %>
    <fbody class="school_class_subjects">  
      <%= render 'school_class_subject_fields', form: school_class_subject %>
    </tbody>    
    <% end %>

    <%= link_to_add_association "Add Subject", form, :school_class_subjects, data: {association_insertion_node: '.school_class_subjects', association_insertion_method: :append}, form_name: 'form' %>

Partial:
<div class="nested-fields">
	<%= form.collection_select :subject_id, Subject.order(:description), :id, :description, {}, {:multiple => false} %> <br/>
	       
	<%= form.collection_select :teacher_id, Teacher.order(:name), :id, :name, {}, {:multiple => false} %> <br/>
	<%= link_to_remove_association "Remove Subject", form %>
</div>

Any ideas of what's going on?

**Comment by nathanvda** [comment]
This sounds like the cocoon javascript code is not loaded correctly.

* is the cocoon javascript included in the application.js?
* is the cocoon javascript loaded on the page?
* do you have an error somewhere in your javascript (check the javascript console) blocking the parsing/running of the javascript before it gets to the cocoon part

**Comment by maykcastroo** [comment]
Hey @nathanvda I just checked the javascript console and I got this error: 
cocoon.self-93f6a0ae289b45a10cca9a37fd83317f30d955625d791077135f56fe87c6816f.js?body=1:137 Uncaught ReferenceError: jQuery is not defined
    at cocoon.self-93f6a0ae289b45a10cca9a37fd83317f30d955625d791077135f56fe87c6816f.js?body=1:137

**Comment by nathanvda** [comment]
This error seems self-explanatory to me, but apparently it is not for you, so 

* the error means jquery is not found
* if this was not clear before: cocoon relies on the presence of jquery
* this means you have to add jquery to your application.js
* before cocoon

**Comment by maykcastroo** [comment]
I added jquery-rails and it's working. Thanks for the help!
