### ISSUE TITLE
Dynamic creation of link_to_add_association

### ISSUE THREAD

**Issue by jordan-realfoto** [nathanvda/cocoon#492]
I've already asked this on SO but I thought I would throw it in here in case it is not feasible.

I have a form which allows the adding of possibly hundreds of different association types to a form. I'm using the cocoon gem's link_to_add_association but rendering 100's of links is very slow as they're populated with all the html required to add them. Is there any way to dynamically create the links from an ajax request? The problem is link_to_add_association requires the form builder object which is unavailable after the initial page request.

As a side note the links are grouped so if I'm hoping to render the links for that particular group when it's clicked.

https://stackoverflow.com/questions/49341061/rails-cocoon-dynamic-creation-of-link-to-add-association

**Comment by nathanvda** [comment]
Wow. Hundreds of associations? Could you explain in a little more detail what you are trying to accomplish? (out of interest, I am curious what kind of problem area would require this, also: how do you make that user-friendly in any way).

But indeed: rendering a page with +100 links, all with their form pre-built, I can imagine is really heavy/slow. Actually: cocoon is just built to _avoid_ an ajax call, but indeed in your case using ajax/xhr to only build an additional form on demand seems the way forward, but unfortunately you are pretty much on your own there. At my work we have also a lot of generic, different models (e.g. pipeline-parts, and there are a lot of them), so most of our views and forms are built completely generically, so I am hoping you did something similar so you did not have to write 100+ forms 😱 :scream: :scream:  😉

**Comment by jordan-realfoto** [comment]
Thanks for the reply! The links were all the same association but different data so it was only one form. I ended up rendering a new form for each group which worked out quite well.
