### ISSUE TITLE
Creating Batches of Nested Models

### ISSUE THREAD

**Issue by activestylus** [nathanvda/cocoon#494]
I'm creating a CMS that features creation of grids/layouts.

This requires me to build a form with two levels of nesting.

```ruby
class Post < ActiveRecord::Base
  has_many :nodes, inverse_of: :post
  accepts_nested_attributes_for :nodes
end

class Node < ActiveRecord::Base
  belongs_to :post
  has_many :cells, inverse_of: :node
  accepts_nested_attributes_for :cells
end

class Cell < ActiveRecord::Base
  belongs_to :node
end
```

Here is a screenshot of what I'm trying to accomplish:

![image](https://user-images.githubusercontent.com/285/37863933-1df0c93e-2f67-11e8-958b-b6fdff772020.png)

The top level is a Node and I am giving users the option to choose grid layouts that contain multiple configurations of Cells.

The "+ Add Node" button is actually a menu of buttons (2 column, 4 column, etc) and depending on which one you press it will instantly generate the right amount of Cells inside the newly created Node.

(1) Is it possible to create more than one child at a time (each with a unique ID for saving)?

(2) Is there a way to programatically alter the AddNested link so that it dynamically adds the right number of cells based on say, a data-attribute?

Thanks in advance for any guidance

**Comment by nathanvda** [comment]
You can specify the number of items to generate when clicking, by doing something like 

    = link_to_add_association 'add post', f, :posts, count: 4

This answers both of your questions? I am not sure what question (1) is "at a time" --> when saving at the server? Yes. Actually we do not generate an actual id client-side, it is only when the form is saved that it gets the actual id.

**Comment by activestylus** [comment]
Thanks for the tip! In regards to my previous query regarding the ID, I was referring to the timestamp used to differentiate the child nodes, which apparently is handled by this functionality. I just need to figure out how to programaticaly alter the count attribute depending on which button is pressed and I'm golden. Pretty confident I will pull it off but will check in here if I run into any issues. In the meantime I'm closing this so your issues are a bit more tidy
