### ISSUE TITLE
Multiple nested partials from other forms

### ISSUE THREAD

**Issue by gabriellima** [nathanvda/cocoon#50]
Hi. I'm using rails 3.2. Given I have the follow:

./views/article/_form.html.haml

``` ruby
= semantic_form_for @article do |f|
  = render 'contents/basic_data', :f => f
```

./views/contents/_basic_data.html.haml

``` ruby
%fieldset{:id => "dados_basicos"}
  #......................
  = f.semantic_fields_for :authors do |author|
    = render 'contents/author_fields', :f => author
```

./views/contents/_author_fields.html.haml

``` ruby
.nested-fields
  = f.inputs do
    #.......
```

When I access `article/new`, the following error appears:

```
Missing partial article/author_fields, inherited_resources/base/author_fields, application/author_fields
```

I.e., I think that these nested partial views are somehow messing with it's locations... because I sinalized that partial view `_author_fields` is at `/views/contents/`

To workaround this, I had to put `_author_fields` at `/views/application/`, but I'd like to know a better solution.

Thanks in advance! And congratulations for this project, by the way!

**Comment by escapetherobots** [comment]
@nathanvda Thank you so much for explaining the :partial key on the "link_to_add_association"!
