### ISSUE TITLE
Display secondary parent first_name and last_name

### ISSUE THREAD

**Issue by sidhunavroop** [nathanvda/cocoon#505]
_form.html.erb

```
<div class='row'>
  <div class= 'col-xs-12'>
    <%= form_for(@parent, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    	<div class = "form-group">
        <div class="control-label col-sm-2">
    	<%= f.label :parent_1_firstname %>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :parent_1_firstname, class: "form-control", placeholder: "Parent 1 first name", 
      autofocus:true %>
      </div>
    </div>
     <div class = "form-group">
        <div class="control-label col-sm-2">
             <%= f.label :parent_1_lastname %>
           </div>
           <div class="col-sm-8">
             <%= f.text_field :parent_1_lastname, class: "form-control", placeholder: "Parent 1 last name", 
           autofocus:true %>
          </div>
        </div>
        <p><strong>Add Secondary Parents or Guardians<br /></strong></p>
        <div id ='secondaryparents'>
        <%= f.fields_for :secondaryparents do |builder| %>
        <%= render 'secondaryparent_fields', :f => builder %>
        <% end %>
        <%= link_to_add_association 'Add Secondary Parent', f, :secondaryparents %>
      </div>
      <div class="form-group">
        <div class="col-sm-10">
      	<%= f.submit class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
<% end %>
```
_secondaryparent_fields.html.erb

```
	<div class = "form-group">
        <div class="control-label col-sm-2">
             <%= f.label :parent_first_name %>
           </div>
           <div class="col-sm-8">
             <%= f.text_field :parent_first_name, class: "form-control", placeholder: "Parent First Name", 
             autofocus:true %>
          </div>
        </div>
        <div class = "form-group">
        <div class="control-label col-sm-2">
             <%= f.label :parent_last_name %>
           </div>
           <div class="col-sm-8">
             <%= f.text_field :parent_last_name, class: "form-control", placeholder: "Parent Last Name", 
            autofocus:true %>
          </div>
        </div>
        <%= link_to_remove_association "Remove Parent", f %>
```

show.html.erb

```
<h2>Family Information</h2>
<p><strong>Primary Parent or Guardian in the home<br /></strong></p>
<p>First Name: <%= @parent.parent_1_firstname %></p>
<p>Last name:<%= @parent.parent_1_lastname %></p>
<p><strong>Secondary Parents or Guardians<br /></strong></p>
<p>First Name:<%= @secondaryparent.first_name %></p>
<p>Last Name:<%= @secondaryparent.last_name %></p>
<hr>
```

please help
How to display the secondary parent first name and last name?

**Comment by nathanvda** [comment]
I fixed your formatting. 

I prefer if questions like this are asked on stackoverflow, where there are more people watching. 

The question is completely unclear. In the `show.html.erb` you show the  parent and secondary parent, and that works? It does not work? How are `@parent` and `@secondaryparent` set in the controller? Or do you want to show the secondaryparents in the `_form` ? 

How are the associations? I am guessing a family has parent_1 and has_many secondaryparents. 
Should you not iterate over all `@family.secondaryparents` in the view, or are you only interested in the first? Like `@secondaryparent= family.secondaryparents.first` ?

**Comment by sidhunavroop** [comment]
there is parent table which includes the parent_1. there is a secondaryparent table which includes all the secondaryparent, if someone adds them in the _form. parent has_many association with secondary_parents. what I want is when someone ends the name of secondary parents it displays in show.html.erb. I dont know how to figure that out

**Comment by sidhunavroop** [comment]
def new
		@parent = Parent.new
		@parent.secondaryparents.build

	end
	def edit
		
	end

	def create
		@parent = Parent.new(parent_params)
		@parent.family = current_user
		if @parent.save
			flash[:success] = "Family details were added"
		redirect_to parent_path(@parent)
	else 
		render 'new'
	end
end
	def update
		
		if @parent.update(parent_params)
			flash[:success] = "Family details were updated"
		redirect_to parent_path(@parent)
	else 
		render 'edit'
	end
end

	def show
		
	end
	def destroy
		
		@parent.destroy
		flash[:danger] = "Family details were successfully deleted"
		redirect_to parents_path 
	end


	private
	def set_parent
			@parent = Parent.find(params[:id])	
	end
	def parent_params
			params.require(:parent).permit(:parent_1_firstname, :parent_1_lastname, :address, :city, :province, :telephone_number, :postal_code, :email, :family_type, :family_size, :family_situation, secondaryparents_attributes: Secondaryparent.attribute_names.map(&:to_sym).push(:_destroy))
	end

**Comment by nathanvda** [comment]
Hi @sidhunavroop this is a very basic question, it is not related to cocoon at all, so please ask this question on stackoverflow.com.

Please attempt to use the editor to 1) correctly indicate a piece of text is code, and 2) make sure you have proper indentation (ruby standard indents by 2 spaces, see [style guide](https://github.com/bbatsov/ruby-style-guide#source-code-layout) )   

Post the link to the question on stackoverflow here, and I will answer there if nobody has had a look yet.

**Comment by sidhunavroop** [comment]
okay
thank you @nathanvda
