### ISSUE TITLE
Breaking changes with Mongoid 7

### ISSUE THREAD

**Issue by nofxx** [nathanvda/cocoon#506]
Just a heads up, lost long time on this one (didn't noticed mongoid got upgraded too hehe)

Mongoid's changed ```#reflect_on_association``` on v7, instead of returning Mongoid::Metadada:

```ActionView::Template::Error (undefined method `collection' for #<Mongoid::Association::Embedded::EmbedsMany:0x0000560d1865b0a0>```

or ```Mongoid::Association::Referenced::HasMany```

**Comment by nathanvda** [comment]
Thanks for the heads up. Personally never tested with Mongoid. Can you open a PR to fix this? Or what is the intention of this is issue?

**Comment by wryanp** [comment]
Any ideas on this?

In my case, everything works fine with Cocoon except for `link_to_add_association`.  I get the error `undefined method `collection?' for #<Mongoid::Association::Referenced::HasMany:0x00007f80b7e33db8>`.

**Comment by nathanvda** [comment]
As said before: I personally am currently not working with mongoid, so I am unable to reproduce and/or fix this at the moment.

**Comment by Startouf** [comment]
The following (very dirty) monkeypatch seems to work

```
# initializers/cocoon_mongoid_monkeypatch.rb
# Monkeypatch for https://github.com/nathanvda/cocoon/issues/506
# Need to use specific Mongoid 7 Logic
module Cocoon
  module ViewHelpers
    def create_object_on_association(f, association, instance, force_non_association_create)
      if instance.class.name == "Mongoid::Relations::Metadata" || force_non_association_create
        create_object_with_conditions(instance)
      else
        assoc_obj = nil

        # assume ActiveRecord or compatible
        # Breaking change with Mongoid 7 forces us to check metadata in different way
        if collection?(instance)
          assoc_obj = f.object.send(association).build
          f.object.send(association).delete(assoc_obj)
        else
          assoc_obj = f.object.send("build_#{association}")
          f.object.send(association).delete
        end

        assoc_obj = assoc_obj.dup if assoc_obj.frozen?

        assoc_obj
      end
    end

    def collection?(instance)
      if respond_to?(:collection?)
        instance.collection?
      elsif defined?(Mongoid) && Mongoid::VERSION.starts_with?('7')
        instance.is_a?(::Mongoid::Association::Referenced::HasMany) ||
          instance.is_a?(::Mongoid::Association::Referenced::HasAndBelongsToMany) ||
          instance.is_a?(::Mongoid::Association::Embedded::EmbedsMany)
      end
    end
  end
end
```
Note

1- There is probably a much cleaner way to check collection-like behavior if we look more thoroughly in ActiveModel documentation (or not ?)

2-If not, I would hint to use the [Mongoid compatibility gem](https://github.com/mongoid/mongoid-compatibility) instead of making a dirty `starts_with?` on the version string (otherwise we have to lock the compatibility to `mongoid < 8`)

**Comment by Startouf** [comment]
@nofxx I am pinging you since you might be interested

**Comment by nathanvda** [comment]
Hi @startouf, thanks for your monkeypatch! Maybe i am mistaken, but I assumed previously it just checked the class, being `Mongoid:Relations:Metadata` and then create an object --not on the association. So I would assume the simpler check would be to have something like 

```
if instance.class.name.starts_with?('Mongoid::') || force_non_association_create
  create_object_with_conditions(instance)
else
```

Not sure if you would be 1) willing to test and create a PR, or 2) if I create a branch, verify it works?

**Comment by Startouf** [comment]
Oh that's right, I am so silly I did not even look at the code before the breaking method and skipped directly to the crashing line 🙄

Your patch also works, just tested it on my original failing spec, I'm running my test suite again with this

**Comment by nathanvda** [comment]
If it is too much work, I can easily do it but I would prefer to give you credit.

**Comment by Startouf** [comment]
I'm afraid I won't have time to write specs (unless it is quite easy). I will start the PR with this quick fix, but I cannot check if this works fine with previous mongoid versions. It is fine if someone takes over my PR
