### ISSUE TITLE
ID For On Cocoon Listeners

### ISSUE THREAD

**Issue by ZASMan** [nathanvda/cocoon#509]
I'm trying to figure out how to execute a javascript function after an item is eventually inserted. According to your documentation:
```
$(document).ready(function() {
    $('#owner')
      .on('cocoon:before-insert', function() {
        $("#owner_from_list").hide();
        $("#owner a.add_fields").hide();
      })
      .on('cocoon:after-insert', function() {
        /* ... do something ... */
      })
```

What exactly is the "#owner" event here? If its listening for page ready, how is it listening on "owner"? What exactly would the owner element be?
```
MY javascript looks like this:
$(document).ready(function() {
  var my_model_add_button = $("#my_model_add_button");
  // Is the my_model_add_button button supposed to be the thing being listened on?
  $(my_model_add_button).on('cocoon:cocoon:before-insert', function(e, insertedItem) {
  	insertedItem.attr("title", "Delete Last Object Form");
  });
})```

**Comment by nathanvda** [comment]
Mmmmm this is basic jquery: I register an event-handler on a div with id `#owner`. The div should encompass an area where cocoon is responsible to add new linked items. 

If this is unclear, the full example is in the demo project: https://github.com/nathanvda/cocoon_simple_form_demo

In your example I have a few remarks: 

* you mention "class" but you write `#my_model_add_button` which looks for a html id
* you name it `my_model_add_button` which seems to indicate it is part of the button, but you should use a surrounding/encompassing div. The event is triggered on the insertion element (so the place where the new item will/is inserted), not the button.

**Comment by ZASMan** [comment]
Thanks, I ended up figuring it out. I did something like this:
```
$(document).on("cocoon:after-remove", function() {
  // My function here
});
```

And it executed every time after a cocoon event

**Comment by nathanvda** [comment]
Nice :+1: that definitely works! :+1: 🎉 🎉  If you have multiple `link_to_add_association` buttons on a page, it helps to use a more fine-grained approach (so use a smaller containing div). But that would be exceptional I guess.

**Comment by ZASMan** [comment]
In my code I just put to execute it on `if ((element.length))` type thing so that should cover it
