### ISSUE TITLE
saving problem

### ISSUE THREAD

**Issue by armanlearn** [nathanvda/cocoon#512]
hi

my form not save, but if I input value to database directly data shown in form and also removes work.

```
class Jadval < ApplicationRecord
	has_many :dakals
	accepts_nested_attributes_for :dakals,  :allow_destroy => true
end
```

```
class Dakal < ApplicationRecord
	belongs_to :jadval
end
```

```
    def jadval_params
      params.require(:jadval).permit(:mojavez_haml_number, :gharardad_number, :dakal, :karfarma_name, :site_code, :taghir_dakal, :taghir_site, :site_addr, :tahvil_date, :gharardad_date,
                                     :shabloon_date, :dakal_date, :resid, :sader_shode, :tayeed_shode, :tozihat,
                                      :daryaft_pool,  dakal_attributes: [:id, :name, :tedad, :residshoodeh ,:_destroy]     )
    end

```

`

                        <div class="panel panel-default">
                          <div class="panel-heading">اطلاعات رسید</div>
                            <div class="panel-body">

                                  <div id="dakals">
                                    <%= f.simple_fields_for :dakals do |dakal| %>
                                      <%= render 'dakal_fields', :f => dakal %>
                                    <% end %>
                                    <div class='links'>
                                      <%= link_to_add_association 'add dakal', f, :dakals %>
                                    </div>

                                  </div>

                          </div></div>

`

`<div class='nested-fields'>
    <%= f.input :name %>
    <%= f.input :tedad %>
     <%= f.input :residshoodeh %>
    <%= link_to_remove_association "remove dakal", f %>
</div>`

I did every things from sample code and wiki but I don't know why I have problem in save.

tanks for helping me

**Comment by nathanvda** [comment]
When using rails 5 you have to write: 

    has_many :dakals, inverse_of: :jadval 

Are you using rails 5? Does that help? Otherwise show us the part of the `development.log` so we can see what is posted and might go wrong.

**Comment by armanlearn** [comment]
Hi again
Tanks for your reply.
yes I am using rails 5.1. I tried inverse_of: :jadval  before and now I put it again in my code but it not work.
remove record works fine. I put value in database with sqlite manager and when I see form it show records, when I remove it works but add new record not works.

should I use turn on turbo like
regards.

**Comment by armanlearn** [comment]
sorry this is my log file
```

Started GET "/" for 127.0.0.1 at 2018-06-24 12:26:29 +0430
  [1m[35m (0.2ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
Processing by JadvalsController#index as HTML
  [1m[36mUser Load (0.2ms)[0m  [1m[34mSELECT  "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?[0m  [["id", 1], ["LIMIT", 1]]
  Rendering jadvals/index.html.erb within layouts/application
  [1m[36mJadval Load (0.2ms)[0m  [1m[34mSELECT "jadvals".* FROM "jadvals"[0m
  Rendered jadvals/index.html.erb within layouts/application (1633.8ms)
  Rendered layouts/partials/_topnavbar.html.erb (2.5ms) [cache miss]
  Rendered layouts/partials/_footer.html.erb (0.2ms) [cache miss]
Completed 200 OK in 1806ms (Views: 1768.3ms | ActiveRecord: 1.9ms)


Started GET "/api/i18n/site-en.json" for 127.0.0.1 at 2018-06-24 12:26:38 +0430
  
ActionController::RoutingError (No route matches [GET] "/api/i18n/site-en.json"):
Started GET "/jadvals/2/edit" for 127.0.0.1 at 2018-06-24 12:26:38 +0430
  
Processing by JadvalsController#edit as HTML
actionpack (5.1.0) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
web-console (3.6.2) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.6.2) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.6.2) lib/web_console/middleware.rb:20:in `catch'
web-console (3.6.2) lib/web_console/middleware.rb:20:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.0) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.0) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.0) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.0) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.0) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.0) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
railties (5.1.0) lib/rails/engine.rb:522:in `call'
puma (3.11.4) lib/puma/configuration.rb:225:in `call'
puma (3.11.4) lib/puma/server.rb:632:in `handle_request'
puma (3.11.4) lib/puma/server.rb:446:in `process_client'
puma (3.11.4) lib/puma/server.rb:306:in `block in run'
puma (3.11.4) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
  Parameters: {"id"=>"2"}
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT  "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?[0m  [["id", 1], ["LIMIT", 1]]
  [1m[36mJadval Load (0.2ms)[0m  [1m[34mSELECT  "jadvals".* FROM "jadvals" WHERE "jadvals"."id" = ? LIMIT ?[0m  [["id", 2], ["LIMIT", 1]]
  Rendering jadvals/edit.html.erb within layouts/application
  [1m[36mDakal Load (0.3ms)[0m  [1m[34mSELECT "dakals".* FROM "dakals" WHERE "dakals"."jadval_id" = ?[0m  [["jadval_id", 2]]
  Rendered jadvals/_dakal_fields.html.erb (13.4ms) [cache miss]
  Rendered jadvals/_form.html.erb (407.9ms) [cache miss]
  Rendered jadvals/edit.html.erb within layouts/application (409.9ms)
  Rendered layouts/partials/_topnavbar.html.erb (3.7ms) [cache miss]
  Rendered layouts/partials/_footer.html.erb (0.4ms) [cache miss]
Completed 200 OK in 560ms (Views: 550.9ms | ActiveRecord: 1.8ms)


Started GET "/" for 127.0.0.1 at 2018-06-24 12:26:48 +0430
Processing by JadvalsController#index as HTML
  [1m[36mUser Load (0.2ms)[0m  [1m[34mSELECT  "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?[0m  [["id", 1], ["LIMIT", 1]]
  Rendering jadvals/index.html.erb within layouts/application
  [1m[36mJadval Load (0.2ms)[0m  [1m[34mSELECT "jadvals".* FROM "jadvals"[0m
  Rendered jadvals/index.html.erb within layouts/application (5.5ms)
  Rendered layouts/partials/_topnavbar.html.erb (3.8ms) [cache miss]
  Rendered layouts/partials/_footer.html.erb (0.6ms) [cache miss]
Completed 200 OK in 100ms (Views: 95.3ms | ActiveRecord: 0.5ms)


Started GET "/jadvals/1/edit" for 127.0.0.1 at 2018-06-24 12:26:50 +0430
Processing by JadvalsController#edit as HTML
  Parameters: {"id"=>"1"}
  [1m[36mUser Load (0.2ms)[0m  [1m[34mSELECT  "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?[0m  [["id", 1], ["LIMIT", 1]]
  [1m[36mJadval Load (0.1ms)[0m  [1m[34mSELECT  "jadvals".* FROM "jadvals" WHERE "jadvals"."id" = ? LIMIT ?[0m  [["id", 1], ["LIMIT", 1]]
  Rendering jadvals/edit.html.erb within layouts/application
  [1m[36mDakal Load (0.2ms)[0m  [1m[34mSELECT "dakals".* FROM "dakals" WHERE "dakals"."jadval_id" = ?[0m  [["jadval_id", 1]]
  Rendered jadvals/_dakal_fields.html.erb (7.2ms) [cache miss]
  Rendered jadvals/_dakal_fields.html.erb (6.8ms) [cache miss]
  Rendered jadvals/_form.html.erb (42.0ms) [cache miss]
  Rendered jadvals/edit.html.erb within layouts/application (43.8ms)
  Rendered layouts/partials/_topnavbar.html.erb (2.1ms) [cache miss]
  Rendered layouts/partials/_footer.html.erb (0.3ms) [cache miss]
Completed 200 OK in 139ms (Views: 135.5ms | ActiveRecord: 0.5ms)


Started PATCH "/jadvals/1" for 127.0.0.1 at 2018-06-24 12:27:11 +0430
Processing by JadvalsController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"vFWRLnnIP+KU5dFGDhuSmco5S3CbojBIQPuoINsacMZMVRrueYgA6qdE2vG7av264UdW0OzBoMuyyUCQO5QjHQ==", "jadval"=>{"gharardad_number"=>"3312e21", "mojavez_haml_number"=>"1e2e1212", "karfarma_name"=>"", "dakal"=>"", "site_addr"=>"", "site_code"=>"", "tahvildate"=>"", "dakals_attributes"=>{"0"=>{"name"=>"arman", "tedad"=>"22", "residshoodeh"=>"12", "_destroy"=>"false", "id"=>"1"}}, "shabloondate"=>"", "dakaldate"=>"", "resid"=>"0", "taghir_dakal"=>"", "taghir_site"=>"", "sadershode"=>"", "tayeedshode"=>"", "daryaft_pool"=>"0"}, "commit"=>"ثبت", "id"=>"1"}
  [1m[36mUser Load (0.2ms)[0m  [1m[34mSELECT  "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?[0m  [["id", 1], ["LIMIT", 1]]
  [1m[36mJadval Load (0.2ms)[0m  [1m[34mSELECT  "jadvals".* FROM "jadvals" WHERE "jadvals"."id" = ? LIMIT ?[0m  [["id", 1], ["LIMIT", 1]]
Unpermitted parameters: :tahvildate, :dakals_attributes, :shabloondate, :dakaldate, :sadershode, :tayeedshode
  [1m[35m (0.1ms)[0m  [1m[36mbegin transaction[0m
  [1m[35m (0.1ms)[0m  [1m[36mcommit transaction[0m
Redirected to http://localhost:3000/jadvals/1
Completed 302 Found in 7ms (ActiveRecord: 0.6ms)


Started GET "/jadvals/1" for 127.0.0.1 at 2018-06-24 12:27:11 +0430
Processing by JadvalsController#show as HTML
  Parameters: {"id"=>"1"}
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT  "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?[0m  [["id", 1], ["LIMIT", 1]]
  [1m[36mJadval Load (0.1ms)[0m  [1m[34mSELECT  "jadvals".* FROM "jadvals" WHERE "jadvals"."id" = ? LIMIT ?[0m  [["id", 1], ["LIMIT", 1]]
  Rendering jadvals/show.html.erb within layouts/application
  Rendered jadvals/show.html.erb within layouts/application (1.6ms)
  Rendered layouts/partials/_topnavbar.html.erb (2.9ms) [cache miss]
  Rendered layouts/partials/_footer.html.erb (0.4ms) [cache miss]
Completed 200 OK in 101ms (Views: 97.8ms | ActiveRecord: 0.3ms)


Started GET "/jadvals/1/edit" for 127.0.0.1 at 2018-06-24 12:27:18 +0430
Processing by JadvalsController#edit as HTML
  Parameters: {"id"=>"1"}
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT  "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?[0m  [["id", 1], ["LIMIT", 1]]
  [1m[36mJadval Load (0.1ms)[0m  [1m[34mSELECT  "jadvals".* FROM "jadvals" WHERE "jadvals"."id" = ? LIMIT ?[0m  [["id", 1], ["LIMIT", 1]]
  Rendering jadvals/edit.html.erb within layouts/application
  [1m[36mDakal Load (0.1ms)[0m  [1m[34mSELECT "dakals".* FROM "dakals" WHERE "dakals"."jadval_id" = ?[0m  [["jadval_id", 1]]
  Rendered jadvals/_dakal_fields.html.erb (6.2ms) [cache miss]
  Rendered jadvals/_dakal_fields.html.erb (5.7ms) [cache miss]
  Rendered jadvals/_form.html.erb (34.9ms) [cache miss]
  Rendered jadvals/edit.html.erb within layouts/application (36.7ms)
  Rendered layouts/partials/_topnavbar.html.erb (2.2ms) [cache miss]
  Rendered layouts/partials/_footer.html.erb (0.3ms) [cache miss]
Completed 200 OK in 137ms (Views: 133.3ms | ActiveRecord: 0.5ms)


```

**Comment by armanlearn** [comment]
dear mr @nathanvda  any idea !!?

**Comment by armanlearn** [comment]
int permitted attributes I change dakal_attributes: to dakals_attributes: now I can edit record that insert to database directly, steel have problem for new records!! any idea!!

**Comment by armanlearn** [comment]
should I write any jquery or javascript for my app to use cocoon?

**Comment by armanlearn** [comment]
it really make me crazy. it seems every things fine. there is no jQuery error
offffwww

**Comment by armanlearn** [comment]
when I change the value of records that I submit directly from data base , console output is like this

  Parameters: {"utf8"=>"✓", "authenticity_token"=>"wUdK3h2WstvjQ19SQ+m+Ij/mMR2znPDTB8poU+LhsMUmMKRn/YnjoeOj+WZNXkNb52ezqS7+UeqRvB+ZRu11hQ==", "jadval"=>{"gharardad_number"=>"7615376153276", "mojavez_haml_number"=>"187368136", "karfarma_name"=>"همراه اول", "site_addr"=>"تهران - دریاچه", "site_code"=>"۳۴۶۷", "tahvildate"=>"1397/04/03", "shabloondate"=>"1397/04/03", "dakaldate"=>"1397/04/03", "resid"=>"1", "taghir_dakal"=>"dsdsdf", "taghir_site"=>"sdfsdsfd", "sadershode"=>"1397/04/03", "tayeedshode"=>"1397/04/03", "daryaft_pool"=>"0"}, "commit"=>"ثبت", "id"=>"2"}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?  [["id", 1], ["LIMIT", 1]]
  Jadval Load (0.1ms)  SELECT  "jadvals".* FROM "jadvals" WHERE "jadvals"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
Unpermitted parameters: :tahvildate, :shabloondate, :dakaldate, :sadershode, :tayeedshode
   (0.1ms)  begin transaction
   (0.1ms)  commit transaction
Redirected to http://localhost:3000/jadvals/2
Completed 302 Found in 6ms (ActiveRecord: 0.5ms)


Started GET "/jadvals/2" for 127.0.0.1 at 2018-06-24 16:40:58 +0430
Processing by JadvalsController#show as HTML
  Parameters: {"id"=>"2"}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?  [["id", 1], ["LIMIT", 1]]
  Jadval Load (0.1ms)  SELECT  "jadvals".* FROM "jadvals" WHERE "jadvals"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
  Rendering jadvals/show.html.erb within layouts/application
  Rendered jadvals/show.html.erb within layouts/application (1.8ms)
  Rendered layouts/partials/_topnavbar.html.erb (1.8ms) [cache miss]
  Rendered layouts/partials/_footer.html.erb (0.2ms) [cache miss]
Completed 200 OK in 98ms (Views: 94.0ms | ActiveRecord: 0.4ms)


but when I add new button to a record that is not include any data from database (for this record I did not put nested value directly an this is new record) output is like this

`  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?  [["id", 1], ["LIMIT", 1]]
  Jadval Load (0.1ms)  SELECT  "jadvals".* FROM "jadvals" WHERE "jadvals"."id" = ? LIMIT ?  [["id", 5], ["LIMIT", 1]]
  Rendering jadvals/edit.html.erb within layouts/application
  Dakal Load (0.1ms)  SELECT "dakals".* FROM "dakals" WHERE "dakals"."jadval_id" = ?  [["jadval_id", 5]]
  Rendered jadvals/_dakal_fields.html.erb (5.7ms) [cache miss]
  Rendered jadvals/_form.html.erb (28.6ms) [cache miss]
  Rendered jadvals/edit.html.erb within layouts/application (30.6ms)
  Rendered layouts/partials/_topnavbar.html.erb (2.8ms) [cache miss]
  Rendered layouts/partials/_footer.html.erb (0.4ms) [cache miss]
Completed 200 OK in 146ms (Views: 142.0ms | ActiveRecord: 0.5ms)


Started PATCH "/jadvals/5" for 127.0.0.1 at 2018-06-24 16:47:13 +0430
Processing by JadvalsController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"uiyFLF5eWwMV4ikHPH7qQiQE0RdmCIR5pHBclbmv1DpKLA7sXh5kCyZDIrCJD4VhD3rMtxFrFPpWQrQlWSGH4Q==", "jadval"=>{"gharardad_number"=>"1010200", "mojavez_haml_number"=>"100200300", "karfarma_name"=>"آرمان عمادی", "site_addr"=>"نداریم", "site_code"=>"2002", "tahvildate"=>"1397/04/03", "shabloondate"=>"1397/04/03", "dakaldate"=>"1397/04/03", "resid"=>"0", "taghir_dakal"=>"", "taghir_site"=>"", "sadershode"=>"1397/04/03", "tayeedshode"=>"1397/04/03", "daryaft_pool"=>"0"}, "commit"=>"ثبت", "id"=>"5"}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?  [["id", 1], ["LIMIT", 1]]
  Jadval Load (0.1ms)  SELECT  "jadvals".* FROM "jadvals" WHERE "jadvals"."id" = ? LIMIT ?  [["id", 5], ["LIMIT", 1]]
Unpermitted parameters: :tahvildate, :shabloondate, :dakaldate, :sadershode, :tayeedshode
   (0.1ms)  begin transaction
   (0.0ms)  commit transaction
Redirected to http://localhost:3000/jadvals/5
Completed 302 Found in 5ms (ActiveRecord: 0.4ms)


Started GET "/jadvals/5" for 127.0.0.1 at 2018-06-24 16:47:13 +0430
Processing by JadvalsController#show as HTML
  Parameters: {"id"=>"5"}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?  [["id", 1], ["LIMIT", 1]]
  Jadval Load (0.2ms)  SELECT  "jadvals".* FROM "jadvals" WHERE "jadvals"."id" = ? LIMIT ?  [["id", 5], ["LIMIT", 1]]
  Rendering jadvals/show.html.erb within layouts/application
  Rendered jadvals/show.html.erb within layouts/application (1.3ms)
  Rendered layouts/partials/_topnavbar.html.erb (2.3ms) [cache miss]
  Rendered layouts/partials/_footer.html.erb (0.4ms) [cache miss]
Completed 200 OK in 97ms (Views: 92.8ms | ActiveRecord: 0.4ms)



`

it seems that nested attribute eliminated !!!

**Comment by armanlearn** [comment]
nested form params is not in sended params to controller

it is amazing that when I edid form nested form is in params but when I add new data it is not in params. did you see this before?



regards.

**Comment by nathanvda** [comment]
Ok, can you summarise what we have now: 

* now you can edit existing rows but not create new ones? 
* I do not seed anything in the logging for a create action (only patch which is editing an existing) 
* you fixed the `dakal_attributes` to `dakvals_attributes` 
* you added the `inverse_of:` option? (this will fail to create new nested items) 

Can you show the controller code for the `create` action? Can you show the log part for a `create` action (so we can see what is posted and which error you get).

**Comment by nathanvda** [comment]
Closed due to inactivity
