### ISSUE TITLE
Look up or create :has_many :through multiple from list

### ISSUE THREAD

**Issue by nrosella** [nathanvda/cocoon#513]
Following the demo code you've kindly provided I've been able to recreate a lookup or create `:has_many, through:` in my own app.

Currently you can either choose an existing `tag` from a list or create a new tag. I have the requirement to choose more than one existing `tag` _as well as_ creating a new `tag`. Right now even if the user clicks "or create a new tag" and also selects an existing `tag` only the new `tag` gets saved.

How could I implement this? I've been going around in circles and not achieving anything.

I hope the above makes sense.

Cheers

**Comment by nrosella** [comment]
Sure thing. [Right here](https://github.com/nathanvda/cocoon_simple_form_demo)

**Comment by Mirv** [comment]
So I think it worked for me.

Steps I took,
Cloned repo
Bundle install
Rails db:migrate
Ran server
Clicked new project, entered name
Clicked tags has_many, 
Clicked choose an existing tag (none), so had to create first tag, filled in name
Clicked create project
Clicked edit
Clicked tags
(At this point point I have an existing project, an existing tag to test against)

From here ...I click...
add tag, then select one create tag
add tag, select the already existing
update 

This works for me.

Next I made a brand new project, selected the existing tag first, then created one.

This also  worked.

So, both creating a new project & editing a project appear to be working for either order of creating or selecting tags.

My suggestion is clone the demo repo project & see if it works in the same way I've described (basically testing if it's the workstation/environment or maybe some instruction you missed).

**Comment by nrosella** [comment]
Thanks for taking the time to help with this.

Turns out I was mixing a little bit of outdated code from the [guide to doing nested model forms](https://github.com/nathanvda/cocoon/wiki/A-guide-to-doing-nested-model-forms#the-has_many-through-relation) with the project linked previously. Everything works fine now that I've updated my code to match the demo.

**Comment by Mirv** [comment]
Awesome, feel free to close this issue when you get a chance!
