### ISSUE TITLE
couldnt add class to input fields in partials 

### ISSUE THREAD

**Issue by thirugnanamal** [nathanvda/cocoon#519]
I am trying to add id/class to a input field (in partial). I am doing this for autocomplete( I am using typeahead.js), Whenever I use the extra class for typeahead I am not receiving the params in controller. I face the same issue when i try to add a class for bootstrap datepicker.

My partial : 
placed this inside "nested-fields" class. 

                                    <div class="row align-items-center">
                                      <div class="col-lg-3 col-12">
                                        <%= f.text_field :company, :class => 'form-control typeahead-company' %>
                                      </div>
                                      <%= link_to_remove_association "remove", f, :class => 'class="btn btn-styled btn-sm slate btn-base-1' %></div>

My index html.erb : 

    <div id='positions'>
                              <%= f.fields_for :positions do |position| %>
                              <%= render 'position_fields', :f => position %>
                              <% end %>
                              <div class='links'>
                                 <%= link_to_add_association 'add position', f, :positions, :class =>'btn btn-styled btn-xs permission btn-base-1' %>
                              </div>
                           </div>

All the things work fine regarding the associations, deleting, adding fields, partial rendering. The problem is that I don't get the params in my respective controller whenever I add the 'typeahead-company' / 'datepicker' class to the 'company' field. My typeahead/datepicker functionality is working fine though. I have tried adding the class using cocoon after insert event. Still the problem persists 

Any idea of why I am facing this?

**Comment by nathanvda** [comment]
It is a bit unclear, but I am guessing you mean: _after_ dynamically inserting a child-partial, the javascript does not work, but it does work if the child already exists? 

E.g. check issues #502 , #479, #451 

In short: on dynamically inserted HTML th typeahead/datepicker functionality will not be enabled and you will have to use the callbacks to explicitly enable that. E.g. do something like 

    $('form').on('cocoon:after-insert', function(e, insertedItem) {
        insertedItem.find('.datepicker').datepicker();
        insertedItem.find('.typeahead').typeahead(); 
    });

If I miss-interpreted your question, could you please elaborate what you expect to see and how cocoon affects that.

**Comment by thirugnanamal** [comment]
Hi nathanvda 

Thanks for the response. I mean to say that the javascript is working for absolutely fine when i add the class to text field  <%= f.text_field :company, :class => 'form-control  typeahead_company' %> without using the cocoon:after-insert . my javascript : 

$(document).ready(function(){
  $('.typeahead_company').typeahead(null, {
    name: 'education',
    display: 'company',
    hint: true,
    highlight: true,
    source: comPanies
  });

 But I dont receive params in my controller
  <%= f.text_field :company, :class => 'form-control ' %>
Params : 
"positions_attributes"=>{"0"=>{"position"=>"vs"}. There you see no params pertaining to the company field. 

This is when I have my field as  : <%= f.text_field :company, :class => 'form-control ' %>
Params : 
"positions_attributes"=>{"0"=>{"position"=>"vs", "company" => 'xyz'}. I can get the company param here. 

My javascript is working fine in front end. no issues about that

**Comment by nathanvda** [comment]
Could you please format your question/code. 

Are you using the `after-insert` callback at all? Can you show it? 

If you use the same javascript in the `document-ready` as is in the `after-insert` callback, I cannot explain why it would not work for dynamically added fields.

**Comment by nathanvda** [comment]
Closed due to inactivity.
