### ISSUE TITLE
Form only works after page refresh (rails 5.2, jquery 4.3.3, 

### ISSUE THREAD

**Issue by marchoeppner** [nathanvda/cocoon#520]
Hi,

new rails/cocoon user, so bare with me. I just installed rails, latest cocoon and jquery and noticed that (in development) my forms (or rather the submit button) will only work if I reload the page first. I read some stuff about this maybe being caused by turbolinks, or incomatible versions of jquery, or maybe not properly updating the application.js, or the application.html.erb.

`gem list --local

turbolinks (5.1.1)

rails (5.2.1, 5.2.0)

cocoon (1.2.11)

jquery-rails (4.3.3)

<snip>
`
Being a novice, I feel somewhat lost (and don't understand explanations involving actual javascript code..). Happy to post any and all code if that is useful, but it sounds like this is perhaps something more "general"?

My application.js:

```
//= require rails-ujs
//= require jquery_ujs
//= require jquery
//= require activestorage
//= require turbolinks
//= require_tree .
//= require cocoon
```
My application.html.erb

```
<head>
    <title>Phenogenomics</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
```
My application setup is as follows:

Project
- has many tasks
-- has many sub tasks

Which means I have a _form.html that allows adding tasks in _tasks_fields.html.erb, which then allows adding sub tasks through _subtasks_fields.html.erb.

Renders fine, but again, the submit button only works after page refresh. Any ideas?

**Comment by nathanvda** [comment]
So, to make sure I understand correctly: 

-  you can add nested items? (clicking the `link_to_add_association` link) 
- but you cannot submit the form? 

Cocoon does not change anything about the actual form handling, only the nested part. 

If only the submit fails, you might need to check if you have some code attached to it. At least cocoon does not interfere with that in any way. Maybe check if there are some errors in the javascript console (enter developer mode of your browser to find it).

**Comment by marchoeppner** [comment]
Right, so that throws:
```
Uncaught ReferenceError: jQuery is not defined
    at jquery_ujs.self-784a997f6726036b1993eb2217c9cb558e1cbb801c6da88105588c56f13b466a.js?body=1:555
```

**Comment by marchoeppner** [comment]
Which was fixed by moving jquery to the top of the application.js require list. Problem persists tho

**Comment by nathanvda** [comment]
You never explicitly confirmed, but I presume it is _only_ the submit that fails, right?

The reload seems to indicate a turbolinks problem. But not sure. 

Anyway, in your application.js you should not load `rails-ujs` and `jquery-ujs` both. In rails 5 you just need `rails-ujs` (which is no longer dependant on jquery). 

So something like this: 

```
//= require jquery
//= require turbolinks
//= require rails-ujs
//= require activestorage
//= require cocoon
//= require_tree .
```

I would load jquery and turbolinks first, and then the other stuff that might depend on it.

**Comment by marchoeppner** [comment]
So apparently this was a CSS issue, which I am still tracking down. Closing this for now - thanks!
