### ISSUE TITLE
Problem when edit a cocoon form.

### ISSUE THREAD

**Issue by ciromine** [nathanvda/cocoon#523]
hi it's me again jaja. 

I have another form with cocoon and it works perfectly but, when I edit the product and don't added or removed more nested attributes . But when edit de product magically more nested attributes was added.

The code is the following:

```
<%= f.fields_for :sale_dish_transactions do |sale_dish_transaction| %>
  <%= render 'sale_dish_transaction_fields', :f => sale_dish_transaction %>
<% end %>

<%= link_to_add_association 'Agregar Plato', f, :sale_dish_transactions, {:class => 'btn btn-success', :'data-association-insertion-method' => :append} %>
```

```
<div class="card nested-fields bg-light mb-3">
	<ul class="list-group list-group-flush">
  	<li class="list-group-item">
    	<div class="form-inline">
	    	<%= f.label :dish_id, :class => 'col-auto my-1' %>
    		<%= f.select(:dish_id, Dish.order(:id).map{ |c| [c.name, c.id] }, {}, { :class => 'custom-select mr-sm-2' }) %>
			</div> 
	  </li>
  </ul>
  <div class="card-body">
    <%= link_to_remove_association "Eliminar plato", f, :class => 'btn btn-danger' %>
  </div>
</div> 
```

I think is necessary to add, the ID of the nested attribute when I render the form, but I don't know how because I only have de :f but the variable :f doesn't contains the id of the attribute? How is the correct way to avoid this error?

I use Rails 5.1.6, Regards!

**Comment by nathanvda** [comment]
Please show the strong parameters definition in the controller (check the documentation how it should be set, you should include the `:id`). Please show the information that is posted to the controller. What does "magically more nested attributes are added" mean: they are duplicated?

**Comment by ciromine** [comment]
Sorry for my last explaination! Yes they are duplicated.

Now I put the code I have two nested attributes in this form. All of this is based in this example https://hackhands.com/building-has_many-model-relationship-form-cocoon/

The strong parameter of the Dishes Controller:
```
def safe_params
    params.require(:dish).permit(:name, :price, {store_ids: []}, quantities_attributes: [:id, :amount, :product_id, :_destroy])
  end
```

and the models:
Sales
```
class Sale < ApplicationRecord
  belongs_to :store

  has_many :sale_dish_transactions, inverse_of: :dish
  has_many :dishes, :through => :sale_dish_transactions
  accepts_nested_attributes_for :sale_dish_transactions, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :dishes

  has_many :sale_product_transactions, inverse_of: :product
  has_many :products, :through => :sale_product_transactions
  accepts_nested_attributes_for :sale_product_transactions, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :products
end

```

SaleDishTransaction Model
```
class SaleDishTransaction < ApplicationRecord
	belongs_to :sale
  belongs_to :dish

  accepts_nested_attributes_for :dish, reject_if: :all_blank, allow_destroy: true
end

```

Dish Model
```
class Dish < ApplicationRecord
  has_many :sales, through: :sale_dish_transactions
end
```

Regards!

**Comment by nathanvda** [comment]
You show me the strong parameters from the `DishesController` it seems? Yet we are looking at a form to create a `Sale` that has many `SaleDishTransaction` 's, right?

**Comment by ciromine** [comment]
Yes exactly!

the code is here:

```
def safe_params
    params.require(:dish).permit(:name, :price, {store_ids: []})
  end
```

thanks!

**Comment by nathanvda** [comment]
Mmmmmm. That is weird. It does not allow any nested params?? Please check the documentation how it should be specified.

**Comment by nathanvda** [comment]
Closed due to inactivity
