### ISSUE TITLE
Attempting nested form using join table

### ISSUE THREAD

**Issue by JCesana** [nathanvda/cocoon#526]
Hi there

Before I dive in, I just want to say I'm pretty new and just starting to learn development. I've been stuck on this for quite a while, and I honestly don't know who else to ask for guidance. That being said, I hope I can explain my issue clearly and concisely.... here goes.

I'm making a recipes web application. A recipe has many ingredients through a join table called recipe_ingredients. This table also has quantity and unit for when I display the recipe. 

I want each ingredient to be a master record, so that the ingredient is the same row that is used for each recipe it is in. Hence, the reason I have a join table. 

Github repo for reference: [rails-recipes](https://github.com/JCesana/rails-recipes)

MY QUESTION:

For my form, I want the quantity, unit, and ingredient to be grouped together so that each link_to_add_association will add all 3 fields at once. How can I get this to work? As of now, I only see the ingredient field (which functions correctly). The quantity and unit fields are not there at all.

My models:

```
class Recipe < ApplicationRecord
  belongs_to :user

  has_many :recipe_ingredients, inverse_of: :recipe
  has_many :ingredients, through: :recipe_ingredients

  has_many :directions, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :ingredients, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :directions, :reject_if => :all_blank, :allow_destroy => true

  validates :title, :description, presence: true

  has_one_attached :image
end
```

```
class RecipeIngredient < ApplicationRecord
  belongs_to :ingredient
  belongs_to :recipe

  # Do I need this??
  # accepts_nested_attributes_for :ingredient, :reject_if => :all_blank

  validates_uniqueness_of :recipe_id, :scope => :ingredient_id

  def recipe_line_detail
    "#{clean_number(self.quantity.to_f)} #{self.unit.pluralize(self.quantity.to_f)} #{self.ingredient.name}"
  end

  # only shows decimal if needed, otherwise integer
  def clean_number(num)
    "%.3g" % ("%.2f" % num)
  end

end
```

```
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients, inverse_of: :ingredient
  has_many :recipes, through: :recipe_ingredients

  validates :name, uniqueness: true

  accepts_nested_attributes_for :recipe_ingredients, :reject_if => :all_blank, :allow_destroy => true
end
```

```
My recipe controller:

class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :image_present?, only: [:create]

  def index
    @recipes = Recipe.all.order("created_at DESC")
  end

  def show
    @comment = Comment.new
    @comments = @recipe.comments.order("created_at DESC")
  end

  def new
    @recipe = current_user.recipes.build
    @recipe.ingredients.build
    @recipe.recipe_ingredients.build
    @recipe.directions.build
  end

  def create
    @recipe = current_user.recipes.build(title: recipe_params[:title])
    @recipe.description = recipe_params[:description]

    recipe_params[:ingredients_attributes].each do |key, value|
        ingredient_name = clean_up_ingredient_title(value)
        @recipe.ingredients << Ingredient.find_or_initialize_by(name: ingredient_name)
    end

    recipe_params[:directions_attributes].each do |key, value|
      @recipe.directions << Direction.new(step: value[:step])
    end

    @recipe.image.attach(recipe_params[:image])

    clean_up_recipe

    if @recipe.save
      redirect_to @recipe, notice: "Successfully created new recipe"
    else
      flash[:alert] = @recipe.error.full_messages
      render 'new'
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path, notice: "Successfully deleted recipe"
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :description, :image,
      ingredients_attributes: [:id, :name, :_destroy, recipe_ingredients_attributes: [:quantity, :unit, :_destroy] ],
      directions_attributes: [:step, :_destroy])
  end

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def clean_up_ingredient_title(ingredient_hash)
    ingredient_name = ingredient_hash[:name]
    ingredient_name.downcase!
    ingredient_name.strip!
    ingredient_name
  end

  def clean_up_recipe
    @recipe.title.strip!
    @recipe.description.strip!

    @recipe.directions.each do |direction|
      direction.step.strip!
    end
  end

  def image_present?
    if recipe_params[:image].nil?
      redirect_to new_recipe_path, alert: "Please upload an image with your recipe."
    end
  end

end
```

My form:

```
<%= form_for @recipe do |f| %>
  <%= render 'errors' %>

    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="field">
          <div class="control">
            <%= f.text_field :title, class: 'input is-large', placeholder: "Recipe Title" %><br /><br />
          </div>
        </div>
        <div class="field">
          <div class="control">
            <%= f.text_area :description, class: 'textarea', rows: 4, placeholder: "Recipe description..." %><br /><br />
          </div>
        </div>
        <div class="field">
          <div class="control">
            <div class="file">
              <label class="file-label">
                <%= f.file_field :image %>
                <!-- <span class="file-cta">
                  <span class="file-icon">
                    <i class="fas fa-upload"></i>
                  </span>
                  <span class="file-label">
                    Upload image…
                  </span>
                </span> -->
              </label>
            </div>

          </div>
        </div>

      </div>
    </div>

<div class="panel-body">

    <div class="row">
      <div class="column">
        <h3>Ingredients</h3>
        <div id="ingredients">
          <%= f.fields_for :ingredients do |ingredient| %>

              <div class="field">
                <%= render 'ingredient_fields', :f => ingredient %>
              </div>

          <% end %>

          <div class="links">
            <%= link_to_add_association 'Add Ingredient', f, :ingredients, class: 'button is-light' %>
          </div>
        </div>
      </div>
      <div class="column">
        <h3>Directions</h3>
        <div id="directions">
          <%= f.fields_for :directions do |direction| %>
            <%= render 'direction_fields', f: direction %>
          <% end %>
          <div class="links">
            <%= link_to_add_association "Add Step", f, :directions, class: "btn btn-default add-button" %>
          </div>
        </div>
      </div>



  </div>

  <%= f.button "Submit", class: "button is-primary", :disable_with => 'Please wait ...' %>
<% end %>

```

```
<div class="nested-fields field">
  <div class="field has-addons">
    <div class="control">
      <%= link_to_remove_association f, class: 'button is-info is-light' do %>
        <i class="fas fa-times"></i>
      <% end %>
    </div>
    <div class="control">
      <%= f.text_field :name, class: 'input', placeholder: 'Ingredient Name' %>

      <div id="recipe_ingredients">
        <%= f.fields_for :recipe_ingredients do |recipe_ingredient| %>
          <%= render 'recipe_ingredients', :f => recipe_ingredient %>
        <% end %>
      </div>
  </div>
</div>

```

```
<div class="nested-fields field">
  <div class="control">
      <%= f.text_field :quantity, class: 'input', placeholder: 'Qty' %>
      <%= f.text_field :unit, class: 'input', placeholder: 'unit(s)' %>
  </div>
</div>

```

I hope this all makes sense.

Before I tried to add the recipe_ingredient (quantity, unit) function, everything seemed to work fine. I cannot wrap my head around how to get the recipe_ingredients join table in to play in this form so that it works how I want it to.

Any help or guidance would be much much appreciated! Thanks!

**Comment by nathanvda** [comment]
Well: you first add the ingredient and then the recipe-ingredient, which seems the wrong way around. It might make more sense from UI/UX view, but you should just add the `recipe-ingredient` at once, which would make it a lot easier. 

Then I would allow to either use a dropdown to select an existing ingredient or create a new one (from the U). But I now see your code already does this in your controller-code (which seemed to be complex, since for a good nested form it can just be saved in one go). But it is also a very good/sensible approach. Advantages of using a drop-down list: because a user can select from a list  will make sure different spellings of ingredients 

So to show this in code: 

```
<h3>Ingredients</h3>
        <div id="ingredients">
          <%= f.fields_for :recipe_ingredients do |ingredient| %>

              <div class="field">
                <%= render 'recipe_ingredient_fields', :f => ingredient %>
              </div>

          <% end %>

          <div class="links">
            <%= link_to_add_association 'Add Ingredient', f, :recipe_ingredients, class: 'button is-light' %>
          </div>
        </div>
      </div>
```

And then in the `recipe_ingredient_fields` just let the user enter the string to look up or create the wanted ingredient. Does that make sense?  

Hints to make your code easier/more readable is to use haml and simple-form, because you have to type a lot less so there is less room for errors --but also read a lot less which helps _a lot_ in understanding code  (but this is obviously also a personal choice).

**Comment by JCesana** [comment]
Thanks so much for your help. 

I cleaned things up in my controllers and was able to get things to work how I wanted using a single strong params line, like in your demo. 

However, I'm unable to add all 3 fields at once in the view. I can only add recipe_ingredients (Quantity and Unit) with one add button, and an ingredient (name) with another add button. I'm going to leave it as is for now since I've put so much time in to this. 

Here's a quick [video demo](https://www.screenmailer.com/v/eG7a3hlJoNxPGdo) of the behavior I'm seeing. 

If you want to take a quick look at my code, I would love to be able to add all 3 fields with one link:

**_form**
```
<div id="ingredients">
     <%= f.fields_for :recipe_ingredients do |recipe_ingredient| %>
          <div class="field">
             <%= render 'recipe_ingredient_fields', f: recipe_ingredient %>
          </div>
     <% end %>
     <%= link_to_add_association 'Add Qty/Unit', f, :recipe_ingredients, class: 'button is-light' %>
</div>
```


**_recipe_ingredients_fields**
```
<div class="nested-fields field">
     <div class="field has-addons">
          <%= link_to_remove_association f, class: 'button is-info is-light' do %>
               <i class="fas fa-times"></i>
           <% end %>

          <div class="field">
               <%= f.text_field :quantity, placeholder: "Qty" %>
               <%= f.text_field :unit, placeholder: "Unit" %>
          </div>
          <div class="ingredient">
               <%= f.fields_for :ingredient do |ingredient| %>
                    <%= render 'ingredient_fields', f: ingredient %>
               <% end %>
          </div>
          <div class="links">
               <%= link_to_add_association 'Add Ingredient', f, :ingredient, class: 'button is-light' %>
          </div>
     </div>
</div>
```


**_ingredient_fields**
```
<div class="nested-fields">
    <div class="field">
         <div class="control">
              <%= f.text_field :name, placeholder: "Ingredient" %>
         </div>
     </div>
</div>
```

Thanks again for your time and guidance. You've helped me quite a bit. Wonderful job on this gem, too!

**Comment by nathanvda** [comment]
Ow that was not what I meant. So you start well: you add the `_recipe_ingredient` but then inside the recipe-organisation you should just fill in the name, like you did before, and then use that name to fnd or create the linked ingredient. 

> Note: this is not how I would generally do it, I would show a drop-down box to select an (existing) ingredient and allow to add a new one (if it did not exist before). But your solution is very intuitive albeit it might generate some data-polution (misspelled or differently spelled ingredients).

So in short something like: 

###_recipe_ingredients_fields

```
<div class="nested-fields field">
     <div class="field has-addons">
          <%= link_to_remove_association f, class: 'button is-info is-light' do %>
               <i class="fas fa-times"></i>
           <% end %>

          <div class="field">
               <%= f.text_field :quantity, placeholder: "Qty" %>
               <%= f.text_field :unit, placeholder: "Unit" %>
              <%= f.text_field :name, class: 'input', placeholder: 'Ingredient Name' %>
          </div>
     </div>
</div>
```

And then in the controller you can, as you did before, find the matching ingredient or create a new one. 

Is that clearer?

**Comment by JCesana** [comment]
Hi again. 

Yes that is very clear. I actually believe I tried this before without success. I tried it again just now and received the following error: 

**undefined method `name' for #<RecipeIngredient:0x007fa3318a9f68>**

![screen shot 2018-10-10 at 1 19 54 pm](https://user-images.githubusercontent.com/35906346/46763771-89421880-cc8f-11e8-9305-6cb40a91cd4a.png)

This is because the original form `fields_for` in **_form** is wrapped in a recipe_ingredient object, therefore there is no 'name' method - that is for ingredient. 

**_form**

```
 <div id="ingredients">
       <%= f.fields_for :recipe_ingredients do |recipe_ingredient| %>
            <div class="field">
                 <%= render 'recipe_ingredient_fields', f: recipe_ingredient %>
            </div>
       <% end %>
       <%= link_to_add_association 'Add Ingredient', f, :recipe_ingredients, class: 'button is-light' %>
  </div>
```

I'm not sure how to get around this issue. I feel  like I'm so close! :)

**Comment by nathanvda** [comment]
if you add a `attr_accessor :name` (or `:ingredient_name` is maybe more appropriate) to your recipe-ingredient, you should be able to use the field `:name` or `:ingredient_name` in the form, to then use that in the controller to look up the actual ingredient (or create it) and fill in the `ingredient_id`. Does that work/help/make sense?

**Comment by JCesana** [comment]
That did it!!! Finally everything works precisely how I imagined. I really appreciate you taking the time to help me out. Thanks!

**Comment by nathanvda** [comment]
Awesome work!! :+1: :+1: 🎉 🍰 🍾

**Comment by lukaszmarcinkowski** [comment]
Hi @JCesana and @nathanvda !
I know it is almost 2yrs since You did your job but maybe in some way You can refresh this topic and show us working code?:)
I trying to do the same as U did but with Products and Parts:)
I googled a lot of examples a did some but when I found your issue it looks the same as mine now:)

**Comment by nathanvda** [comment]
Hi @lukaszmarcinkowski your remark is not very helpful afaik, because a lot of code is shared here, we have fixed the problem, there is a lot of documentation in general, there is a [demo project](https://github.com/nathanvda/cocoon_simple_form_demo) containing a range of possible relation types.

But I can understand it is hard to map all those possible solutions to your own problem, definitely when you are starting or new to the problem. So I would suggest you open a new issue with your problem, or ask your question on stackoverflow (and share the link to your question here).

What helps to know is: what did you try (your code/relations/view) and what is not working.

**Comment by lukaszmarcinkowski** [comment]
Hi @nathanvda ,
Than You for your response and advices. I go with this example of @JCesana and I am trying to do almost the same.
I put my problem on [stackoverflow](https://stackoverflow.com/questions/63562411/simple-form-with-has-many-through-and-join-table/63632668#63632668).
I You would have some time to look on I will be grateful.
Regards
