### ISSUE TITLE
link_to_remove_association removes all nearby links and form fields.

### ISSUE THREAD

**Issue by mradeybee** [nathanvda/cocoon#529]
When I am on the edit view on my form and I click to remove one nested field, all nearby fields and links are removed from the form.

![cocoon-issue](https://user-images.githubusercontent.com/10416202/50059621-f7530200-014e-11e9-93aa-0cb382b8aaa1.gif)

Here is my code:
`_form.html.erb`
```
<fieldset class="fieldset-border">
  <legend class="fieldset-border">
    <% if new %>
      Add Plan
    <% else%>
      Edit Plan
    <% end %>
  </legend>

  <%= simple_form_for @plan, html: {class: 'form'} do |f| %>
    <div class='form-instruction'>Fields with * are required</div>
    <div class='form-instruction'>NOTE: Plan Name, Amount, Interval Count and Interval(Day/Week/Month/Year) can not be edited once created.</div>
    <%= f.text_field :name, class: 'full-input-text', placeholder: '* Plan Name', disabled: !new %>
    <%= f.text_field :amount, class: 'full-input-text', placeholder: '* Amount in cents', disabled: !new %>
    <%= f.text_field :interval_count, class: 'full-input-text', placeholder: '* Interval Count Eg: 1', disabled: !new %>
    <%= f.select :interval, ['Day', 'Week', 'Month', 'Year'],  {}, class: 'full-input-text', disabled: !new %>
    <%= f.text_field :trendships, class: 'full-input-text', placeholder: 'Number of Trendships' %>
    <%= f.text_field :additional_credit, class: 'full-input-text', placeholder: 'Addtional trendships cost in cents' %>
    <%= f.select :status, ['Active', 'Inactive'], {}, class: 'full-input-text' %>
    <div class='textarea-box'>
      <%= f.text_area :info, class: 'textarea', placeholder: 'Plan Info', rows: 5 %>
    </div>

    <p>
      <%= f.check_box(:recommended, class: 'check-box')  %>
      <%= f.label(:recommended) %>
    </p>

    <%= f.simple_fields_for :plan_benefits do |plan_benefit| %>
      <%= render 'plan_benefits', f: plan_benefit %>
    <% end %>

    <div class="links">
      <%= link_to_add_association 'Add Benefits', f, :plan_benefits, class: 'btn btn-outline-secondary pull-right' %>
    </div>

    <%= f.submit "Save", class: 'btn btn-primary' %>

    <div class='error-container'>
      <ul>
        <li><%= flash[:plan_error] %></li>
      </ul>
    </div>
  <% end %>
</fieldset>
```

`plan_benefit_fields.html.erb`

```
<div class='nested-fields' id ="nested-fields">
  <div class='field'>
    <%= f.text_field :details, class: 'full-input-text', placeholder: 'Eg. Featured on Trendship social media'%>
  <div>
  <p class='links'>
    <%= link_to_remove_association "Remove Benefit", f, class: 'btn btn-danger' %>
  </p>
</div>
```

Please what could I be doing wrong?

**Comment by nathanvda** [comment]
I can't be entirely sure, but the 

      <div class='nested-fields' id ="nested-fields">

should be at least 

      <div class='nested-fields'>

an `id` is ment to be unique on a page, and while the page will render it could behave unexpectedly. E.g. this would most likely affect the saving of the form. 

But nevertheless afaik this would not cause the effect we are seeing here. When clicking the `link_to_remove_association` the code will remove the nearest div with class `.nested-fields` so not sure why the save/add links would also disappear, unless you have some other error in the html?

**Comment by mradeybee** [comment]
@nathanvda I got it fixed, thanks to your observation about the HTML. The issue was with the ` <div class='field'>` and `<p class='links'>` in the nested partial. Once I removed those, it worked fine.

This issue can be closed, sorry for the false alarm.

**Comment by nathanvda** [comment]
Hi with your hint I saw it: in your code you wrote 

```
<div class='field'>
    <%= f.text_field :details, class: 'full-input-text', placeholder: 'Eg. Featured on Trendship social media'%>
  <div>
```

Notice the second `<div>` which should have been `</div>`. 

Can I suggest to take a look at haml or slim which really help in writing html that is always correct? I know it is not for everybody but for me it has proven a great help, because imho it makes my view code more readable and cleaner and will prevent me from mistakes like that. 

But you found and fixed it yourself! :+1: :+1: :+1:
