### ISSUE TITLE
Using EmojiArea with Coocon gem 

### ISSUE THREAD

**Issue by Rubioli** [nathanvda/cocoon#532]
First of all allow me to say, **THANK YOU** for this great gem. It has saved me so much time so many times. So I really appreciate your work and to make this great gem🥇 💯 

In my application, I have `messages` & `translations`. Everything works fine regarding nested forms and all, but this time I need to implement [EmojiArea](https://github.com/mervick/emojionearea).

This is my set up:

```
# _form.html.haml
= f.input :title, input_html: {class: 'emojioneArea'}
= f.input :body, input_html: {class: 'emojioneArea'}
#translations
  = f.simple_fields_for :translations do |translation|
    = render 'translation_fields', f: translation
  .link
    = link_to_add_association 'Add New', f, :translations

:javascript
  $(document).ready(function() {
    $(".emojioneArea").emojioneArea({
      emojiPlaceholder: ":smile_cat:",
      pickerPosition: "bottom",
      searchPosition: "bottom"
    });
  });

# _translation_fields.html.haml
.nested-fields
  = f.input :title input_html: {class: 'emojioneArea'}
  = f.input :body, as: :text, input_html: {class: 'emojioneArea'}
  = link_to_remove_association 'Remove', f

# MessagesController
def new
    @message.translations.build
end
```

This works fine for the inputs that are already added when the page is loaded (which is understandable because of `$(document).ready(function()`), but than **new** nested forms inputs doesn't get EmojiArea.

so I changed my `javascript` in `_form.html.haml` to:
```
:javascript
  $(document).ready(function() {
    $('#translations')
      .on('cocoon:after-insert', function() {
        $(".emojioneArea").emojioneArea({
          emojiPlaceholder: ":smile_cat:"
        });
      });
  });
```

Which adds the EmojiArea *after* a nested form is added but `inputs` that were added on the page load, doesn't have EmojiArea (which is again understandable because of `.on('cocoon:after-insert', function() `), BUT this makes the form to behave really strange. 

I wasn't sure how I could explain it so instead, I created a video/gif to give a better overview.
![cocoon](https://user-images.githubusercontent.com/16593596/50687081-370b5c00-1020-11e9-841c-46b3c8eda078.gif)

When I change my `javascript` to **(below)**, inputs will have the EmojiArea from start but, that strange behaviour still there.

```
:javascript
  $(document).ready(function() {
   $(".emojioneArea").emojioneArea({
      emojiPlaceholder: ":smile_cat:",
      pickerPosition: "bottom",
      searchPosition: "bottom"
    });
    $('#translations')
      .on('cocoon:after-insert', function() {
        $(".emojioneArea").emojioneArea({
          emojiPlaceholder: ":smile_cat:"
        });
      });
  });
```

Any feedback and help are much appreciated and thanks in advance!

**Comment by nathanvda** [comment]
Thank you for your detailed question :clap: :clap: :+1:  

Now you already do everything near perfectly, as far as cocoon is related imho. The only thing I can imagine, which could explain maybe strange behaviour, is if the emoji-picker acts strange when it is "enabled" multiple times. 

So an easy fix for that would be: 

```
:javascript
  $(document).ready(function() {
   $(".emojioneArea").emojioneArea({
      emojiPlaceholder: ":smile_cat:",
      pickerPosition: "bottom",
      searchPosition: "bottom"
    });
    $('#translations')
      .on('cocoon:after-insert', function(e, s) {
        s.find(".emojioneArea").emojioneArea({
          emojiPlaceholder: ":smile_cat:"
        });
      });
  });
```

This will only enable the emojioneArea inside the newly inserted nested item (after the insert).  

But if this does not help, I am afraid this not an issue for the emoji-picker you are using. I have no idea what the normal behaviour is for the plugin, and  I cannot see how I can help other then start to investigate the emoji-picker plugin you are using.

**Comment by Rubioli** [comment]
YOU ARE THE MAN @nathanvda 🥇 This did the trick. You just made my Friday :)

Thanks a lot for your help 👍
