### ISSUE TITLE
Self-referential form infinite loop even with force_non_association_create = true

### ISSUE THREAD

**Issue by davismattg** [nathanvda/cocoon#533]
Using Cocoon 1.2.11 and Rails 5.1.6, I have the following relationship:
```
class Group < ApplicationRecord
  belongs_to :parent_group, class_name: 'Group', optional: true
  has_many :sub_groups, class_name: 'Group', foreign_key: 'parent_group_id', dependent: :destroy
  accepts_nested_attributes_for :sub_groups, allow_destroy: true
end
```

I want to be able to add an arbitrary number of `sub_groups` both from within a `Group`, and within a `sub_group`. My form to add `sub_groups` from the `group_fields.html.haml` partial works fine. The issue is when I try to add `sub_groups` from within the `sub_group_fields.html.haml` partial. 

I have read about the `force_non_association_create` argument for `link_to_add_association` which I think should be doing what I need, but even with it set to `true` I get an infinite loop for the following:
```
# groups/sub_group_fields.html.haml
  .sub_groups_list
    = f.fields_for :sub_groups do |ffff|
      = render 'groups/sub_group_fields', f: ffff
    .add_sub_groups
      = link_to_add_association 'Add Subgroup', f, :sub_groups, { partial: 'groups/sub_group_fields', force_non_association_create: true, render_options: { locals: {parent_model_name: parent_model_name} }, class: 'btn btn-default' }
```

Am I misinterpreting the `force_non_association_create` argument or does this look like an issue?

**Comment by nathanvda** [comment]
So every `link_to_add_association` will pre-render the partial on the server-side, if each partial itself contains the same `link_to_add_association` again, this will create an infinite loop. 

The solution to this is either limit the maximum allowed nested levels. This is demonstrated here: https://github.com/nathanvda/cocoon-self_join-form

If, however, you require an unlimited nested level, cocoon is not the right solution for you. You will then have to resort to using something like xhr/js. 

Related issues: #408 and #96

**Comment by davismattg** [comment]
Thanks for the quick reply, Nathan. What you say makes sense, but then what is the point of the `force_non_association_create` argument?

**Comment by nathanvda** [comment]
As stated in the documentation, mainly for backwards compatibility (it is no longer relevant for this specific case), and _maybe_ sometimes you really do not want to create the object on the association, for whatever reason (e.g. overrule default values).
