### ISSUE TITLE
No console error but when i click on remove button is not working

### ISSUE THREAD

**Issue by CloudMaster-Manoj** [nathanvda/cocoon#541]
When i click link to remove button it just adds '#'  the url and nothing else is happening . Do i need to write any Jquery ? or am i missing something ?

**Comment by Mirv** [comment]
It kind of sounds like you started to already - did you check out this example project?

https://github.com/nathanvda/cocoon_simple_form_demo/blob/master/app/assets/javascripts/projects.js

Something like ... 

```
$(document).ready(function() {
    $("#owner a.add_fields"). data("association-insertion-position", 'before').data("association-insertion-node", 'this');
  ...
```

Or from my project when I was first hacking away at cocoon ...

```
   $(document).on('cocoon:before-insert', 'form', function(e,field_to_be_added) {
     e.stopPropagation();
     field_to_be_added.fadeIn('slow');
   });
```

**Comment by nathanvda** [comment]
A bit hard to deduce if @CloudMaster-Manoj writes so little information, but I see a few main reasons:

- either the cocoon.js is not included correctly (but then the add link would also not work)
- you have some error in your js (but then you would have an error in the console --but _before_ clicking the link)
- your nested child partial is not wrapped inside a div with class `.nested-fields` (but you can use any wrapper class, but you have to specify it in the `link_to_remove_association` --see [documentation](https://github.com/nathanvda/cocoon#link_to_remove_association))

**Comment by nathanvda** [comment]
Closed due to inactivity.
