### ISSUE TITLE
The add_association link only copies the form

### ISSUE THREAD

**Issue by Kutomore** [nathanvda/cocoon#556]
I don't know if it's intended, and if so I'm sorry to bother, but it seems to me that when I click the `link_to_add_association` the js copies and pastes the same html form, which makes it so all the nested_attributes share a single array index.

For example. I have an Order, which has many Frames, this frame has an attribute called `type_of_frame`. If i'm not mistaken then, if I have two Frames inside my order the fields should be both `order[frames_attributes][0][type_of_frame]` and `order[frames_attributes][1][type_of_frame]`. But what seems to be happening is the javascript simply creates both forms with the same index, so both of them are `order[frames_attributes][0][type_of_frame]`, this makes it so only one of the nested_forms is saved.

Am I configuring something wrong?

**Comment by nathanvda** [comment]
Can you show us some code? Are those form-names `order[frames_atrributes][0][type_of_frame]` actually copied from the html, because the behaviour should be as follows: 

* either the id exists, and then it should use the `id` of the item 
* when inserting new items using `link_to_add_association` I calculate a new, unexisting id, so rails will know to generate a new child 

You are correct that the partial to be inserted is rendered server-side, but the id's are replaced upon insertion. You could verify this easily by inspecting the js code.

Usually the reason why posting several new items and only one gets saved is having html id's for repeating elements (e.g. using something like `#type_of_frame` instead of `.type_of_frame` --because a HTML id is semantically only allowed to occur once on a page, and while the page will render correctly, upon composing the form data it will not). You can easily verify this by checking your logfile to see what is posted to the server.  

So please show us 

* some view-code so we can think further. 
* if the HTML is not what you expect, post a screenshot/copy from the browser inspect tool after adding a new nested item 
* what parameters are posted to the server 
* what is your strong parameters definition

**Comment by Kutomore** [comment]
Hey, thanks for the quick response, let me provide you with some background then. I have a Order, that Order has one or more frames, that frame belongs_to a image.

I build this on my controller as `@order.frames.build.build_image`

Then I have the following view as my _form.
```
<div class="col-md-8 card centered">
    <div id="frames-form">
      <%= form.fields_for :frames do |frames_form| %>
        <%=link_to_add_association 'Add Frame',
                                   form,
                                   :frames,
                                   class: 'button btn btn-primary col-md-12',
                                   partial: 'frames_form',
                                   render_options: {
                                       locals: {
                                           frames_form: frames_form
                                       },
                                   } %>
        <%=render partial: 'frames_form', locals: {frames_form: frames_form} %>
      <% end %>
    </div>
    <div class="actions form-group col-md-5">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>
```

I've ommited the Order fields that are not related to the frames in order to make it smaller. This view render the partial 'frames_form', which is poorly named and I plan to change it in the future, the partial looks like this:

```
<fieldset>
  <legend class="col-md-4 control-label"><strong>Quadro:</strong></legend>
  <div class="form-group">
    <%= frames_form.label :type_of_frame, class: "col-md-4 control-label" %>
    <div class="col-md-12">
      <%= frames_form.select :type_of_frame, options_for_enum(Frame.new, :type_of_frame), {}, {class: 'form-control'} %>
    </div>
  </div>
  <div class="form-group">
    <%= frames_form.label :frame_status, class: "col-md-4 control-label" %>
    <div class="col-md-12">
      <%= frames_form.select :frame_status, options_for_enum(Frame.new, :frame_status), {}, {class: 'form-control'} %>
    </div>
  </div>
  <div class="form-group">
    <%= frames_form.label :is_broken, class: "col-md-3 control-label" %>
    <%=frames_form.check_box :is_broken %>
  </div>
  <div class="form-group">
    <%= frames_form.label :frame_value, class: "col-md-4 control-label" %>
    <div class="col-md-12">
      <%= frames_form.text_field :frame_value %>
    </div>
  </div>
  <div class="col-md-6 control-label">
    <button type="button" class="btn btn-secondary button-to-add-image" data-toggle="modal" data-target="#image-modal">
      Add Image
    </button>
  </div>
</fieldset>
<br>
<div class="modal fade" id="image-modal" tabindex="-1" role="dialog" aria-labelledby="image-modal-label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="image-modal-label">Add Image</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= frames_form.fields_for :image do |image_form| %>
          <%=render partial: 'image_form', locals: {image_form: image_form} %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
```
Which has all the necessary attributes for a Frame, and also has a button that opens a modal with a form for the frame image. Said modal renders the following form:

```
<div class="image-form">
  <label>Adicione uma nova imagem</label>
  <div class="field">
    <%= image_form.label :description %>
    <%= image_form.text_field :description %>
  </div>
  <div class="field">
    <%= image_form.label :art %>
    <%= image_form.file_field :art %>
  </div>
</div>
```

These are all the relevant views. By going in the application and testing it manually, by adding a single extra frame to the one that's added by default I can see that the type_of_frame field in both forms looks the same:
![image](https://user-images.githubusercontent.com/19594428/59939011-f87e2800-942c-11e9-97a9-2aba678eb1fe.png)
![image](https://user-images.githubusercontent.com/19594428/59939035-09c73480-942d-11e9-9c7f-ea19fd115f11.png)

Not only those but no matter how many I create all the fields use the same array index, 0. Also, about the modal, I don't expect the gem to handle it by itself when it comes to opening the modal, I'll handle it by catching the event and editing the modal.

**Comment by nathanvda** [comment]
Mmmmm you do something weird: 

* you only render the `link_to_add_association` inside the `fields_for` loop (there will be no button to add if there is not an item already?)
* you explicitly hand the existing frame using the `frames_form` variable, why? 

Maybe that is caused because you had to read haml (which is imho much clearer, but if you are not used to it). 
Did you find the ERB examples in the wiki:  https://github.com/nathanvda/cocoon/wiki/ERB-examples

**Comment by Kutomore** [comment]
> you only render the link_to_add_association inside the fields_for loop (there will be no button to add if there is not an item already?)

Well, I only do it because I need to pass the local, If I were to do something like:
```
    <div id="frames-form">
      <%= form.fields_for :frames do |frames_form| %>
        <%=render partial: 'frames_form', locals: {frames_form: frames_form} %>
      <% end %>
    </div>
    <%=link_to_add_association 'Add Frame',
                               form,
                               :frames,
                               class: 'button btn btn-primary col-md-12 add_nested_fields',
                               partial: 'frames_form',
                               render_options: {
                                   locals: {
                                       frames_form: frames_form
                                   },
                               } %>
```

It would throw an error because the variable frames form only exists inside the loop. If I do try and make it equal the link you provided, like:

```
<div id="frames-form">
      <%= form.fields_for :frames do |frame| %>
        <%=render 'frame_fields', form: frame %>
      <% end %>
      <%=link_to_add_association 'Add Frame', form, :frames %>
</div>
```
Which lets the link outside the fields_for loop, I get an error `undefined local variable or method `form' for` when trying to open the page. Which leads me to believe the form is not beign sent, If I do explictly send the form variable with the locals like:

```
<%=link_to_add_association 'Add Frame', form, :frames,
                                 render_options: {
                                     locals: {
                                         form: form
                                     }
                                 }
      %>
```

Then I get `undefined method `type_of_frame' for #<Order:0x00007efc6f33d4d0>`, which shows me that the form that I'm sending as the local is the OrderForm, not the FrameForm

**Comment by nathanvda** [comment]
Not sure if that would remove your problem, but it would work better if you just did this: 

```
    <div id="frames-form">
      <%= form.fields_for :frames do |frames_form| %>
        <%=render 'frames_form', frames_form: frames_form %>
      <% end %>
      <%=link_to_add_association 'Add Frame',
                                   form,
                                   :frames,
                                   class: 'button btn btn-primary col-md-12',
                                   partial: 'frames_form',
                                   form_name: 'frames_form' 
                              %>
    </div>
```

The `link_to_add_association` will generate a new object on the association and render the partial and by default (check the examples --did you get a simple example running?) it will use `f` as the form-name, but since you use `frames_form`, you just have to specify that.

**Comment by Kutomore** [comment]
Oh, It actually works now, It seems that the issue was that I wasn't specifying the form_name. Welp that's great then. Thanks man.
