### ISSUE TITLE
Client side validations

### ISSUE THREAD

**Issue by link-er** [nathanvda/cocoon#56]
Hello
I'm using client_side_validations(3.2.0.beta.3) and client_side_validations-formtastic (2.0.0.beta.3) (https://github.com/bcardarella/client_side_validations)
On the form I have nested fields that is added with help of the cocoon gem and validations throw an error 'validators is undefined'
Can you help please?

**Comment by jmarceli** [comment]
IMO it is the problem with `client-side-validations` gem not with the `cocoon`. If anyone would like to see my workaround it is described here: http://stackoverflow.com/questions/13329248/client-side-validations-on-nested-field-not-generate-valiadtion/29490646#29490646

**Comment by nathanvda** [comment]
Thanks @jmarceli. Now I can close the ticket.

**Comment by joshleitzel** [comment]
I'm not seeing the OP's error but I am seeing that nested fields added by cocoon to the DOM don't validate with the `client_side_validations` gem. Using the callback as @nathanvda suggested above does seem to work in the most recent versions of the gems:

```coffeescript
$('body').on 'cocoon:after-insert', (event, insertion) ->
  insertion.closest('form').validate()
```

Now when the user submits the form the validations trigger correctly for the cocoon-added elements.
