### ISSUE TITLE
Undefined method 'new_record' for nil:NilClass

### ISSUE THREAD

**Issue by frankkdrebin** [nathanvda/cocoon#563]
Hello, 

like a lot of people that posted issues in here, i read a lot about this issue and what could cause the error but im not able to see what is wrong, i even see my code as the one from the examples but it is clear it is not the same. Im getting this 'undefined method new_record' error, which i read is because is trying to delete something is not there, right? Okay, if i delete this remove_association, i get this error:

Association comments doesn't exist on Comment

which is driving me crazy. Here is my code.

Comment model:

`class Comment < ApplicationRecord
  belongs_to :article, inverse_of: :comments
end
`

Article model

```
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy, inverse_of: :article
  accepts_nested_attributes_for :comments, reject_if: :all_blank, allow_destroy: true
  validates :title, presence: true,
                    length: { minimum: 5 }

end

```
_comment_fields

```
<div class="nested-fields">
  <p>
    <strong>Commenter:</strong>
    <%= form.input :commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= form.input :body %>
  </p>
  <p>
  </p>
</div>
```

show form

```
<%= simple_form_for([@article,@article.comments.build], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <div id='comments'>
    <%= form.simple_fields_for :comments do |comment| %>
      <%= render 'comments/comment_fields', :form => comment %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'add comentario', form, :comments %>
    </div>
  </div>
  <p>
    <%= form.submit %>
  </p>
<% end %>
```
Im not very sure about the part `[@article,@article.comments.build]` since im already doing that in the new method in the controller, but i think this is not giving the error.

And my ArticlesController

```
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
    @article.comments.build
  end

  private
    def article_params
      params.require(:article).permit(:title, :text, comments_attributes: [:id, :commenter, :body, :_destroy])
    end
end
```

Sorry about asking about this error but i dont find the solution, and ive been reading the docs and issues of other people for a while. thank you in advance.

**Comment by nathanvda** [comment]
Just a quick guess: why don't you write `simple_form_for @article, local: true do |f|` ? 

If that does not help: which line is giving you the error, because that is most of the times also a big clue 😛

**Comment by frankkdrebin** [comment]
If i change that, it tells me `undefined method 'commenter' in line 28 from show.html.erb

`<%= form.text_field :commenter %>`

I dont understand this. It says undefined method commenter on line 28 but the same :commenter is on line 27? Thank you for your answers, im having a hard time fixing this lol

**Comment by nathanvda** [comment]
Do  you have the `:commenter` field on both the article and the comment, that seems a bit weird?

**Comment by nathanvda** [comment]
You are building a form to edit/create an article, and the comments at the same time, right? (although that also seems a bit weird haha --normally the author of an article is not the person adding a comment, but I guess this is just an example or maybe simplified code --always weird to reason about some anonymous code-sample).

**Comment by frankkdrebin** [comment]
Im basically following the starter guide for rails:

https://guides.rubyonrails.org/getting_started.html

So i just did everything that is there. I dont know what you mean with having the :commenter field on both article and comment, i defined it only comment. Sorry if im sound like a total noob, but thats what i am right now haha my intention whats just to test this gem in this example, so i can be able to have more than 1 comment field, which i know doesnt make sense, the whole purpose of this its to just make the gem so i can understand it and use it in my project, which will have more complex associations. thank you for your time, really appreaciated.

[
![rails](https://user-images.githubusercontent.com/53220018/62771726-c9cc1780-ba95-11e9-8afb-169e38c4518a.png)
](url)

**Comment by nathanvda** [comment]
Well I can only know what you are showing me, but afaik your form now looks like this: 

```
<%= simple_form_for([@article,@article.comments.build], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <div id='comments'>
    <%= form.simple_fields_for :comments do |comment| %>
...
```

The first field inside the article form is the `commenter` column, which you now said (as I asked) is not defined on article. I thought me asking that question would make clear that that is why you are getting the error?

**Comment by frankkdrebin** [comment]
yes, but that only fails if i erase @article.comments.build, i left it as it is as the guide i was following tell us to do this, but i still get the error:

`Association comments doesnt exist on Comment`

The first part of the form you are telling me is part of the getting started guide in the ruby page, so that is not the problem, as i erased it and the problem persists. 

So i was thinking, in your cocoon example, your form is in a partial, but mine it is not, its a normal view (show.html.erb), maybe this is a problem?

**Comment by nathanvda** [comment]
Ok. I think now I get the confusion. 

Either you build a form for a single comment, and then you use 

     simple_form [@article, @article.comments.build]

which will post to a nested route under the given article. But in that case you do not need cocoon, you just open a form to add a single comment. This makes sense. But: do comments have nested comments? From what you showed in your question, it does not? So: no need for cocoon.

Or you have a form for an article, with nested comments, and then you can use cocoon. And your form would look like 

     simple_form_for @article 

and the `@article` has the association to `comments`.

But not sure if that makes sense because that would mean that the author of an article would be adding comments?? but maybe for testing/learning purposes I can imagine :shrug: . 

So you have to think more clearly about what you are trying to achieve and how. 

If that is clear to you, and still not working, could you then please show me the _current code_ and the errors you encounter. You show me code, which you now say you no longer use, you point me to a guide which has no reference to cocoon, so that makes it very hard for me when you make remarks what you are referring to. I get that you see your code before you, and you know what you are doing and trying to achieve, but I can only guess.

**Comment by frankkdrebin** [comment]
Okay so as i said my goal was to understand cocoon, i wanted just to be able to add fields dynamically in a form. As i am new, i thought the best would be to follow the ruby started guide and then, with that guide done, trying to implement cocoon in the example.

I know it makes no sense to have multiple comment fields since you write one comment, post it, then create another, not need to have 3 fields at the same time, but i didnt think about that, i just wanted to make it work.

so yes, i want an article with nested comments, which also doesnt make sense since the author is posting comments but like i said this is just for testing.

Okay so i fixed the errors, which is a big step for me since ive been getting these errors for the past 2 days, but the link work work, when i click "add comment" it doesnt do anything, the same with remove comment. It doesnt give me error either, it just stays there. So what fixed this was adding this line:

`<%= link_to_add_association 'add comentario', form, :comments, partial: 'comments/comment_fields', form_name: 'form' %>`

Thank you again for taking your time to answer and sorry about the confusions. I know yo dont see all the code and is difficult to guess whats happening but i didndt want to paste here a lot of code, i think i paste the important things, if there is any other file you want to see just tell me but i think with these is okay.

**Comment by nathanvda** [comment]
So if I understand correctly you got it to work to your satisfaction, right? Awesome work :clap: :clap: :+1: 👍

**Comment by frankkdrebin** [comment]
More or less, i got rid of those errors which is important, but when clickin the link_to_add_association y doesnt add anything, but thats another problem i hope i can resolve by myself, if not i hope you dont mind maybe asking around here. Thank you again!

**Comment by nathanvda** [comment]
Ah I thought you fixed that by specifying the correct path to the partial. In general I place the `_comments.html.haml` partial in the `articles` folder, because that is the context in which it is used, but if the partial is shared (one could comment on a lot of things) it definitely makes sense to place in a shared folder. 

Probably too obvious: but did you include the `cocoon.js` in the `application.js` ? Because that would be a first candidate to look if your js is not doing anything. Secondly, check errors in your browsers javascript console (if there is some error in the javascript it blocks further js processing).

**Comment by frankkdrebin** [comment]
I wrote "the link work work" when it was "the link wont work" so maybe thats why you thought that hahaha

Yes i included cocoon in the application.js, as it says in the cocoon github. Looking at the console i saw this error
![cocoon_error](https://user-images.githubusercontent.com/53220018/62777928-db69eb00-baa6-11e9-981c-4984ac652c19.png)

which points to this part of the code:

![jqeury_error](https://user-images.githubusercontent.com/53220018/62778006-13712e00-baa7-11e9-971e-e0555299c17e.png)

**Comment by nathanvda** [comment]
Yes, `jQuery` is (still) a prerequisite of this gem. You will have to include it in your project if you want to use cocoon. I am guessing you googled it by now, but an easy way is to use the [jquery-rails gem](https://github.com/rails/jquery-rails)

**Comment by frankkdrebin** [comment]
Okay, i finally did it, im able to add more nested comments although it doesnt make sense hahaha

Im closing this, thank you very much nathan!!

**Comment by nathanvda** [comment]
Woooot awesome! :clap: :clap: :+1: :+1:
