### ISSUE TITLE
Clarification on Array Fields

### ISSUE THREAD

**Issue by vpfaulkner** [nathanvda/cocoon#568]
Hello!

I am confused about how to support array attributes. Let's say I have simple `urls` array field on `users` like so:
```
  create_table "users", force: :cascade do |t|
    t.text "urls", default: [], array: true
  end
```

From searching the issues, it appears I need to define a `build_url` field on the `User` model? Is that correct? What else would I need to do? Or is there a simple example somewhere for this?

**Comment by gasperhafner** [comment]
hm if I understand you correctly you are having an issue saving urls?
in your controller, in permit method urls has to be at the end.. I hope this helps you?

my example:

```
def change
    create_table :timeslots_configs do |t|
      t.references :area, foreign_key: true
      t.integer :address_type
      t.integer :from_hour
      t.integer :to_hour
      t.integer :days, array: true
      t.boolean :green

      t.timestamps
    end

def area_params
    params
      .require(:area)
      .permit(:name, :timezone, timeslots_configs_attributes: [
        :id,
        :address_type,
        :from_hour,
        :to_hour,
        :green,
        :_destroy,
        days: []
      ])
  end
```

**Comment by anaulin** [comment]
@vpfaulkner (blast from the past!) did you ever figure this out?

I am struggling to get Cocoon working with an Array field that does not contain models (which seems to be the assumption in https://github.com/nathanvda/cocoon/pull/90). It is possible at all to use Cocoon with such fields?

After defining the methods `build_<association_singular>` and `build_<association_plural>` I get the error:
```
undefined method `reflect_on_association' for Array:Class
```

**Comment by anaulin** [comment]
I figured this out, and my problem above had to do with my partials not being named correctly in the scheme that Cocoon expects. 🤦🏼 

Although it does seem like I'll have to roll my own "remove" links, since Cocoon's version doesn't fully remove the nested elements from the form.

**Comment by nathanvda** [comment]
@anaulin the remove links should work, so please open a new ticket, and give a little more information (show your view code).

I will close this one since @gasperhafner answered it for the OP.
