### ISSUE TITLE
Undefined method 'new_record' for nil:NilClass with Administrate and Globalize

### ISSUE THREAD

**Issue by sedubois** [nathanvda/cocoon#569]
As reported [here](https://github.com/nickcharlton/administrate-field-nested_has_many/issues/1#issuecomment-545326143), I did not manage to make nested forms work when combining Administrate with Globalize and `administrate-field-nested_has_many`, which itself makes use of Cocoon. Nested forms are required to e.g create a `Post` and its `Post::Translation`s in one go, otherwise one needs to create a `Post`, then navigate to the translation creation form and create translations separately afterwards.

When trying to load the creation form (URL http://localhost:3000/admin/posts/new) I get the error `undefined method 'new_record?' for nil:NilClass`, which is thrown at [`cocoon (1.2.14) lib/cocoon/view_helpers.rb:29`](https://github.com/nathanvda/cocoon/blob/master/lib/cocoon/view_helpers.rb#L29).

I use Rails 5.2.3 + Globalize 5.3.0 + Adminstrate 0.12.0 + administrate-field-nested_has_many 1.1.0 + cocoon 1.2.14 with the administrate config below. Would anyone have an idea?

```rb
# db/schema.rb
ActiveRecord::Schema.define(version: XXX) do
  create_table "posts", force: :cascade do |t|
    ...
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
  create_table "post_translations", force: :cascade do |t|
    t.integer "post_id", null: false
    t.string "locale", null: false
    t.string "title", null: false
    t.text "content", null: false
    ...
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["locale"], name: "index_post_translations_on_locale"
    t.index ["post_id"], name: "index_post_translations_on_post_id"
  end
end

# app/models/post.rb
class Post < ApplicationRecord
  translates :title, :content, ..., versioning: :paper_trail
  accepts_nested_attributes_for :translations, allow_destroy: true
  ...
end

# app/dashboards/post_dashboard.rb
class PostDashboard < Administrate::BaseDashboard
  ATTRIBUTE_TYPES = {
    translations: Field::NestedHasMany.with_options(class_name: "Post::Translation"),
    ...
  }
  FORM_ATTRIBUTES = %i[
    translations
    ...
  ]
end

# app/dashboards/post/translation_dashboard.rb
class Post::TranslationDashboard < Administrate::BaseDashboard
  ATTRIBUTE_TYPES = {
    id: Field::Number,
    post_id: Field::Number,
    globalized_model: Field::BelongsTo.with_options(class_name: "Post"),
    ...
  ]
  FORM_ATTRIBUTES = %i[
  post_id
  ...
  ]
end
```

**Comment by nathanvda** [comment]
Very hard for me, as I have no knowledge of the libraries  you mention _using_ cocoon. 

I have no idea how the `has_many :translations` is defined, if it is of class `Post::Translation`? if there is an error in the adminstrate configuration?

**Comment by sedubois** [comment]
My understanding is that `translates ...` calls [this Globalize code](https://github.com/globalize/globalize/blob/8f1e84942a1bbe4e77ae2ce87450c43eb447bbaa/lib/globalize/active_record/act_macro.rb#L98-L103):

```rb
        has_many :translations, :class_name  => translation_class.name,
                                :foreign_key => options[:foreign_key],
                                :dependent   => :destroy,
                                :extend      => HasManyExtensions,
                                :autosave    => false,
                                :inverse_of  => :globalized_model
```

The debugger shows that `translation_class` is a `Post::Translation`, and `options[:foreign_key]` is `"post_id"`.

**Comment by sedubois** [comment]
The error is raised in Cocoon's `link_to_remove_association`, which is called in [this view](https://github.com/nickcharlton/administrate-field-nested_has_many/blob/master/app/views/fields/nested_has_many/_fields.html.erb#L8) and gets passed an argument `f`, with the debugger showing that it is of type `ActionView::Helpers::FormBuilder` and indeed, its `object` attribute is nil. I do not know what is supposed to set this object.

**Comment by nathanvda** [comment]
Normally there is a `fields_for` call, which gets the handle to an association and then it iterates over the association (setting `f.object`). However, if the the handle does not point to an association, the will just act as a "name" to group fields together and there will be no `f.object` set. 

Not sure if that is clear? The name of a field inside a `fields_for` get prefixed/nested with the name of the association, but you can also use it to "group" fields together, e.g. something like 

       f.fields_for :symbolic_grouping do |f| 
           f.text_field :name 
           f.text_field :description

and this will build a form `:symbolic_grouping => {name: ..., description: ... }

So my guess would be that somehow the association name is not correctly filled in or not correctly recognised by the `fields_for` statement?

**Comment by sedubois** [comment]
Thanks @nathanvda, we're on to something! `administrate-field-nested_has_many` doesn't cope well with Namedspaced models. It calls `fields_for` [like this](https://github.com/nickcharlton/administrate-field-nested_has_many/blob/35a7abf37285b1b6f24e4c252c90190ea1ad8ce5/app/views/fields/nested_has_many/_form.html.erb#L3):
```rb
<fieldset ...>
  <%= f.fields_for field.association_name do |nested_form| %>
    ...
  <% end %>
  <div>
    <%= link_to_add_association(...) %>
  </div>
</fieldset>
```

`field.association_name` is defined as:
```rb
      def association_name
        associated_class_name.underscore.pluralize
      end
```

So `"Post::Translation".underscore.pluralize` yields `post/translations` instead of `translations`. I've managed to workaround the issue by creating my own custom Administrate field extending `Field::NestedHasMany`, then overriding `association_name` to return `translations` instead of `post/translations`.

So it's got nothing to do with Cocoon! Sorry for the noise here and thanks a lot for the help 👍
