### ISSUE TITLE
JS does not respond with remove link

### ISSUE THREAD

**Issue by RickEaton** [nathanvda/cocoon#574]
I'm integrating your excellent gem in a Rails app. Everything is working except the js callbacks to modify the form appearance. I can add and remove objects, but when I click on the add or remove links, my custom before-insert and before-remove actions are not triggering. Can you help me figure out what I am doing wrong?

custom_cocoon.js:
$(document).ready(function() {
    alert('Custom Cocoon js is loaded.')
    $('#special_diets')
        .on('cocoon:before-insert', function() {
            alert('Before insert')
        })
        .on('cocoon:after-insert', function() {
            alert('After insert')
        })
        .on('cocoon:before-remove', function(e, special_diet) {
            // allow some time for the animation to complete
            $(this).data('remove-timeout', 1000);
            special_diet.fadeOut('slow');
        });
});

My form:
          <div class="diet-section">
            <h4><strong>Special Diet Needs</strong> (Click on the 'Add a Special Diet' link below to tell us about special diet requirements, including food allergies)</h4>
            <div id="special_diets">
              <%= r.semantic_fields_for :special_diets do |special_diet| %>
                <%= render 'roster_item/special_diet_fields', f: special_diet %>
              <% end %>
            </div>
            <div class='links'>
              <%= link_to_add_association 'Add a Special Diet', r, :special_diets, partial: 'roster_item/special_diet_fields' %>
            </div>
          </div>

The nested form partial:
<div class="'nested-fields'">
  <%= f.inputs do %>
    <%= f.input :special_diet_type_id, label: 'Select your dietary need', as: :radio, collection: SpecialDietType.all %>
    <%= f.input :allergy_related, label: 'Is this related to an allergy?', as: :radio %>
    <%= f.input :severity, label: 'How severe is the allergy?', as: :select, collection: SpecialDiet::VALID_SEVERITY_VALUES %>
    <%= f.input :trigger, label: 'What causes or triggers the allergy?', as: :select, collection: SpecialDiet::VALID_TRIGGER_VALUES %>
    <%= f.input :note, label: 'What else would you like to share about this?', as: :string, maxlength: 255 %>
    <%= link_to_remove_association 'Remove This Special Diet', f %>
  <% end %>
</div>

Any guidance you can provide will be greatly appreciated!

**Comment by nathanvda** [comment]
Two remarks: 

1) please format your code in a legible way (it is really easy)
2) to fix this problem, as [documented](https://github.com/nathanvda/cocoon#link_to_remove_association) please wrap your partial in a surrounding `div`, the default class is `nested-fields`, but you could also choose a different class (by specifying the `wrapper_class` option for your `link_to_remove_association`.

**Comment by RickEaton** [comment]
Thank you for responding. Sorry about the formatting.

The partial is wrapped in a nested-fields class as shown in the documentation:

```
<div class="'nested-fields'">
<%= f.inputs do %>
    <%= f.input :special_diet_type_id, label: 'Select your dietary need', as: :radio, collection: SpecialDietType.all %>
    <%= f.input :allergy_related, label: 'Is this related to an allergy?', as: :radio %>
    <%= f.input :severity, label: 'How severe is the allergy?', as: :select, collection: SpecialDiet::VALID_SEVERITY_VALUES %>
    <%= f.input :trigger, label: 'What causes or triggers the allergy?', as: :select, collection: SpecialDiet::VALID_TRIGGER_VALUES %>
    <%= f.input :note, label: 'What else would you like to share about this?', as: :string, maxlength: 255 %>
    <%= link_to_remove_association 'Remove This Special Diet', f %>
  <% end %>
</div>
```

Could the problem be in my javascript code? None of the alerts, other than the first one, is firing.

```
`$(document).ready(function() {
    alert('Custom Cocoon js is loaded.')
    $('#special_diets')
        .on('cocoon:before-insert', function() {
            alert('Before insert')
        })
        .on('cocoon:after-insert', function() {
            alert('After insert')
        })
        .on('cocoon:before-remove', function(e, special_diet) {
            // allow some time for the animation to complete
            $(this).data('remove-timeout', 1000);
            special_diet.fadeOut('slow');
        });
});`
```

**Comment by nathanvda** [comment]
This looks better. In the initial question there was no wrapping class, right? 

So clicking the `link_to_add_association` does work? But the callbacks do not? And the removal also does not? 

If the `link_to_add_association` works, at least the cocoon js is loaded correctly, in which the remove should also work (if you use the correct wrapper-class).

For the callbacks it is essential to attach them to a surrounding div, that exists at the time the js code is run. Unfortunately it is impossible for me to see that `#special_diets` exists in your page (I see no such definition in what you have shown me).

**Comment by RickEaton** [comment]
Nathan,

Thanks again for your help with this. This is what the relevant part of the main form looks like, and it is working. It looks like 
```

          <div class="diet-section">
            <h4><strong>Special Diet Needs</strong> (Click on the 'Add a Special Diet' link below to tell us about special diet requirements, including food allergies)</h4>
            <div class="special_diets">
              <%= r.semantic_fields_for :special_diets do |special_diet| %>
                <%= render 'roster_item/special_diet_fields', f: special_diet %>
              <% end %>
            </div>
            <div class='links'>
              <%= link_to_add_association 'Add a Special Diet', r, :special_diets, partial: 'roster_item/special_diet_fields' %>
            </div>
          </div>
```

**Comment by nathanvda** [comment]
Is everything working? Things I still see:

* you have a class `.special_diets` and I do not see an `#special_diets` (to which you attached the callbacks)
* to capture the events, you need the surrounding class of the `link_to_add_association`, which in your example would be `.diet-section` 

If you need the `erb` examples, you can find those [here](https://github.com/nathanvda/cocoon/wiki/ERB-examples)

**Comment by RickEaton** [comment]
Nathan,

Thank you again for your help on this. This are working, but not quite the way I would like them to

This is the main form:


<div id="special_diets">
  <h4><strong>Special Diet Needs</strong> (Click on the 'Add a Special Diet' link below to tell us about special diet requirements, including food allergies)</h4>
  <div class="special_diet">
    <%= r.semantic_fields_for :special_diets do |special_diet| %>
      <%= render 'roster_item/special_diet_fields', f: special_diet %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'Add a Special Diet', r, :special_diets, partial: 'roster_item/special_diet_fields' %>
    </div>
  </div>
</div>
And the subform:


<div class="'nested-fields'">
  <%= f.inputs do %>
    <%= f.input :special_diet_type_id, label: 'Select your dietary need', as: :radio, collection: SpecialDietType.all %>
    <%= f.input :allergy_related, label: 'Is this related to an allergy?', as: :radio %>
    <%= f.input :severity, label: 'How severe is the allergy?', as: :select, collection: SpecialDiet::VALID_SEVERITY_VALUES %>
    <%= f.input :trigger, label: 'What causes or triggers the allergy?', as: :select, collection: SpecialDiet::VALID_TRIGGER_VALUES %>
    <%= f.input :note, label: 'What else would you like to share about this?', as: :string, maxlength: 255 %>
    <%= link_to_remove_association 'Remove This Special Diet', f, { wrapper_class: 'special_diet'} %>
  <% end %>
</div>

And the JS:

$(document).ready(function() {
    alert('Custom Cocoon js is loaded.')
    $('#special_diets')
        .on('cocoon:before-insert', function() {
            alert('Before insert')
        })
        .on('cocoon:after-insert', function() {
            alert('This special diet will be added.')
        })
        .on('cocoon:before-remove', function(e, special_diet) {
            // allow some time for the animation to complete
            $(this).data('remove-timeout', 1000);
            special_diet.fadeOut('slow');
        });
});

What is working:

  *   The js is firing. The alerts take place and the before-remove action (fade out) is taking place.
  *   The subform’s models are being added and displayed correctly. The remove link is also removing the correct linked object.

But:

  *   Since the special_diet class encloses the link_to_add_association, this link disappears when I remove a subform. This is not desired, since I still want to be able to add additional objects after removing one.
  *   If I change the form so that the special_diet div does not include the link_to_add_association, it stops working.

Thoughts?

Rick Eaton
Eaton Nonprofit Solutions
916-718-5063
http://www.eatonnpsolutions.com<http://www.eatonnpsolutions.com/>

**Comment by nathanvda** [comment]
Why did you use `wrapper_class: 'special_diet' ` ? just remove that option in the `link_to_remove_association`. Your nested fields are wrapped in the default class `.nested-fields` so the default behaviour will work.

**Comment by RickEaton** [comment]
Nathan,

Thank you so much for your reply. That did it!

Rick

Rick Eaton
Eaton Nonprofit Solutions
916-718-5063
http://www.eatonnpsolutions.com<http://www.eatonnpsolutions.com/>
