### ISSUE TITLE
Deep nesting form accessing last nested model

### ISSUE THREAD

**Issue by f-adrien** [nathanvda/cocoon#582]
Hi!
I have a project with Forms, FormQuestion and QuestionSublabel models, so 2 level deep nested form is needed. The creation of the form works just fine and the associations are correctly built. But when entering the edit view I have this error:
undefined method `label' for #<QuestionSublabel:0x0000...>
Which is odd because "label" is an input for the FormQuestion object, as you can see in my code below. I cannot understand why the form is passing the last nested object to its parents form builder.

here are my models:

form.rb
`class Form < ApplicationRecord
  has_many :form_questions, inverse_of: :form, dependent: :destroy
  has_many :question_sublabels, through: :form_questions
  has_many :form_answers, dependent: :nullify

  accepts_nested_attributes_for :form_questions, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :question_sublabels, reject_if: :all_blank, allow_destroy: true
end`

form_question.rb
`class FormQuestion < ApplicationRecord
  belongs_to :form, optional: true
  has_many :form_answers, dependent: :nullify
  has_many :question_sublabels, inverse_of: :form_question, dependent: :destroy

  accepts_nested_attributes_for :question_sublabels, reject_if: :all_blank, allow_destroy: true
end`

question_sublabel.rb
`class QuestionSublabel < ApplicationRecord
  belongs_to :form_question, optional: true
end`

Here is my controller:

forms_controller:

`  def new_form
    @form = Form.new
    @user_id = params[:user_id]
    @institution_id = params[:institution_id]
  end

  def create_form
    @form = Form.new(set_form_params)
    @user_id = params[:form][:user_id]
    if @form.save!
      redirect_to admin_user_show_path(subdomain: 'admin', id: @user_id)
    else
      @institution = params[:form][:institution_id]
      render :new_form
    end
  end
 
def edit_form
    @form = Form.find(params[:id])
    @user_id = params[:user_id]
    @institution_id = params[:institution_id]
  end

def set_form_params
    params.require(:form).permit(:name, :user_id, :institution_id, form_questions_attributes: [:id, :label, :question_type, :_destroy, question_sublabels_attributes: [:id, :sublabel_field, :_destroy]])
 end`

and for the views:

form_form.html.erb

`<%= simple_form_for @form, url: url, method: method do |f| %>
    <%= f.input :user_id,
      as: :hidden,
      input_html: {value: @user_id},
      wrapper_html: {class: "m-0"}
    %>
    <%= f.input :institution_id,
      as: :hidden,
      input_html: {value: @institution_id},
      wrapper_html: {class: "m-0"}
    %>
    <div class="a__box">
      <div class="a__box-title">
        <h5>Information principale</h5>
      </div>
      <div class="section-separator"></div>
        <div class='row'>
          <div class='col-md-6'>
            <%= f.input :name,
            label: "Nom du formulaire" %>
          </div>
        </div>
    </div>
    <div class="questions-fields">
      <%= f.simple_fields_for :form_questions do |builder|  %>
        <%= render 'form_question_fields', f: builder %>
      <% end %>
    </div>
    <div class='d-flex mt-3'>
      <%= f.button :button, "Sauvegarder", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i>" + "Sauvegarder" }, class: "btn btn-light btn-small" %>
      <%= link_to_add_association 'Ajouter une question', f, :form_questions, class: 'btn btn-light btn-small ml-2' %>
    </div>
  <% end %>`

_form_question_fields.html.erb

`<div class="a__box mt-4 question-field">
  <div class="d-flex justify-content-between">
    <p class="a__box-subtitle mb-2 mt-0 question-title"></p>
    <%= link_to_remove_association 'Remove question', f, { wrapper_class: 'question-field' } %>
  </div>
  <div class='row'>
    <%= f.input_field :_destroy, as: :hidden %>
    <div class='col-md-6'>
      <%= f.input :label,
      label: "Label" %>
    </div>
    <div class='col-md-6'>
      <%= f.input :question_type,
      collection: ['text', 'checkboxes', 'radio_buttons', 'boolean'],
      include_blank: false,
      label: "Type de question",
      input_html: {id: 'form_form_questions_attributes_1_label', class: "form_question_type_select", data: { value: '' }} %>
    </div>
  </div>
  <div class="question-sublabels-fields u-display-none" data-id=''>
    <%= f.simple_fields_for :question_sublabels do |builder| %>
        <%= render 'form_question_fields', f: builder %>
    <% end %>
    <div>
    <%= link_to_add_association 'Ajouter un sublabel', f, :question_sublabels, class: 'btn btn-light btn-small' %>
    </div>
  </div>
</div>`

_question_sublabel_fields.html.erb

`<div class="sublabel-field">
<%= f.input_field :_destroy, as: :hidden %>
  <div class="col-md-3 pl-0">
    <div class="d-flex justify-content-between">
      <%= f.label "Sublabel" %>
      <%= link_to_remove_association 'Effacer', f, { wrapper_class: 'sublabel-field' } %>
    </div>
    <%= f.input :sublabel_field,
    label: false,
    required: false %>
  </div>
</div>`

Thank you for your help and sorry for my English, I hope I made myself clear enough.

**Comment by nathanvda** [comment]
Hi there, thank you for opening your first issue! Can you please attempt to format the question a bit better, please use the preview tab to verify how your question is looking. Especially the code-bits are badly formatted and it makes the whole question very difficult to read.

**Comment by f-adrien** [comment]
Sure! Sorry for that !
(The example might be a bit confusing because I have a Form model. In order to avoid confusions I will refer to the Form model with an upcase letter)

As I was saying, I created a 2 level deep nested form with cocoon with FormQuestion nested into Form and QuestionSublabel that are nested inside FormQuestion. When creating a new Form instance it works fine and I have the correct associations done. But when I want to edit the Form instance, as soon as I enter the edit view I get this error: 

"undefined method `label' for #<QuestionSublabel:0x00007f84283d2e18>"

which is odd because as you can see in the code below, the label input is proper to the form_questions and not the question_sublabels

form.rb
```
class Form < ApplicationRecord
  has_many :form_questions, inverse_of: :form, dependent: :destroy
  has_many :question_sublabels, through: :form_questions
  has_many :form_answers, dependent: :nullify

  accepts_nested_attributes_for :form_questions, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :question_sublabels, reject_if: :all_blank, allow_destroy: true
end
```

form_question.rb

```
class FormQuestion < ApplicationRecord
  belongs_to :form, optional: true
  has_many :form_answers, dependent: :nullify
  has_many :question_sublabels, inverse_of: :form_question, dependent: :destroy

  accepts_nested_attributes_for :question_sublabels, reject_if: :all_blank, allow_destroy: true
end
```

question_sublabel.rb

```
class QuestionSublabel < ApplicationRecord 
  belongs_to :form_question, optional: true 
end
```

Here is my controller:

forms_controller:

```
def new_form
  @Form = Form.new
  @user_id = params[:user_id]
  @institution_id = params[:institution_id]
end

def create_form
  @Form = Form.new(set_form_params)
  @user_id = params[:form][:user_id]
  if @form.save!
    redirect_to admin_user_show_path(subdomain: 'admin', id: @user_id)
  else
    @institution = params[:form][:institution_id]
    render :new_form
  end
end

def edit_form
  @Form = Form.find(params[:id])
  @user_id = params[:user_id]
  @institution_id = params[:institution_id]
end

private

def set_form_params
  params.require(:form).permit(:name, :user_id, :institution_id, form_questions_attributes: [:id, :label, :question_type, :_destroy, question_sublabels_attributes: [:id, :sublabel_field, :_destroy]])
end
```

and for the views:

form_form.html.erb

```
<%= simple_form_for @form, url: url, method: method do |f| %>
   <%= f.input :user_id, as: :hidden, input_html: {value: @user_id}, wrapper_html: {class: "m-0"} %> 
  <%= f.input :institution_id, as: :hidden, input_html: {value: @institution_id}, wrapper_html: {class: "m-0"} %> 
  <div class="a__box"> 
    <div class="a__box-title"> 
      <h5>Information principale</h5> 
    </div> 
    <div class="section-separator"></div> 
    <div class='row'> 
      <div class='col-md-6'> 
        <%= f.input :name, label: "Nom du formulaire" %> 
      </div> 
    </div> 
  </div> 
  <div class="questions-fields"> 
    <%= f.simple_fields_for :form_questions do |builder| %> 
      <%= render 'form_question_fields', f: builder %> 
    <% end %> 
  </div> 
  <div class='d-flex mt-3'> 
    <%= f.button :button, "Sauvegarder", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i>" + "Sauvegarder" }, class: "btn btn-light btn-small" %> 
    <%= link_to_add_association 'Ajouter une question', f, :form_questions, class: 'btn btn-light btn-small ml-2' %> 
  </div> 
<% end %>
```

_form_question_fields.html.erb

```
<div class="a__box mt-4 question-field">
  <div class="d-flex justify-content-between">
    <p class="a__box-subtitle mb-2 mt-0 question-title"></p>
    <%= link_to_remove_association 'Remove question', f, { wrapper_class: 'question-field' } %>
  </div>
  <div class='row'>
    <%= f.input_field :_destroy, as: :hidden %>
    <div class='col-md-6'>
      <%= f.input :label,
      label: "Label" %>
    </div>
    <div class='col-md-6'>
      <%= f.input :question_type,
      collection: ['text', 'checkboxes', 'radio_buttons', 'boolean'],
      include_blank: false,
      label: "Type de question",
      input_html: {id: 'form_form_questions_attributes_1_label', class: "form_question_type_select", data: { value: '' }} %>
    </div>
  </div>
  <div class="question-sublabels-fields u-display-none" data-id=''>
    <%= f.simple_fields_for :question_sublabels do |builder| %>
        <%= render 'form_question_fields', f: builder %>
    <% end %>
    <div>
    <%= link_to_add_association 'Ajouter un sublabel', f, :question_sublabels, class: 'btn btn-light btn-small' %>
    </div>
  </div>
</div>
```

_question_sublabel_fields.html.erb

```
<div class="sublabel-field">
<%= f.input_field :_destroy, as: :hidden %>
  <div class="col-md-3 pl-0">
    <div class="d-flex justify-content-between">
      <%= f.label "Sublabel" %>
      <%= link_to_remove_association 'Effacer', f, { wrapper_class: 'sublabel-field' } %>
    </div>
    <%= f.input :sublabel_field,
    label: false,
    required: false %>
  </div>
</div>
```

Thank you for your help and sorry for my English, I hope I made myself clear enough.

**Comment by nathanvda** [comment]
On which line do you have the error, what is the callstack? It is a bit weird that `new` works and `edit` does not, normally the form is shared between the new and edit action, is that for you also the case? 

Also is there a specific reason why you are using custom action names (`new_form`, `edit_form`, `create_form` ... instead of restful routes) ? Because if you use restful routes, you would not have to specify the `url` manually (also weird: I see the `url` as parameter in the form, but I do not see where it is set). E.g. a new form is normally always `POST-ed`, while an edit form uses `PATCH` (where the http methods also have a meaning).

**Comment by f-adrien** [comment]
Hi Nathan, thank you very much for your time.

The error is raised in the _form_question_fields.html.erb file in the following input (but I guess all the following inputs are concerned as well):

```
 <%= f.input :label,
 label: "Label" %>
```
Following your answer, I simplified the routes to get the restful routes (new, create, edit, update) but since I have a namespace I still have to specify a url as a parameter, here you can check where I define the urls:

new.html.erb

```
<div class="sidebar__wrapper">
  <div class="a__page-title">
    <h2>Nouveau formulaire</h2>
  </div>
  <%= render 'admin/forms/partials/form_form', url: admin_form_create_path(@form) %>
</div>
```

edit.html.erb

```
<div class="sidebar__wrapper">
  <div class="a__page-title">
    <h2>Nouveau formulaire</h2>
  </div>
  <%= render 'admin/forms/partials/form_form', url: admin_form_update_path(@form) %>
</div>
```
So now my simple_form entry line is just:

`<%= simple_form_for @form, url: url do |f| %>`

Also I want to mention that when I try to build the associations in the NEW method in the controller like the example below, I get exactly the same error raised in the new.html.erb view:

forms_controller.html.erb
```
def new_form
    @form = Form.new
    @form.form_questions.build.question_sublabels.build
    @user_id = params[:user_id]
    @institution_id = params[:institution_id]
  end
```

Also, what do you mean by call stack ?

Thanks again!

**Comment by nathanvda** [comment]
We are digressing here, but using restful routes you could write

     = simple_form_for [:admin, @form] 

And if you would want to have explicit routes, I would assume you would write `admin_form_path` in both cases, and depending on the state of the `@form` it would either be a POST (=create) or PATCH (=edit), so you would have to write

     = simple_form_for @form, url: admin_form_path(@form) 

which is identical to the above BTW. In your routes you would then have 

      namespace :admin 
         resources :forms 

Anywayyyyyyy, that does not bring us any closer to the reason of your error. The error seems to suggest we are iterating over `QuestionSubLabel`-s in the initial `fields_for :form_questions` loop, which seems a bit odd. So that is why I wanted to see the call stack. 

The call stack = when you get an error, you also get a list of call leading to the place of the error. This sometimes gives an indication why we go there in the first place. This should be in your logfile?

**Comment by f-adrien** [comment]
Thank you for the private form class! I will do that, it's way cleaner.

Below you can find a full screenshot of the error with the call stack:

![image](https://user-images.githubusercontent.com/52235257/81050903-20e60800-8ec1-11ea-8ea1-19f0901cad42.png)

**Comment by nathanvda** [comment]
Thank you for sharing the call stack, the error then popped out to me: you iterate over the `:question_sublabels` but render the wrong partial. 

See: 

```
    <%= f.simple_fields_for :question_sublabels do |builder| %>
        <%= render 'form_question_fields', f: builder %>
    <% end %>
```

**Comment by f-adrien** [comment]
How could I be so blind! Thank you very much Nathan, works perfectly now. Again thank you very much for your time. I am closing the issue :)
