### ISSUE TITLE
Only show new fields page refresh

### ISSUE THREAD

**Issue by RailsCod3rFuture** [nathanvda/cocoon#583]
I love the gem, its wonderful -- The issue I am having is how do you ensure only new form inputs after submitting the nested fields. For instance, every time the page loads - I should only see new inputs, not edit forms for the fields? Thank you.

**Comment by nathanvda** [comment]
Can you explain this in a little more detail? You do want an edit form, but you do not want to show the existing items (so _not_ edit them?). You only want to allow to add new items? Is that correct?

And do you actually want to edit the parent object or not?
