### ISSUE TITLE
Nested Form not visible in Edit Page

### ISSUE THREAD

**Issue by apjanvekar** [nathanvda/cocoon#594]
Hi Nathan,

I am having a Parent form but and one child form.

TemplateCode => Parent Form.

ChildTemplate => ChileForm.(This is a nested form which belongs to Parent Form)

Issue is while save record with no data in ChildTemplate, form is not getting displayed under edit page as it gets displayed in New Page.

So i just want a blank data to be appeared for ChildTemplate form when there is no data in ChildTemplate form so that user can enter records in edit mode.

Please Help.

**Comment by nathanvda** [comment]
Hi @apjanvekar, this is a good introduction, but very vague for me to help you find an error. 

I do not understand the relations or the explicit behaviour that fails or is wanted.

Please show me the 

* actual associations and `accepts_nested_attributes_for` statements (check do you have a `reject_if: :all_blank` option?)
* do you have relevant validations? that would block saving? 
* the views: do you correctly iterate over the associations

I am assuming you have an empty form that is displayed when creating a new `TemplateCode`, but if you do not fill any of the nested forms, the intermediate levels are not saved? Is that correct?

**Comment by nathanvda** [comment]
Closed due to inactivity.
