### ISSUE TITLE
Cocoon and active storage. ActionView::Template::Error (picture delegated to blob, but blob is nil):

### ISSUE THREAD

**Issue by Lee1984** [nathanvda/cocoon#597]
Trying to render A new gallery form, but get this error on the fields `ActionView::Template::Error (picture delegated to blob, but blob is nil):` on the line in form partial `<% if f.object.picture.attached? %>`. It happens on any of the fields, though except for the active storage attribute `picture` IE `<%= f.file_field :picture, accept: 'image/jpg,image/jpeg,image/gif,image/png', id: "gallery_pictures" %>` Inspecting `f.object` is actually an active storage object, not a normal picture object. Eg `#<ActiveStorage::Attachment id: nil, name: "pictures", record_type: "Gallery", record_id: nil, blob_id: nil, created_at: nil>` I only get the error when I add the `has_many_attached :pictures` to gallery model.

Gallery model

    class Gallery < ApplicationRecord

      has_many :pictures, dependent: :destroy
      has_many_attached :pictures
    end

form 

    <%= form_for([@user, @gallery]) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
      <table class="user-picture-form" width="50%">
        <thead>
	   <th>
	      <%= link_to_add_association 'Add picture', f, :pictures, data: {"association-insertion-method" => :append, "association-insertion-node" => ".gal_picture_fields" } %>
	    </th>
	  </thead> 
          <tbody class="gal_picture_fields">
	  </tbody>
      </table>     
  
      <%= f.submit nil, id: "formsubmit" %>

    <% end %>

form partial

    <tr class="nested-fields">
       <td class="picture_input" colspan="2">
         <label class="pictures_input_label"><%= icon("fas", "hand-pointer") %>
            <%= f.file_field :picture, accept: 'image/jpg,image/jpeg,image/gif,image/png', id: "gallery_pictures" %>
         </label>
       </td>
       <td class="thumb" colspan="3">
       <% if f.object.picture.attached? %>
         <%= image_tag f.object.thumb %>
         <% end %>
       </td>
       <td class="picture_location" colspan="5">
         <%= f.text_area :location, id: "gallery_location" %>
       </td>
       <td class="picture_remove" colspan="2"> 
         <%= link_to_remove_association "X", f %>
       </td>          
    </tr>

Thanks Nathan

EDIT: Sorry I realised in the end it may be a active storage issue. Also I found that I switched the order of the methods fixed the issue, not sure why :/

    class Gallery < ApplicationRecord
      
      has_many_attached :pictures
      has_many :pictures, dependent: :destroy
    end

**Comment by nathanvda** [comment]
Why do you declare the `has_many_attached` and `has_many` both? Imho you should only write `has_many_attached` for which the default `dependent` setting is to destroy the attached pictures when the owner is destroyed (unless specified otherwise). See [documentation](https://api.rubyonrails.org/v5.2/classes/ActiveStorage/Attached/Macros.html)

**Comment by Lee1984** [comment]
Ok it seems it has something to do with `accepts_nested_attributes_for`. I removed that and now it complains, when I do something like user.pictures `ActionView::Template::Error (Could not find the source association(s) "picture" or :pictures in model Gallery. Try 'has_many :pictures, :through => :galleries, :source => <name>'. Is it one of pictures_attachments, pictures_blobs, microposts, or user?):` Still working on it

**Comment by nathanvda** [comment]
Ha ok, I stand corrected. I guess you need both `has_many_attached` and `has_many` if you want to use cocoon for adding multiple attachments (personally I generally use something like `dropzone.js` for adding multiple attachments since that feels more natural to me).

**Comment by Lee1984** [comment]
I believe it works it's just that the through relationship won't work, if you remove it.
