### ISSUE TITLE
Examples in ERB?

### ISSUE THREAD

**Issue by tibbon** [nathanvda/cocoon#60]
Everyone doing Rails knows ERB- but not everyone knows SAAS, HAML, etc...

Any chance that the demos and documentation could be reworked in ERB for legibility for more people?

**Comment by ror6ax** [comment]
There's still lack of examples for standard Rails form_for in erb.

**Comment by nathanvda** [comment]
Call me lazy, I avoided doing all the typing and left the most verbose example as an exercise for my readers :grin:  

But I understand the current documentation not clear to you?

The mapping is really simple: just drop the `semantic_`/`simple_` prefix and just write `form_for` and 'fields_for`. 

There was an example for standard rails form in haml, and I just added the ERB example to the wiki page.

Still, if you are a beginner, you should really compare the examples and consider moving to simple-form and haml :+1:

**Comment by ror6ax** [comment]
I've actually went and rewritten my erb into haml.
Clicking on link_to_add_association does not work, silently, though...

**Comment by nathanvda** [comment]
:+1: for using haml! :smile: 

If you are having more problems, please ask help on stackoverflow.com (and tag with `cocoon-gem`) or open a new issue. First guess: you are missing the javascript?
