### ISSUE TITLE
Question: Is there a way to call link_to_add_association outside the parent?

### ISSUE THREAD

**Issue by LJ-03** [nathanvda/cocoon#602]
For example, if I have a project (parent), and want to add, remove and edit tasks (child), I want to do all of this in separate views/forms.

So I would like to add/edit one task without rendering the project and all other tasks for editing too. Is this possible?

**Comment by nathanvda** [comment]
This sounds like the normal/default rails behaviour, for which you do not need cocoon at all? 

So: render a page with the parent and it's children. For each you have an "edit" button. The button links to the `edit` action of the child itself, remotely. Something like 

    = link_to 'Edit', edit_child_path(child), class: 'btn btn-default', remote: true 

In your edit action you can then just render the form, either using a modal, replacing the child-div with the form ... or just open the edit form (not remote?). 

No need for cocoon in that case. Is that close to what you ment?

**Comment by LJ-03** [comment]
Hey Nathan,

Yeah that's about right. My apologies - I'm still fairly new to rails and the cocoon gem too. I still haven't fully figured out nesting, association and creating paths/routes and we were trialling cocoon for our website. Thanks so much for clearing up the confusion here!
