### ISSUE TITLE
History.md maintenance

### ISSUE THREAD

**Issue by brandoncc** [nathanvda/cocoon#607]
I'm upgrading gems and it is bummer to see that History.md stopped being updated 10 versions ago :-/

**Comment by nathanvda** [comment]
... and 7 years ago. Agreed: a bummer, but it was mostly a copy of the commit-log anyway. But probably confusing indeed.

**Comment by brandoncc** [comment]
Gotcha, change logs that are just commit titles are indeed not as helpful as ones that give context and descriptions to each version.

Thanks for maintaining this gem, it is very helpful for us 😊
