### ISSUE TITLE
Rails 6 compatibility

### ISSUE THREAD

**Issue by brandoncc** [nathanvda/cocoon#608]
I see commits about Rails 6 compatibility, but the readme says it is compatible up to v5. Is it actually compatibly up to v6?

Thanks!

**Comment by nathanvda** [comment]
Yes. If you would read further down in the readme, it immediately mentions how to install for rails 6. But good catch anyway.

**Comment by brandoncc** [comment]
Oops, I see it now. Sorry to bother you, but thanks for the quick response!
