### ISSUE TITLE
Javascript not included in Rails 7

### ISSUE THREAD

**Issue by ConfusedVorlon** [nathanvda/cocoon#613]
I'm ahead of the game here - but in Rails 7 (at least with the setup used by JumpstartRails), the cocoon.js file doesn't get included.
Everything seems to work if I manually add it - but presumably the gem should be able to do that automatically.

thanks for a great project.

**Comment by ConfusedVorlon** [comment]
sorry - I got the wrong end of the stick on this.

**Comment by jeygeethan** [comment]
How did you include it? @ConfusedVorlon

**Comment by ConfusedVorlon** [comment]
I import it manually

<img width="926" alt="Screenshot 2022-02-12 at 10 03 13" src="https://user-images.githubusercontent.com/586910/153706759-e7ba272a-76b6-4725-bf98-efdb31682d11.png">
