### ISSUE TITLE
Font awesome icon with link_to_add_association

### ISSUE THREAD

**Issue by kouroubel** [nathanvda/cocoon#619]
Is it possible to have a font awesome icon in the link_to_add_association/link_to_remove_association button? My code currently looks like this

```
    <%= link_to_add_association "+", f, :lessons, 
                           data: {"association-insertion-node" => "tbody.lessons", "association-insertion-method" => "append"}, 
                           class: "btn btn-sm btn-danger" %>
```
I would like to have a font awesome icon instead of the "+" but nothing I have tried can accomplish that. 

For example, I tried

```
<%= link_to_add_association "", f, :lessons, 
                         data: {"association-insertion-node" => "tbody.lessons", "association-insertion-method" => "append"}, 
                         class: "btn btn-sm btn-danger" do %>
       <i class="fa-solid fa-circle-plus"></i>                           
<% end %>
```

but this generates an exception "undefined method `delete' for :lessons:Symbol".

Any suggestions?

**Comment by nathanvda** [comment]
Almost correct. The `link_to_add_association` works in the same way as `link_to`, which means you can omit the first parameter and add a block. 

So in your case that would become something like

```
<%= link_to_add_association f, :lessons, 
                         data: {"association-insertion-node" => "tbody.lessons", "association-insertion-method" => "append"}, 
                         class: "btn btn-sm btn-danger" do %>
       <i class="fa-solid fa-circle-plus"></i>                           
<% end %>
```

**Comment by kouroubel** [comment]
Damn, I knew I was close :) Thank you very much. This worked like a charm!!!
