### ISSUE TITLE
Double nested forms aren't rendered

### ISSUE THREAD

**Issue by dnagir** [nathanvda/cocoon#91]
It appears that it is not possible to use this gem ATM with double nested forms.

When we want to show fields for another association rendered via `fields_for`/`simple_fields_for` those are just ignored.

This restrictions only allows to use the 'flat' dynamic listes without nested models within the lists.

Pretty important for me ATM and wonder if it would be possible to fix it somehow.

**Comment by KevinBongart** [comment]
7 years later, I run into this same issue, was opening a GitHub issue with all my code, and @nathanvda saves the day. Will try to add this to the wiki! ❤️
